export const yzw_ec66 = {
  deltX: 46,
  deltY: 34,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 37,
      h: 38,
    },
    {
      keyName: '1',
      value: 30,
      x: 49,
      y: 0,
      w: 37,
      h: 38,
    },
    {
      keyName: '2',
      value: 31,
      x: 98,
      y: 0,
      w: 37,
      h: 38,
    },
    {
      keyName: '3',
      value: 32,
      x: 147,
      y: 0,
      w: 37,
      h: 38,
    },
    {
      keyName: '4',
      value: 33,
      x: 195,
      y: 0,
      w: 37,
      h: 38,
    },
    {
      keyName: '5',
      value: 34,
      x: 243,
      y: 0,
      w: 37,
      h: 38,
    },
    {
      keyName: '6',
      value: 35,
      x: 292,
      y: 0,
      w: 37,
      h: 38,
    },
    {
      keyName: '7',
      value: 36,
      x: 341,
      y: 0,
      w: 37,
      h: 38,
    },
    {
      keyName: '8',
      value: 37,
      x: 390,
      y: 0,
      w: 37,
      h: 38,
    },
    {
      keyName: '9',
      value: 38,
      x: 438,
      y:0,
      w: 37,
      h: 38,
    },
    {
      keyName: '0',
      value: 39,
      x: 487,
      y: 0,
      w: 37,
      h: 38,
    },
    {
      keyName: '-',
      value: 45,
      x: 535,
      y: 0,
      w: 37,
      h: 38,
    },
    {
      keyName: '=',
      value: 46,
      x: 583,
      y: 0,
      w: 37,
      h: 38,
    },
    {
      keyName: 'Backspace',
      value: 42,
      x: 634,
      y: 0,
      w: 81,
      h: 38,
    },
    {
      keyName: 'U-',
      value: 0x0300ea00,
      knob: true,
      x: 732,
      y: 7,
      w: 13,
      h: 51,
    },
    {
      keyName: 'Mute',
      value: 0x0300e200,
      knob: true,
      x: 756,
      y: 7,
      w: 13,
      h: 51,
    },
    {
      keyName: 'U+',
      value: 0x0300e900,
      knob: true,
      x: 780,
      y: 7,
      w: 13,
      h: 51,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -47,
      w: 60,
      h: 38,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 72,
      y: -47,
      w: 37,
      h: 38,
    },
    {
      keyName: 'W',
      value: 26,
      x: 121,
      y: -47,
      w: 37,
      h: 38,
    },
    {
      keyName: 'E',
      value: 8,
      x: 170,
      y: -47,
      w: 37,
      h: 38,
    },
    {
      keyName: 'R',
      value: 21,
      x: 218,
      y: -47,
      w: 37,
      h: 38,
    },
    {
      keyName: 'T',
      value: 23,
      x: 266,
      y: -47,
      w: 37,
      h: 38,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 314,
      y: -47,
      w: 37,
      h: 38,
    },
    {
      keyName: 'U',
      value: 24,
      x: 363,
      y: -47,
      w: 37,
      h: 38,
    },
    {
      keyName: 'I',
      value: 12,
      x: 411,
      y: -47,
      w: 37,
      h: 38,
    },
    {
      keyName: 'O',
      value: 18,
      x: 459,
      y: -47,
      w: 37,
      h: 38,
    },
    {
      keyName: 'P',
      value: 19,
      x: 508,
      y: -47,
      w: 37,
      h: 38,
    },
    {
      keyName: '[',
      value: 47,
      x: 556,
      y: -47,
      w: 37,
      h: 38,
    },
    {
      keyName: ']',
      value: 48,
      x: 604,
      y: -47,
      w: 37,
      h: 38,
    },
    {
      keyName: '\\',
      value: 49,
      x: 653,
      y: -47,
      w: 62,
      h: 38,
    },
    {
      keyName: 'Page\nUp',
      value: 75,
      x: 742,
      y: -62,
      w: 37,
      h: 38,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -95,
      w: 72,
      h: 38,
    },
    {
      keyName: 'A',
      value: 4,
      x: 85,
      y: -95,
      w: 37,
      h: 38,
    },
    {
      keyName: 'S',
      value: 22,
      x: 133,
      y: -95,
      w: 37,
      h: 38,
    },
    {
      keyName: 'D',
      value: 7,
      x: 181,
      y: -95,
      w: 37,
      h: 38,
    },
    {
      keyName: 'F',
      value: 9,
      x: 229,
      y: -95,
      w: 37,
      h: 38,
    },
    {
      keyName: 'G',
      value: 10,
      x: 277,
      y: -95,
      w: 37,
      h: 38,
    },
    {
      keyName: 'H',
      value: 11,
      x: 325,
      y: -95,
      w: 37,
      h: 38,
    },
    {
      keyName: 'J',
      value: 13,
      x: 374,
      y: -95,
      w: 37,
      h: 38,
    },
    {
      keyName: 'K',
      value: 14,
      x: 423,
      y: -95,
      w: 37,
      h: 38,
    },
    {
      keyName: 'L',
      value: 15,
      x: 471,
      y: -95,
      w: 37,
      h: 38,
    },
    {
      keyName: ';',
      value: 51,
      x: 519,
      y: -95,
      w: 37,
      h: 38,
    },
    {
      keyName: '"',
      value: 52,
      x: 569,
      y: -95,
      w: 37,
      h: 38,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 619,
      y: -95,
      w: 96,
      h: 38,
    },
    {
      keyName: 'Page\nDown',
      value: 78,
      x: 742,
      y: -110,
      w: 37,
      h: 38,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -143,
      w: 98,
      h: 38,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 110,
      y: -143,
      w: 37,
      h: 38,
    },
    {
      keyName: 'X',
      value: 27,
      x: 159,
      y: -143,
      w: 37,
      h: 38,
    },
    {
      keyName: 'C',
      value: 6,
      x: 207,
      y: -143,
      w: 37,
      h: 38,
    },
    {
      keyName: 'V',
      value: 25,
      x: 256,
      y: -143,
      w: 37,
      h: 38,
    },
    {
      keyName: 'B',
      value: 5,
      x: 304,
      y: -143,
      w: 37,
      h: 38,
    },
    {
      keyName: 'N',
      value: 17,
      x: 352,
      y: -143,
      w: 37,
      h: 38,
    },
    {
      keyName: 'M',
      value: 16,
      x: 401,
      y: -143,
      w: 37,
      h: 38,
    },
    {
      keyName: ',',
      value: 54,
      x: 448,
      y: -143,
      w: 37,
      h: 38,
    },
    {
      keyName: '.',
      value: 55,
      x: 497,
      y: -143,
      w: 37,
      h: 38,
    },
    {
      keyName: '/',
      value: 56,
      x: 546,
      y: -143,
      w: 37,
      h: 38,
    },
    {
      keyName: 'R-Shift',
      value: 229,
      x: 594,
      y: -143,
      w: 73,
      h: 38,
    },
    {
      keyName: '↑',
      value: 82,
      x: 677,
      y: -143,
      w: 37,
      h: 38,
    },
    {
      keyName: 'Ctrl',
      value: 224,
      x: 0,
      y: -191,
      w: 49,
      h: 38,
    },
    {
      keyName: 'win',
      value: 227,
      x: 60,
      y: -191,
      w: 49,
      h: 38,
    },
    {
      keyName: 'Alt',
      value: 226,
      x: 120,
      y: -191,
      w: 49,
      h: 38,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 182,
      y: -191,
      w: 287,
      h: 38,
    },
    {
      keyName: 'r-Alt',
      value: 230,
      x: 483,
      y: -191,
      w: 37,
      h: 38,
    },
    {
      keyName: 'Fn',
      value: 0x0a010000,
      x: 531,
      y: -191,
      w: 37,
      h: 38,
    },
    {
      keyName: 'r-Ctrl',
      value: 228,
      x: 580,
      y: -191,
      w: 37,
      h: 38,
    },
    {
      keyName: '←',
      value: 80,
      x: 628,
      y: -191,
      w: 37,
      h: 38,
    },
    {
      keyName: '↓',
      value: 81,
      x: 677,
      y: -191,
      w: 37,
      h: 38,
    },
    {
      keyName: '→',
      value: 79,
      x: 726,
      y: -191,
      w: 37,
      h: 38,
    },
  ],
}
