export const yzw_kb910_g682_noled = {
  deltX: 11,
  deltY: 14,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 34,
      h: 33,
     },
    {
      keyName: 'F1',
      value: 58,
      x: 46,
      y: 0,
      w: 34,
      h: 33,
    },
    {
      keyName: 'F2',
      value: 59,
      x: 90,
      y: 0,
      w: 34,
      h: 33,
    },
    {
      keyName: 'F3',
      value: 60,
      x: 135,
      y: 0,
      w: 34,
      h: 33,
    },
    {
      keyName: 'F4',
      value: 61,
      x: 181,
      y: 0,
      w: 34,
      h: 33,
    },
    {
      keyName: 'F5',
      value: 62,
      x: 228,
      y: 0,
      w: 34,
      h: 33,
    },
    {
      keyName: 'F6',
      value: 63,
      x: 272,
      y: 0,
      w: 34,
      h: 33,
    },
    {
      keyName: 'F7',
      value: 64,
      x: 317,
      y: 0,
      w: 34,
      h: 33,
    },
    {
      keyName: 'F8',
      value: 65,
      x: 361,
      y: 0,
      w: 34,
      h: 33,
    },
    {
      keyName: 'F9',
      value: 66,
      x: 408,
      y: 0,
      w: 34,
      h: 33,
    },
    {
      keyName: 'F10',
      value: 67,
      x: 452,
      y: 0,
      w: 34,
      h: 33,
    },
    {
      keyName: 'F11',
      value: 68,
      x: 497,
      y: 0,
      w: 34,
      h: 33,
    },
    {
      keyName: 'F12',
      value: 69,
      x: 544,
      y: 0,
      w: 34,
      h: 33,
    },
    {
      keyName: 'Print\nScreen',
      value: 70,
      x: 589,
      y: 0,
      w: 34,
      h: 33,
    },
    {
      keyName: 'Delete',
      value: 76,
      x: 635,
      y: 0,
      w: 34,
      h: 33,
    },
    {
      keyName: 'Home',
      value: 74,
      x: 680,
      y: 0,
      w: 34,
      h: 33,
    },
    {
      keyName: 'End',
      value: 77,
      x: 724,
      y: 0,
      w: 34,
      h: 33,
    },
    {
      keyName: 'Page\nUp',
      value: 75,
      x: 770,
      y: 0,
      w: 34,
      h: 33,
    },
    {
      keyName: 'Page\nDown',
      value: 78,
      x: 815,
      y: 0,
      w: 34,
      h: 33,
    },
    {
      keyName: '`',
      value: 53,
      x: 0,
      y: -45,
      w: 34,
      h: 33,
    },
    {
      keyName: '1',
      value: 30,
      x: 46,
      y: -45,
      w: 34,
      h: 33,
    },
    {
      keyName: '2',
      value: 31,
      x: 90,
      y: -45,
      w: 34,
      h: 33,
    },
    {
      keyName: '3',
      value: 32,
      x: 135,
      y: -45,
      w: 34,
      h: 33,
    },
    {
      keyName: '4',
      value: 33,
      x: 181,
      y: -45,
      w: 34,
      h: 33,
    },
    {
      keyName: '5',
      value: 34,
      x: 226,
      y: -45,
      w: 34,
      h: 33,
    },
    {
      keyName: '6',
      value: 35,
      x: 272,
      y: -45,
      w: 34,
      h: 33,
    },
    {
      keyName: '7',
      value: 36,
      x: 317,
      y: -45,
      w: 34,
      h: 33,
    },
    {
      keyName: '8',
      value: 37,
      x: 361,
      y: -45,
      w: 34,
      h: 33,
    },
    {
      keyName: '9',
      value: 38,
      x: 408,
      y: -45,
      w: 34,
      h: 33,
    },
    {
      keyName: '0',
      value: 39,
      x: 452,
      y: -45,
      w: 34,
      h: 33,
    },
    {
      keyName: '-',
      value: 45,
      x: 497,
      y: -45,
      w: 34,
      h: 33,
    },
    {
      keyName: '=',
      value: 46,
      x: 544,
      y: -45,
      w: 34,
      h: 33,
    },
    {
      keyName: 'BackSpace',
      value: 42,
      x: 589,
      y: -45,
      w: 80,
      h: 33,
    },
    {
      keyName: 'Num\nLock',
      value: 83,
      x: 680,
      y: -45,
      w: 34,
      h: 33,
    },
    {
      keyName: 'num_/',
      value: 84,
      x: 724,
      y: -45,
      w: 34,
      h: 33,
    },
    {
      keyName: 'num_*',
      value: 85,
      x: 770,
      y: -45,
      w: 34,
      h: 33,
    },
    {
      keyName: 'num_-',
      value: 86,
      x: 815,
      y: -45,
      w: 34,
      h: 33,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -90,
      w: 59,
      h: 33,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 70,
      y: -90,
      w: 34,
      h: 33,
    },
    {
      keyName: 'W',
      value: 26,
      x: 114,
      y: -90,
      w: 34,
      h: 33,
    },
    {
      keyName: 'E',
      value: 8,
      x: 159,
      y: -90,
      w: 34,
      h: 33,
    },
    {
      keyName: 'R',
      value: 21,
      x: 205,
      y: -90,
      w: 34,
      h: 33,
    },
    {
      keyName: 'T',
      value: 23,
      x: 250,
      y: -90,
      w: 34,
      h: 33,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 296,
      y: -90,
      w: 34,
      h: 33,
    },
    {
      keyName: 'U',
      value: 24,
      x: 340,
      y: -90,
      w: 34,
      h: 33,
    },
    {
      keyName: 'I',
      value: 12,
      x: 384,
      y: -90,
      w: 34,
      h: 33,
    },
    {
      keyName: 'O',
      value: 18,
      x: 430,
      y: -90,
      w: 34,
      h: 33,
    },
    {
      keyName: 'P',
      value: 19,
      x: 475,
      y: -90,
      w: 34,
      h: 33,
    },
    {
      keyName: '[',
      value: 47,
      x: 521,
      y: -90,
      w: 34,
      h: 33,
    },
    {
      keyName: ']',
      value: 48,
      x: 566,
      y: -90,
      w: 34,
      h: 33,
    },
    {
      keyName: '\\',
      value: 49,
      x: 611,
      y: -90,
      w: 58,
      h: 33,
    },
    {
      keyName: 'num_7',
      value: 95,
      x: 679,
      y: -90,
      w: 34,
      h: 33,
    },
    {
      keyName: 'num_8',
      value: 96,
      x: 724,
      y: -90,
      w: 34,
      h: 33,
    },
    {
      keyName: 'num_9',
      value: 97,
      x: 769,
      y: -90,
      w: 34,
      h: 33,
    },
    {
      keyName: 'num_+',
      value: 87,
      x: 813,
      y: -90,
      w: 34,
      h: 77,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -134,
      w: 71,
      h: 33,
    },
    {
      keyName: 'A',
      value: 4,
      x: 80,
      y: -134,
      w: 34,
      h: 33,
    },
    {
      keyName: 'S',
      value: 22,
      x: 125,
      y: -134,
      w: 34,
      h: 33,
    },
    {
      keyName: 'D',
      value: 7,
      x: 170,
      y: -134,
      w: 34,
      h: 33,
    },
    {
      keyName: 'F',
      value: 9,
      x: 216,
      y: -134,
      w: 34,
      h: 33,
    },
    {
      keyName: 'G',
      value: 10,
      x: 259,
      y: -134,
      w: 34,
      h: 33,
    },
    {
      keyName: 'H',
      value: 11,
      x: 305,
      y: -134,
      w: 34,
      h: 33,
    },
    {
      keyName: 'J',
      value: 13,
      x: 350,
      y: -134,
      w: 34,
      h: 33,
    },
    {
      keyName: 'K',
      value: 14,
      x: 396,
      y: -134,
      w: 34,
      h: 33,
    },
    {
      keyName: 'L',
      value: 15,
      x: 441,
      y: -134,
      w: 34,
      h: 33,
    },
    {
      keyName: ';',
      value: 51,
      x: 486,
      y: -134,
      w: 34,
      h: 33,
    },
    {
      keyName: '\'',
      value: 52,
      x: 532,
      y: -134,
      w: 34,
      h: 33,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 577,
      y: -134,
      w: 92,
      h: 33,
    },
    {
      keyName: 'num_4',
      value: 92,
      x: 679,
      y: -134,
      w: 34,
      h: 33,
    },
    {
      keyName: 'num_5',
      value: 93,
      x: 724,
      y: -134,
      w: 34,
      h: 33,
    },
    {
      keyName: 'num_6',
      value: 94,
      x: 769,
      y: -134,
      w: 34,
      h: 33,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -179,
      w: 94,
      h: 33,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 103,
      y: -179,
      w: 34,
      h: 33,
    },
    {
      keyName: 'X',
      value: 27,
      x: 147,
      y: -179,
      w: 34,
      h: 33,
    },
    {
      keyName: 'C',
      value: 6,
      x: 192,
      y: -179,
      w: 34,
      h: 33,
    },
    {
      keyName: 'V',
      value: 25,
      x: 238,
      y: -179,
      w: 34,
      h: 33,
    },
    {
      keyName: 'B',
      value: 5,
      x: 284,
      y: -179,
      w: 34,
      h: 33,
    },
    {
      keyName: 'N',
      value: 17,
      x: 329,
      y: -179,
      w: 34,
      h: 33,
    },
    {
      keyName: 'M',
      value: 16,
      x: 374,
      y: -179,
      w: 34,
      h: 33,
    },
    {
      keyName: ',',
      value: 54,
      x: 420,
      y: -179,
      w: 34,
      h: 33,
    },
    {
      keyName: '.',
      value: 55,
      x: 464,
      y: -179,
      w: 34,
      h: 33,
    },
    {
      keyName: '/',
      value: 56,
      x: 509,
      y: -179,
      w: 34,
      h: 33,
    },
    {
      keyName: 'r_Shift',
      value: 229,
      x: 554,
      y: -179,
      w: 70,
      h: 33,
    },
    {
      keyName: '↑',
      value: 82,
      x: 635,
      y: -179,
      w: 34,
      h: 33,
    },
    {
      keyName: 'num_1',
      value: 89,
      x: 679,
      y: -179,
      w: 34,
      h: 33,
    },
    {
      keyName: 'num_2',
      value: 90,
      x: 723,
      y: -179,
      w: 34,
      h: 33,
    },
    {
      keyName: 'num_3',
      value: 91,
      x: 769,
      y: -179,
      w: 34,
      h: 33,
    },
    {
      keyName: 'num_Enter',
      value: 88,
      x: 813,
      y: -179,
      w: 34,
      h: 77,
    },
    {
      keyName: 'Ctrl',
      value: 224,
      x: 0,
      y: -224,
      w: 48,
      h: 33,
    },
    {
      keyName: 'Win',
      value: 227,
      x: 57,
      y: -224,
      w: 48,
      h: 33,
    },
    {
      keyName: 'Alt',
      value: 226,
      x: 113,
      y: -224,
      w: 48,
      h: 33,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 171,
      y: -224,
      w: 271,
      h: 33,
    },
    {
      keyName: 'r_Alt',
      value: 230,
      x: 453,
      y: -224,
      w: 34,
      h: 33,
    },
    {
      keyName: 'fn',
      value: 0x0a010000,
      x: 499,
      y: -224,
      w: 34,
      h: 33,
    },
    {
      keyName: 'r_Ctrl',
      value: 228,
      x: 544,
      y: -224,
      w: 34,
      h: 33,
    },
    {
      keyName: '←',
      value: 80,
      x: 589,
      y: -224,
      w: 34,
      h: 33,
    },
    {
      keyName: '↓',
      value: 81,
      x: 634,
      y: -224,
      w: 34,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
      h: 33,
    },
    {
      keyName: '→',
      value: 79,
      x: 681,
      y: -224,
      w: 34,
      h: 33,
    },
    {
      keyName: 'num_0',
      value: 98,
      x: 724,
      y: -224,
      w: 34,
      h: 33,
    },
    {
      keyName: 'num_.',
      value: 99,
      x: 769,
      y: -224,
      w: 34,
      h: 33,
    },
  ],
}
