export const yzw_hf67_uk_dm = {
  deltX: 51,
  deltY: 32,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 31,
      h: 36,
    },
    {
      keyName: '1',
      value: 30,
      x: 48,
      y: 0,
      w: 31,
      h: 36,
    },
    {
      keyName: '2',
      value: 31,
      x: 95,
      y: 0,
      w: 31,
      h: 36,
    },
    {
      keyName: '3',
      value: 32,
      x: 143,
      y: 0,
      w: 31,
      h: 36,
    },
    {
      keyName: '4',
      value: 33,
      x: 190,
      y: 0,
      w: 31,
      h: 36,
    },
    {
      keyName: '5',
      value: 34,
      x: 238,
      y: 0,
      w: 31,
      h: 36,
    },
    {
      keyName: '6',
      value: 35,
      x: 285,
      y: 0,
      w: 31,
      h: 36,
    },
    {
      keyName: '7',
      value: 36,
      x: 333,
      y: 0,
      w: 31,
      h: 36,
    },
    {
      keyName: '8',
      value: 37,
      x: 380,
      y: 0,
      w: 31,
      h: 36,
    },
    {
      keyName: '9',
      value: 38,
      x: 428,
      y: 0,
      w: 31,
      h: 36,
    },
    {
      keyName: '0',
      value: 39,
      x: 475,
      y: 0,
      w: 31,
      h: 36,
    },
    {
      keyName: '-',
      value: 45,
      x: 523,
      y: 0,
      w: 31,
      h: 36,
    },
    {
      keyName: '=',
      value: 46,
      x: 570,
      y: 0,
      w: 31,
      h: 36,
    },
    {
      keyName: 'Backspace',
      value: 42,
      x: 618,
      y: 0,
      w: 79,
      h: 36,
    },
    {
      keyName: 'U-',
      value: 0x0300ea00,
      knob: true,
      x: 727,
      y: 21,
      w: 13,
      h: 56,
    },
    {
      keyName: 'play',
      value: 0x0300cd00,
      knob: true,
      x: 748,
      y: 15,
      w: 13,
      h: 44,
    },
    {
      keyName: 'U+',
      value: 0x0300e900,
      knob: true,
      x: 769,
      y: 21,
      w: 13,
      h: 56,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -47,
      w: 55,
      h: 36,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 72,
      y: -47,
      w: 31,
      h: 36,
    },
    {
      keyName: 'W',
      value: 26,
      x: 119,
      y: -47,
      w: 31,
      h: 36,
    },
    {
      keyName: 'E',
      value: 8,
      x: 167,
      y: -47,
      w: 31,
      h: 36,
    },
    {
      keyName: 'R',
      value: 21,
      x: 214,
      y: -47,
      w: 31,
      h: 36,
    },
    {
      keyName: 'T',
      value: 23,
      x: 262,
      y: -47,
      w: 31,
      h: 36,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 309,
      y: -47,
      w: 31,
      h: 36,
    },
    {
      keyName: 'U',
      value: 24,
      x: 357,
      y: -47,
      w: 31,
      h: 36,
    },
    {
      keyName: 'I',
      value: 12,
      x: 405,
      y: -47,
      w: 31,
      h: 36,
    },
    {
      keyName: 'O',
      value: 18,
      x: 452,
      y: -47,
      w: 31,
      h: 36,
    },
    {
      keyName: 'P',
      value: 19,
      x: 499,
      y: -47,
      w: 31,
      h: 36,
    },
    {
      keyName: '[',
      value: 47,
      x: 547,
      y: -47,
      w: 31,
      h: 36,
    },
    {
      keyName: ']',
      value: 48,
      x: 594,
      y: -47,
      w: 31,
      h: 36,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 643,
      y: -47,
      w: 54,
      h: 82,
    },
    {
      keyName: 'Delete',
      value: 76,
      x: 738,
      y: -47,
      w: 31,
      h: 36,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -95,
      w: 67,
      h: 36,
    },
    {
      keyName: 'A',
      value: 4,
      x: 84,
      y: -98,
      w: 31,
      h: 36,
    },
    {
      keyName: 'S',
      value: 22,
      x: 131,
      y: -98,
      w: 31,
      h: 36,
    },
    {
      keyName: 'D',
      value: 7,
      x: 179,
      y: -98,
      w: 31,
      h: 36,
    },
    {
      keyName: 'F',
      value: 9,
      x: 226,
      y: -98,
      w: 31,
      h: 36,
    },
    {
      keyName: 'G',
      value: 10,
      x: 274,
      y: -98,
      w: 31,
      h: 36,
    },
    {
      keyName: 'H',
      value: 11,
      x: 321,
      y: -98,
      w: 31,
      h: 36,
    },
    {
      keyName: 'J',
      value: 13,
      x: 369,
      y: -98,
      w: 31,
      h: 36,
    },
    {
      keyName: 'K',
      value: 14,
      x: 416,
      y: -98,
      w: 31,
      h: 36,
    },
    {
      keyName: 'L',
      value: 15,
      x: 464,
      y: -98,
      w: 31,
      h: 36,
    },
    {
      keyName: ';',
      value: 51,
      x: 511,
      y: -98,
      w: 31,
      h: 36,
    },
    {
      keyName: '"',
      value: 52,
      x: 559,
      y: -98,
      w: 31,
      h: 36,
    },
    {
      keyName: '`',
      value: 50,
      x: 608,
      y: -98,
      w: 31,
      h: 36,
    },
    {
      keyName: 'Page\nUp',
      value: 75,
      x: 738,
      y: -98,
      w: 31,
      h: 36,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -142,
      w: 43,
      h: 36,
    },
    {
      keyName: '\\',
      value: 49,
      x: 60,
      y: -142,
      w: 31,
      h: 36,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 108,
      y: -142,
      w: 31,
      h: 36,
    },
    {
      keyName: 'X',
      value: 27,
      x: 155,
      y: -142,
      w: 31,
      h: 36,
    },
    {
      keyName: 'C',
      value: 6,
      x: 203,
      y: -142,
      w: 31,
      h: 36,
    },
    {
      keyName: 'V',
      value: 25,
      x: 250,
      y: -142,
      w: 31,
      h: 36,
    },
    {
      keyName: 'B',
      value: 5,
      x: 298,
      y: -142,
      w: 31,
      h: 36,
    },
    {
      keyName: 'N',
      value: 17,
      x: 345,
      y: -142,
      w: 31,
      h: 36,
    },
    {
      keyName: 'M',
      value: 16,
      x: 392,
      y: -142,
      w: 31,
      h: 36,
    },
    {
      keyName: ',',
      value: 54,
      x: 440,
      y: -142,
      w: 31,
      h: 36,
    },
    {
      keyName: '.',
      value: 55,
      x: 487,
      y: -142,
      w: 31,
      h: 36,
    },
    {
      keyName: '/',
      value: 56,
      x: 535,
      y: -142,
      w: 31,
      h: 36,
    },
    {
      keyName: 'R-Shift',
      value: 229,
      x: 583,
      y: -142,
      w: 66,
      h: 36,
    },
    {
      keyName: 'Page\nDown',
      value: 78,
      x: 738,
      y: -142,
      w: 31,
      h: 36,
    },
    {
      keyName: '↑',
      value: 82,
      x: 678,
      y: -155,
      w: 31,
      h: 36,
    },
    {
      keyName: 'Ctrl',
      value: 224,
      x: 0,
      y: -190,
      w: 43,
      h: 36,
    },
    {
      keyName: 'win',
      value: 227,
      x: 60,
      y: -190,
      w: 43,
      h: 36,
    },
    {
      keyName: 'Alt',
      value: 226,
      x: 119,
      y: -190,
      w: 43,
      h: 36,
    },
    {
      keyName: 'space',
      value: 44,
      x: 179,
      y: -190,
      w: 280,
      h: 36,
    },
    {
      keyName: 'r-Alt',
      value: 230,
      x: 475,
      y: -190,
      w: 31,
      h: 36,
    },
    {
      keyName: 'Fn',
      value: 0x0a010000,
      x: 522,
      y: -190,
      w: 31,
      h: 36,
    },
    {
      keyName: 'r-Ctrl',
      value: 228,
      x: 570,
      y: -190,
      w: 31,
      h: 36,
    },
    {
      keyName: '←',
      value: 80,
      x: 631,
      y: -202,
      w: 31,
      h: 36,
    },
    {
      keyName: '↓',
      value: 81,
      x: 678,
      y: -202,
      w: 31,
      h: 36,
    },
    {
      keyName: '→',
      value: 79,
      x: 726,
      y: -202,
      w: 31,
      h: 36,
    },
  ],
}
