export const yzw_cl87 = {
  deltX: 94,
  deltY: 27,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 25,
      h: 28,
    },
    {
      keyName: 'F1',
      value: 58,
      x: 77,
      y: 0,
      w: 25,
      h: 28,
    },
    {
      keyName: 'F2',
      value: 59,
      x: 115,
      y: 0,
      w: 25,
      h: 28,
    },
    {
      keyName: 'F3',
      value: 60,
      x: 153,
      y: 0,
      w: 25,
      h: 28,
    },
    {
      keyName: 'F4',
      value: 61,
      x: 191,
      y: 0,
      w: 25,
      h: 28,
    },
    {
      keyName: 'F5',
      value: 62,
      x: 248,
      y: 0,
      w: 25,
      h: 28,
    },
    {
      keyName: 'F6',
      value: 63,
      x: 286,
      y: 0,
      w: 25,
      h: 28,
    },
    {
      keyName: 'F7',
      value: 64,
      x: 324,
      y: 0,
      w: 25,
      h: 28,
    },
    {
      keyName: 'F8',
      value: 65,
      x: 362,
      y: 0,
      w: 25,
      h: 28,
    },
    {
      keyName: 'F9',
      value: 66,
      x: 419,
      y: 0,
      w: 25,
      h: 28,
    },
    {
      keyName: 'F10',
      value: 67,
      x: 457,
      y: 0,
      w: 25,
      h: 28,
    },
    {
      keyName: 'F11',
      value: 68,
      x: 495,
      y: 0,
      w: 25,
      h: 28,
    },
    {
      keyName: 'F12',
      value: 69,
      x: 534,
      y: 0,
      w: 25,
      h: 28,
    },
    {
      keyName: 'Print\nScreen',
      value: 70,
      x: 582,
      y: 0,
      w: 25,
      h: 28,
    },
    {
      keyName: 'Scroll\nLock',
      value: 71,
      x: 620,
      y: 0,
      w: 25,
      h: 28,
    },
    {
      keyName: 'Pause',
      value: 72,
      x: 658,
      y: 0,
      w: 25,
      h: 28,
    },
    {
      keyName: '`',
      value: 53,
      x: 0,
      y: -57,
      w: 25,
      h: 28,
    },
    {
      keyName: '1',
      value: 30,
      x: 39,
      y: -57,
      w: 25,
      h: 28,
    },
    {
      keyName: '2',
      value: 31,
      x: 77,
      y: -57,
      w: 25,
      h: 28,
    },
    {
      keyName: '3',
      value: 32,
      x: 115,
      y: -57,
      w: 25,
      h: 28,
    },
    {
      keyName: '4',
      value: 33,
      x: 153,
      y: -57,
      w: 25,
      h: 28,
    },
    {
      keyName: '5',
      value: 34,
      x: 190,
      y: -57,
      w: 25,
      h: 28,
    },
    {
      keyName: '6',
      value: 35,
      x: 228,
      y: -57,
      w: 25,
      h: 28,
    },
    {
      keyName: '7',
      value: 36,
      x: 267,
      y: -57,
      w: 25,
      h: 28,
    },
    {
      keyName: '8',
      value: 37,
      x: 304,
      y: -57,
      w: 25,
      h: 28,
    },
    {
      keyName: '9',
      value: 38,
      x: 342,
      y: -57,
      w: 25,
      h: 28,
    },
    {
      keyName: '0',
      value: 39,
      x: 381,
      y: -57,
      w: 25,
      h: 28,
    },
    {
      keyName: '-',
      value: 45,
      x: 418,
      y: -57,
      w: 25,
      h: 28,
    },
    {
      keyName: '=',
      value: 46,
      x: 456,
      y: -57,
      w: 25,
      h: 28,
    },
    {
      keyName: 'BackSpace',
      value: 42,
      x: 495,
      y: -57,
      w: 62,
      h: 28,
    },
    {
      keyName: 'Insert',
      value: 73,
      x: 582,
      y: -57,
      w: 25,
      h: 28,
    },
    {
      keyName: 'Home',
      value: 74,
      x: 620,
      y: -57,
      w: 25,
      h: 28,
    },
    {
      keyName: 'Page\nUp',
      value: 75,
      x: 658,
      y: -57,
      w: 25,
      h: 28,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -95,
      w: 44,
      h: 28,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 57,
      y: -95,
      w: 25,
      h: 28,
    },
    {
      keyName: 'W',
      value: 26,
      x: 95,
      y: -95,
      w: 25,
      h: 28,
    },
    {
      keyName: 'E',
      value: 8,
      x: 133,
      y: -95,
      w: 25,
      h: 28,
    },
    {
      keyName: 'R',
      value: 21,
      x: 171,
      y: -95,
      w: 25,
      h: 28,
    },
    {
      keyName: 'T',
      value: 23,
      x: 209,
      y: -95,
      w: 25,
      h: 28,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 247,
      y: -95,
      w: 25,
      h: 28,
    },
    {
      keyName: 'U',
      value: 24,
      x: 285,
      y: -95,
      w: 25,
      h: 28,
    },
    {
      keyName: 'I',
      value: 12,
      x: 323,
      y: -95,
      w: 25,
      h: 28,
    },
    {
      keyName: 'O',
      value: 18,
      x: 361,
      y: -95,
      w: 25,
      h: 28,
    },
    {
      keyName: 'P',
      value: 19,
      x: 399,
      y: -95,
      w: 25,
      h: 28,
    },
    {
      keyName: '[',
      value: 47,
      x: 437,
      y: -95,
      w: 25,
      h: 28,
    },
    {
      keyName: ']',
      value: 48,
      x: 475,
      y: -95,
      w: 25,
      h: 28,
    },
    {
      keyName: '\\',
      value: 49,
      x: 514,
      y: -95,
      w: 43,
      h: 28,
    },
    {
      keyName: 'Delete',
      value: 76,
      x: 582,
      y: -95,
      w: 25,
      h: 28,
    },
    {
      keyName: 'End',
      value: 77,
      x: 620,
      y: -95,
      w: 25,
      h: 28,
    },
    {
      keyName: 'Page\nDown',
      value: 78,
      x: 658,
      y: -95,
      w: 25,
      h: 28,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -133,
      w: 54,
      h: 28,
    },
    {
      keyName: 'A',
      value: 4,
      x: 67,
      y: -133,
      w: 25,
      h: 28,
    },
    {
      keyName: 'S',
      value: 22,
      x: 105,
      y: -133,
      w: 25,
      h: 28,
    },
    {
      keyName: 'D',
      value: 7,
      x: 143,
      y: -133,
      w: 25,
      h: 28,
    },
    {
      keyName: 'F',
      value: 9,
      x: 181,
      y: -133,
      w: 25,
      h: 28,
    },
    {
      keyName: 'G',
      value: 10,
      x: 219,
      y: -133,
      w: 25,
      h: 28,
    },
    {
      keyName: 'H',
      value: 11,
      x: 257,
      y: -133,
      w: 25,
      h: 28,
    },
    {
      keyName: 'J',
      value: 13,
      x: 295,
      y: -133,
      w: 25,
      h: 28,
    },
    {
      keyName: 'K',
      value: 14,
      x: 333,
      y: -133,
      w: 25,
      h: 28,
    },
    {
      keyName: 'L',
      value: 15,
      x: 371,
      y: -133,
      w: 25,
      h: 28,
    },
    {
      keyName: ';',
      value: 51,
      x: 409,
      y: -133,
      w: 25,
      h: 28,
    },
    {
      keyName: '\'',
      value: 52,
      x: 447,
      y: -133,
      w: 25,
      h: 28,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 485,
      y: -133,
      w: 72,
      h: 28,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -171,
      w: 73,
      h: 28,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 86,
      y: -171,
      w: 25,
      h: 28,
    },
    {
      keyName: 'X',
      value: 27,
      x: 124,
      y: -171,
      w: 25,
      h: 28,
    },
    {
      keyName: 'C',
      value: 6,
      x: 162,
      y: -171,
      w: 25,
      h: 28,
    },
    {
      keyName: 'V',
      value: 25,
      x: 200,
      y: -171,
      w: 25,
      h: 28,
    },
    {
      keyName: 'B',
      value: 5,
      x: 238,
      y: -171,
      w: 25,
      h: 28,
    },
    {
      keyName: 'N',
      value: 17,
      x: 276,
      y: -171,
      w: 25,
      h: 28,
    },
    {
      keyName: 'M',
      value: 16,
      x: 314,
      y: -171,
      w: 25,
      h: 28,
    },
    {
      keyName: ',',
      value: 54,
      x: 352,
      y: -171,
      w: 25,
      h: 28,
    },
    {
      keyName: '.',
      value: 55,
      x: 390,
      y: -171,
      w: 25,
      h: 28,
    },
    {
      keyName: '/',
      value: 56,
      x: 428,
      y: -171,
      w: 25,
      h: 28,
    },
    {
      keyName: 'r_Shift',
      value: 229,
      x: 466,
      y: -171,
      w: 91,
      h: 28,
    },
    {
      keyName: '↑',
      value: 82,
      x: 620,
      y: -171,
      w: 25,
      h: 28,
    },
    {
      keyName: 'Ctrl',
      value: 224,
      x: 0,
      y: -209,
      w: 34,
      h: 28,
    },
    {
      keyName: 'Win',
      value: 227,
      x: 49,
      y: -209,
      w: 34,
      h: 28,
    },
    {
      keyName: 'Alt',
      value: 226,
      x: 96,
      y: -209,
      w: 34,
      h: 28,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 144,
      y: -209,
      w: 223,
      h: 28,
    },
    {
      keyName: 'r_Alt',
      value: 230,
      x: 381,
      y: -209,
      w: 34,
      h: 28,
    },
    {
      keyName: '(Application)',
      value: 101,
      x: 428,
      y: -209,
      w: 34,
      h: 28,
    },
    {
      keyName: 'FN',
      value: 0x0a010000,
      x: 476,
      y: -209,
      w: 34,
      h: 28,
    },
    {
      keyName: 'r_Ctrl',
      value: 228,
      x: 523,
      y: -209,
      w: 34,
      h: 28,
    },
    {
      keyName: '←',
      value: 80,
      x: 582,
      y: -209,
      w: 25,
      h: 28,
    },
    {
      keyName: '↓',
      value: 81,
      x: 620,
      y: -209,
      w: 25,
      h: 28,
    },
    {
      keyName: '→',
      value: 79,
      x: 658,
      y: -209,
      w: 25,
      h: 28,
    },
  ],
}
