export const yzw_dk67_k700x_dm = {
  deltX: 41,
  deltY: 19,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 33,
      h: 37,
    },
    {
      keyName: '1',
      value: 30,
      x: 49,
      y: 0,
      w: 33,
      h: 37,
    },
    {
      keyName: '2',
      value: 31,
      x: 98,
      y: 0,
      w: 33,
      h: 37,
    },
    {
      keyName: '3',
      value: 32,
      x: 147,
      y: 0,
      w: 33,
      h: 37,
    },
    {
      keyName: '4',
      value: 33,
      x: 196,
      y: 0,
      w: 33,
      h: 37,
    },
    {
      keyName: '5',
      value: 34,
      x: 245,
      y: 0,
      w: 33,
      h: 37,
    },
    {
      keyName: '6',
      value: 35,
      x: 294,
      y: 0,
      w: 33,
      h: 37,
    },
    {
      keyName: '7',
      value: 36,
      x: 344,
      y: 0,
      w: 33,
      h: 37,
    },
    {
      keyName: '8',
      value: 37,
      x: 393,
      y: 0,
      w: 33,
      h: 37,
    },
    {
      keyName: '9',
      value: 38,
      x: 442,
      y: 0,
      w: 33,
      h: 37,
    },
    {
      keyName: '0',
      value: 39,
      x: 491,
      y: 0,
      w: 33,
      h: 37,
    },
    {
      keyName: '-',
      value: 45,
      x: 540,
      y: 0,
      w: 33,
      h: 37,
    },
    {
      keyName: '=',
      value: 46,
      x: 589,
      y: 0,
      w: 33,
      h: 37,
    },
    {
      keyName: 'Backspace',
      value: 42,
      x: 638,
      y: 0,
      w: 82,
      h: 37,
    },
    {
      keyName: 'U-',
      value: 0x0300ea00,
      knob: true,
      x: 745,
      y: 13,
      w: 11,
      h: 52,
    },
    {
      keyName: 'play',
      value: 0x0300e200,
      knob: true,
      x: 766,
      y: 13,
      w: 11,
      h: 52,
    },
    {
      keyName: 'U+',
      value: 0x0300e900,
      knob: true,
      x: 787,
      y: 13,
      w: 11,
      h: 52,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -49,
      w: 58,
      h: 37,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 73,
      y: -49,
      w: 33,
      h: 37,
    },
    {
      keyName: 'W',
      value: 26,
      x: 122,
      y: -49,
      w: 33,
      h: 37,
    },
    {
      keyName: 'E',
      value: 8,
      x: 171,
      y: -49,
      w: 33,
      h: 37,
    },
    {
      keyName: 'R',
      value: 21,
      x: 220,
      y: -49,
      w: 33,
      h: 37,
    },
    {
      keyName: 'T',
      value: 23,
      x: 269,
      y: -49,
      w: 33,
      h: 37,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 318,
      y: -49,
      w: 33,
      h: 37,
    },
    {
      keyName: 'U',
      value: 24,
      x: 368,
      y: -49,
      w: 33,
      h: 37,
    },
    {
      keyName: 'I',
      value: 12,
      x: 417,
      y: -49,
      w: 33,
      h: 37,
    },
    {
      keyName: 'O',
      value: 18,
      x: 466,
      y: -49,
      w: 33,
      h: 37,
    },
    {
      keyName: 'P',
      value: 19,
      x: 515,
      y: -49,
      w: 33,
      h: 37,
    },
    {
      keyName: '[',
      value: 47,
      x: 564,
      y: -49,
      w: 33,
      h: 37,
    },
    {
      keyName: ']',
      value: 48,
      x: 613,
      y: -49,
      w: 33,
      h: 37,
    },
    {
      keyName: '\\',
      value: 50,
      x: 662,
      y: -49,
      w: 58,
      h: 37,
    },
    {
      keyName:'Delete',
      value: 76,
      x: 755,
      y: -49,
      w: 33,
      h: 37,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -98,
      w: 70,
      h: 37,
    },
    {
      keyName: 'A',
      value: 4,
      x: 86,
      y: -98,
      w: 33,
      h: 37,
    },
    {
      keyName: 'S',
      value: 22,
      x: 135,
      y: -98,
      w: 33,
      h: 37,
    },
    {
      keyName: 'D',
      value: 7,
      x: 184,
      y: -98,
      w: 33,
      h: 37,
    },
    {
      keyName: 'F',
      value: 9,
      x: 233,
      y: -98,
      w: 33,
      h: 37,
    },
    {
      keyName: 'G',
      value: 10,
      x: 282,
      y: -98,
      w: 33,
      h: 37,
    },
    {
      keyName: 'H',
      value: 11,
      x: 331,
      y: -98,
      w: 33,
      h: 37,
    },
    {
      keyName: 'J',
      value: 13,
      x: 381,
      y: -98,
      w: 33,
      h: 37,
    },
    {
      keyName: 'K',
      value: 14,
      x: 430,
      y: -98,
      w: 33,
      h: 37,
    },
    {
      keyName: 'L',
      value: 15,
      x: 479,
      y: -98,
      w: 33,
      h: 37,
    },
    {
      keyName: ';',
      value: 51,
      x: 528,
      y: -98,
      w: 33,
      h: 37,
    },
    {
      keyName: '"',
      value: 52,
      x: 577,
      y: -98,
      w: 33,
      h: 37,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 626,
      y: -98,
      w: 94,
      h: 37,
    },
    {
      keyName: 'Page\nUp',
      value: 75,
      x: 755,
      y: -98,
      w: 33,
      h: 37,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -147,
      w: 95,
      h: 37,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 110,
      y: -147,
      w: 33,
      h: 37,
    },
    {
      keyName: 'X',
      value: 27,
      x: 159,
      y: -147,
      w: 33,
      h: 37,
    },
    {
      keyName: 'C',
      value: 6,
      x: 208,
      y: -147,
      w: 33,
      h: 37,
    },
    {
      keyName: 'V',
      value: 25,
      x: 257,
      y: -147,
      w: 33,
      h: 37,
    },
    {
      keyName: 'B',
      value: 5,
      x: 306,
      y: -147,
      w: 33,
      h: 37,
    },
    {
      keyName: 'N',
      value: 17,
      x: 355,
      y: -147,
      w: 33,
      h: 37,
    },
    {
      keyName: 'M',
      value: 16,
      x: 405,
      y: -147,
      w: 33,
      h: 37,
    },
    {
      keyName: ',',
      value: 54,
      x: 454,
      y: -147,
      w: 33,
      h: 37,
    },
    {
      keyName: '.',
      value: 55,
      x: 503,
      y: -147,
      w: 33,
      h: 37,
    },
    {
      keyName: '/',
      value: 56,
      x: 552,
      y: -147,
      w: 33,
      h: 37,
    },
    {
      keyName: 'R-Shift',
      value: 229,
      x: 601,
      y: -147,
      w: 69,
      h: 37,
    },
    {
      keyName: 'Page\nDown',
      value:  78,
      x: 755,
      y: -147,
      w: 33,
      h: 37,
    },
    {
      keyName: 'Ctrl',
      value: 224,
      x: 0,
      y: -196,
      w: 48,
      h: 37,
    },
    {
      keyName: 'win',
      value: 227,
      x: 62,
      y: -196,
      w: 48,
      h: 37,
    },
    {
      keyName: 'Alt',
      value: 226,
      x: 123,
      y: -196,
      w: 48,
      h: 37,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 185,
      y: -196,
      w: 290,
      h: 37,
    },
    {
      keyName: 'r-Alt',
      value: 230,
      x: 490,
      y: -196,
      w: 33,
      h: 37,
    },
    {
      keyName: 'Fn',
      value: 0x0a010000,
      x: 539,
      y: -196,
      w: 33,
      h: 37,
    },
    {
      keyName: 'r-Ctrl',
      value: 228,
      x: 588,
      y: -196,
      w: 33,
      h: 37,
    },
    {
      keyName: '↑',
      value: 82,
      x: 696,
      y: -157,
      w: 33,
      h: 37,
    },
    {
      keyName: '←',
      value: 80,
      x: 647,
      y: -206,
      w: 33,
      h: 37,
    },
    {
      keyName: '↓',
      value: 81,
      x: 696,
      y: -206,
      w: 33,
      h: 37,
    },
    {
      keyName: '→',
      value: 79,
      x: 745,
      y: -206,
      w: 33,
      h: 37,
    },
  ],
}
