export const yzw_k229 = {
  deltX: 65,
  deltY: 48,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 28,
      h: 33,
    },
    {
      keyName: '1',
      value: 30,
      x: 44,
      y: 0,
      w: 28,
      h: 33,
    },
    {
      keyName: '2',
      value: 31,
      x: 88,
      y: 0,
      w: 28,
      h: 33,
    },
    {
      keyName: '3',
      value: 32,
      x: 132,
      y: 0,
      w: 28,
      h: 33,
    },
    {
      keyName: '4',
      value: 33,
      x: 176,
      y: 0,
      w: 28,
      h: 33,
    },
    {
      keyName: '5',
      value: 34,
      x: 220,
      y: 0,
      w: 28,
      h: 33,
    },
    {
      keyName: '6',
      value: 35,
      x: 264,
      y: 0,
      w: 28,
      h: 33,
    },
    {
      keyName: '7',
      value: 36,
      x: 307,
      y: 0,
      w: 28,
      h: 33,
    },
    {
      keyName: '8',
      value: 37,
      x: 351,
      y: 0,
      w: 28,
      h: 33,
    },
    {
      keyName: '9',
      value: 38,
      x: 394,
      y: 0,
      w: 28,
      h: 33,
    },
    {
      keyName: '0',
      value: 39,
      x: 438,
      y: 0,
      w: 28,
      h: 33,
    },
    {
      keyName: '-',
      value: 45,
      x: 482,
      y: 0,
      w: 28,
      h: 33,
    },
    {
      keyName: '=',
      value: 46,
      x: 526,
      y: 0,
      w: 28,
      h: 33,
    },
    {
      keyName: 'Backspace',
      value: 42,
      x: 570,
      y: 0,
      w: 71,
      h: 33,
    },
    {
      keyName: 'Insert',
      value: 73,
      x: 670,
      y: 0,
      w: 28,
      h: 33,
    },
    {
      keyName: 'Page\nUp',
      value: 75,
      x: 714,
      y: 0,
      w: 28,
      h: 33,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -43,
      w: 50,
      h: 33,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 66,
      y: -43,
      w: 28,
      h: 33,
    },
    {
      keyName: 'W',
      value: 26,
      x: 110,
      y: -43,
      w: 28,
      h: 33,
    },
    {
      keyName: 'E',
      value: 8,
      x: 154,
      y: -43,
      w: 28,
      h: 33,
    },
    {
      keyName: 'R',
      value: 21,
      x: 198,
      y: -43,
      w: 28,
      h: 33,
    },
    {
      keyName: 'T',
      value: 23,
      x: 241,
      y: -43,
      w: 28,
      h: 33,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 285,
      y: -43,
      w: 28,
      h: 33,
    },
    {
      keyName: 'U',
      value: 24,
      x: 329,
      y: -43,
      w: 28,
      h: 33,
    },
    {
      keyName: 'I',
      value: 12,
      x: 373,
      y: -43,
      w: 28,
      h: 33,
    },
    {
      keyName: 'O',
      value: 18,
      x: 416,
      y: -43,
      w: 28,
      h: 33,
    },
    {
      keyName: 'P',
      value: 19,
      x: 460,
      y: -43,
      w: 28,
      h: 33,
    },
    {
      keyName: '[',
      value: 47,
      x: 504,
      y: -43,
      w: 28,
      h: 33,
    },
    {
      keyName: ']',
      value: 48,
      x: 548,
      y: -43,
      w: 28,
      h: 33,
    },
    {
      keyName: '\\',
      value: 49,
      x: 591,
      y: -43,
      w: 50,
      h: 33,
    },
    {
      keyName: 'Delete',
      value: 76,
      x: 670,
      y: -43,
      w: 28,
      h: 33,
    },
    {
      keyName: 'Page\nDown',
      value: 78,
      x: 714,
      y: -43,
      w: 28,
      h: 33,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -88,
      w: 61,
      h: 33,
    },
    {
      keyName: 'A',
      value: 4,
      x: 77,
      y: -88,
      w: 28,
      h: 33,
    },
    {
      keyName: 'S',
      value: 22,
      x: 121,
      y: -88,
      w: 28,
      h: 33,
    },
    {
      keyName: 'D',
      value: 7,
      x: 165,
      y: -88,
      w: 28,
      h: 33,
    },
    {
      keyName: 'F',
      value: 9,
      x: 208,
      y: -88,
      w: 28,
      h: 33,
    },
    {
      keyName: 'G',
      value: 10,
      x: 252,
      y: -88,
      w: 28,
      h: 33,
    },
    {
      keyName: 'H',
      value: 11,
      x: 296,
      y: -88,
      w: 28,
      h: 33,
    },
    {
      keyName: 'J',
      value: 13,
      x: 340,
      y: -88,
      w: 28,
      h: 33,
    },
    {
      keyName: 'K',
      value: 14,
      x: 384,
      y: -88,
      w: 28,
      h: 33,
    },
    {
      keyName: 'L',
      value: 15,
      x: 427,
      y: -88,
      w: 28,
      h: 33,
    },
    {
      keyName: ';',
      value: 51,
      x: 471,
      y: -88,
      w: 28,
      h: 33,
    },
    {
      keyName: '\'',
      value: 52,
      x: 515,
      y: -88,
      w: 28,
      h: 33,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 559,
      y: -88,
      w: 82,
      h: 33,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -131,
      w: 83,
      h: 33,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 99,
      y: -131,
      w: 28,
      h: 33,
    },
    {
      keyName: 'X',
      value: 27,
      x: 143,
      y: -131,
      w: 28,
      h: 33,
    },
    {
      keyName: 'C',
      value: 6,
      x: 187,
      y: -131,
      w: 28,
      h: 33,
    },
    {
      keyName: 'V',
      value: 25,
      x: 231,
      y: -131,
      w: 28,
      h: 33,
    },
    {
      keyName: 'B',
      value: 5,
      x: 275,
      y: -131,
      w: 28,
      h: 33,
    },
    {
      keyName: 'N',
      value: 17,
      x: 317,
      y: -131,
      w: 28,
      h: 33,
    },
    {
      keyName: 'M',
      value: 16,
      x: 361,
      y: -131,
      w: 28,
      h: 33,
    },
    {
      keyName: ',',
      value: 54,
      x: 405,
      y: -131,
      w: 28,
      h: 33,
    },
    {
      keyName: '.',
      value: 55,
      x: 449,
      y: -131,
      w: 28,
      h: 33,
    },
    {
      keyName: '/',
      value: 56,
      x: 493,
      y: -131,
      w: 28,
      h: 33,
    },
    {
      keyName: 'r_Shift',
      value: 229,
      x: 537,
      y: -131,
      w: 104,
      h: 33,
    },
    {
      keyName: '↑',
      value: 82,
      x: 670,
      y: -131,
      w: 28,
      h: 33,
    },
    {
      keyName: 'CTRL',
      value: 224,
      x: 0,
      y: -174,
      w: 39,
      h: 33,
    },
    {
      keyName: 'Win',
      value: 227,
      x: 55,
      y: -174,
      w: 39,
      h: 33,
    },
    {
      keyName: 'ALT',
      value: 226,
      x: 110,
      y: -174,
      w: 39,
      h: 33,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 165,
      y: -174,
      w: 257,
      h: 33,
    },
    {
      keyName: 'r_Alt',
      value: 230,
      x: 438,
      y: -174,
      w: 39,
      h: 33,
    },
    {
      keyName: 'FN',
      value: 0x0a010000,
      x: 493,
      y: -174,
      w: 39,
      h: 33,
    },
    {
      keyName: 'r_Ctrl',
      value: 228,
      x: 548,
      y: -174,
      w: 39,
      h: 33,
    },
    {
      keyName: '←',
      value: 80,
      x: 625,
      y: -174,
      w: 28,
      h: 33,
    },
    {
      keyName: '↓',
      value: 81,
      x: 670,
      y: -174,
      w: 28,
      h: 33,
    },
    {
      keyName: '→',
      value: 79,
      x: 713,
      y: -174,
      w: 28,
      h: 33,
    },
  ],
}
