export const yzw_mod008_dm = {
  deltX: 74,
  deltY: 37,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 31,
      h: 33,
    },
    {
      keyName: '1',
      value: 30,
      x: 45,
      y: 0,
      w: 31,
      h: 33,
    },
    {
      keyName: '2',
      value: 31,
      x: 90,
      y: 0,
      w: 31,
      h: 33,
    },
    {
      keyName: '3',
      value: 32,
      x: 134,
      y: 0,
      w: 31,
      h: 33,
    },
    {
      keyName: '4',
      value: 33,
      x: 179,
      y: 0,
      w: 31,
      h: 33,
    },
    {
      keyName: '5',
      value: 34,
      x: 224,
      y: 0,
      w: 31,
      h: 33,
    },
    {
      keyName: '6',
      value: 35,
      x: 268,
      y: 0,
      w: 31,
      h: 33,
    },
    {
      keyName: '7',
      value: 36,
      x: 313,
      y: 0,
      w: 31,
      h: 33,
    },
    {
      keyName: '8',
      value: 37,
      x: 358,
      y: 0,
      w: 31,
      h: 33,
    },
    {
      keyName: '9',
      value: 38,
      x: 402,
      y: 0,
      w: 31,
      h: 33,
    },
    {
      keyName: '0',
      value: 39,
      x: 447,
      y: 0,
      w: 31,
      h: 33,
    },
    {
      keyName: '-',
      value: 45,
      x: 492,
      y: 0,
      w: 31,
      h: 33,
    },
    {
      keyName: '=',
      value: 46,
      x: 536,
      y: 0,
      w: 31,
      h: 33,
    },
    {
      keyName: 'Backspace',
      value: 42,
      x: 581,
      y: 0,
      w: 75,
      h: 33,
    },
    {
      keyName: 'U-',
      value: 0x0300ea00,
      knob: true,
      x: 681,
      y: 11,
      w: 14,
      h: 49,
    },
    {
      keyName: 'play',
      value: 0x0a0d0000,
      knob: true,
      ban:true,
      x: 701,
      y: 11,
      w: 14,
      h: 49,
    },
    {
      keyName: 'U+',
      value: 0x0300e900,
      knob: true,
      x: 721,
      y: 11,
      w: 14,
      h: 49,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -44,
      w: 52,
      h: 33,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 68,
      y: -44,
      w: 31,
      h: 33,
    },
    {
      keyName: 'W',
      value: 26,
      x: 113,
      y: -44,
      w: 31,
      h: 33,
    },
    {
      keyName: 'E',
      value: 8,
      x: 157,
      y: -44,
      w: 31,
      h: 33,
    },
    {
      keyName: 'R',
      value: 21,
      x: 202,
      y: -44,
      w: 31,
      h: 33,
    },
    {
      keyName: 'T',
      value: 23,
      x: 247,
      y: -44,
      w: 31,
      h: 33,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 291,
      y: -44,
      w: 31,
      h: 33,
    },
    {
      keyName: 'U',
      value: 24,
      x: 336,
      y: -44,
      w: 31,
      h: 33,
    },
    {
      keyName: 'I',
      value: 12,
      x: 381,
      y: -44,
      w: 31,
      h: 33,
    },
    {
      keyName: 'O',
      value: 18,
      x: 425,
      y: -44,
      w: 31,
      h: 33,
    },
    {
      keyName: 'P',
      value: 19,
      x: 470,
      y: -44,
      w: 31,
      h: 33,
    },
    {
      keyName: '[',
      value: 47,
      x: 515,
      y: -44,
      w: 31,
      h: 33,
    },
    {
      keyName: ']',
      value: 48,
      x: 559,
      y: -44,
      w: 31,
      h: 33,
    },
    {
      keyName: '\\',
      value: 49,
      x: 604,
      y: -44,
      w: 52,
      h: 33,
    },
    {
      keyName:'Page\nUp',
      value: 75,
      x: 692,
      y: -44,
      w: 31,
      h: 33,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -89,
      w: 65,
      h: 33,
    },
    {
      keyName: 'A',
      value: 4,
      x: 79,
      y: -89,
      w: 31,
      h: 33,
    },
    {
      keyName: 'S',
      value: 22,
      x: 124,
      y: -89,
      w: 31,
      h: 33,
    },
    {
      keyName: 'D',
      value: 7,
      x: 168,
      y: -89,
      w: 31,
      h: 33,
    },
    {
      keyName: 'F',
      value: 9,
      x: 213,
      y: -89,
      w: 31,
      h: 33,
    },
    {
      keyName: 'G',
      value: 10,
      x: 258,
      y: -89,
      w: 31,
      h: 33,
    },
    {
      keyName: 'H',
      value: 11,
      x: 302,
      y: -89,
      w: 31,
      h: 33,
    },
    {
      keyName: 'J',
      value: 13,
      x: 347,
      y: -89,
      w: 31,
      h: 33,
    },
    {
      keyName: 'K',
      value: 14,
      x: 392,
      y: -89,
      w: 31,
      h: 33,
    },
    {
      keyName: 'L',
      value: 15,
      x: 436,
      y: -89,
      w: 31,
      h: 33,
    },
    {
      keyName: ';',
      value: 51,
      x: 481,
      y: -89,
      w: 31,
      h: 33,
    },
    {
      keyName: '"',
      value: 52,
      x: 526,
      y: -89,
      w: 31,
      h: 33,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 570,
      y: -89,
      w: 86,
      h: 33,
    },
    {
      keyName: 'Page\nDown',
      value: 78,
      x: 692,
      y: -89,
      w: 31,
      h: 33,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -133,
      w: 86,
      h: 33,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 101,
      y: -133,
      w: 31,
      h: 33,
    },
    {
      keyName: 'X',
      value: 27,
      x: 146,
      y: -133,
      w: 31,
      h: 33,
    },
    {
      keyName: 'C',
      value: 6,
      x: 190,
      y: -133,
      w: 31,
      h: 33,
    },
    {
      keyName: 'V',
      value: 25,
      x: 235,
      y: -133,
      w: 31,
      h: 33,
    },
    {
      keyName: 'B',
      value: 5,
      x: 280,
      y: -133,
      w: 31,
      h: 33,
    },
    {
      keyName: 'N',
      value: 17,
      x: 324,
      y: -133,
      w: 31,
      h: 33,
    },
    {
      keyName: 'M',
      value: 16,
      x: 369,
      y: -133,
      w: 31,
      h: 33,
    },
    {
      keyName: ',',
      value: 54,
      x: 414,
      y: -133,
      w: 31,
      h: 33,
    },
    {
      keyName: '.',
      value: 55,
      x: 458,
      y: -133,
      w: 31,
      h: 33,
    },
    {
      keyName: '/',
      value: 56,
      x: 503,
      y: -133,
      w: 31,
      h: 33,
    },
    {
      keyName: 'R-Shift',
      value: 229,
      x: 547,
      y: -133,
      w: 66,
      h: 33,
    },
    {
      keyName: '↑',
      value: 82,
      x: 637,
      y: -144,
      w: 31,
      h: 33,
    },
    {
      keyName: 'Delete',
      value:  76,
      x: 692,
      y: -133,
      w: 31,
      h: 33,
    },
    {
      keyName: 'Ctrl',
      value: 224,
      x: 0,
      y: -178,
      w: 41,
      h: 33,
    },
    {
      keyName: 'win',
      value: 227,
      x: 57,
      y: -178,
      w: 41,
      h: 33,
    },
    {
      keyName: 'Alt',
      value: 226,
      x: 113,
      y: -178,
      w: 41,
      h: 33,
    },
    {
      keyName: 'space',
      value: 44,
      x: 168,
      y: -178,
      w: 265,
      h: 33,
    },
    {
      keyName: 'r-Alt',
      value: 230,
      x: 447,
      y: -178,
      w: 31,
      h: 33,
    },
    {
      keyName: 'Fn',
      value: 0x0a010000,
      x: 491,
      y: -178,
      w: 31,
      h: 33,
    },
    {
      keyName: 'r-Ctrl',
      value: 228,
      x: 536,
      y: -178,
      w: 31,
      h: 33,
    },
    {
      keyName: '←',
      value: 80,
      x: 593,
      y: -188,
      w: 31,
      h: 33,
    },
    {
      keyName: '↓',
      value: 81,
      x: 637,
      y: -188,
      w: 31,
      h: 33,
    },
    {
      keyName: '→',
      value: 79,
      x: 682,
      y: -188,
      w: 31,
      h: 33,
    },
  ],
}
