export const yzw_gm898 = {
  deltX: 16,
  deltY: 13,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'F1',
      value: 58,
      x: 45,
      y: 0,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'F2',
      value: 59,
      x: 90,
      y: 0,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'F3',
      value: 60,
      x: 135,
      y: 0,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'F4',
      value: 61,
      x: 180,
      y: 0,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'F5',
      value: 62,
      x: 225,
      y: 0,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'F6',
      value: 63,
      x: 270,
      y: 0,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'F7',
      value: 64,
      x: 315,
      y: 0,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'F8',
      value: 65,
      x: 359,
      y: 0,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'F9',
      value: 66,
      x: 405,
      y: 0,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'F10',
      value: 67,
      x: 449,
      y: 0,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'F11',
      value: 68,
      x: 494,
      y: 0,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'F12',
      value: 69,
      x: 538,
      y: 0,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'Print\nScreen',
      value: 70,
      x: 584,
      y: 0,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'Insert',
      value: 73,
      x: 629,
      y: 0,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'Home',
      value: 74,
      x: 675,
      y: 0,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'Delete',
      value: 76,
      x: 720,
      y: 0,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'Page\nUp',
      value: 75,
      x: 765,
      y: 0,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'Page\nDown',
      value: 78,
      x: 810,
      y: 0,
      w: 30, 
      h: 34, 
    },
    {
      keyName: '`',
      value: 53,
      x: 0,
      y: -44,
      w: 30, 
      h: 34, 
     },
    {
      keyName: '1',
      value: 30,
      x: 45,
      y: -44,
      w: 30, 
      h: 34, 
    },
    {
      keyName: '2',
      value: 31,
      x: 90,
      y: -44,
      w: 30, 
      h: 34, 
    },
    {
      keyName: '3',
      value: 32,
      x: 135,
      y: -44,
      w: 30, 
      h: 34, 
    },
    {
      keyName: '4',
      value: 33,
      x: 180,
      y: -44,
      w: 30, 
      h: 34, 
    },
    {
      keyName: '5',
      value: 34,
      x: 225,
      y: -44,
      w: 30, 
      h: 34, 
    },
    {
      keyName: '6',
      value: 35,
      x: 270,
      y: -44,
      w: 30, 
      h: 34, 
    },
    {
      keyName: '7',
      value: 36,
      x: 315,
      y: -44,
      w: 30, 
      h: 34, 
    },
    {
      keyName: '8',
      value: 37,
      x: 359,
      y: -44,
      w: 30, 
      h: 34, 
    },
    {
      keyName: '9',
      value: 38,
      x: 405,
      y: -44,
      w: 30, 
      h: 34, 
    },
    {
      keyName: '0',
      value: 39,
      x: 450,
      y: -44,
      w: 30, 
      h: 34, 
    },
    {
      keyName: '-',
      value: 45,
      x: 494,
      y: -44,
      w: 30, 
      h: 34, 
    },
    {
      keyName: '=',
      value: 46,
      x: 539,
      y: -44,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'Backspace',
      value: 42,
      x: 584,
      y: -44,
      w: 75, 
      h: 34, 
    },
    {
      keyName: 'Num\nLock',
      value: 83,
      x: 675,
      y: -44,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'num_/',
      value: 84,
      x: 720,
      y: -44,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'num_*',
      value: 85,
      x: 765,
      y: -44,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'num_-',
      value: 86,
      x: 810,
      y: -44,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -90,
      w: 54, 
      h: 34, 
    },
    {
      keyName: 'Q',
      value: 20,
      x: 68,
      y: -90,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'W',
      value: 26,
      x: 113,
      y: -90,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'E',
      value: 8,
      x: 158,
      y: -90,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'R',
      value: 21,
      x: 203,
      y: -90,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'T',
      value: 23,
      x: 248,
      y: -90,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'Y',
      value: 28,
      x: 293,
      y: -90,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'U',
      value: 24,
      x: 338,
      y: -90,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'I',
      value: 12,
      x: 382,
      y: -90,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'O',
      value: 18,
      x: 428,
      y: -90,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'P',
      value: 19,
      x: 473,
      y: -90,
      w: 30, 
      h: 34, 
    },
    {
      keyName: '[',
      value: 47,
      x: 517,
      y: -90,
      w: 30, 
      h: 34, 
    },
    {
      keyName: ']',
      value: 48,
      x: 562,
      y: -90,
      w: 30, 
      h: 34, 
    },
    {
      keyName: '\\',
      value: 49,
      x: 599,
      y: -90,
      w: 60, 
      h: 34, 
    },
    {
      keyName: 'num_7',
      value: 95,
      x: 675,
      y: -90,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'num_8',
      value: 96,
      x: 720,
      y: -90,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'num_9',
      value: 97,
      x: 765,
      y: -90,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'num_+',
      value: 87,
      x: 810,
      y: -90,
      w: 30, 
      h: 80, 
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -134,
      w: 68, 
      h: 34, 
    },
    {
      keyName: 'A',
      value: 4,
      x: 80,
      y: -134,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'S',
      value: 22,
      x: 124,
      y: -134,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'D',
      value: 7,
      x: 169,
      y: -134,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'F',
      value: 9,
      x: 214,
      y: -134,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'G',
      value: 10,
      x: 259,
      y: -134,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'H',
      value: 11,
      x: 303,
      y: -134,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'J',
      value: 13,
      x: 348,
      y: -134,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'K',
      value: 14,
      x: 392,
      y: -134,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'L',
      value: 15,
      x: 438,
      y: -134,
      w: 30, 
      h: 34, 
    },
    {
      keyName: ';',
      value: 51,
      x: 483,
      y: -134,
      w: 30, 
      h: 34, 
    },
    {
      keyName: '\'',
      value: 52,
      x: 527,
      y: -134,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 572,
      y: -134,
      w: 87, 
      h: 34, 
    },
    {
      keyName: 'num_4',
      value: 92,
      x: 675,
      y: -134,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'num_5',
      value: 93,
      x: 720,
      y: -134,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'num_6',
      value: 94,
      x: 765,
      y: -134,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -179,
      w: 90, 
      h: 34, 
    },
    {
      keyName: 'Z',
      value: 29,
      x: 103,
      y: -179,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'X',
      value: 27,
      x: 147,
      y: -179,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'C',
      value: 6,
      x: 192,
      y: -179,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'V',
      value: 25,
      x: 237,
      y: -179,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'B',
      value: 5,
      x: 282,
      y: -179,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'N',
      value: 17,
      x: 326,
      y: -179,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'M',
      value: 16,
      x: 371,
      y: -179,
      w: 30, 
      h: 34, 
    },
    {
      keyName: ',',
      value: 54,
      x: 415,
      y: -179,
      w: 30, 
      h: 34, 
    },
    {
      keyName: '.',
      value: 55,
      x: 461,
      y: -179,
      w: 30, 
      h: 34, 
    },
    {
      keyName: '/',
      value: 56,
      x: 506,
      y: -179,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'r_Shift',
      value: 229,
      x: 550,
      y: -179,
      w: 66, 
      h: 34, 
    },
    {
      keyName: '↑',
      value: 82,
      x: 630,
      y: -179,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'num_1',
      value: 89,
      x: 675,
      y: -179,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'num_2',
      value: 90,
      x: 720,
      y: -179,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'num_3',
      value: 91,
      x: 765,
      y: -179,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'num_Enter',
      value: 88,
      x: 810,
      y: -179,
      w: 30, 
      h: 80, 
    },
    {
      keyName: 'CTRL',
      value: 224,
      x: 0,
      y: -223,
      w: 45, 
      h: 34, 
    },
    {
      keyName: 'Win',
      value: 227,
      x: 56,
      y: -223,
      w: 45, 
      h: 34, 
    },
    {
      keyName: 'ALT',
      value: 226,
      x: 111,
      y: -223,
      w: 45, 
      h: 34, 
    },
    {
      keyName: '(space)',
      value: 44,
      x: 169,
      y: -223,
      w: 269, 
      h: 34, 
    },
    {
      keyName: 'r_Alt',
      value: 230,
      x: 451,
      y: -223,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'FN',
      value: 0x0a010000,
      x: 495,
      y: -223,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'r_Ctrl',
      value: 228,
      x: 539,
      y: -223,
      w: 30, 
      h: 34, 
    },
    {
      keyName: '←',
      value: 80,
      x: 585,
      y: -223,
      w: 30, 
      h: 34, 
    },
    {
      keyName: '↓',
      value: 81,
      x: 630,
      y: -223,
      w: 30, 
      h: 34, 
    },
    {
      keyName: '→',
      value: 79,
      x: 675,
      y: -223,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'num_0',
      value: 98,
      x: 720,
      y: -223,
      w: 30, 
      h: 34, 
    },
    {
      keyName: 'num_.',
      value: 99,
      x: 765,
      y: -223,
      w: 30, 
      h: 34, 
    },
  ],
}
