export const yzw_gm898_bt_2m = {
  deltX: 46,
  deltY: 24,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 27,
      h: 31,
     },
    {
      keyName: 'F1',
      value: 58,
      x: 41,
      y: 0,
      w: 27,
      h: 31,
    },
    {
      keyName: 'F2',
      value: 59,
      x: 83,
      y: 0,
      w: 27,
      h: 31,
    },
    {
      keyName: 'F3',
      value: 60,
      x: 125,
      y: 0,
      w: 27,
      h: 31,
    },
    {
      keyName: 'F4',
      value: 61,
      x: 168,
      y: 0,
      w: 27,
      h: 31,
    },
    {
      keyName: 'F5',
      value: 62,
      x: 209,
      y: 0,
      w: 27,
      h: 31,
    },
    {
      keyName: 'F6',
      value: 63,
      x: 251,
      y: 0,
      w: 27,
      h: 31,
    },
    {
      keyName: 'F7',
      value: 64,
      x: 292,
      y: 0,
      w: 27,
      h: 31,
    },
    {
      keyName: 'F8',
      value: 65,
      x: 334,
      y: 0,
      w: 27,
      h: 31,
    },
    {
      keyName: 'F9',
      value: 66,
      x: 377,
      y: 0,
      w: 27,
      h: 31,
    },
    {
      keyName: 'F10',
      value: 67,
      x: 418,
      y: 0,
      w: 27,
      h: 31,
    },
    {
      keyName: 'F11',
      value: 68,
      x: 460,
      y: 0,
      w: 27,
      h: 31,
    },
    {
      keyName: 'F12',
      value: 69,
      x: 501,
      y: 0,
      w: 27,
      h: 31,
    },
    {
      keyName: 'Print\nScreen',
      value: 70,
      x: 543,
      y: 0,
      w: 27,
      h: 31,
    },
    {
      keyName: 'Insert',
      value: 73,
      x: 585,
      y: 0,
      w: 27,
      h: 31,
    },
    {
      keyName: 'Home',
      value: 74,
      x: 627,
      y: 0,
      w: 27,
      h: 31,
    },
    {
      keyName: 'Delete',
      value: 76,
      x: 668,
      y: 0,
      w: 27,
      h: 31,
    },
    {
      keyName: 'Page\nUp',
      value: 75,
      x: 710,
      y: 0,
      w: 27,
      h: 31,
    },
    {
      keyName: 'Page\nDown',
      value: 78,
      x: 752,
      y: 0,
      w: 27,
      h: 31,
    },
    {
      keyName: '`',
      value: 53,
      x: 0,
      y: -41,
      w: 27,
      h: 31,
    },
    {
      keyName: '1',
      value: 30,
      x: 41,
      y: -41,
      w: 27,
      h: 31,
    },
    {
      keyName: '2',
      value: 31,
      x: 82,
      y: -41,
      w: 27,
      h: 31,
    },
    {
      keyName: '3',
      value: 32,
      x: 125,
      y: -41,
      w: 27,
      h: 31,
    },
    {
      keyName: '4',
      value: 33,
      x: 168,
      y: -41,
      w: 27,
      h: 31,
    },
    {
      keyName: '5',
      value: 34,
      x: 209,
      y: -41,
      w: 27,
      h: 31,
    },
    {
      keyName: '6',
      value: 35,
      x: 251,
      y: -41,
      w: 27,
      h: 31,
    },
    {
      keyName: '7',
      value: 36,
      x: 292,
      y: -41,
      w: 27,
      h: 31,
    },
    {
      keyName: '8',
      value: 37,
      x: 334,
      y: -41,
      w: 27,
      h: 31,
    },
    {
      keyName: '9',
      value: 38,
      x: 376,
      y: -41,
      w: 27,
      h: 31,
    },
    {
      keyName: '0',
      value: 39,
      x: 418,
      y: -41,
      w: 27,
      h: 31,
    },
    {
      keyName: '-',
      value: 45,
      x: 460,
      y: -41,
      w: 27,
      h: 31,
    },
    {
      keyName: '=',
      value: 46,
      x: 501,
      y: -41,
      w: 27,
      h: 31,
    },
    {
      keyName: 'BackSpace',
      value: 42,
      x: 543,
      y: -41,
      w: 69,
      h: 31,
    },
    {
      keyName: 'Num\nLock',
      value: 83,
      x: 627,
      y: -41,
      w: 27,
      h: 31,
    },
    {
      keyName: 'num_/',
      value: 84,
      x: 668,
      y: -41,
      w: 27,
      h: 31,
    },
    {
      keyName: 'num_*',
      value: 85,
      x: 710,
      y: -41,
      w: 27,
      h: 31,
    },
    {
      keyName: 'num_-',
      value: 86,
      x: 752,
      y: -41,
      w: 27,
      h: 31,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -82,
      w: 50,
      h: 31,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 62,
      y: -82,
      w: 27,
      h: 31,
    },
    {
      keyName: 'W',
      value: 26,
      x: 103,
      y: -82,
      w: 27,
      h: 31,
    },
    {
      keyName: 'E',
      value: 8,
      x: 146,
      y: -82,
      w: 27,
      h: 31,
    },
    {
      keyName: 'R',
      value: 21,
      x: 189,
      y: -82,
      w: 27,
      h: 31,
    },
    {
      keyName: 'T',
      value: 23,
      x: 230,
      y: -82,
      w: 27,
      h: 31,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 272,
      y: -82,
      w: 27,
      h: 31,
    },
    {
      keyName: 'U',
      value: 24,
      x: 312,
      y: -82,
      w: 27,
      h: 31,
    },
    {
      keyName: 'I',
      value: 12,
      x: 355,
      y: -82,
      w: 27,
      h: 31,
    },
    {
      keyName: 'O',
      value: 18,
      x: 397,
      y: -82,
      w: 27,
      h: 31,
    },
    {
      keyName: 'P',
      value: 19,
      x: 439,
      y: -82,
      w: 27,
      h: 31,
    },
    {
      keyName: '[',
      value: 47,
      x: 481,
      y: -82,
      w: 27,
      h: 31,
    },
    {
      keyName: ']',
      value: 48,
      x: 522,
      y: -82,
      w: 27,
      h: 31,
    },
    {
      keyName: '\\',
      value: 49,
      x: 564,
      y: -82,
      w: 48,
      h: 31,
    },
    {
      keyName: 'num_7',
      value: 95,
      x: 627,
      y: -82,
      w: 27,
      h: 31,
    },
    {
      keyName: 'num_8',
      value: 96,
      x: 668,
      y: -82,
      w: 27,
      h: 31,
    },
    {
      keyName: 'num_9',
      value: 97,
      x: 710,
      y: -82,
      w: 27,
      h: 31,
    },
    {
      keyName: 'num_+',
      value: 87,
      x: 752,
      y: -82,
      w: 27,
      h: 72,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -123,
      w: 58,
      h: 31,
    },
    {
      keyName: 'A',
      value: 4,
      x: 75,
      y: -123,
      w: 27,
      h: 31,
    },
    {
      keyName: 'S',
      value: 22,
      x: 116,
      y: -123,
      w: 27,
      h: 31,
    },
    {
      keyName: 'D',
      value: 7,
      x: 159,
      y: -123,
      w: 27,
      h: 31,
    },
    {
      keyName: 'F',
      value: 9,
      x: 200,
      y: -123,
      w: 27,
      h: 31,
    },
    {
      keyName: 'G',
      value: 10,
      x: 241,
      y: -123,
      w: 27,
      h: 31,
    },
    {
      keyName: 'H',
      value: 11,
      x: 283,
      y: -123,
      w: 27,
      h: 31,
    },
    {
      keyName: 'J',
      value: 13,
      x: 325,
      y: -123,
      w: 27,
      h: 31,
    },
    {
      keyName: 'K',
      value: 14,
      x: 367,
      y: -123,
      w: 27,
      h: 31,
    },
    {
      keyName: 'L',
      value: 15,
      x: 410,
      y: -123,
      w: 27,
      h: 31,
    },
    {
      keyName: ';',
      value: 51,
      x: 450,
      y: -123,
      w: 27,
      h: 31,
    },
    {
      keyName: '\'',
      value: 52,
      x: 491,
      y: -123,
      w: 27,
      h: 31,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 534,
      y: -123,
      w: 78,
      h: 31,
    },
    {
      keyName: 'num_4',
      value: 92,
      x: 627,
      y: -123,
      w: 27,
      h: 31,
    },
    {
      keyName: 'num_5',
      value: 93,
      x: 668,
      y: -123,
      w: 27,
      h: 31,
    },
    {
      keyName: 'num_6',
      value: 94,
      x: 710,
      y: -123,
      w: 27,
      h: 31,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -164,
      w: 82,
      h: 31,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 95,
      y: -164,
      w: 27,
      h: 31,
    },
    {
      keyName: 'X',
      value: 27,
      x: 136,
      y: -164,
      w: 27,
      h: 31,
    },
    {
      keyName: 'C',
      value: 6,
      x: 179,
      y: -164,
      w: 27,
      h: 31,
    },
    {
      keyName: 'V',
      value: 25,
      x: 220,
      y: -164,
      w: 27,
      h: 31,
    },
    {
      keyName: 'B',
      value: 5,
      x: 261,
      y: -164,
      w: 27,
      h: 31,
    },
    {
      keyName: 'N',
      value: 17,
      x: 303,
      y: -164,
      w: 27,
      h: 31,
    },
    {
      keyName: 'M',
      value: 16,
      x: 345,
      y: -164,
      w: 27,
      h: 31,
    },
    {
      keyName: ',',
      value: 54,
      x: 387,
      y: -164,
      w: 27,
      h: 31,
    },
    {
      keyName: '.',
      value: 55,
      x: 430,
      y: -164,
      w: 27,
      h: 31,
    },
    {
      keyName: '/',
      value: 56,
      x: 470,
      y: -164,
      w: 27,
      h: 31,
    },
    {
      keyName: 'r_Shift',
      value: 229,
      x: 513,
      y: -164,
      w: 57,
      h: 31,
    },
    {
      keyName: '↑',
      value: 82,
      x: 586,
      y: -164,
      w: 27,
      h: 31,
    },
    {
      keyName: 'num_1',
      value: 89,
      x: 627,
      y: -162,
      w: 27,
      h: 31,
    },
    {
      keyName: 'num_2',
      value: 90,
      x: 668,
      y: -162,
      w: 27,
      h: 31,
    },
    {
      keyName: 'num_3',
      value: 91,
      x: 710,
      y: -162,
      w: 27,
      h: 31,
    },
    {
      keyName: 'num_Enter',
      value: 88,
      x: 752,
      y: -162,
      w: 27,
      h: 72,
    },
    {
      keyName: 'Ctrl',
      value: 224,
      x: 0,
      y: -205,
      w: 39,
      h: 31,
    },
    {
      keyName: 'Win',
      value: 227,
      x: 53,
      y: -205,
      w: 39,
      h: 31,
    },
    {
      keyName: 'Alt',
      value: 226,
      x: 105,
      y: -205,
      w: 39,
      h: 31,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 156,
      y: -205,
      w: 245,
      h: 31,
    },
    {
      keyName: 'r_Alt',
      value: 230,
      x: 419,
      y: -205,
      w: 27,
      h: 31,
    },
    {
      keyName: 'fn',
      value: 0x0a010000,
      x: 460,
      y: -205,
      w: 27,
      h: 31,
    },
    {
      keyName: 'r_Ctrl',
      value: 228,
      x: 502,
      y: -205,
      w: 27,
      h: 31,
    },
    {
      keyName: '←',
      value: 80,
      x: 545,
      y: -205,
      w: 27,
      h: 31,
    },
    {
      keyName: '↓',
      value: 81,
      x: 585,
      y: -205,
      w: 27,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
      h: 31,
    },
    {
      keyName: '→',
      value: 79,
      x: 627,
      y: -205,
      w: 27,
      h: 31,
    },
    {
      keyName: 'num_0',
      value: 98,
      x: 668,
      y: -205,
      w: 27,
      h: 31,
    },
    {
      keyName: 'num_.',
      value: 99,
      x: 710,
      y: -205,
      w: 27,
      h: 31,
    },
  ],
}
