export const yzw_sk3 = {
  deltX: 88,
  deltY: 14,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 28,
      h: 28,
    },
    {
      keyName: '1',
      value: 30,
      x: 44,
      y: 0,
      w: 28,
      h: 28,
    },
    {
      keyName: '2',
      value: 31,
      x: 89,
      y: 0,
      w: 28,
      h: 28,
    },
    {
      keyName: '3',
      value: 32,
      x: 134,
      y: 0,
      w: 28,
      h: 28,
    },
    {
      keyName: '4',
      value: 33,
      x: 178,
      y: 0,
      w: 28,
      h: 28,
    },
    {
      keyName: '5',
      value: 34,
      x: 223,
      y: 0,
      w: 28,
      h: 28,
    },
    {
      keyName: '6',
      value: 35,
      x: 268,
      y: 0,
      w: 28,
      h: 28,
    },
    {
      keyName: '7',
      value: 36,
      x: 313,
      y: 0,
      w: 28,
      h: 28,
    },
    {
      keyName: '8',
      value: 37,
      x: 357,
      y: 0,
      w: 28,
      h: 28,
    },
    {
      keyName: '9',
      value: 38,
      x: 402,
      y: 0,
      w: 28,
      h: 28,
    },
    {
      keyName: '0',
      value: 39,
      x: 447,
      y: 0,
      w: 28,
      h: 28,
    },
    {
      keyName: '-',
      value: 45,
      x: 491,
      y: 0,
      w: 28,
      h: 28,
    },
    {
      keyName: '=',
      value: 46,
      x: 536,
      y: 0,
      w: 28,
      h: 28,
    },
    {
      keyName: 'Backspace',
      value: 42,
      x: 581,
      y: 0,
      w: 73,
      h: 28,
    },
    {
      keyName: 'Home',
      value: 74,
      x: 670,
      y: 0,
      w: 28,
      h: 28,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -44,
      w: 49,
      h: 28,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 66,
      y: -44,
      w: 28,
      h: 28,
    },
    {
      keyName: 'W',
      value: 26,
      x: 111,
      y: -44,
      w: 28,
      h: 28,
    },
    {
      keyName: 'E',
      value: 8,
      x: 156,
      y: -44,
      w: 28,
      h: 28,
    },
    {
      keyName: 'R',
      value: 21,
      x: 201,
      y: -44,
      w: 28,
      h: 28,
    },
    {
      keyName: 'T',
      value: 23,
      x: 245,
      y: -44,
      w: 28,
      h: 28,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 290,
      y: -44,
      w: 28,
      h: 28,
    },
    {
      keyName: 'U',
      value: 24,
      x: 335,
      y: -44,
      w: 28,
      h: 28,
    },
    {
      keyName: 'I',
      value: 12,
      x: 379,
      y: -44,
      w: 28,
      h: 28,
    },
    {
      keyName: 'O',
      value: 18,
      x: 424,
      y: -44,
      w: 28,
      h: 28,
    },
    {
      keyName: 'P',
      value: 19,
      x: 469,
      y: -44,
      w: 28,
      h: 28,
    },
    {
      keyName: '[',
      value: 47,
      x: 514,
      y: -44,
      w: 28,
      h: 28,
    },
    {
      keyName: ']',
      value: 48,
      x: 559,
      y: -44,
      w: 28,
      h: 28,
    },
    {
      keyName: '\\',
      value: 49,
      x: 603,
      y: -44,
      w: 51,
      h: 28,
    },
    {
      keyName: 'Delete',
      value: 76,
      x: 670,
      y: -44,
      w: 28,
      h: 28,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -88,
      w: 61,
      h: 28,
    },
    {
      keyName: 'A',
      value: 4,
      x: 77,
      y: -88,
      w: 28,
      h: 28,
    },
    {
      keyName: 'S',
      value: 22,
      x: 122,
      y: -88,
      w: 28,
      h: 28,
    },
    {
      keyName: 'D',
      value: 7,
      x: 167,
      y: -88,
      w: 28,
      h: 28,
    },
    {
      keyName: 'F',
      value: 9,
      x: 212,
      y: -88,
      w: 28,
      h: 28,
    },
    {
      keyName: 'G',
      value: 10,
      x: 256,
      y: -88,
      w: 28,
      h: 28,
    },
    {
      keyName: 'H',
      value: 11,
      x: 301,
      y: -88,
      w: 28,
      h: 28,
    },
    {
      keyName: 'J',
      value: 13,
      x: 346,
      y: -88,
      w: 28,
      h: 28,
    },
    {
      keyName: 'K',
      value: 14,
      x: 390,
      y: -88,
      w: 28,
      h: 28,
    },
    {
      keyName: 'L',
      value: 15,
      x: 435,
      y: -88,
      w: 28,
      h: 28,
    },
    {
      keyName: ';',
      value: 51,
      x: 480,
      y: -88,
      w: 28,
      h: 28,
    },
    {
      keyName: '"',
      value: 52,
      x: 525,
      y: -88,
      w: 28,
      h: 28,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 570,
      y: -88,
      w: 84,
      h: 28,
    },
    {
      keyName: 'Page\nUp',
      value: 75,
      x: 670,
      y: -88,
      w: 28,
      h: 28,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -133,
      w: 83,
      h: 28,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 100,
      y: -133,
      w: 28,
      h: 28,
    },
    {
      keyName: 'X',
      value: 27,
      x: 145,
      y: -133,
      w: 28,
      h: 28,
    },
    {
      keyName: 'C',
      value: 6,
      x: 190,
      y: -133,
      w: 28,
      h: 28,
    },
    {
      keyName: 'V',
      value: 25,
      x: 235,
      y: -133,
      w: 28,
      h: 28,
    },
    {
      keyName: 'B',
      value: 5,
      x: 279,
      y: -133,
      w: 28,
      h: 28,
    },
    {
      keyName: 'N',
      value: 17,
      x: 324,
      y: -133,
      w: 28,
      h: 28,
    },
    {
      keyName: 'M',
      value: 16,
      x: 368,
      y: -133,
      w: 28,
      h: 28,
    },
    {
      keyName: ',',
      value: 54,
      x: 413,
      y: -133,
      w: 28,
      h: 28,
    },
    {
      keyName: '.',
      value: 55,
      x: 458,
      y: -133,
      w: 28,
      h: 28,
    },
    {
      keyName: '/',
      value: 56,
      x: 502,
      y: -133,
      w: 28,
      h: 28,
    },
    {
      keyName: 'R-Shift',
      value: 229,
      x: 547,
      y: -133,
      w: 61,
      h: 28,
    },
    {
      keyName: '↑',
      value: 82,
      x: 625,
      y: -133,
      w: 28,
      h: 28,
    },
    {
      keyName: 'Page\nDown',
      value: 78,
      x: 670,
      y: -133,
      w: 28,
      h: 28,
    },
    {
      keyName: 'Fn',
      value: 0x0a010000,
      x: 0,
      y: -177,
      w: 28,
      h: 28,
    },
    {
      keyName: 'Ctrl',
      value: 224,
      x: 44,
      y: -177,
      w: 28,
      h: 28,
    },
    {
      keyName: 'Win',
      value: 227,
      x: 88,
      y: -177,
      w: 28,
      h: 28,
    },
    {
      keyName: 'Alt',
      value: 226,
      x: 133,
      y: -177,
      w: 39,
      h: 28,
    },
    {
      keyName: '(space)',
      index: 1,
      value: 44,
      x: 189,
      y: -177,
      w: 263,
      h: 28,
    },
    {
      keyName: 'r-Alt',
      value: 230,
      x: 469,
      y: -177,
      w: 39,
      h: 28,
    },
    {
      keyName: '(Application)',
      value: 101,
      x: 525,
      y: -177,
      w: 39,
      h: 28,
    },
    {
      keyName: '←',
      value: 80,
      x: 581,
      y: -177,
      w: 28,
      h: 28,
    },
    {
      keyName: '↓',
      value: 81,
      x: 625,
      y: -177,
      w: 28,
      h: 28,
    },
    {
      keyName: '→',
      value: 79,
      x: 670,
      y: -177,
      w: 28,
      h: 28,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 190,
      y: -237,
      w: 83,
      h: 26,
    },
    {
      keyName: '(space)',
      index: 1,
      value: 44,
      x: 290,
      y: -237,
      w: 62,
      h: 26,
    },
    {
      keyName: '(space)',
      index: 2,
      value: 44,
      x: 369,
      y: -237,
      w: 83,
      h: 26,
    },
  ],
}
