export const yzw_fk2102t_uk = {
  deltX: 72,
  deltY: 7,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 34,
      h: 34,
     },
    {
      keyName: 'F1',
      value: 58,
      x: 46,
      y: 0,
      w: 34,
      h: 34,
    },
    {
      keyName: 'F2',
      value: 59,
      x: 92,
      y: 0,
      w: 34,
      h: 34,
    },
    {
      keyName: 'F3',
      value: 60,
      x: 138,
      y: 0,
      w: 34,
      h: 34,
    },
    {
      keyName: 'F4',
      value: 61,
      x: 185,
      y: 0,
      w: 34,
      h: 34,
    },
    {
      keyName: 'F5',
      value: 62,
      x: 231,
      y: 0,
      w: 34,
      h: 34,
    },
    {
      keyName: 'F6',
      value: 63,
      x: 277,
      y: 0,
      w: 34,
      h: 34,
    },
    {
      keyName: 'F7',
      value: 64,
      x: 323,
      y: 0,
      w: 34,
      h: 34,
    },
    {
      keyName: 'F8',
      value: 65,
      x: 369,
      y: 0,
      w: 34,
      h: 34,
    },
    {
      keyName: 'F9',
      value: 66,
      x: 415,
      y: 0,
      w: 34,
      h: 34,
    },
    {
      keyName: 'F10',
      value: 67,
      x: 461,
      y: 0,
      w: 34,
      h: 34,
    },
    {
      keyName: 'F11',
      value: 68,
      x: 508,
      y: 0,
      w: 34,
      h: 34,
    },
    {
      keyName: 'F12',
      value: 69,
      x: 554,
      y: 0,
      w: 34,
      h: 34,
    },
    {
      keyName: 'Print\nScreen',
      value: 70,
      x: 600,
      y: 0,
      w: 34,
      h: 34,
    },
    {
      keyName: 'Insert',
      value: 73,
      x: 646,
      y: 0,
      w: 34,
      h: 34,
    },
    {
      keyName: 'Delete',
      value: 76,
      x: 692,
      y: 0,
      w: 34,
      h: 34,
    },
    {
      keyName: '`',
      value: 53,
      x: 0,
      y: -46,
      w: 34,
      h: 34,
    },
    {
      keyName: '1',
      value: 30,
      x: 46,
      y: -46,
      w: 34,
      h: 34,
    },
    {
      keyName: '2',
      value: 31,
      x: 92,
      y: -46,
      w: 34,
      h: 34,
    },
    {
      keyName: '3',
      value: 32,
      x: 138,
      y: -46,
      w: 34,
      h: 34,
    },
    {
      keyName: '4',
      value: 33,
      x: 185,
      y: -46,
      w: 34,
      h: 34,
    },
    {
      keyName: '5',
      value: 34,
      x: 231,
      y: -46,
      w: 34,
      h: 34,
    },
    {
      keyName: '6',
      value: 35,
      x: 277,
      y: -46,
      w: 34,
      h: 34,
    },
    {
      keyName: '7',
      value: 36,
      x: 323,
      y: -46,
      w: 34,
      h: 34,
    },
    {
      keyName: '8',
      value: 37,
      x: 369,
      y: -46,
      w: 34,
      h: 34,
    },
    {
      keyName: '9',
      value: 38,
      x: 415,
      y: -46,
      w: 34,
      h: 34,
    },
    {
      keyName: '0',
      value: 39,
      x: 461,
      y: -46,
      w: 34,
      h: 34,
    },
    {
      keyName: '-',
      value: 45,
      x: 508,
      y: -46,
      w: 34,
      h: 34,
    },
    {
      keyName: '=',
      value: 46,
      x: 554,
      y: -46,
      w: 34,
      h: 34,
    },
    {
      keyName: 'BackSpace',
      value: 42,
      x: 600,
      y: -46,
      w: 80,
      h: 34,
    },
    {
      keyName: 'Home',
      value: 74,
      x: 692,
      y: -46,
      w: 34,
      h: 34,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -93,
      w: 57,
      h: 34,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 70,
      y: -93,
      w: 34,
      h: 34,
    },
    {
      keyName: 'W',
      value: 26,
      x: 116,
      y: -93,
      w: 34,
      h: 34,
    },
    {
      keyName: 'E',
      value: 8,
      x: 163,
      y: -93,
      w: 34,
      h: 34,
    },
    {
      keyName: 'R',
      value: 21,
      x: 209,
      y: -93,
      w: 34,
      h: 34,
    },
    {
      keyName: 'T',
      value: 23,
      x: 255,
      y: -93,
      w: 34,
      h: 34,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 301,
      y: -93,
      w: 34,
      h: 34,
    },
    {
      keyName: 'U',
      value: 24,
      x: 347,
      y: -93,
      w: 34,
      h: 34,
    },
    {
      keyName: 'I',
      value: 12,
      x: 393,
      y: -93,
      w: 34,
      h: 34,
    },
    {
      keyName: 'O',
      value: 18,
      x: 439,
      y: -93,
      w: 34,
      h: 34,
    },
    {
      keyName: 'P',
      value: 19,
      x: 486,
      y: -93,
      w: 34,
      h: 34,
    },
    {
      keyName: '[',
      value: 47,
      x: 532,
      y: -93,
      w: 34,
      h: 34,
    },
    {
      keyName: ']',
      value: 48,
      x: 577,
      y: -93,
      w: 34,
      h: 34,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 634,
      y: -93,
      w: 46,
      h: 81,
    },
    {
      keyName: 'End',
      value: 77,
      x: 692,
      y: -93,
      w: 34,
      h: 34,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -139,
      w: 70,
      h: 34,
    },
    {
      keyName: 'A',
      value: 4,
      x: 81,
      y: -139,
      w: 34,
      h: 34,
    },
    {
      keyName: 'S',
      value: 22,
      x: 127,
      y: -139,
      w: 34,
      h: 34,
    },
    {
      keyName: 'D',
      value: 7,
      x: 174,
      y: -139,
      w: 34,
      h: 34,
    },
    {
      keyName: 'F',
      value: 9,
      x: 220,
      y: -139,
      w: 34,
      h: 34,
    },
    {
      keyName: 'G',
      value: 10,
      x: 266,
      y: -139,
      w: 34,
      h: 34,
    },
    {
      keyName: 'H',
      value: 11,
      x: 312,
      y: -139,
      w: 34,
      h: 34,
    },
    {
      keyName: 'J',
      value: 13,
      x: 358,
      y: -139,
      w: 34,
      h: 34,
    },
    {
      keyName: 'K',
      value: 14,
      x: 404,
      y: -139,
      w: 34,
      h: 34,
    },
    {
      keyName: 'L',
      value: 15,
      x: 450,
      y: -139,
      w: 34,
      h: 34,
    },
    {
      keyName: ';',
      value: 51,
      x: 497,
      y: -139,
      w: 34,
      h: 34,
    },
    {
      keyName: '\'',
      value: 52,
      x: 543,
      y: -139,
      w: 34,
      h: 34,
    },
    {
      keyName: '\\',
      value: 50,
      x: 588,
      y: -139,
      w: 34,
      h: 34,
    },
    {
      keyName: 'Page\nUp',
      value: 75,
      x: 692,
      y: -139,
      w: 34,
      h: 34,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -185,
      w: 46,
      h: 34,
    },
    {
      keyName: '\\',
      value: 100,
      x: 58,
      y: -185,
      w: 34,
      h: 34,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 104,
      y: -185,
      w: 34,
      h: 34,
    },
    {
      keyName: 'X',
      value: 27,
      x: 151,
      y: -185,
      w: 34,
      h: 34,
    },
    {
      keyName: 'C',
      value: 6,
      x: 197,
      y: -185,
      w: 34,
      h: 34,
    },
    {
      keyName: 'V',
      value: 25,
      x: 243,
      y: -185,
      w: 34,
      h: 34,
    },
    {
      keyName: 'B',
      value: 5,
      x: 289,
      y: -185,
      w: 34,
      h: 34,
    },
    {
      keyName: 'N',
      value: 17,
      x: 335,
      y: -185,
      w: 34,
      h: 34,
    },
    {
      keyName: 'M',
      value: 16,
      x: 381,
      y: -185,
      w: 34,
      h: 34,
    },
    {
      keyName: ',',
      value: 54,
      x: 427,
      y: -185,
      w: 34,
      h: 34,
    },
    {
      keyName: '.',
      value: 55,
      x: 474,
      y: -185,
      w: 34,
      h: 34,
    },
    {
      keyName: '/',
      value: 56,
      x: 520,
      y: -185,
      w: 34,
      h: 34,
    },
    {
      keyName: 'r_Shift',
      value: 229,
      x: 565,
      y: -185,
      w: 69,
      h: 34,
    },
    {
      keyName: '↑',
      value: 82,
      x: 646,
      y: -185,
      w: 34,
      h: 34,
    },
    {
      keyName: 'Page\nDown',
      value: 78,
      x: 692,
      y: -185,
      w: 34,
      h: 34,
    },
    {
      keyName: 'Ctrl',
      value: 224,
      x: 0,
      y: -232,
      w: 46,
      h: 34,
    },
    {
      keyName: 'Win',
      value: 227,
      x: 58,
      y: -232,
      w: 46,
      h: 34,
    },
    {
      keyName: 'Alt',
      value: 226,
      x: 115,
      y: -232,
      w: 46,
      h: 34,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 174,
      y: -232,
      w: 276,
      h: 34,
    },
    {
      keyName: 'r_Alt',
      value: 230,
      x: 460,
      y: -232,
      w: 34,
      h: 34,
    },
    {
      keyName: 'fn',
      value: 0x0a010000,
      x: 506,
      y: -232,
      w: 34,
      h: 34,
    },
    {
      keyName: 'r_Ctrl',
      value: 228,
      x: 552,
      y: -232,
      w: 34,
      h: 34,
    },
    {
      keyName: '←',
      value: 80,
      x: 598,
      y: -232,
      w: 34,
      h: 34,
    },
    {
      keyName: '↓',
      value: 81,
      x: 645,
      y: -232,
      w: 34,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
      h: 34,
    },
    {
      keyName: '→',
      value: 79,
      x: 691,
      y: -232,
      w: 34,
      h: 34,
    },
  ],
}
