export const yzw_zen67 = {
  deltX: 70,
  deltY: 37,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 30,
      h: 35,
    },
    {
      keyName: '1',
      value: 30,
      x: 45,
      y: 0,
      w: 30,
      h: 35,
    },
    {
      keyName: '2',
      value: 31,
      x: 90,
      y: 0,
      w: 30,
      h: 35,
    },
    {
      keyName: '3',
      value: 32,
      x: 135,
      y: 0,
      w: 30,
      h: 35,
    },
    {
      keyName: '4',
      value: 33,
      x: 180,
      y: 0,
      w: 30,
      h: 35,
    },
    {
      keyName: '5',
      value: 34,
      x: 226,
      y: 0,
      w: 30,
      h: 35,
    },
    {
      keyName: '6',
      value: 35,
      x: 271,
      y: 0,
      w: 30,
      h: 35,
    },
    {
      keyName: '7',
      value: 36,
      x: 316,
      y: 0,
      w: 30,
      h: 35,
    },
    {
      keyName: '8',
      value: 37,
      x: 361,
      y: 0,
      w: 30,
      h: 35,
    },
    {
      keyName: '9',
      value: 38,
      x: 407,
      y: 0,
      w: 30,
      h: 35,
    },
    {
      keyName: '0',
      value: 39,
      x: 452,
      y: 0,
      w: 30,
      h: 35,
    },
    {
      keyName: '-',
      value: 45,
      x: 497,
      y: 0,
      w: 30,
      h: 35,
    },
    {
      keyName: '=',
      value: 46,
      x: 542,
      y: 0,
      w: 30,
      h: 35,
    },
    {
      keyName: 'Backspace',
      value: 42,
      x: 587,
      y: 0,
      w: 75,
      h: 35,
    },
    {
      keyName: 'U-',
      value: 0x0300ea00,
      knob: true,
      x: 682,
      y: 23,
      w: 17,
      h: 62,
    },
    {
      keyName: 'play',
      value: 0x0300cd00,
      knob: true,
      x: 708,
      y: 23,
      w: 17,
      h: 62,
    },
    {
      keyName: 'U+',
      value: 0x0300e900,
      knob: true,
      x: 734,
      y: 23,
      w: 17,
      h: 62,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -45,
      w: 52,
      h: 35,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 68,
      y: -45,
      w: 30,
      h: 35,
    },
    {
      keyName: 'W',
      value: 26,
      x: 113,
      y: -45,
      w: 30,
      h: 35,
    },
    {
      keyName: 'E',
      value: 8,
      x: 158,
      y: -45,
      w: 30,
      h: 35,
    },
    {
      keyName: 'R',
      value: 21,
      x: 203,
      y: -45,
      w: 30,
      h: 35,
    },
    {
      keyName: 'T',
      value: 23,
      x: 249,
      y: -45,
      w: 30,
      h: 35,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 294,
      y: -45,
      w: 30,
      h: 35,
    },
    {
      keyName: 'U',
      value: 24,
      x: 339,
      y: -45,
      w: 30,
      h: 35,
    },
    {
      keyName: 'I',
      value: 12,
      x: 384,
      y: -45,
      w: 30,
      h: 35,
    },
    {
      keyName: 'O',
      value: 18,
      x: 429,
      y: -45,
      w: 30,
      h: 35,
    },
    {
      keyName: 'P',
      value: 19,
      x: 474,
      y: -45,
      w: 30,
      h: 35,
    },
    {
      keyName: '[',
      value: 47,
      x: 519,
      y: -45,
      w: 30,
      h: 35,
    },
    {
      keyName: ']',
      value: 48,
      x: 564,
      y: -45,
      w: 30,
      h: 35,
    },
    {
      keyName: '\\',
      value: 49,
      x: 610,
      y: -45,
      w: 52,
      h: 35,
    },
    {
      keyName:'Delete',
      value: 76,
      x: 701,
      y: -45,
      w: 30,
      h: 35,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -90,
      w: 63,
      h: 35,
    },
    {
      keyName: 'A',
      value: 4,
      x: 79,
      y: -90,
      w: 30,
      h: 35,
    },
    {
      keyName: 'S',
      value: 22,
      x: 125,
      y: -90,
      w: 30,
      h: 35,
    },
    {
      keyName: 'D',
      value: 7,
      x: 170,
      y: -90,
      w: 30,
      h: 35,
    },
    {
      keyName: 'F',
      value: 9,
      x: 215,
      y: -90,
      w: 30,
      h: 35,
    },
    {
      keyName: 'G',
      value: 10,
      x: 260,
      y: -90,
      w: 30,
      h: 35,
    },
    {
      keyName: 'H',
      value: 11,
      x: 305,
      y: -90,
      w: 30,
      h: 35,
    },
    {
      keyName: 'J',
      value: 13,
      x: 350,
      y: -90,
      w: 30,
      h: 35,
    },
    {
      keyName: 'K',
      value: 14,
      x: 395,
      y: -90,
      w: 30,
      h: 35,
    },
    {
      keyName: 'L',
      value: 15,
      x: 440,
      y: -90,
      w: 30,
      h: 35,
    },
    {
      keyName: ';',
      value: 51,
      x: 485,
      y: -90,
      w: 30,
      h: 35,
    },
    {
      keyName: '"',
      value: 52,
      x: 530,
      y: -90,
      w: 30,
      h: 35,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 575,
      y: -90,
      w: 87,
      h: 35,
    },
    {
      keyName: 'PgUp',
      value: 75,
      x: 701,
      y: -90,
      w: 30,
      h: 35,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -135,
      w: 87,
      h: 35,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 102,
      y: -135,
      w: 30,
      h: 35,
    },
    {
      keyName: 'X',
      value: 27,
      x: 147,
      y: -135,
      w: 30,
      h: 35,
    },
    {
      keyName: 'C',
      value: 6,
      x: 193,
      y: -135,
      w: 30,
      h: 35,
    },
    {
      keyName: 'V',
      value: 25,
      x: 238,
      y: -135,
      w: 30,
      h: 35,
    },
    {
      keyName: 'B',
      value: 5,
      x: 283,
      y: -135,
      w: 30,
      h: 35,
    },
    {
      keyName: 'N',
      value: 17,
      x: 328,
      y: -135,
      w: 30,
      h: 35,
    },
    {
      keyName: 'M',
      value: 16,
      x: 373,
      y: -135,
      w: 30,
      h: 35,
    },
    {
      keyName: ',',
      value: 54,
      x: 418,
      y: -135,
      w: 30,
      h: 35,
    },
    {
      keyName: '.',
      value: 55,
      x: 463,
      y: -135,
      w: 30,
      h: 35,
    },
    {
      keyName: '/',
      value: 56,
      x: 508,
      y: -135,
      w: 30,
      h: 35,
    },
    {
      keyName: 'R-Shift',
      value: 229,
      x: 553,
      y: -135,
      w: 63,
      h: 35,
    },
    {
      keyName: '↑',
      value: 82,
      x: 644,
      y: -146,
      w: 30,
      h: 35,
    },
    {
      keyName: 'PgDn',
      value:  78,
      x: 701,
      y: -135,
      w: 30,
      h: 35,
    },
    {
      keyName: 'Ctrl',
      value: 224,
      x: 0,
      y: -180,
      w: 41,
      h: 35,
    },
    {
      keyName: 'win',
      value: 227,
      x: 57,
      y: -180,
      w: 41,
      h: 35,
    },
    {
      keyName: 'Alt',
      value: 226,
      x: 113,
      y: -180,
      w: 41,
      h: 35,
    },
    {
      keyName: 'space',
      value: 44,
      x: 170,
      y: -180,
      w: 267,
      h: 35,
    },
    {
      keyName: 'R-Alt',
      value: 230,
      x: 452,
      y: -180,
      w: 30,
      h: 35,
    },
    {
      keyName: 'Fn',
      value: 0x0a010000,
      x: 497,
      y: -180,
      w: 30,
      h: 35,
    },
    {
      keyName: 'R-Ctrl',
      value: 228,
      x: 542,
      y: -180,
      w: 30,
      h: 35,
    },
    {
      keyName: '←',
      value: 80,
      x: 599,
      y: -191,
      w: 30,
      h: 35,
    },
    {
      keyName: '↓',
      value: 81,
      x: 644,
      y: -191,
      w: 30,
      h: 35,
    },
    {
      keyName: '→',
      value: 79,
      x: 689,
      y: -191,
      w: 30,
      h: 35,
    },
  ],
}
