export const yzw_kl_k84_dm = {
  deltX: 110,
  deltY: 32,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 31,
      h: 32,
     },
    {
      keyName: 'F1',
      value: 58,
      x: 40,
      y: 0,
      w: 31,
      h: 32,
    },
    {
      keyName: 'F2',
      value: 59,
      x: 82,
      y: 0,
      w: 31,
      h: 32,
    },
    {
      keyName: 'F3',
      value: 60,
      x: 123,
      y: 0,
      w: 31,
      h: 32,
    },
    {
      keyName: 'F4',
      value: 61,
      x: 164,
      y: 0,
      w: 31,
      h: 32,
    },
    {
      keyName: 'F5',
      value: 62,
      x: 206,
      y: 0,
      w: 31,
      h: 32,
    },
    {
      keyName: 'F6',
      value: 63,
      x: 247,
      y: 0,
      w: 31,
      h: 32,
    },
    {
      keyName: 'F7',
      value: 64,
      x: 288,
      y: 0,
      w: 31,
      h: 32,
    },
    {
      keyName: 'F8',
      value: 65,
      x: 330,
      y: 0,
      w: 31,
      h: 32,
    },
    {
      keyName: 'F9',
      value: 66,
      x: 371,
      y: 0,
      w: 31,
      h: 32,
    },
    {
      keyName: 'F10',
      value: 67,
      x: 413,
      y: 0,
      w: 31,
      h: 32,
    },
    {
      keyName: 'F11',
      value: 68,
      x: 454,
      y: 0,
      w: 31,
      h: 32,
    },
    {
      keyName: 'F12',
      value: 69,
      x: 496,
      y: 0,
      w: 31,
      h: 32,
    },
    {
      keyName: 'Print\nScreen',
      value: 70,
      x: 537,
      y: 0,
      w: 31,
      h: 32,
    },
    {
      keyName: 'Pause',
      value: 72,
      x: 579,
      y: 0,
      w: 31,
      h: 32,
    },
    {
      keyName: 'Delete',
      value: 76,
      x: 619,
      y: 0,
      w: 31,
      h: 32,
    },
    {
      keyName: '`',
      value: 53,
      x: 0,
      y: -42,
      w: 31,
      h: 32,
    },
    {
      keyName: '1',
      value: 30,
      x: 40,
      y: -42,
      w: 31,
      h: 32,
    },
    {
      keyName: '2',
      value: 31,
      x: 82,
      y: -42,
      w: 31,
      h: 32,
    },
    {
      keyName: '3',
      value: 32,
      x: 123,
      y: -42,
      w: 31,
      h: 32,
    },
    {
      keyName: '4',
      value: 33,
      x: 165,
      y: -42,
      w: 31,
      h: 32,
    },
    {
      keyName: '5',
      value: 34,
      x: 205,
      y: -42,
      w: 31,
      h: 32,
    },
    {
      keyName: '6',
      value: 35,
      x: 247,
      y: -42,
      w: 31,
      h: 32,
    },
    {
      keyName: '7',
      value: 36,
      x: 288,
      y: -42,
      w: 31,
      h: 32,
    },
    {
      keyName: '8',
      value: 37,
      x: 330,
      y: -42,
      w: 31,
      h: 32,
    },
    {
      keyName: '9',
      value: 38,
      x: 370,
      y: -42,
      w: 31,
      h: 32,
    },
    {
      keyName: '0',
      value: 39,
      x: 412,
      y: -42,
      w: 31,
      h: 32,
    },
    {
      keyName: '-',
      value: 45,
      x: 453,
      y: -42,
      w: 31,
      h: 32,
    },
    {
      keyName: '=',
      value: 46,
      x: 495,
      y: -42,
      w: 31,
      h: 32,
    },
    {
      keyName: 'BackSpace',
      value: 42,
      x: 536,
      y: -42,
      w: 73,
      h: 32,
    },
    {
      keyName: 'Home',
      value: 74,
      x: 619,
      y: -42,
      w: 31,
      h: 32,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -83,
      w: 53,
      h: 32,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 61,
      y: -83,
      w: 31,
      h: 32,
    },
    {
      keyName: 'W',
      value: 26,
      x: 103,
      y: -83,
      w: 31,
      h: 32,
    },
    {
      keyName: 'E',
      value: 8,
      x: 144,
      y: -83,
      w: 31,
      h: 32,
    },
    {
      keyName: 'R',
      value: 21,
      x: 184,
      y: -83,
      w: 31,
      h: 32,
    },
    {
      keyName: 'T',
      value: 23,
      x: 226,
      y: -83,
      w: 31,
      h: 32,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 267,
      y: -83,
      w: 31,
      h: 32,
    },
    {
      keyName: 'U',
      value: 24,
      x: 309,
      y: -83,
      w: 31,
      h: 32,
    },
    {
      keyName: 'I',
      value: 12,
      x: 350,
      y: -83,
      w: 31,
      h: 32,
    },
    {
      keyName: 'O',
      value: 18,
      x: 391,
      y: -83,
      w: 31,
      h: 32,
    },
    {
      keyName: 'P',
      value: 19,
      x: 433,
      y: -83,
      w: 31,
      h: 32,
    },
    {
      keyName: '[',
      value: 47,
      x: 474,
      y: -83,
      w: 31,
      h: 32,
    },
    {
      keyName: ']',
      value: 48,
      x: 515,
      y: -83,
      w: 31,
      h: 32,
    },
    {
      keyName: '\\',
      value: 49,
      x: 557,
      y: -83,
      w: 52,
      h: 32,
    },
    {
      keyName: 'End',
      value: 77,
      x: 619,
      y: -83,
      w: 31,
      h: 32,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -124,
      w: 63,
      h: 32,
    },
    {
      keyName: 'A',
      value: 4,
      x: 71,
      y: -124,
      w: 31,
      h: 32,
    },
    {
      keyName: 'S',
      value: 22,
      x: 113,
      y: -124,
      w: 31,
      h: 32,
    },
    {
      keyName: 'D',
      value: 7,
      x: 153,
      y: -124,
      w: 31,
      h: 32,
    },
    {
      keyName: 'F',
      value: 9,
      x: 195,
      y: -124,
      w: 31,
      h: 32,
    },
    {
      keyName: 'G',
      value: 10,
      x: 236,
      y: -124,
      w: 31,
      h: 32,
    },
    {
      keyName: 'H',
      value: 11,
      x: 278,
      y: -124,
      w: 31,
      h: 32,
    },
    {
      keyName: 'J',
      value: 13,
      x: 318,
      y: -124,
      w: 31,
      h: 32,
    },
    {
      keyName: 'K',
      value: 14,
      x: 362,
      y: -124,
      w: 31,
      h: 32,
    },
    {
      keyName: 'L',
      value: 15,
      x: 402,
      y: -124,
      w: 31,
      h: 32,
    },
    {
      keyName: ';',
      value: 51,
      x: 443,
      y: -124,
      w: 31,
      h: 32,
    },
    {
      keyName: '\'',
      value: 52,
      x: 485,
      y: -124,
      w: 31,
      h: 32,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 526,
      y: -124,
      w: 83,
      h: 32,
    },
    {
      keyName: 'Page\nUp',
      value: 75,
      x: 618,
      y: -124,
      w: 31,
      h: 32,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -166,
      w: 82,
      h: 32,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 92,
      y: -166,
      w: 31,
      h: 32,
    },
    {
      keyName: 'X',
      value: 27,
      x: 133,
      y: -166,
      w: 31,
      h: 32,
    },
    {
      keyName: 'C',
      value: 6,
      x: 174,
      y: -166,
      w: 31,
      h: 32,
    },
    {
      keyName: 'V',
      value: 25,
      x: 215,
      y: -166,
      w: 31,
      h: 32,
    },
    {
      keyName: 'B',
      value: 5,
      x: 256,
      y: -166,
      w: 31,
      h: 32,
    },
    {
      keyName: 'N',
      value: 17,
      x: 298,
      y: -166,
      w: 31,
      h: 32,
    },
    {
      keyName: 'M',
      value: 16,
      x: 338,
      y: -166,
      w: 31,
      h: 32,
    },
    {
      keyName: ',',
      value: 54,
      x: 381,
      y: -166,
      w: 31,
      h: 32,
    },
    {
      keyName: '.',
      value: 55,
      x: 422,
      y: -166,
      w: 31,
      h: 32,
    },
    {
      keyName: '/',
      value: 56,
      x: 464,
      y: -166,
      w: 31,
      h: 32,
    },
    {
      keyName: 'r_Shift',
      value: 229,
      x: 505,
      y: -166,
      w: 62,
      h: 32,
    },
    {
      keyName: '↑',
      value: 82,
      x: 578,
      y: -166,
      w: 31,
      h: 32,
    },
    {
      keyName: 'Page\nDown',
      value: 78,
      x: 619,
      y: -166,
      w: 31,
      h: 32,
    },
    {
      keyName: 'Ctrl',
      value: 224,
      x: 0,
      y: -208,
      w: 41,
      h: 32,
    },
    {
      keyName: 'Win',
      value: 227,
      x: 52,
      y: -208,
      w: 41,
      h: 32,
    },
    {
      keyName: 'Alt',
      value: 226,
      x: 102,
      y: -208,
      w: 41,
      h: 32,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 154,
      y: -208,
      w: 247,
      h: 32,
    },
    {
      keyName: 'r_Alt',
      value: 230,
      x: 413,
      y: -208,
      w: 31,
      h: 32,
    },
    {
      keyName: 'FN',
      value: 0x0a010000,
      x: 453,
      y: -208,
      w: 31,
      h: 32,
    },
    {
      keyName: 'r_Ctrl',
      value: 228,
      x: 495,
      y: -208,
      w: 31,
      h: 32,
    },
    {
      keyName: '←',
      value: 80,
      x: 536,
      y: -208,
      w: 31,
      h: 32,
    },
    {
      keyName: '↓',
      value: 81,
      x: 577,
      y: -208,
      w: 31,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
      h: 32,
    },
    {
      keyName: '→',
      value: 79,
      x: 619,
      y: -208,
      w: 31,
      h: 32,
    },
  ],
}
