export const yzw_qk700_2m_bt = {
  deltX: 14,
  deltY: 14,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 33,
      h: 33,
     },
    {
      keyName: 'F1',
      value: 58,
      x: 45,
      y: 0,
      w: 33,
      h: 33,
    },
    {
      keyName: 'F2',
      value: 59,
      x: 90,
      y: 0,
      w: 33,
      h: 33,
    },
    {
      keyName: 'F3',
      value: 60,
      x: 135,
      y: 0,
      w: 33,
      h: 33,
    },
    {
      keyName: 'F4',
      value: 61,
      x: 180,
      y: 0,
      w: 33,
      h: 33,
    },
    {
      keyName: 'F5',
      value: 62,
      x: 225,
      y: 0,
      w: 33,
      h: 33,
    },
    {
      keyName: 'F6',
      value: 63,
      x: 270,
      y: 0,
      w: 33,
      h: 33,
    },
    {
      keyName: 'F7',
      value: 64,
      x: 314,
      y: 0,
      w: 33,
      h: 33,
    },
    {
      keyName: 'F8',
      value: 65,
      x: 359,
      y: 0,
      w: 33,
      h: 33,
    },
    {
      keyName: 'F9',
      value: 66,
      x: 405,
      y: 0,
      w: 33,
      h: 33,
    },
    {
      keyName: 'F10',
      value: 67,
      x: 449,
      y: 0,
      w: 33,
      h: 33,
    },
    {
      keyName: 'F11',
      value: 68,
      x: 494,
      y: 0,
      w: 33,
      h: 33,
    },
    {
      keyName: 'F12',
      value: 69,
      x: 539,
      y: 0,
      w: 33,
      h: 33,
    },
    {
      keyName: 'Print\nScreen',
      value: 70,
      x: 584,
      y: 0,
      w: 33,
      h: 33,
    },
    {
      keyName: 'Home',
      value: 74,
      x: 629,
      y: 0,
      w: 33,
      h: 33,
    },
    {
      keyName: 'Delete',
      value: 76,
      x: 674,
      y: 0,
      w: 33,
      h: 33,
    },
    {
      keyName: 'End',
      value: 77,
      x: 719,
      y: 0,
      w: 33,
      h: 33,
    },
    {
      keyName: 'Page\nUp',
      value: 75,
      x: 764,
      y: 0,
      w: 33,
      h: 33,
    },
    {
      keyName: 'Page\nDown',
      value: 78,
      x: 808,
      y: 0,
      w: 33,
      h: 33,
    },
    {
      keyName: '`',
      value: 53,
      x: 0,
      y: -45,
      w: 33,
      h: 33,
    },
    {
      keyName: '1',
      value: 30,
      x: 45,
      y: -45,
      w: 33,
      h: 33,
    },
    {
      keyName: '2',
      value: 31,
      x: 90,
      y: -45,
      w: 33,
      h: 33,
    },
    {
      keyName: '3',
      value: 32,
      x: 135,
      y: -45,
      w: 33,
      h: 33,
    },
    {
      keyName: '4',
      value: 33,
      x: 180,
      y: -45,
      w: 33,
      h: 33,
    },
    {
      keyName: '5',
      value: 34,
      x: 225,
      y: -45,
      w: 33,
      h: 33,
    },
    {
      keyName: '6',
      value: 35,
      x: 270,
      y: -45,
      w: 33,
      h: 33,
    },
    {
      keyName: '7',
      value: 36,
      x: 314,
      y: -45,
      w: 33,
      h: 33,
    },
    {
      keyName: '8',
      value: 37,
      x: 359,
      y: -45,
      w: 33,
      h: 33,
    },
    {
      keyName: '9',
      value: 38,
      x: 405,
      y: -45,
      w: 33,
      h: 33,
    },
    {
      keyName: '0',
      value: 39,
      x: 449,
      y: -45,
      w: 33,
      h: 33,
    },
    {
      keyName: '-',
      value: 45,
      x: 494,
      y: -45,
      w: 33,
      h: 33,
    },
    {
      keyName: '=',
      value: 46,
      x: 539,
      y: -45,
      w: 33,
      h: 33,
    },
    {
      keyName: 'BackSpace',
      value: 42,
      x: 584,
      y: -45,
      w: 78,
      h: 33,
    },
    {
      keyName: 'Num\nLock',
      value: 83,
      x: 674,
      y: -45,
      w: 33,
      h: 33,
    },
    {
      keyName: 'num_/',
      value: 84,
      x: 719,
      y: -45,
      w: 33,
      h: 33,
    },
    {
      keyName: 'num_*',
      value: 85,
      x: 764,
      y: -45,
      w: 33,
      h: 33,
    },
    {
      keyName: 'num_-',
      value: 86,
      x: 808,
      y: -45,
      w: 33,
      h: 33,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -90,
      w: 55,
      h: 33,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 67,
      y: -90,
      w: 33,
      h: 33,
    },
    {
      keyName: 'W',
      value: 26,
      x: 112,
      y: -90,
      w: 33,
      h: 33,
    },
    {
      keyName: 'E',
      value: 8,
      x: 157,
      y: -90,
      w: 33,
      h: 33,
    },
    {
      keyName: 'R',
      value: 21,
      x: 202,
      y: -90,
      w: 33,
      h: 33,
    },
    {
      keyName: 'T',
      value: 23,
      x: 247,
      y: -90,
      w: 33,
      h: 33,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 292,
      y: -90,
      w: 33,
      h: 33,
    },
    {
      keyName: 'U',
      value: 24,
      x: 336,
      y: -90,
      w: 33,
      h: 33,
    },
    {
      keyName: 'I',
      value: 12,
      x: 381,
      y: -90,
      w: 33,
      h: 33,
    },
    {
      keyName: 'O',
      value: 18,
      x: 427,
      y: -90,
      w: 33,
      h: 33,
    },
    {
      keyName: 'P',
      value: 19,
      x: 471,
      y: -90,
      w: 33,
      h: 33,
    },
    {
      keyName: '[',
      value: 47,
      x: 516,
      y: -90,
      w: 33,
      h: 33,
    },
    {
      keyName: ']',
      value: 48,
      x: 561,
      y: -90,
      w: 33,
      h: 33,
    },
    {
      keyName: '\\',
      value: 49,
      x: 606,
      y: -90,
      w: 56,
      h: 33,
    },
    {
      keyName: 'num_1',
      value: 95,
      x: 674,
      y: -90,
      w: 33,
      h: 33,
    },
    {
      keyName: 'num_2',
      value: 96,
      x: 719,
      y: -90,
      w: 33,
      h: 33,
    },
    {
      keyName: 'num_3',
      value: 97,
      x: 764,
      y: -90,
      w: 33,
      h: 33,
    },
    {
      keyName: 'num_+',
      value: 87,
      x: 808,
      y: -90,
      w: 33,
      h: 77,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -135,
      w: 65,
      h: 33,
    },
    {
      keyName: 'A',
      value: 4,
      x: 78,
      y: -135,
      w: 33,
      h: 33,
    },
    {
      keyName: 'S',
      value: 22,
      x: 123,
      y: -135,
      w: 33,
      h: 33,
    },
    {
      keyName: 'D',
      value: 7,
      x: 168,
      y: -135,
      w: 33,
      h: 33,
    },
    {
      keyName: 'F',
      value: 9,
      x: 213,
      y: -135,
      w: 33,
      h: 33,
    },
    {
      keyName: 'G',
      value: 10,
      x: 258,
      y: -135,
      w: 33,
      h: 33,
    },
    {
      keyName: 'H',
      value: 11,
      x: 303,
      y: -135,
      w: 33,
      h: 33,
    },
    {
      keyName: 'J',
      value: 13,
      x: 347,
      y: -135,
      w: 33,
      h: 33,
    },
    {
      keyName: 'K',
      value: 14,
      x: 392,
      y: -135,
      w: 33,
      h: 33,
    },
    {
      keyName: 'L',
      value: 15,
      x: 438,
      y: -135,
      w: 33,
      h: 33,
    },
    {
      keyName: ';',
      value: 51,
      x: 482,
      y: -135,
      w: 33,
      h: 33,
    },
    {
      keyName: '\'',
      value: 52,
      x: 527,
      y: -135,
      w: 33,
      h: 33,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 572,
      y: -135,
      w: 90,
      h: 33,
    },
    {
      keyName: 'num_4',
      value: 92,
      x: 674,
      y: -135,
      w: 33,
      h: 33,
    },
    {
      keyName: 'num_5',
      value: 93,
      x: 719,
      y: -135,
      w: 33,
      h: 33,
    },
    {
      keyName: 'num_6',
      value: 94,
      x: 764,
      y: -135,
      w: 33,
      h: 33,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -179,
      w: 90,
      h: 33,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 101,
      y: -179,
      w: 33,
      h: 33,
    },
    {
      keyName: 'X',
      value: 27,
      x: 146,
      y: -179,
      w: 33,
      h: 33,
    },
    {
      keyName: 'C',
      value: 6,
      x: 191,
      y: -179,
      w: 33,
      h: 33,
    },
    {
      keyName: 'V',
      value: 25,
      x: 236,
      y: -179,
      w: 33,
      h: 33,
    },
    {
      keyName: 'B',
      value: 5,
      x: 281,
      y: -179,
      w: 33,
      h: 33,
    },
    {
      keyName: 'N',
      value: 17,
      x: 326,
      y: -179,
      w: 33,
      h: 33,
    },
    {
      keyName: 'M',
      value: 16,
      x: 370,
      y: -179,
      w: 33,
      h: 33,
    },
    {
      keyName: ',',
      value: 54,
      x: 415,
      y: -179,
      w: 33,
      h: 33,
    },
    {
      keyName: '.',
      value: 55,
      x: 461,
      y: -179,
      w: 33,
      h: 33,
    },
    {
      keyName: '/',
      value: 56,
      x: 505,
      y: -179,
      w: 33,
      h: 33,
    },
    {
      keyName: 'r_Shift',
      value: 229,
      x: 550,
      y: -179,
      w: 67,
      h: 33,
    },
    {
      keyName: '↑',
      value: 82,
      x: 629,
      y: -179,
      w: 33,
      h: 33,
    },
    {
      keyName: 'num_7',
      value: 89,
      x: 674,
      y: -179,
      w: 33,
      h: 33,
    },
    {
      keyName: 'num_8',
      value: 90,
      x: 719,
      y: -179,
      w: 33,
      h: 33,
    },
    {
      keyName: 'num_9',
      value: 91,
      x: 764,
      y: -179,
      w: 33,
      h: 33,
    },
    {
      keyName: 'num_Enter',
      value: 88,
      x: 808,
      y: -181,
      w: 33,
      h: 77,
    },
    {
      keyName: 'Ctrl',
      value: 224,
      x: 0,
      y: -226,
      w: 45,
      h: 33,
    },
    {
      keyName: 'Win',
      value: 227,
      x: 56,
      y: -226,
      w: 45,
      h: 33,
    },
    {
      keyName: 'Alt',
      value: 226,
      x: 112,
      y: -226,
      w: 45,
      h: 33,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 168,
      y: -226,
      w: 270,
      h: 33,
    },
    {
      keyName: 'r_Alt',
      value: 230,
      x: 449,
      y: -226,
      w: 33,
      h: 33,
    },
    {
      keyName: 'fn',
      value: 0x0a010000,
      x: 494,
      y: -226,
      w: 33,
      h: 33,
    },
    {
      keyName: 'r_Ctrl',
      value: 228,
      x: 539,
      y: -226,
      w: 33,
      h: 33,
    },
    {
      keyName: '←',
      value: 80,
      x: 584,
      y: -226,
      w: 33,
      h: 33,
    },
    {
      keyName: '↓',
      value: 81,
      x: 629,
      y: -226,
      w: 33,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
      h: 33,
    },
    {
      keyName: '→',
      value: 79,
      x: 674,
      y: -226,
      w: 33,
      h: 33,
    },
    {
      keyName: 'num_0',
      value: 98,
      x: 719,
      y: -226,
      w: 33,
      h: 33,
    },
    {
      keyName: 'num_.',
      value: 99,
      x: 764,
      y: -226,
      w: 33,
      h: 33,
    },
  ],
}
