export const yzw_k231 = {
  deltX: 115,
  deltY: 51,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 29,
      h: 32,
    },
    {
      keyName: '1',
      value: 30,
      x: 43,
      y: 0,
      w: 29,
      h: 32,
    },
    {
      keyName: '2',
      value: 31,
      x: 86,
      y: 0,
      w: 29,
      h: 32,
    },
    {
      keyName: '3',
      value: 32,
      x: 131,
      y: 0,
      w: 29,
      h: 32,
    },
    {
      keyName: '4',
      value: 33,
      x: 174,
      y: 0,
      w: 29,
      h: 32,
    },
    {
      keyName: '5',
      value: 34,
      x: 219,
      y: 0,
      w: 29,
      h: 32,
    },
    {
      keyName: '6',
      value: 35,
      x: 262,
      y: 0,
      w: 29,
      h: 32,
    },
    {
      keyName: '7',
      value: 36,
      x: 306,
      y: 0,
      w: 29,
      h: 32,
    },
    {
      keyName: '8',
      value: 37,
      x: 349,
      y: 0,
      w: 29,
      h: 32,
    },
    {
      keyName: '9',
      value: 38,
      x: 393,
      y: 0,
      w: 29,
      h: 32,
    },
    {
      keyName: '0',
      value: 39,
      x: 437,
      y: 0,
      w: 29,
      h: 32,
    },
    {
      keyName: '-',
      value: 45,
      x: 480,
      y: 0,
      w: 29,
      h: 32,
    },
    {
      keyName: '=',
      value: 46,
      x: 524,
      y: 0,
      w: 29,
      h: 32,
    },
    {
      keyName: 'Backspace',
      value: 42,
      x: 568,
      y: 0,
      w: 72,
      h: 32,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -43,
      w: 51,
      h: 32,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 65,
      y: -43,
      w: 29,
      h: 32,
    },
    {
      keyName: 'W',
      value: 26,
      x: 109,
      y: -43,
      w: 29,
      h: 32,
    },
    {
      keyName: 'E',
      value: 8,
      x: 152,
      y: -43,
      w: 29,
      h: 32,
    },
    {
      keyName: 'R',
      value: 21,
      x: 196,
      y: -43,
      w: 29,
      h: 32,
    },
    {
      keyName: 'T',
      value: 23,
      x: 240,
      y: -43,
      w: 29,
      h: 32,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 283,
      y: -43,
      w: 29,
      h: 32,
    },
    {
      keyName: 'U',
      value: 24,
      x: 327,
      y: -43,
      w: 29,
      h: 32,
    },
    {
      keyName: 'I',
      value: 12,
      x: 371,
      y: -43,
      w: 29,
      h: 32,
    },
    {
      keyName: 'O',
      value: 18,
      x: 414,
      y: -43,
      w: 29,
      h: 32,
    },
    {
      keyName: 'P',
      value: 19,
      x: 458,
      y: -43,
      w: 29,
      h: 32,
    },
    {
      keyName: '[',
      value: 47,
      x: 502,
      y: -43,
      w: 29,
      h: 32,
    },
    {
      keyName: ']',
      value: 48,
      x: 546,
      y: -43,
      w: 29,
      h: 32,
    },
    {
      keyName: '\\',
      value: 49,
      x: 590,
      y: -43,
      w: 50,
      h: 32,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -86,
      w: 61,
      h: 32,
    },
    {
      keyName: 'A',
      value: 4,
      x: 76,
      y: -86,
      w: 29,
      h: 32,
    },
    {
      keyName: 'S',
      value: 22,
      x: 120,
      y: -86,
      w: 29,
      h: 32,
    },
    {
      keyName: 'D',
      value: 7,
      x: 164,
      y: -86,
      w: 29,
      h: 32,
    },
    {
      keyName: 'F',
      value: 9,
      x: 208,
      y: -86,
      w: 29,
      h: 32,
    },
    {
      keyName: 'G',
      value: 10,
      x: 251,
      y: -86,
      w: 29,
      h: 32,
    },
    {
      keyName: 'H',
      value: 11,
      x: 294,
      y: -86,
      w: 29,
      h: 32,
    },
    {
      keyName: 'J',
      value: 13,
      x: 338,
      y: -86,
      w: 29,
      h: 32,
    },
    {
      keyName: 'K',
      value: 14,
      x: 382,
      y: -86,
      w: 29,
      h: 32,
    },
    {
      keyName: 'L',
      value: 15,
      x: 426,
      y: -86,
      w: 29,
      h: 32,
    },
    {
      keyName: ';',
      value: 51,
      x: 469,
      y: -86,
      w: 29,
      h: 32,
    },
    {
      keyName: '\'',
      value: 52,
      x: 513,
      y: -86,
      w: 29,
      h: 32,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 557,
      y: -86,
      w: 83,
      h: 32,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -131,
      w: 84,
      h: 32,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 98,
      y: -131,
      w: 29,
      h: 32,
    },
    {
      keyName: 'X',
      value: 27,
      x: 141,
      y: -131,
      w: 29,
      h: 32,
    },
    {
      keyName: 'C',
      value: 6,
      x: 186,
      y: -131,
      w: 29,
      h: 32,
    },
    {
      keyName: 'V',
      value: 25,
      x: 229,
      y: -131,
      w: 29,
      h: 32,
    },
    {
      keyName: 'B',
      value: 5,
      x: 273,
      y: -131,
      w: 29,
      h: 32,
    },
    {
      keyName: 'N',
      value: 17,
      x: 316,
      y: -131,
      w: 29,
      h: 32,
    },
    {
      keyName: 'M',
      value: 16,
      x: 361,
      y: -131,
      w: 29,
      h: 32,
    },
    {
      keyName: ',',
      value: 54,
      x: 405,
      y: -131,
      w: 29,
      h: 32,
    },
    {
      keyName: '.',
      value: 55,
      x: 448,
      y: -131,
      w: 29,
      h: 32,
    },
    {
      keyName: '/',
      value: 56,
      x: 491,
      y: -131,
      w: 29,
      h: 32,
    },
    {
      keyName: 'r_Shift',
      value: 229,
      x: 535,
      y: -131,
      w: 105,
      h: 32,
    },
    {
      keyName: 'CTRL',
      value: 224,
      x: 0,
      y: -174,
      w: 40,
      h: 32,
    },
    {
      keyName: 'Win',
      value: 227,
      x: 54,
      y: -174,
      w: 40,
      h: 32,
    },
    {
      keyName: 'ALT',
      value: 226,
      x: 109,
      y: -174,
      w: 40,
      h: 32,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 161,
      y: -174,
      w: 261,
      h: 32,
    },
    {
      keyName: 'r_Alt',
      value: 230,
      x: 437,
      y: -174,
      w: 40,
      h: 32,
    },
    {
      keyName: 'FN',
      value: 0x0a010000,
      x: 491,
      y: -174,
      w: 40,
      h: 32,
    },
    {
      keyName: '(Application)',
      value: 101,
      x: 546,
      y: -174,
      w: 40,
      h: 32,
    },
    {
      keyName: 'r_Ctrl',
      value: 228,
      x: 600,
      y: -174,
      w: 40,
      h: 32,
    },
  ],
}
