export const yzw_dk870 = {
  deltX: 139,
  deltY: 70,
  layout: [
     // {
    //   keyName: 'U-',
    //   value: 0x0300ea00,
    //   knob: true,
    //   ban:true,
    //   x: 456,
    //   y: 49,
    //   w: 15,
    //   h: 15,
    // },
    // {
    //   keyName: 'Play',
    //   value: 0x0300cd00,
    //   knob: true,
    //   ban:true,
    //   x: 481,
    //   y: 49,
    //   w: 15,
    //   h: 15,
    // },
    // {
    //   keyName: 'U+',
    //   value: 0x0300e900,
    //   knob: true,
    //   ban:true,
    //   x: 508,
    //   y: 49,
    //   w: 15,
    //   h: 15,
    // },
    {
      keyName: 'Mute',
      value: 0x0300e200,
      knob: true,
      x: 569,
      y: 55,
      w: 12,
      h: 38,
    },
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 23,
      h: 26,
    },
    {
      keyName: 'F1',
      value: 58,
      x: 66,
      y: 0,
      w: 23,
      h: 26,
    },
    {
      keyName: 'F2',
      value: 59,
      x: 99,
      y: 0,
      w: 23,
      h: 26,
    },
    {
      keyName: 'F3',
      value: 60,
      x: 132,
      y: 0,
      w: 23,
      h: 26,
    },
    {
      keyName: 'F4',
      value: 61,
      x: 165,
      y: 0,
      w: 23,
      h: 26,
    },
    {
      keyName: 'F5',
      value: 62,
      x: 214,
      y: 0,
      w: 23,
      h: 26,
    },
    {
      keyName: 'F6',
      value: 63,
      x: 247,
      y: 0,
      w: 23,
      h: 26,
    },
    {
      keyName: 'F7',
      value: 64,
      x: 280,
      y: 0,
      w: 23,
      h: 26,
    },
    {
      keyName: 'F8',
      value: 65,
      x: 313,
      y: 0,
      w: 23,
      h: 26,
    },
    {
      keyName: 'F9',
      value: 66,
      x: 362,
      y: 0,
      w: 23,
      h: 26,
    },
    {
      keyName: 'F10',
      value: 67,
      x: 395,
      y: 0,
      w: 23,
      h: 26,
    },
    {
      keyName: 'F11',
      value: 68,
      x: 428,
      y: 0,
      w: 23,
      h: 26,
    },
    {
      keyName: 'F12',
      value: 69,
      x: 461,
      y: 0,
      w: 23,
      h: 26,
    },
    {
      keyName: 'Print\nScreen',
      value: 70,
      x: 504,
      y: 0,
      w: 23,
      h: 26,
    },
    {
      keyName: 'Scroll\nLock',
      value: 71,
      x: 537,
      y: 0,
      w: 23,
      h: 26,
    },
    {
      keyName: 'Pause',
      value: 72,
      x: 570,
      y: 0,
      w: 23,
      h: 26,
    },
    {
      keyName: '`',
      value: 53,
      x: 0,
      y: -44,
      w: 23,
      h: 26,
    },
    {
      keyName: '1',
      value: 30,
      x: 33,
      y: -44,
      w: 23,
      h: 26,
    },
    {
      keyName: '2',
      value: 31,
      x: 66,
      y: -44,
      w: 23,
      h: 26,
    },
    {
      keyName: '3',
      value: 32,
      x: 99,
      y: -44,
      w: 23,
      h: 26,
    },
    {
      keyName: '4',
      value: 33,
      x: 132,
      y: -44,
      w: 23,
      h: 26,
    },
    {
      keyName: '5',
      value: 34,
      x: 165,
      y: -44,
      w: 23,
      h: 26,
    },
    {
      keyName: '6',
      value: 35,
      x: 197,
      y: -44,
      w: 23,
      h: 26,
    },
    {
      keyName: '7',
      value: 36,
      x: 230,
      y: -44,
      w: 23,
      h: 26,
    },
    {
      keyName: '8',
      value: 37,
      x: 263,
      y: -44,
      w: 23,
      h: 26,
    },
    {
      keyName: '9',
      value: 38,
      x: 296,
      y: -44,
      w: 23,
      h: 26,
    },
    {
      keyName: '0',
      value: 39,
      x: 329,
      y: -44,
      w: 23,
      h: 26,
    },
    {
      keyName: '-',
      value: 45,
      x: 362,
      y: -44,
      w: 23,
      h: 26,
    },
    {
      keyName: '=',
      value: 46,
      x: 394,
      y: -44,
      w: 23,
      h: 26,
    },
    {
      keyName: 'BackSpace',
      value: 42,
      x: 427,
      y: -44,
      w: 56,
      h: 26,
    },
    {
      keyName: 'Insert',
      value: 73,
      x: 504,
      y: -44,
      w: 23,
      h: 26,
    },
    {
      keyName: 'Home',
      value: 74,
      x: 537,
      y: -44,
      w: 23,
      h: 26,
    },
    {
      keyName: 'Page\nUp',
      value: 75,
      x: 570,
      y: -44,
      w: 23,
      h: 26,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -77,
      w: 40,
      h: 26,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 49,
      y: -77,
      w: 23,
      h: 26,
    },
    {
      keyName: 'W',
      value: 26,
      x: 82,
      y: -77,
      w: 23,
      h: 26,
    },
    {
      keyName: 'E',
      value: 8,
      x: 115,
      y: -77,
      w: 23,
      h: 26,
    },
    {
      keyName: 'R',
      value: 21,
      x: 148,
      y: -77,
      w: 23,
      h: 26,
    },
    {
      keyName: 'T',
      value: 23,
      x: 181,
      y: -77,
      w: 23,
      h: 26,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 213,
      y: -77,
      w: 23,
      h: 26,
    },
    {
      keyName: 'U',
      value: 24,
      x: 246,
      y: -77,
      w: 23,
      h: 26,
    },
    {
      keyName: 'I',
      value: 12,
      x: 279,
      y: -77,
      w: 23,
      h: 26,
    },
    {
      keyName: 'O',
      value: 18,
      x: 312,
      y: -77,
      w: 23,
      h: 26,
    },
    {
      keyName: 'P',
      value: 19,
      x: 345,
      y: -77,
      w: 23,
      h: 26,
    },
    {
      keyName: '[',
      value: 47,
      x: 378,
      y: -77,
      w: 23,
      h: 26,
    },
    {
      keyName: ']',
      value: 48,
      x: 410,
      y: -77,
      w: 23,
      h: 26,
    },
    {
      keyName: '\\',
      value: 49,
      x: 443,
      y: -77,
      w: 40,
      h: 26,
    },
    {
      keyName: 'Delete',
      value: 76,
      x: 504,
      y: -77,
      w: 23,
      h: 26,
    },
    {
      keyName: 'End',
      value: 77,
      x: 537,
      y: -77,
      w: 23,
      h: 26,
    },
    {
      keyName: 'Page\nDown',
      value: 78,
      x: 570,
      y: -77,
      w: 23,
      h: 26,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -110,
      w: 48,
      h: 26,
    },
    {
      keyName: 'A',
      value: 4,
      x: 57,
      y: -110,
      w: 23,
      h: 26,
    },
    {
      keyName: 'S',
      value: 22,
      x: 90,
      y: -110,
      w: 23,
      h: 26,
    },
    {
      keyName: 'D',
      value: 7,
      x: 123,
      y: -110,
      w: 23,
      h: 26,
    },
    {
      keyName: 'F',
      value: 9,
      x: 156,
      y: -110,
      w: 23,
      h: 26,
    },
    {
      keyName: 'G',
      value: 10,
      x: 189,
      y: -110,
      w: 23,
      h: 26,
    },
    {
      keyName: 'H',
      value: 11,
      x: 221,
      y: -110,
      w: 23,
      h: 26,
    },
    {
      keyName: 'J',
      value: 13,
      x: 254,
      y: -110,
      w: 23,
      h: 26,
    },
    {
      keyName: 'K',
      value: 14,
      x: 287,
      y: -110,
      w: 23,
      h: 26,
    },
    {
      keyName: 'L',
      value: 15,
      x: 320,
      y: -110,
      w: 23,
      h: 26,
    },
    {
      keyName: ';',
      value: 51,
      x: 353,
      y: -110,
      w: 23,
      h: 26,
    },
    {
      keyName: '\'',
      value: 52,
      x: 386,
      y: -110,
      w: 23,
      h: 26,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 418,
      y: -110,
      w: 65,
      h: 26,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -143,
      w: 64,
      h: 26,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 74,
      y: -143,
      w: 23,
      h: 26,
    },
    {
      keyName: 'X',
      value: 27,
      x: 107,
      y: -143,
      w: 23,
      h: 26,
    },
    {
      keyName: 'C',
      value: 6,
      x: 140,
      y: -143,
      w: 23,
      h: 26,
    },
    {
      keyName: 'V',
      value: 25,
      x: 173,
      y: -143,
      w: 23,
      h: 26,
    },
    {
      keyName: 'B',
      value: 5,
      x: 206,
      y: -143,
      w: 23,
      h: 26,
    },
    {
      keyName: 'N',
      value: 17,
      x: 238,
      y: -143,
      w: 23,
      h: 26,
    },
    {
      keyName: 'M',
      value: 16,
      x: 271,
      y: -143,
      w: 23,
      h: 26,
    },
    {
      keyName: ',',
      value: 54,
      x: 304,
      y: -143,
      w: 23,
      h: 26,
    },
    {
      keyName: '.',
      value: 55,
      x: 337,
      y: -143,
      w: 23,
      h: 26,
    },
    {
      keyName: '/',
      value: 56,
      x: 370,
      y: -143,
      w: 23,
      h: 26,
    },
    {
      keyName: 'r_Shift',
      value: 229,
      x: 403,
      y: -143,
      w: 80,
      h: 26,
    },
    {
      keyName: '↑',
      value: 82,
      x: 537,
      y: -143,
      w: 23,
      h: 26,
    },
    {
      keyName: 'Ctrl',
      value: 224,
      x: 0,
      y: -176,
      w: 31,
      h: 26,
    },
    {
      keyName: 'Win',
      value: 227,
      x: 42,
      y: -176,
      w: 31,
      h: 26,
    },
    {
      keyName: 'Alt',
      value: 226,
      x: 83,
      y: -176,
      w: 31,
      h: 26,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 124,
      y: -176,
      w: 194,
      h: 26,
    },
    {
      keyName: 'r_Alt',
      value: 230,
      x: 328,
      y: -176,
      w: 31,
      h: 26,
    },
    {
      keyName: 'FN',
      value: 0x0a010000,
      x: 370,
      y: -176,
      w: 31,
      h: 26,
    },
    {
      keyName: '(Application)',
      value: 101,
      x: 411,
      y: -176,
      w: 31,
      h: 26,
    },
    {
      keyName: 'r_Ctrl',
      value: 228,
      x: 452,
      y: -176,
      w: 31,
      h: 26,
    },
    {
      keyName: '←',
      value: 80,
      x: 504,
      y: -176,
      w: 23,
      h: 26,
    },
    {
      keyName: '↓',
      value: 81,
      x: 537,
      y: -176,
      w: 23,
      h: 26,
    },
    {
      keyName: '→',
      value: 79,
      x: 570,
      y: -176,
      w: 23,
      h: 26,
    },
  ],
}
