export const yzw_dk67 = {
  deltX: 49,
  deltY: 23,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 34,
      h: 36,
    },
    {
      keyName: '1',
      value: 30,
      x: 48,
      y: 0,
      w: 34,
      h: 36,
    },
    {
      keyName: '2',
      value: 31,
      x: 96,
      y: 0,
      w: 34,
      h: 36,
    },
    {
      keyName: '3',
      value: 32,
      x: 144,
      y: 0,
      w: 34,
      h: 36,
    },
    {
      keyName: '4',
      value: 33,
      x: 192,
      y: 0,
      w: 34,
      h: 36,
    },
    {
      keyName: '5',
      value: 34,
      x: 240,
      y: 0,
      w: 34,
      h: 36,
    },
    {
      keyName: '6',
      value: 35,
      x: 288,
      y: 0,
      w: 34,
      h: 36,
    },
    {
      keyName: '7',
      value: 36,
      x: 336,
      y: 0,
      w: 34,
      h: 36,
    },
    {
      keyName: '8',
      value: 37,
      x: 384,
      y: 0,
      w: 34,
      h: 36,
    },
    {
      keyName: '9',
      value: 38,
      x: 432,
      y: 0,
      w: 34,
      h: 36,
    },
    {
      keyName: '0',
      value: 39,
      x: 480,
      y: 0,
      w: 34,
      h: 36,
    },
    {
      keyName: '-',
      value: 45,
      x: 528,
      y: 0,
      w: 34,
      h: 36,
    },
    {
      keyName: '=',
      value: 46,
      x: 576,
      y: 0,
      w: 34,
      h: 36,
    },
    {
      keyName: 'Backspace',
      value: 42,
      x: 624,
      y: 0,
      w: 82,
      h: 36,
    },
    {
      keyName: 'U-',
      value: 0x0300ea00,
      knob: true,
      x: 728,
      y: 13,
      w: 12,
      h: 52,
    },
    {
      keyName: 'play',
      value: 0x0300e200,
      knob: true,
      x: 750,
      y: 13,
      w: 12,
      h: 52,
    },
    {
      keyName: 'U+',
      value: 0x0300e900,
      knob: true,
      x: 772,
      y: 13,
      w: 12,
      h: 52,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -48,
      w: 57,
      h: 36,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 72,
      y: -48,
      w: 34,
      h: 36,
    },
    {
      keyName: 'W',
      value: 26,
      x: 120,
      y: -48,
      w: 34,
      h: 36,
    },
    {
      keyName: 'E',
      value: 8,
      x: 168,
      y: -48,
      w: 34,
      h: 36,
    },
    {
      keyName: 'R',
      value: 21,
      x: 216,
      y: -48,
      w: 34,
      h: 36,
    },
    {
      keyName: 'T',
      value: 23,
      x: 264,
      y: -48,
      w: 34,
      h: 36,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 312,
      y: -48,
      w: 34,
      h: 36,
    },
    {
      keyName: 'U',
      value: 24,
      x: 360,
      y: -48,
      w: 34,
      h: 36,
    },
    {
      keyName: 'I',
      value: 12,
      x: 408,
      y: -48,
      w: 34,
      h: 36,
    },
    {
      keyName: 'O',
      value: 18,
      x: 456,
      y: -48,
      w: 34,
      h: 36,
    },
    {
      keyName: 'P',
      value: 19,
      x: 504,
      y: -48,
      w: 34,
      h: 36,
    },
    {
      keyName: '[',
      value: 47,
      x: 552,
      y: -48,
      w: 34,
      h: 36,
    },
    {
      keyName: ']',
      value: 48,
      x: 600,
      y: -48,
      w: 34,
      h: 36,
    },
    {
      keyName: '\\',
      value: 50,
      x: 648,
      y: -48,
      w: 58,
      h: 36,
    },
    {
      keyName: 'Delete',
      value: 76,
      x: 739,
      y: -47,
      w: 34,
      h: 36,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -96,
      w: 69,
      h: 36,
    },
    {
      keyName: 'A',
      value: 4,
      x: 84,
      y: -96,
      w: 34,
      h: 36,
    },
    {
      keyName: 'S',
      value: 22,
      x: 132,
      y: -96,
      w: 34,
      h: 36,
    },
    {
      keyName: 'D',
      value: 7,
      x: 180,
      y: -96,
      w: 34,
      h: 36,
    },
    {
      keyName: 'F',
      value: 9,
      x: 228,
      y: -96,
      w: 34,
      h: 36,
    },
    {
      keyName: 'G',
      value: 10,
      x: 276,
      y: -96,
      w: 34,
      h: 36,
    },
    {
      keyName: 'H',
      value: 11,
      x: 324,
      y: -96,
      w: 34,
      h: 36,
    },
    {
      keyName: 'J',
      value: 13,
      x: 372,
      y: -96,
      w: 34,
      h: 36,
    },
    {
      keyName: 'K',
      value: 14,
      x: 420,
      y: -96,
      w: 34,
      h: 36,
    },
    {
      keyName: 'L',
      value: 15,
      x: 468,
      y: -96,
      w: 34,
      h: 36,
    },
    {
      keyName: ';',
      value: 51,
      x: 516,
      y: -96,
      w: 34,
      h: 36,
    },
    {
      keyName: '"',
      value: 52,
      x: 564,
      y: -96,
      w: 34,
      h: 36,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 612,
      y: -96,
      w: 94,
      h: 36,
    },
    {
      keyName: 'PgUp',
      value: 75,
      x: 739,
      y: -95,
      w: 34,
      h: 36,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -144,
      w: 94,
      h: 36,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 108,
      y: -144,
      w: 34,
      h: 36,
    },
    {
      keyName: 'X',
      value: 27,
      x: 156,
      y: -144,
      w: 34,
      h: 36,
    },
    {
      keyName: 'C',
      value: 6,
      x: 204,
      y: -144,
      w: 34,
      h: 36,
    },
    {
      keyName: 'V',
      value: 25,
      x: 252,
      y: -144,
      w: 34,
      h: 36,
    },
    {
      keyName: 'B',
      value: 5,
      x: 300,
      y: -144,
      w: 34,
      h: 36,
    },
    {
      keyName: 'N',
      value: 17,
      x: 348,
      y: -144,
      w: 34,
      h: 36,
    },
    {
      keyName: 'M',
      value: 16,
      x: 396,
      y: -144,
      w: 34,
      h: 36,
    },
    {
      keyName: ',',
      value: 54,
      x: 444,
      y: -144,
      w: 34,
      h: 36,
    },
    {
      keyName: '.',
      value: 55,
      x: 492,
      y: -144,
      w: 34,
      h: 36,
    },
    {
      keyName: '/',
      value: 56,
      x: 540,
      y: -144,
      w: 34,
      h: 36,
    },
    {
      keyName: 'R-Shift',
      value: 229,
      x: 588,
      y: -144,
      w: 68,
      h: 36,
    },
    {
      keyName: '↑',
      value: 82,
      x: 681,
      y: -154,
      w: 34,
      h: 36,
    },
    {
      keyName: 'PgDn',
      value: 78,
      x: 739,
      y: -143,
      w: 34,
      h: 36,
    },
    {
      keyName: 'Ctrl',
      value: 224,
      x: 0,
      y: -192,
      w: 45,
      h: 36,
    },
    {
      keyName: 'win',
      value: 227,
      x: 60,
      y: -192,
      w: 45,
      h: 36,
    },
    {
      keyName: 'Alt',
      value: 226,
      x: 120,
      y: -192,
      w: 45,
      h: 36,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 180,
      y: -192,
      w: 286,
      h: 36,
    },
    {
      keyName: 'r-Alt',
      value: 230,
      x: 480,
      y: -192,
      w: 34,
      h: 36,
    },
    {
      keyName: 'Fn',
      value: 0x0a010000,
      x: 528,
      y: -192,
      w: 34,
      h: 36,
    },
    {
      keyName: 'r-Ctrl',
      value: 228,
      x: 576,
      y: -192,
      w: 34,
      h: 36,
    },
    {
      keyName: '←',
      value: 80,
      x: 633,
      y: -201,
      w: 34,
      h: 36,
    },
    {
      keyName: '↓',
      value: 81,
      x: 681,
      y: -201,
      w: 34,
      h: 36,
    },
    {
      keyName: '→',
      value: 79,
      x: 729,
      y: -201,
      w: 34,
      h: 36,
    },
  ],
}
