export const yzw_mk3108 = {
    deltX: 11,
    deltY: 22,
    layout: [
        {
            keyName: 'Esc',
            value: 41,
            x: 0,
            y: 0,
            w: 25,
            h: 28,
        },
        {
            keyName: 'F1',
            value: 58,
            x: 77,
            y: 0,
            w: 25,
            h: 28,
        },
        {
            keyName: 'F2',
            value: 59,
            x: 115,
            y: 0,
            w: 25,
            h: 28,
        },
        {
            keyName: 'F3',
            value: 60,
            x: 153,
            y: 0,
            w: 25,
            h: 28,
        },
        {
            keyName: 'F4',
            value: 61,
            x: 191,
            y: 0,
            w: 25,
            h: 28,
        },
        {
            keyName: 'F5',
            value: 62,
            x: 249,
            y: 0,
            w: 25,
            h: 28,
        },
        {
            keyName: 'F6',
            value: 63,
            x: 287,
            y: 0,
            w: 25,
            h: 28,
        },
        {
            keyName: 'F7',
            value: 64,
            x: 325,
            y: 0,
            w: 25,
            h: 28,
        },
        {
            keyName: 'F8',
            value: 65,
            x: 363,
            y: 0,
            w: 25,
            h: 28,
        },
        {
            keyName: 'F9',
            value: 66,
            x: 420,
            y: 0,
            w: 25,
            h: 28,
        },
        {
            keyName: 'F10',
            value: 67,
            x: 458,
            y: 0,
            w: 25,
            h: 28,
        },
        {
            keyName: 'F11',
            value: 68,
            x: 496,
            y: 0,
            w: 25,
            h: 28,
        },
        {
            keyName: 'F12',
            value: 69,
            x: 535,
            y: 0,
            w: 25,
            h: 28,
        },
        {
            keyName: 'Print\nScreen',
            value: 70,
            x: 583,
            y: 0,
            w: 25,
            h: 28,
        },
        {
            keyName: 'Scroll\nLock',
            value: 71,
            x: 621,
            y: 0,
            w: 25,
            h: 28,
        },
        {
            keyName: 'Pause',
            value: 72,
            x: 659,
            y: 0,
            w: 25,
            h: 28,
        },
        {
            keyName: 'U-',
            value: 0x0300ea00,
            x: 708,
            y: 0,
            w: 25,
            h: 28,
        },
        {
            keyName: 'U+',
            value: 0x0300e900,
            x: 746,
            y: 0,
            w: 25,
            h: 28,
        },
        {
            keyName: 'mute',
            value: 0x0300e200,
            x: 784,
            y: 0,
            w: 25,
            h: 28,
        },
        {
            keyName: 'Calculator',
            value: 0x03009201,
            x: 822,
            y: 0,
            w: 25,
            h: 28,
        },
        {
            keyName: '`',
            value: 53,
            x: 0,
            y: -56,
            w: 25,
            h: 28,
        },
        {
            keyName: '1',
            value: 30,
            x: 38,
            y: -56,
            w: 25,
            h: 28,
        },
        {
            keyName: '2',
            value: 31,
            x: 77,
            y: -56,
            w: 25,
            h: 28,
        },
        {
            keyName: '3',
            value: 32,
            x: 115,
            y: -56,
            w: 25,
            h: 28,
        },
        {
            keyName: '4',
            value: 33,
            x: 153,
            y: -56,
            w: 25,
            h: 28,
        },
        {
            keyName: '5',
            value: 34,
            x: 191,
            y: -56,
            w: 25,
            h: 28,
        },
        {
            keyName: '6',
            value: 35,
            x: 230,
            y: -56,
            w: 25,
            h: 28,
        },
        {
            keyName: '7',
            value: 36,
            x: 267,
            y: -56,
            w: 25,
            h: 28,
        },
        {
            keyName: '8',
            value: 37,
            x: 306,
            y: -56,
            w: 25,
            h: 28,
        },
        {
            keyName: '9',
            value: 38,
            x: 344,
            y: -56,
            w: 25,
            h: 28,
        },
        {
            keyName: '0',
            value: 39,
            x: 382,
            y: -56,
            w: 25,
            h: 28,
        },
        {
            keyName: '-',
            value: 45,
            x: 420,
            y: -56,
            w: 25,
            h: 28,
        },
        {
            keyName: '=',
            value: 46,
            x: 458,
            y: -56,
            w: 25,
            h: 28,
        },
        {
            keyName: 'BackSpace',
            value: 42,
            x: 497,
            y: -56,
            w: 63,
            h: 28,
        },
        {
            keyName: 'Insert',
            value: 73,
            x: 583,
            y: -56,
            w: 25,
            h: 28,
        },
        {
            keyName: 'Home',
            value: 74,
            x: 621,
            y: -56,
            w: 25,
            h: 28,
        },
        {
            keyName: 'Page\nUp',
            value: 75,
            x: 659,
            y: -56,
            w: 25,
            h: 28,
        },
        {
            keyName: 'Num\nLock',
            value: 83,
            x: 708,
            y: -56,
            w: 25,
            h: 28,
        },
        {
            keyName: 'num_/',
            value: 84,
            x: 746,
            y: -56,
            w: 25,
            h: 28,
        },
        {
            keyName: 'num_*',
            value: 85,
            x: 784,
            y: -56,
            w: 25,
            h: 28,
        },
        {
            keyName: 'num_-',
            value: 86,
            x: 822,
            y: -56,
            w: 25,
            h: 28,
        },
        {
            keyName: 'Tab',
            value: 43,
            x: 0,
            y: -94,
            w: 45,
            h: 28,
        },
        {
            keyName: 'Q',
            value: 20,
            x: 58,
            y: -94,
            w: 25,
            h: 28,
        },
        {
            keyName: 'W',
            value: 26,
            x: 96,
            y: -94,
            w: 25,
            h: 28,
        },
        {
            keyName: 'E',
            value: 8,
            x: 134,
            y: -94,
            w: 25,
            h: 28,
        },
        {
            keyName: 'R',
            value: 21,
            x: 172,
            y: -94,
            w: 25,
            h: 28,
        },
        {
            keyName: 'T',
            value: 23,
            x: 211,
            y: -94,
            w: 25,
            h: 28,
        },
        {
            keyName: 'Y',
            value: 28,
            x: 249,
            y: -94,
            w: 25,
            h: 28,
        },
        {
            keyName: 'U',
            value: 24,
            x: 287,
            y: -94,
            w: 25,
            h: 28,
        },
        {
            keyName: 'I',
            value: 12,
            x: 326,
            y: -94,
            w: 25,
            h: 28,
        },
        {
            keyName: 'O',
            value: 18,
            x: 363,
            y: -94,
            w: 25,
            h: 28,
        },
        {
            keyName: 'P',
            value: 19,
            x: 401,
            y: -94,
            w: 25,
            h: 28,
        },
        {
            keyName: '[',
            value: 47,
            x: 439,
            y: -94,
            w: 25,
            h: 28,
        },
        {
            keyName: ']',
            value: 48,
            x: 477,
            y: -94,
            w: 25,
            h: 28,
        },
        {
            keyName: '\\',
            value: 49,
            x: 515,
            y: -94,
            w: 45,
            h: 28,
        },
        {
            keyName: 'Delete',
            value: 76,
            x: 583,
            y: -94,
            w: 25,
            h: 28,
        },
        {
            keyName: 'End',
            value: 77,
            x: 621,
            y: -94,
            w: 25,
            h: 28,
        },
        {
            keyName: 'Page\nDown',
            value: 78,
            x: 659,
            y: -94,
            w: 25,
            h: 28,
        },
        {
            keyName: 'num_7',
            value: 95,
            x: 708,
            y: -94,
            w: 25,
            h: 28,
        },
        {
            keyName: 'num_8',
            value: 96,
            x: 746,
            y: -94,
            w: 25,
            h: 28,
        },
        {
            keyName: 'num_9',
            value: 97,
            x: 784,
            y: -94,
            w: 25,
            h: 28,
        },
        {
            keyName: 'num_+',
            value: 87,
            x: 822,
            y: -94,
            w: 25,
            h: 67,
        },
        {
            keyName: 'Caps Lock',
            value: 57,
            x: 0,
            y: -133,
            w: 55,
            h: 28,
        },
        {
            keyName: 'A',
            value: 4,
            x: 68,
            y: -133,
            w: 25,
            h: 28,
        },
        {
            keyName: 'S',
            value: 22,
            x: 106,
            y: -133,
            w: 25,
            h: 28,
        },
        {
            keyName: 'D',
            value: 7,
            x: 144,
            y: -133,
            w: 25,
            h: 28,
        },
        {
            keyName: 'F',
            value: 9,
            x: 182,
            y: -133,
            w: 25,
            h: 28,
        },
        {
            keyName: 'G',
            value: 10,
            x: 221,
            y: -133,
            w: 25,
            h: 28,
        },
        {
            keyName: 'H',
            value: 11,
            x: 259,
            y: -133,
            w: 25,
            h: 28,
        },
        {
            keyName: 'J',
            value: 13,
            x: 297,
            y: -133,
            w: 25,
            h: 28,
        },
        {
            keyName: 'K',
            value: 14,
            x: 336,
            y: -133,
            w: 25,
            h: 28,
        },
        {
            keyName: 'L',
            value: 15,
            x: 373,
            y: -133,
            w: 25,
            h: 28,
        },
        {
            keyName: ';',
            value: 51,
            x: 411,
            y: -133,
            w: 25,
            h: 28,
        },
        {
            keyName: '\'',
            value: 52,
            x: 449,
            y: -133,
            w: 25,
            h: 28,
        },
        {
            keyName: 'Enter',
            value: 40,
            x: 487,
            y: -133,
            w: 73,
            h: 28,
        },
        {
            keyName: 'num_4',
            value: 92,
            x: 708,
            y: -133,
            w: 25,
            h: 28,
        },
        {
            keyName: 'num_5',
            value: 93,
            x: 746,
            y: -133,
            w: 25,
            h: 28,
        },
        {
            keyName: 'num_6',
            value: 94,
            x: 784,
            y: -133,
            w: 25,
            h: 28,
        },
        {
            keyName: 'Shift',
            value: 0xe1,
            x: 0,
            y: -171,
            w: 74,
            h: 28,
        },
        {
            keyName: 'Z',
            value: 29,
            x: 86,
            y: -171,
            w: 25,
            h: 28,
        },
        {
            keyName: 'X',
            value: 27,
            x: 125,
            y: -171,
            w: 25,
            h: 28,
        },
        {
            keyName: 'C',
            value: 6,
            x: 163,
            y: -171,
            w: 25,
            h: 28,
        },
        {
            keyName: 'V',
            value: 25,
            x: 201,
            y: -171,
            w: 25,
            h: 28,
        },
        {
            keyName: 'B',
            value: 5,
            x: 239,
            y: -171,
            w: 25,
            h: 28,
        },
        {
            keyName: 'N',
            value: 17,
            x: 277,
            y: -171,
            w: 25,
            h: 28,
        },
        {
            keyName: 'M',
            value: 16,
            x: 315,
            y: -171,
            w: 25,
            h: 28,
        },
        {
            keyName: ',',
            value: 54,
            x: 354,
            y: -171,
            w: 25,
            h: 28,
        },
        {
            keyName: '.',
            value: 55,
            x: 392,
            y: -171,
            w: 25,
            h: 28,
        },
        {
            keyName: '/',
            value: 56,
            x: 430,
            y: -171,
            w: 25,
            h: 28,
        },
        {
            keyName: 'r_Shift',
            value: 229,
            x: 468,
            y: -171,
            w: 92,
            h: 28,
        },
        {
            keyName: '↑',
            value: 82,
            x: 621,
            y: -171,
            w: 25,
            h: 28,
        },
        {
            keyName: 'num_1',
            value: 89,
            x: 708,
            y: -171,
            w: 25,
            h: 28,
        },
        {
            keyName: 'num_2',
            value: 90,
            x: 746,
            y: -171,
            w: 25,
            h: 28,
        },
        {
            keyName: 'num_3',
            value: 91,
            x: 784,
            y: -171,
            w: 25,
            h: 28,
        },
        {
            keyName: 'num_Enter',
            value: 88,
            x: 822,
            y: -171,
            w: 25,
            h: 67,
        },
        {
            keyName: 'Ctrl',
            value: 224,
            x: 0,
            y: -208,
            w: 35,
            h: 28,
        },
        {
            keyName: 'Win',
            value: 227,
            x: 48,
            y: -208,
            w: 35,
            h: 28,
        },
        {
            keyName: 'Alt',
            value: 226,
            x: 96,
            y: -208,
            w: 35,
            h: 28,
        },
        {
            keyName: '(space)',
            value: 44,
            x: 143,
            y: -208,
            w: 226,
            h: 28,
        },
        {
            keyName: 'r_Alt',
            value: 230,
            x: 382,
            y: -208,
            w: 35,
            h: 28,
        },
        {
            keyName: 'FN',
            value: 0x0a010000,
            x: 430,
            y: -208,
            w: 35,
            h: 28,
        },
        {
            keyName: '(Application)',
            value: 101,
            x: 477,
            y: -208,
            w: 35,
            h: 28,
        },
        {
            keyName: 'r_Ctrl',
            value: 228,
            x: 525,
            y: -208,
            w: 35,
            h: 28,
        },
        {
            keyName: '←',
            value: 80,
            x: 583,
            y: -208,
            w: 25,
            h: 28,
        },
        {
            keyName: '↓',
            value: 81,
            x: 621,
            y: -208,
            w: 25,
            h: 28,
        },
        {
            keyName: '→',
            value: 79,
            x: 659,
            y: -208,
            w: 25,
            h: 28,
        },
        {
            keyName: 'num_0',
            value: 98,
            x: 708,
            y: -208,
            w: 63,
            h: 28,
        },
        {
            keyName: 'num_.',
            value: 99,
            x: 784,
            y: -208,
            w: 25,
            h: 28,
        },
    ],
}
