export const yzw_lp87_dm = {
  deltX: 93,
  deltY: 21,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 26,
      h: 29,
    },
    {
      keyName: 'F1',
      value: 58,
      x: 75,
      y: 0,
      w: 26,
      h: 29,
    },
    {
      keyName: 'F2',
      value: 59,
      x: 113,
      y: 0,
      w: 26,
      h: 29,
    },
    {
      keyName: 'F3',
      value: 60,
      x: 151,
      y: 0,
      w: 26,
      h: 29,
    },
    {
      keyName: 'F4',
      value: 61,
      x: 189,
      y: 0,
      w: 26,
      h: 29,
    },
    {
      keyName: 'F5',
      value: 62,
      x: 248,
      y: 0,
      w: 26,
      h: 29,
    },
    {
      keyName: 'F6',
      value: 63,
      x: 286,
      y: 0,
      w: 26,
      h: 29,
    },
    {
      keyName: 'F7',
      value: 64,
      x: 324,
      y: 0,
      w: 26,
      h: 29,
    },
    {
      keyName: 'F8',
      value: 65,
      x: 362,
      y: 0,
      w: 26,
      h: 29,
    },
    {
      keyName: 'F9',
      value: 66,
      x: 419,
      y: 0,
      w: 26,
      h: 29,
    },
    {
      keyName: 'F10',
      value: 67,
      x: 457,
      y: 0,
      w: 26,
      h: 29,
    },
    {
      keyName: 'F11',
      value: 68,
      x: 495,
      y: 0,
      w: 26,
      h: 29,
    },
    {
      keyName: 'F12',
      value: 69,
      x: 533,
      y: 0,
      w: 26,
      h: 29,
    },
    {
      keyName: 'Print\nScreen',
      value: 70,
      x: 581,
      y: 0,
      w: 26,
      h: 29,
    },
    {
      keyName: 'Scroll\nLock',
      value: 71,
      x: 619,
      y: 0,
      w: 26,
      h: 29,
    },
    {
      keyName: 'Pause',
      value: 72,
      x: 658,
      y: 0,
      w: 26,
      h: 29,
    },
    {
      keyName: '`',
      value: 53,
      x: 0,
      y: -56,
      w: 26,
      h: 29,
    },
    {
      keyName: '1',
      value: 30,
      x: 39,
      y: -56,
      w: 26,
      h: 29,
    },
    {
      keyName: '2',
      value: 31,
      x: 77,
      y: -56,
      w: 26,
      h: 29,
    },
    {
      keyName: '3',
      value: 32,
      x: 115,
      y: -56,
      w: 26,
      h: 29,
    },
    {
      keyName: '4',
      value: 33,
      x: 153,
      y: -56,
      w: 26,
      h: 29,
    },
    {
      keyName: '5',
      value: 34,
      x: 191,
      y: -56,
      w: 26,
      h: 29,
    },
    {
      keyName: '6',
      value: 35,
      x: 229,
      y: -56,
      w: 26,
      h: 29,
    },
    {
      keyName: '7',
      value: 36,
      x: 267,
      y: -56,
      w: 26,
      h: 29,
    },
    {
      keyName: '8',
      value: 37,
      x: 306,
      y: -56,
      w: 26,
      h: 29,
    },
    {
      keyName: '9',
      value: 38,
      x: 344,
      y: -56,
      w: 26,
      h: 29,
    },
    {
      keyName: '0',
      value: 39,
      x: 382,
      y: -56,
      w: 26,
      h: 29,
    },
    {
      keyName: '-',
      value: 45,
      x: 419,
      y: -56,
      w: 26,
      h: 29,
    },
    {
      keyName: '=',
      value: 46,
      x: 457,
      y: -56,
      w: 26,
      h: 29,
    },
    {
      keyName: 'BackSpace',
      value: 42,
      x: 495,
      y: -56,
      w: 64,
      h: 29,
    },
    {
      keyName: 'Insert',
      value: 73,
      x: 581,
      y: -56,
      w: 26,
      h: 29,
    },
    {
      keyName: 'Home',
      value: 74,
      x: 619,
      y: -56,
      w: 26,
      h: 29,
    },
    {
      keyName: 'Page\nUp',
      value: 75,
      x: 658,
      y: -56,
      w: 26,
      h: 29,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -94,
      w: 43,
      h: 29,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 59,
      y: -94,
      w: 26,
      h: 29,
    },
    {
      keyName: 'W',
      value: 26,
      x: 97,
      y: -94,
      w: 26,
      h: 29,
    },
    {
      keyName: 'E',
      value: 8,
      x: 135,
      y: -94,
      w: 26,
      h: 29,
    },
    {
      keyName: 'R',
      value: 21,
      x: 173,
      y: -94,
      w: 26,
      h: 29,
    },
    {
      keyName: 'T',
      value: 23,
      x: 211,
      y: -94,
      w: 26,
      h: 29,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 249,
      y: -94,
      w: 26,
      h: 29,
    },
    {
      keyName: 'U',
      value: 24,
      x: 287,
      y: -94,
      w: 26,
      h: 29,
    },
    {
      keyName: 'I',
      value: 12,
      x: 325,
      y: -94,
      w: 26,
      h: 29,
    },
    {
      keyName: 'O',
      value: 18,
      x: 363,
      y: -94,
      w: 26,
      h: 29,
    },
    {
      keyName: 'P',
      value: 19,
      x: 401,
      y: -94,
      w: 26,
      h: 29,
    },
    {
      keyName: '[',
      value: 47,
      x: 439,
      y: -94,
      w: 26,
      h: 29,
    },
    {
      keyName: ']',
      value: 48,
      x: 477,
      y: -94,
      w: 26,
      h: 29,
    },
    {
      keyName: '\\',
      value: 49,
      x: 515,
      y: -94,
      w: 46,
      h: 29,
    },
    {
      keyName: 'Delete',
      value: 76,
      x: 581,
      y: -94,
      w: 26,
      h: 29,
    },
    {
      keyName: 'End',
      value: 77,
      x: 619,
      y: -94,
      w: 26,
      h: 29,
    },
    {
      keyName: 'Page\nDown',
      value: 78,
      x: 657,
      y: -94,
      w: 26,
      h: 29,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -131,
      w: 52,
      h: 29,
    },
    {
      keyName: 'A',
      value: 4,
      x: 67,
      y: -131,
      w: 26,
      h: 29,
    },
    {
      keyName: 'S',
      value: 22,
      x: 106,
      y: -131,
      w: 26,
      h: 29,
    },
    {
      keyName: 'D',
      value: 7,
      x: 144,
      y: -131,
      w: 26,
      h: 29,
    },
    {
      keyName: 'F',
      value: 9,
      x: 182,
      y: -131,
      w: 26,
      h: 29,
    },
    {
      keyName: 'G',
      value: 10,
      x: 220,
      y: -131,
      w: 26,
      h: 29,
    },
    {
      keyName: 'H',
      value: 11,
      x: 259,
      y: -131,
      w: 26,
      h: 29,
    },
    {
      keyName: 'J',
      value: 13,
      x: 297,
      y: -131,
      w: 26,
      h: 29,
    },
    {
      keyName: 'K',
      value: 14,
      x: 335,
      y: -131,
      w: 26,
      h: 29,
    },
    {
      keyName: 'L',
      value: 15,
      x: 373,
      y: -131,
      w: 26,
      h: 29,
    },
    {
      keyName: ';',
      value: 51,
      x: 411,
      y: -131,
      w: 26,
      h: 29,
    },
    {
      keyName: '\'',
      value: 52,
      x: 448,
      y: -131,
      w: 26,
      h: 29,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 487,
      y: -131,
      w: 72,
      h: 29,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -170,
      w: 72,
      h: 29,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 88,
      y: -170,
      w: 26,
      h: 29,
    },
    {
      keyName: 'X',
      value: 27,
      x: 126,
      y: -170,
      w: 26,
      h: 29,
    },
    {
      keyName: 'C',
      value: 6,
      x: 164,
      y: -170,
      w: 26,
      h: 29,
    },
    {
      keyName: 'V',
      value: 25,
      x: 202,
      y: -170,
      w: 26,
      h: 29,
    },
    {
      keyName: 'B',
      value: 5,
      x: 241,
      y: -170,
      w: 26,
      h: 29,
    },
    {
      keyName: 'N',
      value: 17,
      x: 277,
      y: -170,
      w: 26,
      h: 29,
    },
    {
      keyName: 'M',
      value: 16,
      x: 316,
      y: -170,
      w: 26,
      h: 29,
    },
    {
      keyName: ',',
      value: 54,
      x: 354,
      y: -170,
      w: 26,
      h: 29,
    },
    {
      keyName: '.',
      value: 55,
      x: 392,
      y: -170,
      w: 26,
      h: 29,
    },
    {
      keyName: '/',
      value: 56,
      x: 430,
      y: -170,
      w: 26,
      h: 29,
    },
    {
      keyName: 'r_Shift',
      value: 229,
      x: 467,
      y: -170,
      w: 93,
      h: 29,
    },
    {
      keyName: '↑',
      value: 82,
      x: 619,
      y: -170,
      w: 26,
      h: 29,
    },
    {
      keyName: 'Ctrl',
      value: 224,
      x: 0,
      y: -208,
      w: 35,
      h: 29,
    },
    {
      keyName: 'Win',
      value: 227,
      x: 48,
      y: -208,
      w: 35,
      h: 29,
    },
    {
      keyName: 'Alt',
      value: 226,
      x: 97,
      y: -208,
      w: 35,
      h: 29,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 145,
      y: -208,
      w: 225,
      h: 29,
    },
    {
      keyName: 'r_Alt',
      value: 230,
      x: 383,
      y: -208,
      w: 35,
      h: 29,
    },
    {
      keyName: 'FN',
      value: 0x0a010000,
      x: 430,
      y: -208,
      w: 35,
      h: 29,
    },
    {
      keyName: '(Application)',
      value: 101,
      x: 478,
      y: -208,
      w: 35,
      h: 29,
    },
    {
      keyName: 'r_Ctrl',
      value: 228,
      x: 524,
      y: -208,
      w: 35,
      h: 29,
    },
    {
      keyName: '←',
      value: 80,
      x: 582,
      y: -208,
      w: 26,
      h: 29,
    },
    {
      keyName: '↓',
      value: 81,
      x: 620,
      y: -208,
      w: 26,
      h: 29,
    },
    {
      keyName: '→',
      value: 79,
      x: 658,
      y: -208,
      w: 26,
      h: 29,
    },
  ]
}
