export const k68_magnet= {
  deltX: 57,
  deltY: 29,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 44,
      h: 44,
     },
    {
      keyName: '1',
      value: 30,
      x: 47,
      y: 0,
      w: 44,
      h: 44,
    },
    {
      keyName: '2',
      value: 31,
      x: 94,
      y: 0,
      w: 44,
      h: 44,
    },
    {
      keyName: '3',
      value: 32,
      x: 142,
      y: 0,
      w: 44,
      h: 44,
    },
    {
      keyName: '4',
      value: 33,
      x: 189,
      y: 0,
      w: 44,
      h: 44,
    },
    {
      keyName: '5',
      value: 34,
      x: 236,
      y: 0,
      w: 44,
      h: 44,
    },
    {
      keyName: '6',
      value: 35,
      x: 284,
      y: 0,
      w: 44,
      h: 44,
    },
    {
      keyName: '7',
      value: 36,
      x: 331,
      y: 0,
      w: 44,
      h: 44,
    },
    {
      keyName: '8',
      value: 37,
      x: 378,
      y: 0,
      w: 44,
      h: 44,
    },
    {
      keyName: '9',
      value: 38,
      x: 426,
      y: 0,
      w: 44,
      h: 44,
    },
    {
      keyName: '0',
      value: 39,
      x: 473,
      y: 0,
      w: 44,
      h: 44,
    },
    {
      keyName: '-',
      value: 45,
      x: 520,
      y: 0,
      w: 44,
      h: 44,
    },
    {
      keyName: '=',
      value: 46,
      x: 568,
      y: 0,
      w: 44,
      h: 44,
    },
    {
      keyName: 'Backspace',
      value: 42,
      x: 615,
      y: 0,
      w: 91,
      h: 44,
    },
    {
      keyName: 'Page\nUp',
      value: 75,
      x: 710,
      y: 0,
      w: 44,
      h: 44,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -47,
      w: 69,
      h: 44,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 71,
      y: -47,
      w: 44,
      h: 44,
    },
    {
      keyName: 'W',
      value: 26,
      x: 118,
      y: -47,
      w: 44,
      h: 44,
    },
    {
      keyName: 'E',
      value: 8,
      x: 165,
      y: -47,
      w: 44,
      h: 44,
    },
    {
      keyName: 'R',
      value: 21,
      x: 212,
      y: -47,
      w: 44,
      h: 44,
    },
    {
      keyName: 'T',
      value: 23,
      x: 260,
      y: -47,
      w: 44,
      h: 44,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 308,
      y: -47,
      w: 44,
      h: 44,
    },
    {
      keyName: 'U',
      value: 24,
      x: 355,
      y: -47,
      w: 44,
      h: 44,
    },
    {
      keyName: 'I',
      value: 12,
      x: 402,
      y: -47,
      w: 44,
      h: 44,
    },
    {
      keyName: 'O',
      value: 18,
      x: 450,
      y: -47,
      w: 44,
      h: 44,
    },
    {
      keyName: 'P',
      value: 19,
      x: 497,
      y: -47,
      w: 44,
      h: 44,
    },
    {
      keyName: '[',
      value: 47,
      x: 544,
      y: -47,
      w: 44,
      h: 44,
    },
    {
      keyName: ']',
      value: 48,
      x: 591,
      y: -47,
      w: 44,
      h: 44,
    },
    {
      keyName: '\\',
      value: 49,
      x: 639,
      y: -47,
      w: 67,
      h: 44,
    },
    {
      keyName: 'Page\nDown',
      value: 78,
      x: 710,
      y: -47,
      w: 44,
      h: 44,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -95,
      w: 79,
      h: 44,
    },
    {
      keyName: 'A',
      value: 4,
      x: 83,
      y: -95,
      w: 44,
      h: 44,
    },
    {
      keyName: 'S',
      value: 22,
      x: 130,
      y: -95,
      w: 44,
      h: 44,
    },
    {
      keyName: 'D',
      value: 7,
      x: 177,
      y: -95,
      w: 44,
      h: 44,
    },
    {
      keyName: 'F',
      value: 9,
      x: 224,
      y: -95,
      w: 44,
      h: 44,
    },
    {
      keyName: 'G',
      value: 10,
      x: 272,
      y: -95,
      w: 44,
      h: 44,
    },
    {
      keyName: 'H',
      value: 11,
      x: 319,
      y: -95,
      w: 44,
      h: 44,
    },
    {
      keyName: 'J',
      value: 13,
      x: 367,
      y: -95,
      w: 44,
      h: 44,
    },
    {
      keyName: 'K',
      value: 14,
      x: 414,
      y: -95,
      w: 44,
      h: 44,
    },
    {
      keyName: 'L',
      value: 15,
      x: 461,
      y: -95,
      w: 44,
      h: 44,
    },
    {
      keyName: ';',
      value: 51,
      x: 509,
      y: -95,
      w: 44,
      h: 44,
    },
    {
      keyName: '\'',
      value: 52,
      x: 556,
      y: -95,
      w: 44,
      h: 44,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 604,
      y: -95,
      w: 102,
      h: 44,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -142,
      w: 104,
      h: 44,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 107,
      y: -142,
      w: 44,
      h: 44,
    },
    {
      keyName: 'X',
      value: 27,
      x: 154,
      y: -142,
      w: 44,
      h: 44,
    },
    {
      keyName: 'C',
      value: 6,
      x: 201,
      y: -142,
      w: 44,
      h: 44,
    },
    {
      keyName: 'V',
      value: 25,
      x: 249,
      y: -142,
      w: 44,
      h: 44,
    },
    {
      keyName: 'B',
      value: 5,
      x: 296,
      y: -142,
      w: 44,
      h: 44,
    },
    {
      keyName: 'N',
      value: 17,
      x: 343,
      y: -142,
      w: 44,
      h: 44,
    },
    {
      keyName: 'M',
      value: 16,
      x: 391,
      y: -142,
      w: 44,
      h: 44,
    },
    {
      keyName: ',',
      value: 54,
      x: 438,
      y: -142,
      w: 44,
      h: 44,
    },
    {
      keyName: '.',
      value: 55,
      x: 485,
      y: -142,
      w: 44,
      h: 44,
    },
    {
      keyName: '/',
      value: 56,
      x: 532,
      y: -142,
      w: 44,
      h: 44,
    },
    {
      keyName: 'r_Shift',
      value: 229,
      x: 580,
      y: -142,
      w: 78,
      h: 44,
    },
    {
      keyName: '↑',
      value: 82,
      x: 662,
      y: -142,
      w: 44,
      h: 44,
    },
    {
      keyName: 'CTRL',
      value: 224,
      x: 0,
      y: -189,
      w: 57,
      h: 44,
    },
    {
      keyName: 'Win',
      value: 227,
      x: 59,
      y: -189,
      w: 57,
      h: 44,
    },
    {
      keyName: 'ALT',
      value: 226,
      x: 119,
      y: -189,
      w: 57,
      h: 44,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 179,
      y: -189,
      w: 290,
      h: 44,
    },
    {
      keyName: 'r_Alt',
      value: 230,
      x: 472,
      y: -189,
      w: 57,
      h: 44,
    },
    {
      keyName: 'r_Ctrl',
      value: 228,
      x: 532,
      y: -189,
      w: 57,
      h: 44,
    },
    {
      keyName: '←',
      value: 80,
      x: 615,
      y: -189,
      w: 44,
      h: 44,
    },
    {
      keyName: '↓',
      value: 81,
      x: 662,
      y: -189,
      w: 44,
      h: 44,
    },
    {
      keyName: '→',
      value: 79,
      x: 710,
      y: -189,
      w: 44,
      h: 44,
    },
  ],
}
