export const k68_tk568 = {
  deltX: 52,
  deltY: 38,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 33,
      h: 37,
    },
    {
      keyName: '1',
      value: 30,
      x: 48,
      y: 0,
      w: 33,
      h: 37,
    },
    {
      keyName: '2',
      value: 31,
      x: 97,
      y: 0,
      w: 33,
      h: 37,
    },
    {
      keyName: '3',
      value: 32,
      x: 146,
      y: 0,
      w: 33,
      h: 37,
    },
    {
      keyName: '4',
      value: 33,
      x: 195,
      y: 0,
      w: 33,
      h: 37,
    },
    {
      keyName: '5',
      value: 34,
      x: 244,
      y: 0,
      w: 33,
      h: 37,
    },
    {
      keyName: '6',
      value: 35,
      x: 293,
      y: 0,
      w: 33,
      h: 37,
    },
    {
      keyName: '7',
      value: 36,
      x: 342,
      y: 0,
      w: 33,
      h: 37,
    },
    {
      keyName: '8',
      value: 37,
      x: 391,
      y: 0,
      w: 33,
      h: 37,
    },
    {
      keyName: '9',
      value: 38,
      x: 439,
      y: 0,
      w: 33,
      h: 37,
    },
    {
      keyName: '0',
      value: 39,
      x: 488,
      y: 0,
      w: 33,
      h: 37,
    },
    {
      keyName: '-',
      value: 45,
      x: 537,
      y: 0,
      w: 33,
      h: 37,
    },
    {
      keyName: '=',
      value: 46,
      x: 586,
      y: 0,
      w: 33,
      h: 37,
    },
    {
      keyName: 'Backspace',
      value: 42,
      x: 636,
      y: 0,
      w: 83,
      h: 37,
    },
    {
      keyName: 'Delete',
      value: 76,
      x: 734,
      y: 0,
      w: 33,
      h: 37,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -49,
      w: 58,
      h: 37,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 73,
      y: -49,
      w: 33,
      h: 37,
    },
    {
      keyName: 'W',
      value: 26,
      x: 122,
      y: -49,
      w: 33,
      h: 37,
    },
    {
      keyName: 'E',
      value: 8,
      x: 171,
      y: -49,
      w: 33,
      h: 37,
    },
    {
      keyName: 'R',
      value: 21,
      x: 220,
      y: -49,
      w: 33,
      h: 37,
    },
    {
      keyName: 'T',
      value: 23,
      x: 269,
      y: -49,
      w: 33,
      h: 37,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 318,
      y: -49,
      w: 33,
      h: 37,
    },
    {
      keyName: 'U',
      value: 24,
      x: 367,
      y: -49,
      w: 33,
      h: 37,
    },
    {
      keyName: 'I',
      value: 12,
      x: 416,
      y: -49,
      w: 33,
      h: 37,
    },
    {
      keyName: 'O',
      value: 18,
      x: 464,
      y: -49,
      w: 33,
      h: 37,
    },
    {
      keyName: 'P',
      value: 19,
      x: 513,
      y: -49,
      w: 33,
      h: 37,
    },
    {
      keyName: '[',
      value: 47,
      x: 562,
      y: -49,
      w: 33,
      h: 37,
    },
    {
      keyName: ']',
      value: 48,
      x: 611,
      y: -49,
      w: 33,
      h: 37,
    },
    {
      keyName: '\\',
      value: 49,
      x: 660,
      y: -49,
      w: 58,
      h: 37,
    },
    {
      keyName: 'Insert',
      value: 73,
      x: 734,
      y: -49,
      w: 33,
      h: 37,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -98,
      w: 70,
      h: 37,
    },
    {
      keyName: 'A',
      value: 4,
      x: 85,
      y: -98,
      w: 33,
      h: 37,
    },
    {
      keyName: 'S',
      value: 22,
      x: 134,
      y: -98,
      w: 33,
      h: 37,
    },
    {
      keyName: 'D',
      value: 7,
      x: 183,
      y: -98,
      w: 33,
      h: 37,
    },
    {
      keyName: 'F',
      value: 9,
      x: 232,
      y: -98,
      w: 33,
      h: 37,
    },
    {
      keyName: 'G',
      value: 10,
      x: 281,
      y: -98,
      w: 33,
      h: 37,
    },
    {
      keyName: 'H',
      value: 11,
      x: 330,
      y: -98,
      w: 33,
      h: 37,
    },
    {
      keyName: 'J',
      value: 13,
      x: 379,
      y: -98,
      w: 33,
      h: 37,
    },
    {
      keyName: 'K',
      value: 14,
      x: 428,
      y: -98,
      w: 33,
      h: 37,
    },
    {
      keyName: 'L',
      value: 15,
      x: 476,
      y: -98,
      w: 33,
      h: 37,
    },
    {
      keyName: ';',
      value: 51,
      x: 525,
      y: -98,
      w: 33,
      h: 37,
    },
    {
      keyName: '\'',
      value: 52,
      x: 574,
      y: -98,
      w: 33,
      h: 37,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 623,
      y: -98,
      w: 95,
      h: 37,
    },
    {
      keyName: 'Page\nUp',
      value: 75,
      x: 734,
      y: -98,
      w: 33,
      h: 37,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -147,
      w: 97,
      h: 37,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 110,
      y: -147,
      w: 33,
      h: 37,
    },
    {
      keyName: 'X',
      value: 27,
      x: 159,
      y: -147,
      w: 33,
      h: 37,
    },
    {
      keyName: 'C',
      value: 6,
      x: 208,
      y: -147,
      w: 33,
      h: 37,
    },
    {
      keyName: 'V',
      value: 25,
      x: 257,
      y: -147,
      w: 33,
      h: 37,
    },
    {
      keyName: 'B',
      value: 5,
      x: 305,
      y: -147,
      w: 33,
      h: 37,
    },
    {
      keyName: 'N',
      value: 17,
      x: 354,
      y: -147,
      w: 33,
      h: 37,
    },
    {
      keyName: 'M',
      value: 16,
      x: 403,
      y: -147,
      w: 33,
      h: 37,
    },
    {
      keyName: ',',
      value: 54,
      x: 452,
      y: -147,
      w: 33,
      h: 37,
    },
    {
      keyName: '.',
      value: 55,
      x: 501,
      y: -147,
      w: 33,
      h: 37,
    },
    {
      keyName: '/',
      value: 56,
      x: 550,
      y: -147,
      w: 33,
      h: 37,
    },
    {
      keyName: 'r_Shift',
      value: 229,
      x: 599,
      y: -147,
      w: 72,
      h: 37,
    },
    {
      keyName: '↑',
      value: 82,
      x: 685,
      y: -147,
      w: 33,
      h: 37,
    },
    {
      keyName: 'Page\nDown',
      value: 78,
      x: 734,
      y: -147,
      w: 33,
      h: 37,
    },
    {
      keyName: 'CTRL',
      value: 224,
      x: 0,
      y: -196,
      w: 58,
      h: 37,
    },
    {
      keyName: 'FN',
      value: 0x0a010000,
      x: 73,
      y: -196,
      w: 33,
      h: 37,
    },
    {
      keyName: 'Win',
      value: 227,
      x: 122,
      y: -196,
      w: 33,
      h: 37,
    },
    {
      keyName: 'ALT',
      value: 226,
      x: 171,
      y: -196,
      w: 33,
      h: 37,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 220,
      y: -196,
      w: 277,
      h: 37,
    },
    {
      keyName: 'r_Alt',
      value: 230,
      x: 514,
      y: -196,
      w: 33,
      h: 37,
    },
    {
      keyName: 'r_Ctrl',
      value: 228,
      x: 562,
      y: -196,
      w: 57,
      h: 37,
    },
    {
      keyName: '←',
      value: 80,
      x: 636,
      y: -196,
      w: 33,
      h: 37,
    },
    {
      keyName: '↓',
      value: 81,
      x: 685,
      y: -196,
      w: 33,
      h: 37,
    },
    {
      keyName: '→',
      value: 79,
      x: 734,
      y: -196,
      w: 33,
      h: 37,
    },
  ],
}
