export const k68_hyekyu = {
  deltX: 105,
  deltY: 59,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 30,
      h: 34,
     },
    {
      keyName: '1',
      value: 30,
      x: 45,
      y: 0,
      w: 30,
      h: 34,
    },
    {
      keyName: '2',
      value: 31,
      x: 90,
      y: 0,
      w: 30,
      h: 34,
    },
    {
      keyName: '3',
      value: 32,
      x: 134,
      y: 0,
      w: 30,
      h: 34,
    },
    {
      keyName: '4',
      value: 33,
      x: 179,
      y: 0,
      w: 30,
      h: 34,
    },
    {
      keyName: '5',
      value: 34,
      x: 223,
      y: 0,
      w: 30,
      h: 34,
    },
    {
      keyName: '6',
      value: 35,
      x: 268,
      y: 0,
      w: 30,
      h: 34,
    },
    {
      keyName: '7',
      value: 36,
      x: 313,
      y: 0,
      w: 30,
      h: 34,
    },
    {
      keyName: '8',
      value: 37,
      x: 357,
      y: 0,
      w: 30,
      h: 34,
    },
    {
      keyName: '9',
      value: 38,
      x: 401,
      y: 0,
      w: 30,
      h: 34,
    },
    {
      keyName: '0',
      value: 39,
      x: 446,
      y: 0,
      w: 30,
      h: 34,
    },
    {
      keyName: '-',
      value: 45,
      x: 491,
      y: 0,
      w: 30,
      h: 34,
    },
    {
      keyName: '+',
      value: 46,
      x: 536,
      y: 0,
      w: 30,
      h: 34,
    },
    {
      keyName: 'Backspace',
      value: 42,
      x: 581,
      y: 0,
      w: 74,
      h: 34,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -45,
      w: 52,
      h: 34,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 67,
      y: -45,
      w: 30,
      h: 34,
    },
    {
      keyName: 'W',
      value: 26,
      x: 112,
      y: -45,
      w: 30,
      h: 34,
    },
    {
      keyName: 'E',
      value: 8,
      x: 156,
      y: -45,
      w: 30,
      h: 34,
    },
    {
      keyName: 'R',
      value: 21,
      x: 201,
      y: -45,
      w: 30,
      h: 34,
    },
    {
      keyName: 'T',
      value: 23,
      x: 245,
      y: -45,
      w: 30,
      h: 34,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 290,
      y: -45,
      w: 30,
      h: 34,
    },
    {
      keyName: 'U',
      value: 24,
      x: 335,
      y: -45,
      w: 30,
      h: 34,
    },
    {
      keyName: 'I',
      value: 12,
      x: 379,
      y: -45,
      w: 30,
      h: 34,
    },
    {
      keyName: 'O',
      value: 18,
      x: 423,
      y: -45,
      w: 30,
      h: 34,
    },
    {
      keyName: 'P',
      value: 19,
      x: 468,
      y: -45,
      w: 30,
      h: 34,
    },
    {
      keyName: '[',
      value: 47,
      x: 513,
      y: -45,
      w: 30,
      h: 34,
    },
    {
      keyName: ']',
      value: 48,
      x: 558,
      y: -45,
      w: 30,
      h: 34,
    },
    {
      keyName: '\\',
      value: 49,
      x: 602,
      y: -45,
      w: 53,
      h: 34,
    },
    {
      keyName: 'CapsLock',
      value: 57,
      x: 0,
      y: -90,
      w: 67,
      h: 34,
    },
    {
      keyName: 'A',
      value: 4,
      x: 80,
      y: -90,
      w: 30,
      h: 34,
    },
    {
      keyName: 'S',
      value: 22,
      x: 125,
      y: -90,
      w: 30,
      h: 34,
    },
    {
      keyName: 'D',
      value: 7,
      x: 169,
      y: -90,
      w: 30,
      h: 34,
    },
    {
      keyName: 'F',
      value: 9,
      x: 214,
      y: -90,
      w: 30,
      h: 34,
    },
    {
      keyName: 'G',
      value: 10,
      x: 258,
      y: -90,
      w: 30,
      h: 34,
    },
    {
      keyName: 'H',
      value: 11,
      x: 303,
      y: -90,
      w: 30,
      h: 34,
    },
    {
      keyName: 'J',
      value: 13,
      x: 348,
      y: -90,
      w: 30,
      h: 34,
    },
    {
      keyName: 'K',
      value: 14,
      x: 392,
      y: -90,
      w: 30,
      h: 34,
    },
    {
      keyName: 'L',
      value: 15,
      x: 436,
      y: -90,
      w: 30,
      h: 34,
    },
    {
      keyName: ';',
      value: 51,
      x: 481,
      y: -90,
      w: 30,
      h: 34,
    },
    {
      keyName: '"',
      value: 52,
      x: 526,
      y: -90,
      w: 30,
      h: 34,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 571,
      y: -90,
      w: 84,
      h: 34,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -135,
      w: 82,
      h: 34,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 99,
      y: -135,
      w: 30,
      h: 34,
    },
    {
      keyName: 'X',
      value: 27,
      x: 144,
      y: -135,
      w: 30,
      h: 34,
    },
    {
      keyName: 'C',
      value: 6,
      x: 188,
      y: -135,
      w: 30,
      h: 34,
    },
    {
      keyName: 'V',
      value: 25,
      x: 233,
      y: -135,
      w: 30,
      h: 34,
    },
    {
      keyName: 'B',
      value: 5,
      x: 277,
      y: -135,
      w: 30,
      h: 34,
    },
    {
      keyName: 'N',
      value: 17,
      x: 322,
      y: -135,
      w: 30,
      h: 34,
    },
    {
      keyName: 'M',
      value: 16,
      x: 367,
      y: -135,
      w: 30,
      h: 34,
    },
    {
      keyName: ',',
      value: 54,
      x: 411,
      y: -135,
      w: 30,
      h: 34,
    },
    {
      keyName: '.',
      value: 55,
      x: 455,
      y: -135,
      w: 30,
      h: 34,
    },
    {
      keyName: '/',
      value: 56,
      x: 501,
      y: -135,
      w: 43,
      h: 34,
    },
    {
      keyName: '↑',
      value: 82,
      x: 559,
      y: -135,
      w: 43,
      h: 34,
    },
    {
      keyName: 'r_Shift',
      value: 229,
      x: 615,
      y: -135,
      w: 43,
      h: 34,
    },
    {
      keyName: 'CTRL',
      value: 224,
      x: 0,
      y: -180,
      w: 52,
      h: 34,
    },
    {
      keyName: 'Win',
      value: 227,
      x: 67,
      y: -180,
      w: 43,
      h: 34,
    },
    {
      keyName: 'ALT',
      value: 226,
      x: 122,
      y: -180,
      w: 43,
      h: 34,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 175,
      y: -180,
      w: 261,
      h: 34,
    },
    {
      keyName: 'FN',
      value: 0x0a010000,
      x: 447,
      y: -180,
      w: 43,
      h: 34,
    },
    {
      keyName: '←',
      value: 80,
      x: 504,
      y: -180,
      w: 43,
      h: 34,
    },
    {
      keyName: '↓',
      value: 81,
      x: 559,
      y: -180,
      w: 43,
      h: 34,
    },
    {
      keyName: '→',
      value: 79,
      x: 615,
      y: -180,
      w: 43,
      h: 34,
    },
  ],
}
