export const yc500_fk5183_soc = {
  deltX: 32,
  deltY: 30,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 31,
      h: 36,
    },
    {
      keyName: '1',
      value: 30,
      x: 51,
      y: 0,
      w: 31,
      h: 36,
    },
    {
      keyName: '2',
      value: 31,
      x: 103,
      y: 0,
      w: 31,
      h: 36,
    },
    {
      keyName: '3',
      value: 32,
      x: 155,
      y: 0,
      w: 31,
      h: 36,
    },
    {
      keyName: '4',
      value: 33,
      x: 206,
      y: 0,
      w: 31,
      h: 36,
    },
    {
      keyName: '5',
      value: 34,
      x: 258,
      y: 0,
      w: 31,
      h: 36,
    },
    {
      keyName: '6',
      value: 35,
      x: 310,
      y: 0,
      w: 31,
      h: 36,
    },
    {
      keyName: '7',
      value: 36,
      x: 361,
      y: 0,
      w: 31,
      h: 36,
    },
    {
      keyName: '8',
      value: 37,
      x: 413,
      y: 0,
      w: 31,
      h: 36,
    },
    {
      keyName: '9',
      value: 38,
      x: 465,
      y: 0,
      w: 31,
      h: 36,
    },
    {
      keyName: '0',
      value: 39,
      x: 517,
      y: 0,
      w: 31,
      h: 36,
    },
    {
      keyName: '-',
      value: 45,
      x: 569,
      y: 0,
      w: 31,
      h: 36,
    },
    {
      keyName: '=',
      value: 46,
      x: 620,
      y: 0,
      w: 31,
      h: 36,
    },
    {
      keyName: 'Backspace',
      value: 42,
      x: 672,
      y: 0,
      w: 82,
      h: 36,
    },
    {
      keyName: 'U-',
      value: 0x0300ea00,
      knob: true,
      x: 767,
      y: 4,
      w: 12,
      h: 48,
    },
    {
      keyName: 'play',
      value: 0x0300cd00,
      knob: true,
      x: 786,
      y: 4,
      w: 12,
      h: 48,
    },
    {
      keyName: 'U+',
      value: 0x0300e900,
      knob: true,
      x: 804,
      y: 4,
      w: 12,
      h: 48,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -48,
      w: 58,
      h: 36,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 77,
      y: -48,
      w: 31,
      h: 36,
    },
    {
      keyName: 'W',
      value: 26,
      x: 129,
      y: -48,
      w: 31,
      h: 36,
    },
    {
      keyName: 'E',
      value: 8,
      x: 181,
      y: -48,
      w: 31,
      h: 36,
    },
    {
      keyName: 'R',
      value: 21,
      x: 232,
      y: -48,
      w: 31,
      h: 36,
    },
    {
      keyName: 'T',
      value: 23,
      x: 284,
      y: -48,
      w: 31,
      h: 36,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 336,
      y: -48,
      w: 31,
      h: 36,
    },
    {
      keyName: 'U',
      value: 24,
      x: 387,
      y: -48,
      w: 31,
      h: 36,
    },
    {
      keyName: 'I',
      value: 12,
      x: 439,
      y: -48,
      w: 31,
      h: 36,
    },
    {
      keyName: 'O',
      value: 18,
      x: 491,
      y: -48,
      w: 31,
      h: 36,
    },
    {
      keyName: 'P',
      value: 19,
      x: 543,
      y: -48,
      w: 31,
      h: 36,
    },
    {
      keyName: '[',
      value: 47,
      x: 595,
      y: -48,
      w: 31,
      h: 36,
    },
    {
      keyName: ']',
      value: 48,
      x: 646,
      y: -48,
      w: 31,
      h: 36,
    },
    {
      keyName: '\\',
      value: 49,
      x: 696,
      y: -48,
      w: 60,
      h: 36,
    },
    {
      keyName: 'Delete',
      value: 76,
      x: 775,
      y: -48,
      w: 31,
      h: 36,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -96,
      w: 70,
      h: 36,
    },
    {
      keyName: 'A',
      value: 4,
      x: 90,
      y: -96,
      w: 31,
      h: 36,
    },
    {
      keyName: 'S',
      value: 22,
      x: 142,
      y: -96,
      w: 31,
      h: 36,
    },
    {
      keyName: 'D',
      value: 7,
      x: 194,
      y: -96,
      w: 31,
      h: 36,
    },
    {
      keyName: 'F',
      value: 9,
      x: 245,
      y: -96,
      w: 31,
      h: 36,
    },
    {
      keyName: 'G',
      value: 10,
      x: 297,
      y: -96,
      w: 31,
      h: 36,
    },
    {
      keyName: 'H',
      value: 11,
      x: 349,
      y: -96,
      w: 31,
      h: 36,
    },
    {
      keyName: 'J',
      value: 13,
      x: 400,
      y: -96,
      w: 31,
      h: 36,
    },
    {
      keyName: 'K',
      value: 14,
      x: 452,
      y: -96,
      w: 31,
      h: 36,
    },
    {
      keyName: 'L',
      value: 15,
      x: 504,
      y: -96,
      w: 31,
      h: 36,
    },
    {
      keyName: ';',
      value: 51,
      x: 555,
      y: -96,
      w: 31,
      h: 36,
    },
    {
      keyName: '"',
      value: 52,
      x: 607,
      y: -96,
      w: 31,
      h: 36,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 659,
      y: -96,
      w: 95,
      h: 36,
    },
    {
      keyName: 'Home',
      value: 74,
      x: 775,
      y: -96,
      w: 31,
      h: 36,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -144,
      w: 96,
      h: 36,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 116,
      y: -143,
      w: 31,
      h: 36,
    },
    {
      keyName: 'X',
      value: 27,
      x: 168,
      y: -143,
      w: 31,
      h: 36,
    },
    {
      keyName: 'C',
      value: 6,
      x: 220,
      y: -143,
      w: 31,
      h: 36,
    },
    {
      keyName: 'V',
      value: 25,
      x: 271,
      y: -143,
      w: 31,
      h: 36,
    },
    {
      keyName: 'B',
      value: 5,
      x: 323,
      y: -143,
      w: 31,
      h: 36,
    },
    {
      keyName: 'N',
      value: 17,
      x: 375,
      y: -143,
      w: 31,
      h: 36,
    },
    {
      keyName: 'M',
      value: 16,
      x: 426,
      y: -143,
      w: 31,
      h: 36,
    },
    {
      keyName: ',',
      value: 54,
      x: 478,
      y: -143,
      w: 31,
      h: 36,
    },
    {
      keyName: '.',
      value: 55,
      x: 530,
      y: -143,
      w: 31,
      h: 36,
    },
    {
      keyName: '/',
      value: 56,
      x: 581,
      y: -143,
      w: 31,
      h: 36,
    },
    {
      keyName: 'R_Shift',
      value: 229,
      x: 633,
      y: -143,
      w: 69,
      h: 36,
    },
    {
      keyName: '↑',
      value: 82,
      x: 723,
      y: -143,
      w: 31,
      h: 36,
    },
    {
      keyName: 'End',
      value: 77,
      x: 775,
      y: -143,
      w: 31,
      h: 36,
    },
    {
      keyName: 'Ctrl',
      value: 224,
      x: 0,
      y: -193,
      w: 44,
      h: 36,
    },
    {
      keyName: 'win',
      value: 227,
      x: 64,
      y: -193,
      w: 44,
      h: 36,
    },
    {
      keyName: 'Alt',
      value: 226,
      x: 129,
      y: -193,
      w: 44,
      h: 36,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 194,
      y: -193,
      w: 300,
      h: 36,
    },
    {
      keyName: 'Fn',
      value: 0x0a010000,
      x: 517,
      y: -193,
      w: 44,
      h: 36,
    },
    {
      keyName: 'r_Ctrl',
      value: 228,
      x: 582,
      y: -193,
      w: 44,
      h: 36,
    },
    {
      keyName: '←',
      value: 80,
      x: 671,
      y: -193,
      w: 31,
      h: 36,
    },
    {
      keyName: '↓',
      value: 81,
      x: 723,
      y: -193,
      w: 31,
      h: 36,
    },
    {
      keyName: '→',
      value: 79,
      x: 775,
      y: -193,
      w: 31,
      h: 36,
    },
  ],
}
