export const yc500_zsx68 = {
  deltX: 51,
  deltY: 25,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 32,
      h: 36,
    },
    {
      keyName: '1',
      value: 30,
      x: 47,
      y: 0,
      w: 32,
      h: 36,
    },
    {
      keyName: '2',
      value: 31,
      x: 95,
      y: 0,
      w: 32,
      h: 36,
    },
    {
      keyName: '3',
      value: 32,
      x: 143,
      y: 0,
      w: 32,
      h: 36,
    },
    {
      keyName: '4',
      value: 33,
      x: 190,
      y: 0,
      w: 32,
      h: 36,
    },
    {
      keyName: '5',
      value: 34,
      x: 238,
      y: 0,
      w: 32,
      h: 36,
    },
    {
      keyName: '6',
      value: 35,
      x: 285,
      y: 0,
      w: 32,
      h: 36,
    },
    {
      keyName: '7',
      value: 36,
      x: 333,
      y: 0,
      w: 32,
      h: 36,
    },
    {
      keyName: '8',
      value: 37,
      x: 381,
      y: 0,
      w: 32,
      h: 36,
    },
    {
      keyName: '9',
      value: 38,
      x: 429,
      y: 0,
      w: 32,
      h: 36,
    },
    {
      keyName: '0',
      value: 39,
      x: 476,
      y: 0,
      w: 32,
      h: 36,
    },
    {
      keyName: '-',
      value: 45,
      x: 524,
      y: 0,
      w: 32,
      h: 36,
    },
    {
      keyName: '=',
      value: 46,
      x: 572,
      y: 0,
      w: 32,
      h: 36,
    },
    {
      keyName: 'Backspace',
      value: 42,
      x: 619,
      y: 0,
      w: 80,
      h: 36,
    },
    {
      keyName: 'U-',
      value: 0x0300ea00,
      knob: true,
      x: 724,
      y: 15,
      w: 16,
      h: 55,
    },
    {
      keyName: 'Mute',
      value: 0x0300e200,
      knob: true,
      // ban:true,
      x: 747,
      y: 13,
      w: 16,
      h: 51,
    },
    {
      keyName: 'U+',
      value: 0x0300e900,
      knob: true,
      x: 769,
      y: 15,
      w: 16,
      h: 55,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -48,
      w: 56,
      h: 36,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 71,
      y: -48,
      w: 32,
      h: 36,
    },
    {
      keyName: 'W',
      value: 26,
      x: 119,
      y: -48,
      w: 32,
      h: 36,
    },
    {
      keyName: 'E',
      value: 8,
      x: 167,
      y: -48,
      w: 32,
      h: 36,
    },
    {
      keyName: 'R',
      value: 21,
      x: 214,
      y: -48,
      w: 32,
      h: 36,
    },
    {
      keyName: 'T',
      value: 23,
      x: 262,
      y: -48,
      w: 32,
      h: 36,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 309,
      y: -48,
      w: 32,
      h: 36,
    },
    {
      keyName: 'U',
      value: 24,
      x: 357,
      y: -48,
      w: 32,
      h: 36,
    },
    {
      keyName: 'I',
      value: 12,
      x: 405,
      y: -48,
      w: 32,
      h: 36,
    },
    {
      keyName: 'O',
      value: 18,
      x: 453,
      y: -48,
      w: 32,
      h: 36,
    },
    {
      keyName: 'P',
      value: 19,
      x: 500,
      y: -48,
      w: 32,
      h: 36,
    },
    {
      keyName: '[',
      value: 47,
      x: 548,
      y: -48,
      w: 32,
      h: 36,
    },
    {
      keyName: ']',
      value: 48,
      x: 595,
      y: -48,
      w: 32,
      h: 36,
    },
    {
      keyName: '\\',
      value: 49,
      x: 643,
      y: -48,
      w: 56,
      h: 36,
    },
    {
      keyName: 'Delete',
      value: 76,
      x: 738,
      y: -48,
      w: 32,
      h: 36,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -95,
      w: 67,
      h: 36,
    },
    {
      keyName: 'A',
      value: 4,
      x: 83,
      y: -95,
      w: 32,
      h: 36,
    },
    {
      keyName: 'S',
      value: 22,
      x: 131,
      y: -95,
      w: 32,
      h: 36,
    },
    {
      keyName: 'D',
      value: 7,
      x: 179,
      y: -95,
      w: 32,
      h: 36,
    },
    {
      keyName: 'F',
      value: 9,
      x: 226,
      y: -95,
      w: 32,
      h: 36,
    },
    {
      keyName: 'G',
      value: 10,
      x: 274,
      y: -95,
      w: 32,
      h: 36,
    },
    {
      keyName: 'H',
      value: 11,
      x: 321,
      y: -95,
      w: 32,
      h: 36,
    },
    {
      keyName: 'J',
      value: 13,
      x: 369,
      y: -95,
      w: 32,
      h: 36,
    },
    {
      keyName: 'K',
      value: 14,
      x: 417,
      y: -95,
      w: 32,
      h: 36,
    },
    {
      keyName: 'L',
      value: 15,
      x: 465,
      y: -95,
      w: 32,
      h: 36,
    },
    {
      keyName: ';',
      value: 51,
      x: 512,
      y: -95,
      w: 32,
      h: 36,
    },
    {
      keyName: '"',
      value: 52,
      x: 560,
      y: -95,
      w: 32,
      h: 36,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 607,
      y: -95,
      w: 92,
      h: 36,
    },
    {
      keyName: 'Page\nUp',
      value: 75,
      x: 738,
      y: -95,
      w: 32,
      h: 36,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -142,
      w: 92,
      h: 36,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 107,
      y: -142,
      w: 32,
      h: 36,
    },
    {
      keyName: 'X',
      value: 27,
      x: 155,
      y: -142,
      w: 32,
      h: 36,
    },
    {
      keyName: 'C',
      value: 6,
      x: 203,
      y: -142,
      w: 32,
      h: 36,
    },
    {
      keyName: 'V',
      value: 25,
      x: 250,
      y: -142,
      w: 32,
      h: 36,
    },
    {
      keyName: 'B',
      value: 5,
      x: 298,
      y: -142,
      w: 32,
      h: 36,
    },
    {
      keyName: 'N',
      value: 17,
      x: 345,
      y: -142,
      w: 32,
      h: 36,
    },
    {
      keyName: 'M',
      value: 16,
      x: 393,
      y: -142,
      w: 32,
      h: 36,
    },
    {
      keyName: ',',
      value: 54,
      x: 441,
      y: -142,
      w: 32,
      h: 36,
    },
    {
      keyName: '.',
      value: 55,
      x: 489,
      y: -142,
      w: 32,
      h: 36,
    },
    {
      keyName: '/',
      value: 56,
      x: 536,
      y: -142,
      w: 32,
      h: 36,
    },
    {
      keyName: 'R-Shift',
      value: 229,
      x: 584,
      y: -142,
      w: 67,
      h: 36,
    },
    {
      keyName: 'Page\nDown',
      value: 78,
      x: 738,
      y: -142,
      w: 32,
      h: 36,
    },
    {
      keyName: '↑',
      value: 82,
      x: 679,
      y: -154,
      w: 32,
      h: 36,
    },
    {
      keyName: 'Ctrl',
      value: 224,
      x: 0,
      y: -190,
      w: 44,
      h: 36,
    },
    {
      keyName: 'win',
      value: 227,
      x: 59,
      y: -190,
      w: 44,
      h: 36,
    },
    {
      keyName: 'Alt',
      value: 226,
      x: 119,
      y: -190,
      w: 44,
      h: 36,
    },
    {
      keyName: 'space',
      value: 44,
      x: 179,
      y: -190,
      w: 282,
      h: 36,
    },
    {
      keyName: 'r-Alt',
      value: 230,
      x: 477,
      y: -190,
      w: 32,
      h: 36,
    },
    {
      keyName: 'Fn',
      value: 0x0a010000,
      x: 525,
      y: -190,
      w: 32,
      h: 36,
    },
    {
      keyName: 'r-Ctrl',
      value: 228,
      x: 572,
      y: -190,
      w: 32,
      h: 36,
    },
    {
      keyName: '←',
      value: 80,
      x: 631,
      y: -202,
      w: 32,
      h: 36,
    },
    {
      keyName: '↓',
      value: 81,
      x: 679,
      y: -202,
      w: 32,
      h: 36,
    },
    {
      keyName: '→',
      value: 79,
      x: 727,
      y: -202,
      w: 32,
      h: 36,
    },
  ],
}
