export const yc500_nj81_ed = {
  deltX: 105,
  deltY: 14,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 30,
      h: 32,
     },
    {
      keyName: 'F1',
      value: 58,
      x: 77,
      y: 0,
      w: 30,
      h: 32,
    },
    {
      keyName: 'F2',
      value: 59,
      x: 118,
      y: 0,
      w: 30,
      h: 32,
    },
    {
      keyName: 'F3',
      value: 60,
      x: 160,
      y: 0,
      w: 30,
      h: 32,
    },
    {
      keyName: 'F4',
      value: 61,
      x: 201,
      y: 0,
      w: 30,
      h: 32,
    },
    {
      keyName: 'F5',
      value: 62,
      x: 259,
      y: 0,
      w: 30,
      h: 32,
    },
    {
      keyName: 'F6',
      value: 63,
      x: 300,
      y: 0,
      w: 30,
      h: 32,
    },
    {
      keyName: 'F7',
      value: 64,
      x: 342,
      y: 0,
      w: 30,
      h: 32,
    },
    {
      keyName: 'F8',
      value: 65,
      x: 383,
      y: 0,
      w: 30,
      h: 32,
    },
    {
      keyName: 'F9',
      value: 66,
      x: 440,
      y: 0,
      w: 30,
      h: 32,
    },
    {
      keyName: 'F10',
      value: 67,
      x: 481,
      y: 0,
      w: 30,
      h: 32,
    },
    {
      keyName: 'F11',
      value: 68,
      x: 523,
      y: 0,
      w: 30,
      h: 32,
    },
    {
      keyName: 'F12',
      value: 69,
      x: 564,
      y: 0,
      w: 30,
      h: 32,
    },
    {
      keyName: '`',
      value: 53,
      x: 0,
      y: -56,
      w: 30,
      h: 32,
    },
    {
      keyName: '1',
      value: 30,
      x: 42,
      y: -56,
      w: 30,
      h: 32,
    },
    {
      keyName: '2',
      value: 31,
      x: 82,
      y: -56,
      w: 30,
      h: 32,
    },
    {
      keyName: '3',
      value: 32,
      x: 125,
      y: -56,
      w: 30,
      h: 32,
    },
    {
      keyName: '4',
      value: 33,
      x: 167,
      y: -56,
      w: 30,
      h: 32,
    },
    {
      keyName: '5',
      value: 34,
      x: 209,
      y: -56,
      w: 30,
      h: 32,
    },
    {
      keyName: '6',
      value: 35,
      x: 251,
      y: -56,
      w: 30,
      h: 32,
    },
    {
      keyName: '7',
      value: 36,
      x: 293,
      y: -56,
      w: 30,
      h: 32,
    },
    {
      keyName: '8',
      value: 37,
      x: 333,
      y: -56,
      w: 30,
      h: 32,
    },
    {
      keyName: '9',
      value: 38,
      x: 376,
      y: -56,
      w: 30,
      h: 32,
    },
    {
      keyName: '0',
      value: 39,
      x: 418,
      y: -56,
      w: 30,
      h: 32,
    },
    {
      keyName: '-',
      value: 45,
      x: 460,
      y: -56,
      w: 30,
      h: 32,
    },
    {
      keyName: '=',
      value: 46,
      x: 502,
      y: -56,
      w: 30,
      h: 32,
    },
    {
      keyName: 'BackSpace',
      value: 42,
      x: 544,
      y: -56,
      w: 72,
      h: 32,
    },
    {
      keyName: 'Delete',
      value: 76,
      x: 628,
      y: -56,
      w: 30,
      h: 32,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -98,
      w: 50,
      h: 32,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 63,
      y: -98,
      w: 30,
      h: 32,
    },
    {
      keyName: 'W',
      value: 26,
      x: 103,
      y: -98,
      w: 30,
      h: 32,
    },
    {
      keyName: 'E',
      value: 8,
      x: 146,
      y: -98,
      w: 30,
      h: 32,
    },
    {
      keyName: 'R',
      value: 21,
      x: 188,
      y: -98,
      w: 30,
      h: 32,
    },
    {
      keyName: 'T',
      value: 23,
      x: 230,
      y: -98,
      w: 30,
      h: 32,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 272,
      y: -98,
      w: 30,
      h: 32,
    },
    {
      keyName: 'U',
      value: 24,
      x: 314,
      y: -98,
      w: 30,
      h: 32,
    },
    {
      keyName: 'I',
      value: 12,
      x: 354,
      y: -98,
      w: 30,
      h: 32,
    },
    {
      keyName: 'O',
      value: 18,
      x: 397,
      y: -98,
      w: 30,
      h: 32,
    },
    {
      keyName: 'P',
      value: 19,
      x: 439,
      y: -98,
      w: 30,
      h: 32,
    },
    {
      keyName: '[',
      value: 47,
      x: 481,
      y: -98,
      w: 30,
      h: 32,
    },
    {
      keyName: ']',
      value: 48,
      x: 523,
      y: -98,
      w: 30,
      h: 32,
    },
    {
      keyName: '\\',
      value: 49,
      x: 565,
      y: -98,
      w: 51,
      h: 32,
    },
    {
      keyName: 'Page\nUp',
      value: 75,
      x: 628,
      y: -98,
      w: 30,
      h: 32,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -139,
      w: 61,
      h: 32,
    },
    {
      keyName: 'A',
      value: 4,
      x: 73,
      y: -139,
      w: 30,
      h: 32,
    },
    {
      keyName: 'S',
      value: 22,
      x: 113,
      y: -139,
      w: 30,
      h: 32,
    },
    {
      keyName: 'D',
      value: 7,
      x: 156,
      y: -139,
      w: 30,
      h: 32,
    },
    {
      keyName: 'F',
      value: 9,
      x: 198,
      y: -139,
      w: 30,
      h: 32,
    },
    {
      keyName: 'G',
      value: 10,
      x: 240,
      y: -139,
      w: 30,
      h: 32,
    },
    {
      keyName: 'H',
      value: 11,
      x: 282,
      y: -139,
      w: 30,
      h: 32,
    },
    {
      keyName: 'J',
      value: 13,
      x: 324,
      y: -139,
      w: 30,
      h: 32,
    },
    {
      keyName: 'K',
      value: 14,
      x: 364,
      y: -139,
      w: 30,
      h: 32,
    },
    {
      keyName: 'L',
      value: 15,
      x: 407,
      y: -139,
      w: 30,
      h: 32,
    },
    {
      keyName: ';',
      value: 51,
      x: 449,
      y: -139,
      w: 30,
      h: 32,
    },
    {
      keyName: '\'',
      value: 52,
      x: 491,
      y: -139,
      w: 30,
      h: 32,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 533,
      y: -139,
      w: 83,
      h: 32,
    },
    {
      keyName: 'Page\nDown',
      value: 78,
      x: 628,
      y: -139,
      w: 30,
      h: 32,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -181,
      w: 82,
      h: 32,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 94,
      y: -181,
      w: 30,
      h: 32,
    },
    {
      keyName: 'X',
      value: 27,
      x: 134,
      y: -181,
      w: 30,
      h: 32,
    },
    {
      keyName: 'C',
      value: 6,
      x: 177,
      y: -181,
      w: 30,
      h: 32,
    },
    {
      keyName: 'V',
      value: 25,
      x: 219,
      y: -181,
      w: 30,
      h: 32,
    },
    {
      keyName: 'B',
      value: 5,
      x: 261,
      y: -181,
      w: 30,
      h: 32,
    },
    {
      keyName: 'N',
      value: 17,
      x: 303,
      y: -181,
      w: 30,
      h: 32,
    },
    {
      keyName: 'M',
      value: 16,
      x: 345,
      y: -181,
      w: 30,
      h: 32,
    },
    {
      keyName: ',',
      value: 54,
      x: 385,
      y: -181,
      w: 30,
      h: 32,
    },
    {
      keyName: '.',
      value: 55,
      x: 428,
      y: -181,
      w: 30,
      h: 32,
    },
    {
      keyName: '/',
      value: 56,
      x: 470,
      y: -181,
      w: 30,
      h: 32,
    },
    {
      keyName: 'r_Shift',
      value: 229,
      x: 512,
      y: -181,
      w: 63,
      h: 32,
    },
    {
      keyName: '↑',
      value: 82,
      x: 586,
      y: -181,
      w: 30,
      h: 32,
    },
    {
      keyName: 'End',
      value: 77,
      x: 628,
      y: -181,
      w: 30,
      h: 32,
    },
    {
      keyName: 'Ctrl',
      value: 224,
      x: 0,
      y: -221,
      w: 41,
      h: 32,
    },
    {
      keyName: 'Win',
      value: 227,
      x: 51,
      y: -221,
      w: 41,
      h: 32,
    },
    {
      keyName: 'Alt',
      value: 226,
      x: 104,
      y: -221,
      w: 41,
      h: 32,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 157,
      y: -221,
      w: 250,
      h: 32,
    },
    {
      keyName: 'FN',
      value: 0x0a010000,
      x: 417,
      y: -221,
      w: 41,
      h: 32,
    },
    {
      keyName: 'r_Ctrl',
      value: 228,
      x: 470,
      y: -221,
      w: 41,
      h: 32,
    },
    {
      keyName: '←',
      value: 80,
      x: 543,
      y: -221,
      w: 30,
      h: 32,
    },
    {
      keyName: '↓',
      value: 81,
      x: 586,
      y: -221,
      w: 30,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
      h: 32,
    },
    {
      keyName: '→',
      value: 79,
      x: 628,
      y: -221,
      w: 30,
      h: 32,
    },
  ],
}
