
export const yc500_hanan081 = {
  deltX: 108,
  deltY: 19,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 31,
      h: 31,
     },
    {
      keyName: 'F1',
      value: 58,
      x: 51,
      y: 0,
      w: 31,
      h: 31,
    },
    {
      keyName: 'F2',
      value: 59,
      x: 91,
      y: 0,
      w: 31,
      h: 31,
    },
    {
      keyName: 'F3',
      value: 60,
      x: 131,
      y: 0,
      w: 31,
      h: 31,
    },
    {
      keyName: 'F4',
      value: 61,
      x: 172,
      y: 0,
      w: 31,
      h: 31,
    },
    {
      keyName: 'F5',
      value: 62,
      x: 222,
      y: 0,
      w: 31,
      h: 31,
    },
    {
      keyName: 'F6',
      value: 63,
      x: 263,
      y: 0,
      w: 31,
      h: 31,
    },
    {
      keyName: 'F7',
      value: 64,
      x: 303,
      y: 0,
      w: 31,
      h: 31,
    },
    {
      keyName: 'F8',
      value: 65,
      x: 344,
      y: 0,
      w: 31,
      h: 31,
    },
    {
      keyName: 'F9',
      value: 66,
      x: 394,
      y: 0,
      w: 31,
      h: 31,
    },
    {
      keyName: 'F10',
      value: 67,
      x: 435,
      y: 0,
      w: 31,
      h: 31,
    },
    {
      keyName: 'F11',
      value: 68,
      x: 475,
      y: 0,
      w: 31,
      h: 31,
    },
    {
      keyName: 'F12',
      value: 69,
      x: 516,
      y: 0,
      w: 31,
      h: 31,
    },
    {
      keyName: 'Home',
      value: 74,
      x: 567,
      y: 0,
      w: 31,
      h: 31,
    },
    {
      keyName: 'U-',
      value: 0x0300ea00,
      knob: true,
      x: 618,
      y: 2,
      w: 13,
      h: 41,
    },
    {
      keyName: 'play',
      value: 0x0300e200,
      knob: true,
      x: 635,
      y: 2,
      w: 13,
      h: 41,
    },
    {
      keyName: 'U+',
      value: 0x0300e900,
      knob: true,
      x: 652,
      y: 2,
      w: 13,
      h: 41,
    },
    {
      keyName: '`',
      value: 53,
      x: 0,
      y: -50,
      w: 31,
      h: 31,
    },
    {
      keyName: '1',
      value: 30,
      x: 41,
      y: -50,
      w: 31,
      h: 31,
    },
    {
      keyName: '2',
      value: 31,
      x: 81,
      y: -50,
      w: 31,
      h: 31,
    },
    {
      keyName: '3',
      value: 32,
      x: 121,
      y: -50,
      w: 31,
      h: 31,
    },
    {
      keyName: '4',
      value: 33,
      x: 162,
      y: -50,
      w: 31,
      h: 31,
    },
    {
      keyName: '5',
      value: 34,
      x: 202,
      y: -50,
      w: 31,
      h: 31,
    },
    {
      keyName: '6',
      value: 35,
      x: 243,
      y: -50,
      w: 31,
      h: 31,
    },
    {
      keyName: '7',
      value: 36,
      x: 283,
      y: -50,
      w: 31,
      h: 31,
    },
    {
      keyName: '8',
      value: 37,
      x: 323,
      y: -50,
      w: 31,
      h: 31,
    },
    {
      keyName: '9',
      value: 38,
      x: 364,
      y: -50,
      w: 31,
      h: 31,
    },
    {
      keyName: '0',
      value: 39,
      x: 405,
      y: -50,
      w: 31,
      h: 31,
    },
    {
      keyName: '-',
      value: 45,
      x: 445,
      y: -50,
      w: 31,
      h: 31,
    },
    {
      keyName: '=',
      value: 46,
      x: 486,
      y: -50,
      w: 31,
      h: 31,
    },
    {
      keyName: 'BackSpace',
      value: 42,
      x: 527,
      y: -50,
      w: 71,
      h: 31,
    },
    {
      keyName: 'Delete',
      value: 76,
      x: 625,
      y: -50,
      w: 31,
      h: 31,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -91,
      w: 49,
      h: 31,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 61,
      y: -91,
      w: 31,
      h: 31,
    },
    {
      keyName: 'W',
      value: 26,
      x: 101,
      y: -91,
      w: 31,
      h: 31,
    },
    {
      keyName: 'E',
      value: 8,
      x: 141,
      y: -91,
      w: 31,
      h: 31,
    },
    {
      keyName: 'R',
      value: 21,
      x: 182,
      y: -91,
      w: 31,
      h: 31,
    },
    {
      keyName: 'T',
      value: 23,
      x: 222,
      y: -91,
      w: 31,
      h: 31,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 263,
      y: -91,
      w: 31,
      h: 31,
    },
    {
      keyName: 'U',
      value: 24,
      x: 303,
      y: -91,
      w: 31,
      h: 31,
    },
    {
      keyName: 'I',
      value: 12,
      x: 343,
      y: -91,
      w: 31,
      h: 31,
    },
    {
      keyName: 'O',
      value: 18,
      x: 384,
      y: -91,
      w: 31,
      h: 31,
    },
    {
      keyName: 'P',
      value: 19,
      x: 425,
      y: -91,
      w: 31,
      h: 31,
    },
    {
      keyName: '[',
      value: 47,
      x: 465,
      y: -91,
      w: 31,
      h: 31,
    },
    {
      keyName: ']',
      value: 48,
      x: 506,
      y: -91,
      w: 31,
      h: 31,
    },
    {
      keyName: '\\',
      value: 49,
      x: 546,
      y: -91,
      w: 52,
      h: 31,
    },
    {
      keyName: 'Page\nUp',
      value: 75,
      x: 625,
      y: -91,
      w: 31,
      h: 31,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -132,
      w: 59,
      h: 31,
    },
    {
      keyName: 'A',
      value: 4,
      x: 71,
      y: -132,
      w: 31,
      h: 31,
    },
    {
      keyName: 'S',
      value: 22,
      x: 111,
      y: -132,
      w: 31,
      h: 31,
    },
    {
      keyName: 'D',
      value: 7,
      x: 151,
      y: -132,
      w: 31,
      h: 31,
    },
    {
      keyName: 'F',
      value: 9,
      x: 192,
      y: -132,
      w: 31,
      h: 31,
    },
    {
      keyName: 'G',
      value: 10,
      x: 232,
      y: -132,
      w: 31,
      h: 31,
    },
    {
      keyName: 'H',
      value: 11,
      x: 273,
      y: -132,
      w: 31,
      h: 31,
    },
    {
      keyName: 'J',
      value: 13,
      x: 313,
      y: -132,
      w: 31,
      h: 31,
    },
    {
      keyName: 'K',
      value: 14,
      x: 353,
      y: -132,
      w: 31,
      h: 31,
    },
    {
      keyName: 'L',
      value: 15,
      x: 394,
      y: -132,
      w: 31,
      h: 31,
    },
    {
      keyName: ';',
      value: 51,
      x: 435,
      y: -132,
      w: 31,
      h: 31,
    },
    {
      keyName: '\'',
      value: 52,
      x: 475,
      y: -132,
      w: 31,
      h: 31,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 516,
      y: -132,
      w: 82,
      h: 31,
    },
    {
      keyName: 'Page\nDown',
      value: 78,
      x: 625,
      y: -132,
      w: 31,
      h: 31,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -172,
      w: 80,
      h: 31,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 92,
      y: -172,
      w: 31,
      h: 31,
    },
    {
      keyName: 'X',
      value: 27,
      x: 132,
      y: -172,
      w: 31,
      h: 31,
    },
    {
      keyName: 'C',
      value: 6,
      x: 172,
      y: -172,
      w: 31,
      h: 31,
    },
    {
      keyName: 'V',
      value: 25,
      x: 213,
      y: -172,
      w: 31,
      h: 31,
    },
    {
      keyName: 'B',
      value: 5,
      x: 253,
      y: -172,
      w: 31,
      h: 31,
    },
    {
      keyName: 'N',
      value: 17,
      x: 294,
      y: -172,
      w: 31,
      h: 31,
    },
    {
      keyName: 'M',
      value: 16,
      x: 334,
      y: -172,
      w: 31,
      h: 31,
    },
    {
      keyName: ',',
      value: 54,
      x: 374,
      y: -172,
      w: 31,
      h: 31,
    },
    {
      keyName: '.',
      value: 55,
      x: 415,
      y: -172,
      w: 31,
      h: 31,
    },
    {
      keyName: '/',
      value: 56,
      x: 456,
      y: -172,
      w: 31,
      h: 31,
    },
    {
      keyName: 'r_Shift',
      value: 229,
      x: 496,
      y: -172,
      w: 61,
      h: 31,
    },
    {
      keyName: 'Ctrl',
      value: 224,
      x: 0,
      y: -212,
      w: 40,
      h: 31,
    },
    {
      keyName: 'Win',
      value: 227,
      x: 49,
      y: -212,
      w: 40,
      h: 31,
    },
    {
      keyName: 'Alt',
      value: 226,
      x: 99,
      y: -212,
      w: 40,
      h: 31,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 150,
      y: -212,
      w: 241,
      h: 31,
    },
    {
      keyName: 'r_Alt',
      value: 230,
      x: 401,
      y: -212,
      w: 31,
      h: 31,
    },
    {
      keyName: 'FN',
      value: 0x0a010000,
      x: 442,
      y: -212,
      w: 31,
      h: 31,
    },
    {
      keyName: 'r_Ctrl',
      value: 228,
      x: 482,
      y: -212,
      w: 31,
      h: 31,
    },
    {
      keyName: '↑',
      value: 82,
      x: 576,
      y: -180,
      w: 31,
      h: 31,
    },
    {
      keyName: '←',
      value: 80,
      x: 536,
      y: -221,
      w: 31,
      h: 31,
    },
    {
      keyName: '↓',
      value: 81,
      x: 576,
      y: -221,
      w: 31,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
      h: 31,
    },
    {
      keyName: '→',
      value: 79,
      x: 617,
      y: -221,
      w: 31,
      h: 31,
    },
  ],
}
