export const yc500_vgn211_soc = {
  deltX: 357,
  deltY: 17,
  layout: [
    {
      keyName: 'U-',
      value: 0x0300ea00,
      knob: true,
      x: 0,
      y: 0,
      w: 10,
      h: 35,
    },
    {
      keyName: 'Mute',
      value: 0x0300e200,
      knob: true,
      x: 13,
      y: 0,
      w: 10,
      h: 35,
    },
    {
      keyName: 'U+',
      value: 0x0300e900,
      knob: true,
      x: 26,
      y: -1,
      w: 10,
      h: 35,
    },
    {
      keyName: 'Esc',
      value: 41,
      x: 46,
      y: -1,
      w: 27,
      h: 29,
    },
    {
      keyName: 'FN',
      value: 0x0a010000,
      x: 86,
      y: -1,
      w: 27,
      h: 29,
    },
    {
      keyName: 'BackSpace',
      value: 42,
      x: 126,
      y: 0,
      w: 27,
      h: 29,
    },
    {
      keyName: 'Num\nLock',
      value: 83,
      x: 5,
      y: -58,
      w: 27,
      h: 29,
    },
    {
      keyName: 'num_/',
      value: 84,
      x: 46,
      y: -58,
      w: 27,
      h: 29,
    },
    {
      keyName: 'num_*',
      value: 85,
      x: 86,
      y: -58,
      w: 27,
      h: 29,
    },
    {
      keyName: 'num_-',
      value: 86,
      x: 126,
      y: -58,
      w: 27,
      h: 29,
    },
    {
      keyName: 'num_7',
      value: 95,
      x: 5,
      y: -98,
      w: 27,
      h: 29,
    },
    {
      keyName: 'num_8',
      value: 96,
      x: 46,
      y: -98,
      w: 27,
      h: 29,
    },
    {
      keyName: 'num_9',
      value: 97,
      x: 86,
      y: -98,
      w: 27,
      h: 29,
    },
    {
      keyName: 'num_+',
      value: 87,
      x: 123,
      y: -99,
      w: 27,
      h: 68,
    },
    {
      keyName: 'num_4',
      value: 92,
      x: 5,
      y: -137,
      w: 27,
      h: 29,
    },
    {
      keyName: 'num_5',
      value: 93,
      x: 46,
      y: -137,
      w: 27,
      h: 29,
    },
    {
      keyName: 'num_6',
      value: 94,
      x: 86,
      y: -137,
      w: 27,
      h: 29,
    },
    {
      keyName: 'num_1',
      value: 89,
      x: 5,
      y: -177,
      w: 27,
      h: 29,
    },
    {
      keyName: 'num_2',
      value: 90,
      x: 46,
      y: -177,
      w: 27,
      h: 29,
    },
    {
      keyName: 'num_3',
      value: 91,
      x: 86,
      y: -177,
      w: 27,
      h: 29,
    },
    {
      keyName: 'num_Enter',
      value: 88,
      x: 123,
      y: -179,
      w: 27,
      h: 68,
    },
    {
      keyName: 'num_0',
      value: 98,
      x: 5,
      y: -216,
      w: 68,
      h: 29,
    },
    {
      keyName: 'num_.',
      value: 99,
      x: 86,
      y: -216,
      w: 27,
      h: 29,
    },
  ],
}
