export const yc500_gk75 = {
  deltX: 73,
  deltY: 1,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 42,
      h: 42,
     },
    {
      keyName: 'F1',
      value: 58,
      x: 106,
      y: 0,
      w: 42,
      h: 42,
    },
    {
      keyName: 'F2',
      value: 59,
      x: 151,
      y: 0,
      w: 42,
      h: 42,
    },
    {
      keyName: 'F3',
      value: 60,
      x: 196,
      y: 0,
      w: 42,
      h: 42,
    },
    {
      keyName: 'F4',
      value: 61,
      x: 241,
      y: 0,
      w: 42,
      h: 42,
    },
    {
      keyName: 'F5',
      value: 62,
      x: 298,
      y: 0,
      w: 42,
      h: 42,
    },
    {
      keyName: 'F6',
      value: 63,
      x: 343,
      y: 0,
      w: 42,
      h: 42,
    },
    {
      keyName: 'F7',
      value: 64,
      x: 388,
      y: 0,
      w: 42,
      h: 42,
    },
    {
      keyName: 'F8',
      value: 65,
      x: 433,
      y: 0,
      w: 42,
      h: 42,
    },
    {
      keyName: 'F9',
      value: 66,
      x: 491,
      y: 0,
      w: 42,
      h: 42,
    },
    {
      keyName: 'F10',
      value: 67,
      x: 536,
      y: 0,
      w: 42,
      h: 42,
    },
    {
      keyName: 'F11',
      value: 68,
      x: 581,
      y: 0,
      w: 42,
      h: 42,
    },
    {
      keyName: 'F12',
      value: 69,
      x: 625,
      y: 0,
      w: 42,
      h: 42,
    },
    {
      keyName: 'Delete',
      value: 76,
      x: 683,
      y: 0,
      w: 42,
      h: 42,
    },
    {
      keyName: '`',
      value: 53,
      x: 0,
      y: -59,
      w: 42,
      h: 42,
    },
    {
      keyName: '1',
      value: 30,
      x: 45,
      y: -59,
      w: 42,
      h: 42,
    },
    {
      keyName: '2',
      value: 31,
      x: 90,
      y: -59,
      w: 42,
      h: 42,
    },
    {
      keyName: '3',
      value: 32,
      x: 134,
      y: -59,
      w: 42,
      h: 42,
    },
    {
      keyName: '4',
      value: 33,
      x: 179,
      y: -59,
      w: 42,
      h: 42,
    },
    {
      keyName: '5',
      value: 34,
      x: 224,
      y: -59,
      w: 42,
      h: 42,
    },
    {
      keyName: '6',
      value: 35,
      x: 269,
      y: -59,
      w: 42,
      h: 42,
    },
    {
      keyName: '7',
      value: 36,
      x: 313,
      y: -59,
      w: 42,
      h: 42,
    },
    {
      keyName: '8',
      value: 37,
      x: 358,
      y: -59,
      w: 42,
      h: 42,
    },
    {
      keyName: '9',
      value: 38,
      x: 402,
      y: -59,
      w: 42,
      h: 42,
    },
    {
      keyName: '0',
      value: 39,
      x: 447,
      y: -59,
      w: 42,
      h: 42,
    },
    {
      keyName: '-',
      value: 45,
      x: 491,
      y: -59,
      w: 42,
      h: 42,
    },
    {
      keyName: '=',
      value: 46,
      x: 536,
      y: -59,
      w: 42,
      h: 42,
    },
    {
      keyName: 'BackSpace',
      value: 42,
      x: 581,
      y: -59,
      w: 87,
      h: 42,
    },
    {
      keyName: 'Page\nUp',
      value: 75,
      x: 683,
      y: -59,
      w: 42,
      h: 42,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -104,
      w: 66,
      h: 42,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 67,
      y: -104,
      w: 42,
      h: 42,
    },
    {
      keyName: 'W',
      value: 26,
      x: 112,
      y: -104,
      w: 42,
      h: 42,
    },
    {
      keyName: 'E',
      value: 8,
      x: 156,
      y: -104,
      w: 42,
      h: 42,
    },
    {
      keyName: 'R',
      value: 21,
      x: 201,
      y: -104,
      w: 42,
      h: 42,
    },
    {
      keyName: 'T',
      value: 23,
      x: 246,
      y: -104,
      w: 42,
      h: 42,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 291,
      y: -104,
      w: 42,
      h: 42,
    },
    {
      keyName: 'U',
      value: 24,
      x: 335,
      y: -104,
      w: 42,
      h: 42,
    },
    {
      keyName: 'I',
      value: 12,
      x: 380,
      y: -104,
      w: 42,
      h: 42,
    },
    {
      keyName: 'O',
      value: 18,
      x: 424,
      y: -104,
      w: 42,
      h: 42,
    },
    {
      keyName: 'P',
      value: 19,
      x: 469,
      y: -104,
      w: 42,
      h: 42,
    },
    {
      keyName: '[',
      value: 47,
      x: 514,
      y: -104,
      w: 42,
      h: 42,
    },
    {
      keyName: ']',
      value: 48,
      x: 558,
      y: -104,
      w: 42,
      h: 42,
    },
    {
      keyName: '\\',
      value: 49,
      x: 603,
      y: -104,
      w: 66,
      h: 42,
    },
    {
      keyName: 'Page\nDown',
      value: 78,
      x: 683,
      y: -104,
      w: 42,
      h: 42,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -149,
      w: 77,
      h: 42,
    },
    {
      keyName: 'A',
      value: 4,
      x: 78,
      y: -149,
      w: 42,
      h: 42,
    },
    {
      keyName: 'S',
      value: 22,
      x: 123,
      y: -149,
      w: 42,
      h: 42,
    },
    {
      keyName: 'D',
      value: 7,
      x: 167,
      y: -149,
      w: 42,
      h: 42,
    },
    {
      keyName: 'F',
      value: 9,
      x: 212,
      y: -149,
      w: 42,
      h: 42,
    },
    {
      keyName: 'G',
      value: 10,
      x: 257,
      y: -149,
      w: 42,
      h: 42,
    },
    {
      keyName: 'H',
      value: 11,
      x: 302,
      y: -149,
      w: 42,
      h: 42,
    },
    {
      keyName: 'J',
      value: 13,
      x: 346,
      y: -149,
      w: 42,
      h: 42,
    },
    {
      keyName: 'K',
      value: 14,
      x: 391,
      y: -149,
      w: 42,
      h: 42,
    },
    {
      keyName: 'L',
      value: 15,
      x: 435,
      y: -149,
      w: 42,
      h: 42,
    },
    {
      keyName: ';',
      value: 51,
      x: 480,
      y: -149,
      w: 42,
      h: 42,
    },
    {
      keyName: '\'',
      value: 52,
      x: 524,
      y: -149,
      w: 42,
      h: 42,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 569,
      y: -149,
      w: 100,
      h: 42,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -193,
      w: 99,
      h: 42,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 101,
      y: -193,
      w: 42,
      h: 42,
    },
    {
      keyName: 'X',
      value: 27,
      x: 146,
      y: -193,
      w: 42,
      h: 42,
    },
    {
      keyName: 'C',
      value: 6,
      x: 190,
      y: -193,
      w: 42,
      h: 42,
    },
    {
      keyName: 'V',
      value: 25,
      x: 235,
      y: -193,
      w: 42,
      h: 42,
    },
    {
      keyName: 'B',
      value: 5,
      x: 280,
      y: -193,
      w: 42,
      h: 42,
    },
    {
      keyName: 'N',
      value: 17,
      x: 325,
      y: -193,
      w: 42,
      h: 42,
    },
    {
      keyName: 'M',
      value: 16,
      x: 369,
      y: -193,
      w: 42,
      h: 42,
    },
    {
      keyName: ',',
      value: 54,
      x: 414,
      y: -193,
      w: 42,
      h: 42,
    },
    {
      keyName: '.',
      value: 55,
      x: 458,
      y: -193,
      w: 42,
      h: 42,
    },
    {
      keyName: '/',
      value: 56,
      x: 503,
      y: -193,
      w: 42,
      h: 42,
    },
    {
      keyName: 'r_Shift',
      value: 229,
      x: 547,
      y: -193,
      w: 76,
      h: 42,
    },
    {
      keyName: 'Ctrl',
      value: 224,
      x: 0,
      y: -238,
      w: 54,
      h: 42,
    },
    {
      keyName: 'Win',
      value: 227,
      x: 56,
      y: -238,
      w: 54,
      h: 42,
    },
    {
      keyName: 'Alt',
      value: 226,
      x: 112,
      y: -238,
      w: 54,
      h: 42,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 168,
      y: -238,
      w: 278,
      h: 42,
    },
    {
      keyName: 'r_Alt',
      value: 230,
      x: 447,
      y: -238,
      w: 42,
      h: 42,
    },
    {
      keyName: 'FN',
      value: 0x0a010000,
      x: 491,
      y: -238,
      w: 42,
      h: 42,
    },
    {
      keyName: 'r_Ctrl',
      value: 228,
      x: 536,
      y: -238,
      w: 42,
      h: 42,
    },
    {
      keyName: '↑',
      value: 82,
      x: 632,
      y: -200,
      w: 42,
      h: 42,
    },
    {
      keyName: '←',
      value: 80,
      x: 587,
      y: -245,
      w: 42,
      h: 42,
    },
    {
      keyName: '↓',
      value: 81,
      x: 631,
      y: -245,
      w: 42,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
      h: 42,
    },
    {
      keyName: '→',
      value: 79,
      x: 676,
      y: -245,
      w: 42,
      h: 42,
    },
  ],
}
