export const yc500_k22_soc = {
  deltX: 142,
  deltY: 41,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 25,
      h: 27,
     },
    {
      keyName: 'F1',
      value: 58,
      x: 45,
      y: 0,
      w: 25,
      h: 27,
    },
    {
      keyName: 'F2',
      value: 59,
      x: 81,
      y: 0,
      w: 25,
      h: 27,
    },
    {
      keyName: 'F3',
      value: 60,
      x: 118,
      y: 0,
      w: 25,
      h: 27,
    },
    {
      keyName: 'F4',
      value: 61,
      x: 154,
      y: 0,
      w: 25,
      h: 27,
    },
    {
      keyName: 'F5',
      value: 62,
      x: 199,
      y: 0,
      w: 25,
      h: 27,
    },
    {
      keyName: 'F6',
      value: 63,
      x: 236,
      y: 0,
      w: 25,
      h: 27,
    },
    {
      keyName: 'F7',
      value: 64,
      x: 272,
      y: 0,
      w: 25,
      h: 27,
    },
    {
      keyName: 'F8',
      value: 65,
      x: 308,
      y: 0,
      w: 25,
      h: 27,
    },
    {
      keyName: 'F9',
      value: 66,
      x: 354,
      y: 0,
      w: 25,
      h: 27,
    },
    {
      keyName: 'F10',
      value: 67,
      x: 391,
      y: 0,
      w: 25,
      h: 27,
    },
    {
      keyName: 'F11',
      value: 68,
      x: 427,
      y: 0,
      w: 25,
      h: 27,
    },
    {
      keyName: 'F12',
      value: 69,
      x: 463,
      y: 0,
      w: 25,
      h: 27,
    },
    {
      keyName: 'Delete',
      value: 76,
      x: 508,
      y: 0,
      w: 25,
      h: 27,
    },
    {
      keyName: 'Print\nScreen',
      value: 70,
      x: 562,
      y: 0,
      w: 25,
      h: 27,
    },
    {
      keyName: '`',
      value: 53,
      x: 0,
      y: -45,
      w: 25,
      h: 27,
    },
    {
      keyName: '1',
      value: 30,
      x: 36,
      y: -45,
      w: 25,
      h: 27,
    },
    {
      keyName: '2',
      value: 31,
      x: 72,
      y: -45,
      w: 25,
      h: 27,
    },
    {
      keyName: '3',
      value: 32,
      x: 109,
      y: -45,
      w: 25,
      h: 27,
    },
    {
      keyName: '4',
      value: 33,
      x: 145,
      y: -45,
      w: 25,
      h: 27,
    },
    {
      keyName: '5',
      value: 34,
      x: 181,
      y: -45,
      w: 25,
      h: 27,
    },
    {
      keyName: '6',
      value: 35,
      x: 218,
      y: -45,
      w: 25,
      h: 27,
    },
    {
      keyName: '7',
      value: 36,
      x: 254,
      y: -45,
      w: 25,
      h: 27,
    },
    {
      keyName: '8',
      value: 37,
      x: 290,
      y: -45,
      w: 25,
      h: 27,
    },
    {
      keyName: '9',
      value: 38,
      x: 327,
      y: -45,
      w: 25,
      h: 27,
    },
    {
      keyName: '0',
      value: 39,
      x: 363,
      y: -45,
      w: 25,
      h: 27,
    },
    {
      keyName: '-',
      value: 45,
      x: 399,
      y: -45,
      w: 25,
      h: 27,
    },
    {
      keyName: '=',
      value: 46,
      x: 436,
      y: -45,
      w: 25,
      h: 27,
    },
    {
      keyName: 'BackSpace',
      value: 42,
      x: 473,
      y: -45,
      w: 60,
      h: 27,
    },
    {
      keyName: 'Home',
      value: 74,
      x: 562,
      y: -45,
      w: 25,
      h: 27,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -80,
      w: 42,
      h: 27,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 54,
      y: -80,
      w: 25,
      h: 27,
    },
    {
      keyName: 'W',
      value: 26,
      x: 90,
      y: -80,
      w: 25,
      h: 27,
    },
    {
      keyName: 'E',
      value: 8,
      x: 127,
      y: -80,
      w: 25,
      h: 27,
    },
    {
      keyName: 'R',
      value: 21,
      x: 163,
      y: -80,
      w: 25,
      h: 27,
    },
    {
      keyName: 'T',
      value: 23,
      x: 199,
      y: -80,
      w: 25,
      h: 27,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 236,
      y: -80,
      w: 25,
      h: 27,
    },
    {
      keyName: 'U',
      value: 24,
      x: 272,
      y: -80,
      w: 25,
      h: 27,
    },
    {
      keyName: 'I',
      value: 12,
      x: 308,
      y: -80,
      w: 25,
      h: 27,
    },
    {
      keyName: 'O',
      value: 18,
      x: 345,
      y: -80,
      w: 25,
      h: 27,
    },
    {
      keyName: 'P',
      value: 19,
      x: 381,
      y: -80,
      w: 25,
      h: 27,
    },
    {
      keyName: '[',
      value: 47,
      x: 417,
      y: -80,
      w: 25,
      h: 27,
    },
    {
      keyName: ']',
      value: 48,
      x: 454,
      y: -80,
      w: 25,
      h: 27,
    },
    {
      keyName: '\\',
      value: 49,
      x: 491,
      y: -80,
      w: 42,
      h: 27,
    },
    {
      keyName: 'End',
      value: 77,
      x: 562,
      y: -80,
      w: 25,
      h: 27,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -116,
      w: 51,
      h: 27,
    },
    {
      keyName: 'A',
      value: 4,
      x: 64,
      y: -116,
      w: 25,
      h: 27,
    },
    {
      keyName: 'S',
      value: 22,
      x: 100,
      y: -116,
      w: 25,
      h: 27,
    },
    {
      keyName: 'D',
      value: 7,
      x: 137,
      y: -116,
      w: 25,
      h: 27,
    },
    {
      keyName: 'F',
      value: 9,
      x: 173,
      y: -116,
      w: 25,
      h: 27,
    },
    {
      keyName: 'G',
      value: 10,
      x: 209,
      y: -116,
      w: 25,
      h: 27,
    },
    {
      keyName: 'H',
      value: 11,
      x: 246,
      y: -116,
      w: 25,
      h: 27,
    },
    {
      keyName: 'J',
      value: 13,
      x: 282,
      y: -116,
      w: 25,
      h: 27,
    },
    {
      keyName: 'K',
      value: 14,
      x: 318,
      y: -116,
      w: 25,
      h: 27,
    },
    {
      keyName: 'L',
      value: 15,
      x: 355,
      y: -116,
      w: 25,
      h: 27,
    },
    {
      keyName: ';',
      value: 51,
      x: 391,
      y: -116,
      w: 25,
      h: 27,
    },
    {
      keyName: '\'',
      value: 52,
      x: 427,
      y: -116,
      w: 25,
      h: 27,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 464,
      y: -116,
      w: 69,
      h: 27,
    },
    {
      keyName: 'Page\nUp',
      value: 75,
      x: 562,
      y: -116,
      w: 25,
      h: 27,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -152,
      w: 70,
      h: 27,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 81,
      y: -152,
      w: 25,
      h: 27,
    },
    {
      keyName: 'X',
      value: 27,
      x: 117,
      y: -152,
      w: 25,
      h: 27,
    },
    {
      keyName: 'C',
      value: 6,
      x: 154,
      y: -152,
      w: 25,
      h: 27,
    },
    {
      keyName: 'V',
      value: 25,
      x: 190,
      y: -152,
      w: 25,
      h: 27,
    },
    {
      keyName: 'B',
      value: 5,
      x: 226,
      y: -152,
      w: 25,
      h: 27,
    },
    {
      keyName: 'N',
      value: 17,
      x: 263,
      y: -152,
      w: 25,
      h: 27,
    },
    {
      keyName: 'M',
      value: 16,
      x: 299,
      y: -152,
      w: 25,
      h: 27,
    },
    {
      keyName: ',',
      value: 54,
      x: 335,
      y: -152,
      w: 25,
      h: 27,
    },
    {
      keyName: '.',
      value: 55,
      x: 372,
      y: -152,
      w: 25,
      h: 27,
    },
    {
      keyName: '/',
      value: 56,
      x: 408,
      y: -152,
      w: 25,
      h: 27,
    },
    {
      keyName: 'r_Shift',
      value: 229,
      x: 444,
      y: -152,
      w: 52,
      h: 27,
    },
    {
      keyName: 'Page\nDown',
      value: 78,
      x: 562,
      y: -152,
      w: 25,
      h: 27,
    },
    {
      keyName: 'Ctrl',
      value: 224,
      x: 0,
      y: -189,
      w: 33,
      h: 27,
    },
    {
      keyName: 'Win',
      value: 227,
      x: 46,
      y: -189,
      w: 33,
      h: 27,
    },
    {
      keyName: 'Alt',
      value: 226,
      x: 91,
      y: -189,
      w: 33,
      h: 27,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 137,
      y: -189,
      w: 215,
      h: 27,
    },
    {
      keyName: 'r_Alt',
      value: 230,
      x: 363,
      y: -189,
      w: 25,
      h: 27,
    },
    {
      keyName: 'FN',
      value: 0x0a010000,
      x: 399,
      y: -189,
      w: 25,
      h: 27,
    },
    {
      keyName: 'r_Ctrl',
      value: 228,
      x: 436,
      y: -189,
      w: 25,
      h: 27,
    },
    {
      keyName: '↑',
      value: 82,
      x: 517,
      y: -161,
      w: 25,
      h: 27,
    },
    {
      keyName: '←',
      value: 80,
      x: 481,
      y: -198,
      w: 25,
      h: 27,
    },
    {
      keyName: '↓',
      value: 81,
      x: 517,
      y: -198,
      w: 25,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
      h: 27,
    },
    {
      keyName: '→',
      value: 79,
      x: 554,
      y: -198,
      w: 25,
      h: 27,
    },
  ],
}
