export const yc500_vgn811 = {
  deltX: 119,
  deltY: 26,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 26,
      h: 30,
     },
    {
      keyName: 'F1',
      value: 58,
      x: 48,
      y: 0,
      w: 26,
      h: 30,
    },
    {
      keyName: 'F2',
      value: 59,
      x: 86,
      y: 0,
      w: 26,
      h: 30,
    },
    {
      keyName: 'F3',
      value: 60,
      x: 126,
      y: 0,
      w: 26,
      h: 30,
    },
    {
      keyName: 'F4',
      value: 61,
      x: 165,
      y: 0,
      w: 26,
      h: 30,
    },
    {
      keyName: 'F5',
      value: 62,
      x: 216,
      y: 0,
      w: 26,
      h: 30,
    },
    {
      keyName: 'F6',
      value: 63,
      x: 254,
      y: 0,
      w: 26,
      h: 30,
    },
    {
      keyName: 'F7',
      value: 64,
      x: 294,
      y: 0,
      w: 26,
      h: 30,
    },
    {
      keyName: 'F8',
      value: 65,
      x: 333,
      y: 0,
      w: 26,
      h: 30,
    },
    {
      keyName: 'F9',
      value: 66,
      x: 384,
      y: 0,
      w: 26,
      h: 30,
    },
    {
      keyName: 'F10',
      value: 67,
      x: 422,
      y: 0,
      w: 26,
      h: 30,
    },
    {
      keyName: 'F11',
      value: 68,
      x: 462,
      y: 0,
      w: 26,
      h: 30,
    },
    {
      keyName: 'F12',
      value: 69,
      x: 501,
      y: 0,
      w: 26,
      h: 30,
    },
    {
      keyName: 'Delete',
      value: 76,
      x: 549,
      y: 0,
      w: 26,
      h: 30,
    },
    {
      keyName: '`',
      value: 53,
      x: 0,
      y: -49,
      w: 26,
      h: 30,
    },
    {
      keyName: '1',
      value: 30,
      x: 40,
      y: -49,
      w: 26,
      h: 30,
    },
    {
      keyName: '2',
      value: 31,
      x: 78,
      y: -49,
      w: 26,
      h: 30,
    },
    {
      keyName: '3',
      value: 32,
      x: 118,
      y: -49,
      w: 26,
      h: 30,
    },
    {
      keyName: '4',
      value: 33,
      x: 157,
      y: -49,
      w: 26,
      h: 30,
    },
    {
      keyName: '5',
      value: 34,
      x: 197,
      y: -49,
      w: 26,
      h: 30,
    },
    {
      keyName: '6',
      value: 35,
      x: 235,
      y: -49,
      w: 26,
      h: 30,
    },
    {
      keyName: '7',
      value: 36,
      x: 275,
      y: -49,
      w: 26,
      h: 30,
    },
    {
      keyName: '8',
      value: 37,
      x: 314,
      y: -49,
      w: 26,
      h: 30,
    },
    {
      keyName: '9',
      value: 38,
      x: 354,
      y: -49,
      w: 26,
      h: 30,
    },
    {
      keyName: '0',
      value: 39,
      x: 392,
      y: -49,
      w: 26,
      h: 30,
    },
    {
      keyName: '-',
      value: 45,
      x: 432,
      y: -49,
      w: 26,
      h: 30,
    },
    {
      keyName: '=',
      value: 46,
      x: 471,
      y: -49,
      w: 26,
      h: 30,
    },
    {
      keyName: 'BackSpace',
      value: 42,
      x: 510,
      y: -49,
      w: 65,
      h: 30,
    },
    {
      keyName: 'Insert',
      value: 73,
      x: 608,
      y: -49,
      w: 26,
      h: 30,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -88,
      w: 46,
      h: 30,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 59,
      y: -88,
      w: 26,
      h: 30,
    },
    {
      keyName: 'W',
      value: 26,
      x: 97,
      y: -88,
      w: 26,
      h: 30,
    },
    {
      keyName: 'E',
      value: 8,
      x: 137,
      y: -88,
      w: 26,
      h: 30,
    },
    {
      keyName: 'R',
      value: 21,
      x: 176,
      y: -88,
      w: 26,
      h: 30,
    },
    {
      keyName: 'T',
      value: 23,
      x: 216,
      y: -88,
      w: 26,
      h: 30,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 254,
      y: -88,
      w: 26,
      h: 30,
    },
    {
      keyName: 'U',
      value: 24,
      x: 294,
      y: -88,
      w: 26,
      h: 30,
    },
    {
      keyName: 'I',
      value: 12,
      x: 333,
      y: -88,
      w: 26,
      h: 30,
    },
    {
      keyName: 'O',
      value: 18,
      x: 373,
      y: -88,
      w: 26,
      h: 30,
    },
    {
      keyName: 'P',
      value: 19,
      x: 411,
      y: -88,
      w: 26,
      h: 30,
    },
    {
      keyName: '[',
      value: 47,
      x: 451,
      y: -88,
      w: 26,
      h: 30,
    },
    {
      keyName: ']',
      value: 48,
      x: 490,
      y: -88,
      w: 26,
      h: 30,
    },
    {
      keyName: '\\',
      value: 49,
      x: 529,
      y: -88,
      w: 46,
      h: 30,
    },
    {
      keyName: 'End',
      value: 77,
      x: 608,
      y: -88,
      w: 26,
      h: 30,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -127,
      w: 56,
      h: 30,
    },
    {
      keyName: 'A',
      value: 4,
      x: 69,
      y: -127,
      w: 26,
      h: 30,
    },
    {
      keyName: 'S',
      value: 22,
      x: 107,
      y: -127,
      w: 26,
      h: 30,
    },
    {
      keyName: 'D',
      value: 7,
      x: 147,
      y: -127,
      w: 26,
      h: 30,
    },
    {
      keyName: 'F',
      value: 9,
      x: 186,
      y: -127,
      w: 26,
      h: 30,
    },
    {
      keyName: 'G',
      value: 10,
      x: 226,
      y: -127,
      w: 26,
      h: 30,
    },
    {
      keyName: 'H',
      value: 11,
      x: 264,
      y: -127,
      w: 26,
      h: 30,
    },
    {
      keyName: 'J',
      value: 13,
      x: 304,
      y: -127,
      w: 26,
      h: 30,
    },
    {
      keyName: 'K',
      value: 14,
      x: 343,
      y: -127,
      w: 26,
      h: 30,
    },
    {
      keyName: 'L',
      value: 15,
      x: 383,
      y: -127,
      w: 26,
      h: 30,
    },
    {
      keyName: ';',
      value: 51,
      x: 421,
      y: -127,
      w: 26,
      h: 30,
    },
    {
      keyName: '\'',
      value: 52,
      x: 461,
      y: -127,
      w: 26,
      h: 30,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 500,
      y: -127,
      w: 75,
      h: 30,
    },
    {
      keyName: 'Page\nUp',
      value: 75,
      x: 608,
      y: -127,
      w: 26,
      h: 30,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -166,
      w: 74,
      h: 30,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 88,
      y: -166,
      w: 26,
      h: 30,
    },
    {
      keyName: 'X',
      value: 27,
      x: 126,
      y: -166,
      w: 26,
      h: 30,
    },
    {
      keyName: 'C',
      value: 6,
      x: 166,
      y: -166,
      w: 26,
      h: 30,
    },
    {
      keyName: 'V',
      value: 25,
      x: 205,
      y: -166,
      w: 26,
      h: 30,
    },
    {
      keyName: 'B',
      value: 5,
      x: 245,
      y: -166,
      w: 26,
      h: 30,
    },
    {
      keyName: 'N',
      value: 17,
      x: 283,
      y: -166,
      w: 26,
      h: 30,
    },
    {
      keyName: 'M',
      value: 16,
      x: 323,
      y: -166,
      w: 26,
      h: 30,
    },
    {
      keyName: ',',
      value: 54,
      x: 362,
      y: -166,
      w: 26,
      h: 30,
    },
    {
      keyName: '.',
      value: 55,
      x: 402,
      y: -166,
      w: 26,
      h: 30,
    },
    {
      keyName: '/',
      value: 56,
      x: 440,
      y: -166,
      w: 26,
      h: 30,
    },
    {
      keyName: 'r_Shift',
      value: 229,
      x: 480,
      y: -166,
      w: 58,
      h: 30,
    },
    {
      keyName: 'Page\nDown',
      value: 78,
      x: 608,
      y: -166,
      w: 26,
      h: 30,
    },
    {
      keyName: 'Ctrl',
      value: 224,
      x: 0,
      y: -205,
      w: 37,
      h: 30,
    },
    {
      keyName: 'Win',
      value: 227,
      x: 49,
      y: -205,
      w: 37,
      h: 30,
    },
    {
      keyName: 'Alt',
      value: 226,
      x: 98,
      y: -205,
      w: 37,
      h: 30,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 147,
      y: -205,
      w: 233,
      h: 30,
    },
    {
      keyName: 'r_Alt',
      value: 230,
      x: 393,
      y: -205,
      w: 26,
      h: 30,
    },
    {
      keyName: 'FN',
      value: 0x0a010000,
      x: 431,
      y: -205,
      w: 26,
      h: 30,
    },
    {
      keyName: 'r_Ctrl',
      value: 228,
      x: 471,
      y: -205,
      w: 26,
      h: 30,
    },
    {
      keyName: '↑',
      value: 82,
      x: 559,
      y: -175,
      w: 26,
      h: 30,
    },
    {
      keyName: '←',
      value: 80,
      x: 520,
      y: -214,
      w: 26,
      h: 30,
    },
    {
      keyName: '↓',
      value: 81,
      x: 559,
      y: -214,
      w: 26,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
      h: 30,
    },
    {
      keyName: '→',
      value: 79,
      x: 598,
      y: -214,
      w: 26,
      h: 30,
    },
  ],
}
