export const yc500_ak600Min_soc = {
  deltX: 362,
  deltY: 24,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 29,
      h: 31,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 40,
      y: 0,
      w: 29,
      h: 31,
    },
    {
      keyName: 'BackSpace',
      value: 42,
      x: 80,
      y: 0,
      w: 29,
      h: 31,
    },
    {
      keyName: 'FN',
      value: 0x0a010000,
      x: 120,
      y: 0,
      w: 29,
      h: 31,
    },
    {
      keyName: 'Num\nLock',
      value: 83,
      x: 0,
      y: -48,
      w: 29,
      h: 31,
    },
    {
      keyName: 'num_/',
      value: 84,
      x: 40,
      y: -48,
      w: 29,
      h: 31,
    },
    {
      keyName: 'num_*',
      value: 85,
      x: 80,
      y: -48,
      w: 29,
      h: 31,
    },
    {
      keyName: 'num_-',
      value: 86,
      x: 120,
      y: -48,
      w: 29,
      h: 31,
    },
    {
      keyName: 'num_7',
      value: 95,
      x: 0,
      y: -87,
      w: 29,
      h: 31,
    },
    {
      keyName: 'num_8',
      value: 96,
      x: 40,
      y: -87,
      w: 29,
      h: 31,
    },
    {
      keyName: 'num_9',
      value: 97,
      x: 80,
      y: -87,
      w: 29,
      h: 31,
    },
    {
      keyName: 'num_+',
      value: 87,
      x: 120,
      y: -87,
      w: 29,
      h: 70,
    },
    {
      keyName: 'num_4',
      value: 92,
      x: 0,
      y: -126,
      w: 29,
      h: 31,
    },
    {
      keyName: 'num_5',
      value: 93,
      x: 40,
      y: -126,
      w: 29,
      h: 31,
    },
    {
      keyName: 'num_6',
      value: 94,
      x: 80,
      y: -126,
      w: 29,
      h: 31,
    },
    {
      keyName: 'num_1',
      value: 89,
      x: 0,
      y: -167,
      w: 29,
      h: 31,
    },
    {
      keyName: 'num_2',
      value: 90,
      x: 40,
      y: -167,
      w: 29,
      h: 31,
    },
    {
      keyName: 'num_3',
      value: 91,
      x: 80,
      y: -167,
      w: 29,
      h: 31,
    },
    {
      keyName: 'num_Enter',
      value: 88,
      x: 120,
      y: -167,
      w: 29,
      h: 70,
    },
    {
      keyName: 'num_0',
      value: 98,
      x: 0,
      y: -207,
      w: 69,
      h: 31,
    },
    {
      keyName: 'num_.',
      value: 99,
      x: 83,
      y: -207,
      w: 29,
      h: 31,
    },
  ],
}
