export const yc500_acrtop40_dm = {
  deltX: 92,
  deltY: 40,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 40,
      h: 40,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 55,
      y: 0,
      w: 40,
      h: 40,
    },
    {
      keyName: 'W',
      value: 26,
      x: 110,
      y: 0,
      w: 40,
      h: 40,
    },
    {
      keyName: 'E',
      value: 8,
      x: 165,
      y: 0,
      w: 40,
      h: 40,
    },
    {
      keyName: 'R',
      value: 21,
      x: 220,
      y: 0,
      w: 40,
      h: 40,
    },
    {
      keyName: 'T',
      value: 23,
      x: 275,
      y: 0,
      w: 40,
      h: 40,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 330,
      y: 0,
      w: 40,
      h: 40,
    },
    {
      keyName: 'U',
      value: 24,
      x: 385,
      y: 0,
      w: 40,
      h: 40,
    },
    {
      keyName: 'I',
      value: 12,
      x: 440,
      y: 0,
      w: 40,
      h: 40,
    },
    {
      keyName: 'O',
      value: 18,
      x: 495,
      y: 0,
      w: 40,
      h: 40,
    },
    {
      keyName: 'P',
      value: 19,
      x: 550,
      y: 0,
      w: 40,
      h: 40,
    },
    {
      keyName: 'Backspace',
      value: 42,
      x: 605,
      y: 0,
      w: 82,
      h: 40,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -55,
      w: 55,
      h: 40,
    },
    {
      keyName: 'A',
      value: 4,
      x: 69,
      y: -55,
      w: 40,
      h: 40,
    },
    {
      keyName: 'S',
      value: 22,
      x: 124,
      y: -55,
      w: 40,
      h: 40,
    },
    {
      keyName: 'D',
      value: 7,
      x: 179,
      y: -55,
      w: 40,
      h: 40,
    },
    {
      keyName: 'F',
      value: 9,
      x: 234,
      y: -55,
      w: 40,
      h: 40,
    },
    {
      keyName: 'G',
      value: 10,
      x: 289,
      y: -55,
      w: 40,
      h: 40,
    },
    {
      keyName: 'H',
      value: 11,
      x: 344,
      y: -55,
      w: 40,
      h: 40,
    },
    {
      keyName: 'J',
      value: 13,
      x: 399,
      y: -55,
      w: 40,
      h: 40,
    },
    {
      keyName: 'K',
      value: 14,
      x: 454,
      y: -55,
      w: 40,
      h: 40,
    },
    {
      keyName: 'L',
      value: 15,
      x: 509,
      y: -55,
      w: 40,
      h: 40,
    },
    {
      keyName: ';',
      value: 51,
      x: 564,
      y: -55,
      w: 40,
      h: 40,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 619,
      y: -55,
      w: 68,
      h: 40,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -110,
      w: 82,
      h: 40,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 97,
      y: -110,
      w: 40,
      h: 40,
    },
    {
      keyName: 'X',
      value: 27,
      x: 152,
      y: -110,
      w: 40,
      h: 40,
    },
    {
      keyName: 'C',
      value: 6,
      x: 207,
      y: -110,
      w: 40,
      h: 40,
    },
    {
      keyName: 'V',
      value: 25,
      x: 262,
      y: -110,
      w: 40,
      h: 40,
    },
    {
      keyName: 'B',
      value: 5,
      x: 317,
      y: -110,
      w: 40,
      h: 40,
    },
    {
      keyName: 'N',
      value: 17,
      x: 372,
      y: -110,
      w: 40,
      h: 40,
    },
    {
      keyName: 'M',
      value: 16,
      x: 427,
      y: -110,
      w: 40,
      h: 40,
    },
    {
      keyName: ',',
      value: 54,
      x: 482,
      y: -110,
      w: 40,
      h: 40,
    },
    {
      keyName: '.',
      value: 55,
      x: 537,
      y: -110,
      w: 40,
      h: 40,
    },
    {
      keyName: '↑',
      value: 82,
      x: 592,
      y: -110,
      w: 40,
      h: 40,
    },
    {
      keyName: 'r_Shift',
      value: 229,
      x: 646,
      y: -110,
      w: 40,
      h: 40,
    },
    {
      keyName: 'CTRL',
      value: 224,
      x: 0,
      y: -165,
      w: 55,
      h: 40,
    },
    {
      keyName: 'Win',
      value: 227,
      x: 69,
      y: -165,
      w: 55,
      h: 40,
    },
    {
      keyName: 'ALT',
      value: 226,
      x: 138,
      y: -165,
      w: 55,
      h: 40,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 207,
      y: -165,
      w: 108,
      h: 40,
    },
    {
      keyName: '(space)',
      index:1,
      value: 44,
      x: 331,
      y: -165,
      w: 136,
      h: 40,
    },
    {
      keyName: 'FN',
      value: 0x0a010000,
      x: 482,
      y: -165,
      w: 40,
      h: 40,
    },
    {
      keyName: '←',
      value: 80,
      x: 537,
      y: -165,
      w: 40,
      h: 40,
    },
    {
      keyName: '↓',
      value: 81,
      x: 592,
      y: -165,
      w: 40,
      h: 40,
    },
    {
      keyName: '→',
      value: 79,
      x: 646,
      y: -165,
      w: 40,
      h: 40,
    },
  ],
}
