import { ledAKKOCommonLayout } from "./res/lightLayout/ledLayout/ledAKKOCommonLayout"
import { lightAJAZZWAPLayout, lightAJAZZWAPLayout1 } from "./res/lightLayout/lightAJAZZLayout"
import { lightAKKOWAPLayout } from "./res/lightLayout/lightAkkolayout"
import { lightF081Layout } from "./res/lightLayout/lightF081Layout"
import { lightIK75wapLayout } from "./res/lightLayout/lightIK75wapLayout"
import { lightK232Layout } from "./res/lightLayout/lightK232Layout"
import { lightK401tLayout } from "./res/lightLayout/lightK401tLayout"
import { lightK87ProLayout } from "./res/lightLayout/lightK87ProLayout"
import { lightYC200NJ80MacLayout } from "./res/lightLayout/lightNJ80layout"
import { lightRs1Layout } from "./res/lightLayout/lightRs1Layout"
import { lightSK5Layout } from "./res/lightLayout/lightSK5Layout"
import { lightVN66WapLayout } from "./res/lightLayout/lightVN66WapLayout"
import { lightTh21Layout, lightYZ21Layout } from "./res/lightLayout/lightYZ21Layout"
import { yc200CloseCommonLayoutThree, yc200CommonLayout, yc200CommonLayoutOne, yc200CommonLayoutThree, yc200FalseOne, yc200NoRGBCommonLayoutThree } from "./res/lightLayout/yc200CommonLayout"
import { OtherKeydous, OtherKeydousAuto, OtherKeydousLed, OtherTestLed, yc200LEDOther, yc200LEDOther2, yc200LEDOtherH128, yc200LEDOtherH135, yc200LEDOtherH173, yc200LEDOtherH20, yc200LEDOtherH32, yc200LEDOtherH64, yc200LEDOtherH642, yc200Other, yc200Other8, yc200OtherDm } from "./res/otherSetting/yc200Other"
import { SupportDevType } from "./supportDev"

const kRGBGroup = 'rongyuan_k_rgb'
export const supportYC500Dev: SupportDevType[] = [
    {
        id: 9999,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_nj81',
        displayName: 'nj81',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Keydous',
        layout: process.platform === 'darwin' ? lightYC200NJ80MacLayout : yc200CommonLayout,
        fnLayer: 1,
        otherSetting: OtherTestLed
    },
    {
        id: -2147493646,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_pc75b',
        displayName: 'PC75B Plus',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'akko',
        layout: lightAKKOWAPLayout,
        layer: 4,
        fnLayer: 2,
        otherSetting: yc200Other
    },
    {
        id: 9998,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_pc75b',
        displayName: 'PC75B Plus',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'akko',
        layout: lightAKKOWAPLayout,
        layer: 4,
        fnLayer: 2,
        otherSetting: yc200Other
    },
    {
        id: -2147484535,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_mmd87v2_soc',
        displayName: 'MMD87V2',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'MMD',
        layout: lightK87ProLayout,
        fnLayer: 1,
        layer:3,
        otherSetting: yc200Other,
    },
    {
        id: 887,
        vid: 0x3151,
        pid: 0x4015,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_mmd87v2_soc',
        displayName: 'MMD87V2',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'MMD',
        layout: lightK87ProLayout,
        fnLayer: 1,
        layer:3,
        otherSetting: yc200Other,
    },
    {
        id: -2147484522,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_nj81s_ed',
        displayName: 'nj81S-ED',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Keydous',
        layout: process.platform === 'darwin' ? lightYC200NJ80MacLayout : yc200CommonLayout,
        fnLayer: 1,
        otherSetting: OtherKeydousLed
    },
    {
        id: 874,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_nj81s_ed',
        displayName: 'nj81S-ED',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Keydous',
        layout: process.platform === 'darwin' ? lightYC200NJ80MacLayout : yc200CommonLayout,
        fnLayer: 1,
        otherSetting: OtherKeydousLed
    },
    {
        id: -2147484521,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_nj81_ed',
        displayName: 'nj81-ED',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Keydous',
        layout: process.platform === 'darwin' ? lightYC200NJ80MacLayout : yc200CommonLayout,
        fnLayer: 1,
        otherSetting: OtherKeydousLed
    },
    {
        id: 873,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_nj81_ed',
        displayName: 'nj81-ED',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Keydous',
        layout: process.platform === 'darwin' ? lightYC200NJ80MacLayout : yc200CommonLayout,
        fnLayer: 1,
        otherSetting: OtherKeydousLed
    },
    {
        id: 870,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_m1_dm',
        displayName: 'M1',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'MonsGeek',
        layout: lightAKKOWAPLayout,
        fnLayer: 2,
        layer: 4,
    },
    {
        id: -2147484517,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_dagk6098_soc',
        displayName: 'DAGK6098',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'DAGK',
        layout: yc200CommonLayoutOne,
        otherSetting: yc200Other8,
        fnLayer: 1,
        layer: 3
    },
    {
        id: 869,
        vid: 0x3151,
        pid: 0x4015,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_dagk6098_soc',
        displayName: 'DAGK6098',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'DAGK',
        layout: yc200CommonLayoutOne,
        otherSetting: yc200Other8,
        fnLayer: 1,
        layer: 3
    },
    {
        id: 868,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_acrtop40_dm',
        displayName: 'ACR TOP40',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'akko',
        layout: lightAKKOWAPLayout,
        logoLayout: ledAKKOCommonLayout,
        fnLayer: 2,
        layer: 4,
        otherSetting:yc200OtherDm
    },
    {
        id: 865,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_k84_dm',
        displayName: 'K84',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'DUSTSILVER',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 4,
    },
    {
        id: -2147484509,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_h98_soc',
        displayName: 'H98',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: '虎八兔',
        layout: lightK401tLayout,
        layer: 3,
        fnLayer: 1,
        otherSetting: yc200LEDOtherH135,
    },
    {
        id: 861,
        vid: 0x3151,
        pid: 0x4015,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_h98_soc',
        displayName: 'H98',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: '虎八兔',
        layout: lightK401tLayout,
        layer: 3,
        fnLayer: 1,
        otherSetting: yc200LEDOtherH135,
    },
    {
        id: -2147484500,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_sk5',
        displayName: 'SK5',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: '比乐',
        layout: lightSK5Layout,
        layer: 3,
        fnLayer: 1,
        otherSetting: yc200Other
    },
    {
        id: 852,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_sk5',
        displayName: 'SK5',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: '比乐',
        layout: lightSK5Layout,
        layer: 3,
        fnLayer: 1,
        otherSetting: yc200Other
    },
    {
        id: -2147484497,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_mk750_soc',
        displayName: 'MK750',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: '腹灵',
        layout: lightK232Layout,
        fnLayer: 1,
        otherSetting: yc200Other,
    },
    {
        id: 849,
        vid: 0x3151,
        pid: 0x4015,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_mk750_soc',
        displayName: 'MK750',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: '腹灵',
        layout: lightK232Layout,
        fnLayer: 1,
        otherSetting: yc200Other,
    },
    {
        id: -2147484494,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_ak600Min_soc',
        displayName: 'AK600 Min',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'AJAZZ',
        layout: lightAJAZZWAPLayout1,
        otherSetting: yc200Other,
        fnLayer: 1,
        layer: 3,
    },
    {
        id: 846,
        vid: 0x3151,
        pid: 0x4015,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_ak600Min_soc',
        displayName: 'AK600 Min',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'AJAZZ',
        layout: lightAJAZZWAPLayout1,
        otherSetting: yc200Other,
        fnLayer: 1,
        layer: 3,
    },
    {
        id: -2147484493,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_ak600Max_soc',
        displayName: 'AK600 Max',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'AJAZZ',
        layout: lightAJAZZWAPLayout,
        otherSetting: yc200Other,
        fnLayer: 1,
        layer: 3,
    },
    {
        id: 845,
        vid: 0x3151,
        pid: 0x4015,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_ak600Max_soc',
        displayName: 'AK600 Max',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'AJAZZ',
        layout: lightAJAZZWAPLayout,
        otherSetting: yc200Other,
        fnLayer: 1,
        layer: 3,
    },
    {
        id: -2147484488,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_dk67Pro2',
        displayName: 'DK67 V2',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'OUSAID',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other,
    },
    {
        id: 840,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_dk67Pro2',
        displayName: 'DK67 V2',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'OUSAID',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other,
    },
    {
        id: -2147484487,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_cy_th98_soc',
        displayName: 'TH98',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'EPOMAKER',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other,
    },
    {
        id: 839,
        vid: 0x3151,
        pid: 0x4015,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_cy_th98_soc',
        displayName: 'TH98',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'EPOMAKER',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other,
    },
    {
        id: -2147484486,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_sakatana',
        displayName: 'SA-KATANA',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'SADESKATANASK898',
        layout: yc200CommonLayout,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other,
    },
    {
        id: 838,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_sakatana',
        displayName: 'SA-KATANA',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'SADESKATANASK898',
        layout: yc200CommonLayout,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other,
    },
    {
        id: -2147484483,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_tk67_soc',
        displayName: 'B-2 Mini',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'TIETISynapse',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other,
    },
    {
        id: 835,
        vid: 0x3151,
        pid: 0x4015,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_tk67_soc',
        displayName: 'B-2 Mini',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'TIETISynapse',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other,
    },
    {
        id: -2147484478,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_sk8_soc',
        displayName: 'SK8',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: '比乐',
        layout: lightSK5Layout,
        layer: 3,
        fnLayer: 1,
        otherSetting: yc200LEDOtherH64
    },
    {
        id: 830,
        vid: 0x3151,
        pid: 0x4015,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_sk8_soc',
        displayName: 'SK8',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: '比乐',
        layout: lightSK5Layout,
        layer: 3,
        fnLayer: 1,
        otherSetting: yc200LEDOtherH64
    },
    {
        id: -2147484475,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_ck75_single_soc',
        displayName: 'CK75',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: '叠韵创新',
        layout: yc200NoRGBCommonLayoutThree,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other
    },
    {
        id: 827,
        vid: 0x3151,
        pid: 0x4015,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_ck75_single_soc',
        displayName: 'CK75',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: '叠韵创新',
        layout: yc200NoRGBCommonLayoutThree,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other
    },
    {
        id: -2147484471,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_rs2',
        displayName: 'MKS-68 MAX',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Tsunami',
        layout: lightRs1Layout,
        fnLayer: 1,
        otherSetting: yc200Other
    },
    {
        id: 823,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_rs2',
        displayName: 'MKS-68 MAX',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Tsunami',
        layout: lightRs1Layout,
        fnLayer: 1,
        otherSetting: yc200Other
    },
    {
        id: -2147484470,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_kfc100',
        displayName: 'KFC100',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: '鸿丰',
        layout: yc200CommonLayout,
        otherSetting: yc200LEDOtherH173,
        fnLayer: 1,
        layer: 4,
    },
    {
        id: 822,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_kfc100',
        displayName: 'KFC100',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: '鸿丰',
        layout: yc200CommonLayout,
        otherSetting: yc200LEDOtherH173,
        fnLayer: 1,
        layer: 4,
    },
    {
        id: -2147484468,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_l75_soc',
        displayName: 'L75',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'ROYALAXE',
        layout: lightK401tLayout,
        layer: 3,
        fnLayer: 1,
        otherSetting: yc200LEDOtherH135,
    },
    {
        id: 820,
        vid: 0x3151,
        pid: 0x4015,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_l75_soc',
        displayName: 'L75',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'ROYALAXE',
        layout: lightK401tLayout,
        layer: 3,
        fnLayer: 1,
        otherSetting: yc200LEDOtherH135,
    },
    {
        id: -2147484467,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_nj81s',
        displayName: 'NJ81S',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Keydous',
        layout: process.platform === 'darwin' ? lightYC200NJ80MacLayout : yc200CommonLayout,
        fnLayer: 1,
        otherSetting: OtherKeydousLed
    },
    {
        id: 819,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_nj81s',
        displayName: 'NJ81S',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Keydous',
        layout: process.platform === 'darwin' ? lightYC200NJ80MacLayout : yc200CommonLayout,
        fnLayer: 1,
        otherSetting: OtherKeydousLed
    },
    {
        id: 818,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_fk5011gb_dm',
        displayName: 'MF34',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Magicforce',
        layout: yc200FalseOne,
        fnLayer:1,
        layer: 8,
    },
    {
        id: -2147484465,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_fk5011gb',
        displayName: 'MF34',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Magicforce',
        layout: yc200FalseOne,
        otherSetting: yc200Other,
        fnLayer:1,
        layer: 8,
    },
    {
        id: 817,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_fk5011gb',
        displayName: 'MF34',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Magicforce',
        layout: yc200FalseOne,
        otherSetting: yc200Other,
        fnLayer:1,
        layer: 8,
    },
    {
        id: -2147484456,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_k22_soc',
        displayName: 'K22',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'rongyuan',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other
    },
    {
        id: 808,
        vid: 0x3151,
        pid: 0x4015,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_k22_soc',
        displayName: 'K22',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'rongyuan',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other
    },
    {
        id: -2147484455,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_dk737',
        displayName: 'Y4',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'HEXGEARS',
        layout: yc200CloseCommonLayoutThree,
        layer: 4,
        fnLayer: 1,
        otherSetting: yc200Other
    },
    {
        id: 807,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_dk737',
        displayName: 'Y4',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'HEXGEARS',
        layout: yc200CloseCommonLayoutThree,
        layer: 4,
        fnLayer: 1,
        otherSetting: yc200Other
    },
    {
        id: -2147484450,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_kf1800_soc',
        displayName: 'KF1800',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: '鸿丰',
        layout: yc200CommonLayout,
        otherSetting: yc200Other,
        fnLayer: 1,
        layer: 3,
    },
    {
        id: 802,
        vid: 0x3151,
        pid: 0x4015,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_kf1800_soc',
        displayName: 'KF1800',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: '鸿丰',
        layout: yc200CommonLayout,
        otherSetting: yc200Other,
        fnLayer: 1,
        layer: 3,
    },
    {
        id: -2147484447,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_yunzii',
        displayName: 'YZI66',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'YUNZII',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other,
    },
    {
        id: 799,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_yunzii',
        displayName: 'YZI66',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'YUNZII',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other,
    },
    {
        id: -2147484445,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_vgn811',
        displayName: 'VGN811',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'VGN',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200LEDOtherH64,
    },
    {
        id: 797,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_vgn811',
        displayName: 'VGN811',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'VGN',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200LEDOtherH64,
    },
    {
        id: 795,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_sk8_dm',
        displayName: 'SK8 wired',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: '比乐',
        layout: lightSK5Layout,
        layer: 3,
        fnLayer: 1,
    },
    {
        id: -2147484442,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_hf68_soc',
        displayName: 'HF68',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: '鸿丰',
        layout: yc200CommonLayout,
        otherSetting: yc200Other,
        fnLayer: 1,
        layer: 3,
    },
    {
        id: 794,
        vid: 0x3151,
        pid: 0x4015,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_hf68_soc',
        displayName: 'HF68',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: '鸿丰',
        layout: yc200CommonLayout,
        otherSetting: yc200Other,
        fnLayer: 1,
        layer: 3,
    },
    {
        id: -2147484439,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_s3087v3_soc',
        displayName: 'S3087 V100',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Geanykey',
        layout: yc200CommonLayoutOne,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other,
    },
    {
        id: 791,
        vid: 0x3151,
        pid: 0x4015,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_s3087v3_soc',
        displayName: 'S3087 V100',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Geanykey',
        layout: yc200CommonLayoutOne,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other,
    },
    {
        id: -2147484438,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_yzi21',
        displayName: 'YZ-21',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'YUNZII',
        layout: lightTh21Layout,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other,
    },
    {
        id: 790,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_yzi21',
        displayName: 'YZ-21',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'YUNZII',
        layout: lightYZ21Layout,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other,
    },
    {
        id: -2147484437,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_th21',
        displayName: 'TH-21',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'EPOMAKER',
        layout: lightTh21Layout,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other,
    },
    {
        id: 789,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_th21',
        displayName: 'TH-21',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'EPOMAKER',
        layout: lightTh21Layout,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other,
    },
    {
        id: -2147484436,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_ltou75v8',
        displayName: 'Itou75V8',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'rongyuan',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200LEDOther2
    },
    {
        id: 788,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_ltou75v8',
        displayName: 'Itou75V8',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'rongyuan',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200LEDOther2
    },
    {
        id: -2147484434,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_fk5183_soc',
        displayName: 'RS6',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'HEAVYSHELL67',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other
    },
    {
        id: 786,
        vid: 0x3151,
        pid: 0x4015,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_fk5183_soc',
        displayName: 'RS6',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'HEAVYSHELL67',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other
    },
    {
        id: -2147484430,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_th96_uk',
        displayName: 'TH96',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'EPOMAKER',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other,
    },
    {
        id: 782,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_th96_uk',
        displayName: 'TH96',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'EPOMAKER',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other,
    },
    {
        id: -2147484428,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_s3087_soc',
        displayName: 'S3087 V100',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Geanykey',
        layout: yc200CommonLayoutOne,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other,
    },
    {
        id: 780,
        vid: 0x3151,
        pid: 0x4015,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_s3087_soc',
        displayName: 'S3087 V100',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Geanykey',
        layout: yc200CommonLayoutOne,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other,
    },
    {
        id: -2147484427,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_dk750',
        displayName: 'E4',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'HEXGEARS',
        layout: yc200CloseCommonLayoutThree,
        layer: 4,
        fnLayer: 1,
        otherSetting: yc200Other
    },
    {
        id: 779,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_dk750',
        displayName: 'E4',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'HEXGEARS',
        layout: yc200CloseCommonLayoutThree,
        layer: 4,
        fnLayer: 1,
        otherSetting: yc200Other
    },
    {
        id: -2147484426,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_mk857',
        displayName: 'MAXFIT 61',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Fantech',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other
    },
    {
        id: 778,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_mk857',
        displayName: 'MAXFIT 61',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Fantech',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other
    },
    {
        id: -2147484423,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_k239_soc',
        displayName: 'Q75-knob',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: '腹灵',
        layout: lightK232Layout,
        fnLayer: 1,
        otherSetting: yc200Other,
    },
    {
        id: 775,
        vid: 0x3151,
        pid: 0x4015,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_k239_soc',
        displayName: 'Q75-knob',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: '腹灵',
        layout: lightK232Layout,
        fnLayer: 1,
        otherSetting: yc200Other,
    },
    {
        id: -2147484418,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_dk743',
        displayName: 'DK743',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'HEXGEARS',
        layout: yc200CloseCommonLayoutThree,
        layer: 4,
        fnLayer: 1,
        otherSetting: yc200Other
    },
    {
        id: 770,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_dk743',
        displayName: 'DK743',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'HEXGEARS',
        layout: yc200CloseCommonLayoutThree,
        layer: 4,
        fnLayer: 1,
        otherSetting: yc200Other
    },
    {
        id: -2147484417,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_vgn211_soc',
        displayName: 'VGN211',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'VGN',
        layout: lightTh21Layout,
        layer: 3,
        fnLayer: 1,
        otherSetting: yc200Other
    },
    {
        id: 769,
        vid: 0x3151,
        pid: 0x4015,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_vgn211_soc',
        displayName: 'VGN211',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'VGN',
        layout: lightTh21Layout,
        layer: 3,
        fnLayer: 1,
        otherSetting: yc200Other
    },
    {
        id: -2147484416,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_l98_soc',
        displayName: 'L98',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'ROYALAXE',
        layout: lightK401tLayout,
        layer: 3,
        fnLayer: 1,
        otherSetting: yc200LEDOtherH135,
    },
    {
        id: 768,
        vid: 0x3151,
        pid: 0x4015,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_l98_soc',
        displayName: 'L98',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'ROYALAXE',
        layout: lightK401tLayout,
        layer: 3,
        fnLayer: 1,
        otherSetting: yc200LEDOtherH135,
    },
    {
        id: -2147484415,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_dk733',
        displayName: 'Y10',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'HEXGEARS',
        layout: yc200CloseCommonLayoutThree,
        layer: 4,
        fnLayer: 1,
        otherSetting: yc200Other
    },
    {
        id: 767,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_dk733',
        displayName: 'Y10',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'HEXGEARS',
        layout: yc200CloseCommonLayoutThree,
        layer: 4,
        fnLayer: 1,
        otherSetting: yc200Other
    },
    {
        id: -2147484412,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_rs1',
        displayName: 'MK61Max',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Tsunami',
        layout: lightRs1Layout,
        fnLayer: 1,
        otherSetting: yc200Other
    },
    {
        id: 764,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_rs1',
        displayName: 'MK61Max',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Tsunami',
        layout: lightRs1Layout,
        fnLayer: 1,
        otherSetting: yc200Other
    },
    {
        id: -2147484410,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_feker_ik75',
        displayName: 'IK75',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'FEKER',
        fnLayer: 1,
        layout: lightIK75wapLayout,
        otherSetting: yc200Other,
    },
    {
        id: 762,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_feker_ik75',
        displayName: 'IK75',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'FEKER',
        fnLayer: 1,
        layout: lightIK75wapLayout,
        otherSetting: yc200Other,
    },
    {
        id: -2147484408,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_ravanaPro_soc',
        displayName: 'RAVANA PRO',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: '米乐',
        layout: yc200CommonLayoutThree,
        layer: 4,
        fnLayer: 1,
        otherSetting: yc200Other
    },
    {
        id: 760,
        vid: 0x3151,
        pid: 0x4015,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_ravanaPro_soc',
        displayName: 'RAVANA PRO',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: '米乐',
        layout: yc200CommonLayoutThree,
        layer: 4,
        fnLayer: 1,
        otherSetting: yc200Other
    },
    {
        id: -2147484404,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_dk738',
        displayName: 'Y2',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'HEXGEARS',
        layout: yc200CloseCommonLayoutThree,
        layer: 4,
        fnLayer: 1,
        otherSetting: yc200Other
    },
    {
        id: 756,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_dk738',
        displayName: 'Y2',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'HEXGEARS',
        layout: yc200CloseCommonLayoutThree,
        layer: 4,
        fnLayer: 1,
        otherSetting: yc200Other
    },
    {
        id: -2147484402,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_kc21',
        displayName: 'KC21',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: '凯酷',
        layout: lightTh21Layout,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other
    },
    {
        id: 754,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_kc21',
        displayName: 'KC21',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: '凯酷',
        layout: lightTh21Layout,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other
    },
    {
        id: -2147484396,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_th66_uk',
        displayName: 'TH66',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'EPOMAKER',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other,
    },
    {
        id: 748,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_th66_uk',
        displayName: 'TH66',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'EPOMAKER',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other,
    },
    {
        id: 747,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_cy_th66',
        displayName: 'TH66',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'EPOMAKER',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other,
    },
    {
        id: -2147484395,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_cy_th66',
        displayName: 'TH66',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'EPOMAKER',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other,
    },
    {
        id: -2147484390,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_th80',
        displayName: 'TH80',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'EPOMAKER',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other,
    },
    {
        id: 742,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_th80',
        displayName: 'TH80',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'EPOMAKER',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other,
    },
    {
        id: -2147484389,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_th80_uk',
        displayName: 'TH80',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'EPOMAKER',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other,
    },
    {
        id: 741,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_th80_uk',
        displayName: 'TH80',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'EPOMAKER',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other,
    },
    {
        id: -2147484388,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_dk67s',
        displayName: 'DK67S',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'OUSAID',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 4,
        otherSetting: yc200Other,
    },
    {
        id: 740,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_dk67s',
        displayName: 'DK67S',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'OUSAID',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 4,
        otherSetting: yc200Other,
    },
    {
        id: -2147484386,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_kovar_uk_dm',
        displayName: 'KOVAR',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'KOVAR',
        layout: yc200CommonLayout,
        fnLayer: 1,
        layer: 3,
    },
    {
        id: 738,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_kovar_uk_dm',
        displayName: 'KOVAR',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'KOVAR',
        layout: yc200CommonLayout,
        fnLayer: 1,
        layer: 3,
    },
    {
        id: -2147484385,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_kovartkl_uk_dm',
        displayName: 'KOVAR TKL',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'KOVAR',
        layout: yc200CommonLayout,
        fnLayer: 1,
        layer: 3,
    },
    {
        id: 737,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_kovartkl_uk_dm',
        displayName: 'KOVAR TKL',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'KOVAR',
        layout: yc200CommonLayout,
        fnLayer: 1,
        layer: 3,
    },
    {
        id: -2147484384,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_kovar60_uk_dm',
        displayName: 'KOVAR 60',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'KOVAR',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 3,
    },
    {
        id: 736,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_kovar60_uk_dm',
        displayName: 'KOVAR 60',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'KOVAR',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 3,
    },
    {
        id: 735,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_sk6_dm',
        displayName: 'SK6 wired',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: '比乐',
        layout: lightSK5Layout,
        layer: 3,
        fnLayer: 1,
    },
    {
        id: -2147484382,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_sk6',
        displayName: 'SK6',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: '比乐',
        layout: lightSK5Layout,
        layer: 3,
        fnLayer: 1,
        otherSetting: yc200Other
    },
    {
        id: 734,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_sk6',
        displayName: 'SK6',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: '比乐',
        layout: lightSK5Layout,
        layer: 3,
        fnLayer: 1,
        otherSetting: yc200Other
    },
    {
        id: -2147484381,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_hanan081',
        displayName: 'RAKK HANAN',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'RAKKSOFTWARESETUP',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other,
    },
    {
        id: 733,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_hanan081',
        displayName: 'RAKK HANAN',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'RAKKSOFTWARESETUP',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other,
    },
    {
        id: -2147484380,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_nj81',
        displayName: 'nj81',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Keydous',
        layout: process.platform === 'darwin' ? lightYC200NJ80MacLayout : yc200CommonLayout,
        fnLayer: 1,
        otherSetting: OtherKeydousLed
    },
    {
        id: 732,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_nj81',
        displayName: 'nj81',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Keydous',
        layout: process.platform === 'darwin' ? lightYC200NJ80MacLayout : yc200CommonLayout,
        fnLayer: 1,
        otherSetting: OtherKeydousLed
    },
    {
        id: -2147484376,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_vn96_uk',
        displayName: 'VN96',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Dukharo',
        layout: lightVN66WapLayout,
        fnLayer: 1,
        layer: 4,
        otherSetting: yc200Other,
    },
    {
        id: 728,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_vn96_uk',
        displayName: 'VN96',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Dukharo',
        layout: lightVN66WapLayout,
        fnLayer: 1,
        layer: 4,
        otherSetting: yc200Other,
    },
    {
        id: -2147484372,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_vgn811',
        displayName: 'VGN811',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'VGN',
        layout: yc200CommonLayoutOne,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200LEDOtherH64,
    },
    {
        id: 724,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_vgn811',
        displayName: 'VGN811',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'VGN',
        layout: yc200CommonLayoutOne,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200LEDOtherH64,
    },
    {
        id: -2147484371,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_kovar_uk',
        displayName: 'KOVAR WIRELESS',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'KOVAR',
        layout: yc200CommonLayout,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other,
    },
    {
        id: 723,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_kovar_uk',
        displayName: 'KOVAR WIRELESS',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'KOVAR',
        layout: yc200CommonLayout,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other,
    },
    {
        id: -2147484369,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_gk75',
        displayName: 'GK75',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'gamakay2',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 8,
        otherSetting: yc200Other,
    },
    {
        id: 721,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_gk75',
        displayName: 'GK75',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'gamakay2',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 8,
        otherSetting: yc200Other,
    },
    {
        id: -2147484368,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_cl87',
        displayName: 'C87P',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'rongyuan',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other
    },
    {
        id: 720,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_cl87',
        displayName: 'C87P',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'rongyuan',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other
    },
    {
        id: -2147484366,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_c108s',
        displayName: 'C108S',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'rongyuan',
        layout: yc200CommonLayout,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other
    },
    {
        id: 718,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_c108s',
        displayName: 'C108S',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'rongyuan',
        layout: yc200CommonLayout,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other
    },
    {
        id: -2147484364,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_vn96',
        displayName: 'VN96',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Dukharo',
        layout: lightVN66WapLayout,
        fnLayer: 1,
        layer: 4,
        otherSetting: yc200Other,
    },
    {
        id: 716,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_vn96',
        displayName: 'VN96',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Dukharo',
        layout: lightVN66WapLayout,
        fnLayer: 1,
        layer: 4,
        otherSetting: yc200Other,
    },
    {
        id: -2147484362,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_dk740B',
        displayName: 'E2S',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'HEXGEARS',
        layout: yc200CloseCommonLayoutThree,
        layer: 4,
        fnLayer: 1,
        otherSetting: yc200Other
    },
    {
        id: 714,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_dk740B',
        displayName: 'E2S',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'HEXGEARS',
        layout: yc200CloseCommonLayoutThree,
        layer: 4,
        fnLayer: 1,
        otherSetting: yc200Other
    },
    {
        id: -2147484361,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_dk740A',
        displayName: 'E2',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'HEXGEARS',
        layout: yc200CloseCommonLayoutThree,
        layer: 4,
        fnLayer: 1,
        otherSetting: yc200Other
    },
    {
        id: 713,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_dk740A',
        displayName: 'E2',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'HEXGEARS',
        layout: yc200CloseCommonLayoutThree,
        layer: 4,
        fnLayer: 1,
        otherSetting: yc200Other
    },
    {
        id: -2147484360,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_nj68pro',
        displayName: 'NJ68 Pro',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Keydous',
        layout: process.platform === 'darwin' ? lightYC200NJ80MacLayout : yc200CommonLayout,
        fnLayer: 1,
        otherSetting: OtherKeydousLed
    },
    {
        id: 712,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_nj68pro',
        displayName: 'NJ68 Pro',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Keydous',
        layout: process.platform === 'darwin' ? lightYC200NJ80MacLayout : yc200CommonLayout,
        fnLayer: 1,
        otherSetting: OtherKeydousLed
    },
    {
        id: -2147484357,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_vn80_uk',
        displayName: 'VN80',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Dukharo',
        layout: lightVN66WapLayout,
        fnLayer: 1,
        layer: 4,
        otherSetting: yc200Other,
    },
    {
        id: 709,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_vn80_uk',
        displayName: 'VN80',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Dukharo',
        layout: lightVN66WapLayout,
        fnLayer: 1,
        layer: 4,
        otherSetting: yc200Other,
    },
    {
        id: -2147484356,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_k61',
        displayName: 'K61',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'keyxgsul',
        layout: yc200CommonLayoutThree,
        layer: 3,
        fnLayer: 1,
        otherSetting: yc200Other
    },
    {
        id: 708,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_k61',
        displayName: 'K61',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'keyxgsul',
        layout: yc200CommonLayoutThree,
        layer: 3,
        fnLayer: 1,
        otherSetting: yc200Other
    },
    {
        id: -2147484355,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_s68',
        displayName: 'GK-S68PLUS',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Geanykey',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 4,
        otherSetting: yc200Other,
    },
    {
        id: 707,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_s68',
        displayName: 'GK-S68PLUS',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Geanykey',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 4,
        otherSetting: yc200Other,
    },
    {
        id: -2147484351,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_vn80',
        displayName: 'VN80',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Dukharo',
        layout: lightVN66WapLayout,
        fnLayer: 1,
        layer: 4,
        otherSetting: yc200Other,
    },
    {
        id: 703,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_vn80',
        displayName: 'VN80',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Dukharo',
        layout: lightVN66WapLayout,
        fnLayer: 1,
        layer: 4,
        otherSetting: yc200Other,
    },
    {
        id: -2147484349,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_hs_k61',
        displayName: 'K61 PRO',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'gamakay2',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 8,
        otherSetting: yc200Other,
    },
    {
        id: 701,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_hs_k61',
        displayName: 'K61 PRO',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'gamakay2',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 8,
        otherSetting: yc200Other,
    },
    {
        id: -2147484347,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_nj80soc',
        displayName: 'nj80SOC WAP',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Keydous',
        layout: process.platform === 'darwin' ? lightYC200NJ80MacLayout : yc200CommonLayout,
        fnLayer: 1,
        otherSetting: OtherKeydousAuto
    },
    {
        id: 699,
        vid: 0x3151,
        pid: 0x4015,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_nj80soc',
        displayName: 'nj80SOC',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Keydous',
        layout: process.platform === 'darwin' ? lightYC200NJ80MacLayout : yc200CommonLayout,
        fnLayer: 1,
        otherSetting: OtherKeydousAuto
    },
    {
        id: -2147484346,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_k980_oled',
        displayName: 'K980',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'XIBERIA',
        layout: yc200CommonLayoutThree,
        layer: 3,
        fnLayer: 1,
        otherSetting: yc200LEDOther
    },
    {
        id: 698,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_k980_oled',
        displayName: 'K980',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'XIBERIA',
        layout: yc200CommonLayoutThree,
        layer: 3,
        fnLayer: 1,
        otherSetting: yc200LEDOther
    },
    {
        id: -2147484342,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_mk859',
        displayName: 'MAXFIT81',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Fantech',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200LEDOtherH642
    },
    {
        id: 694,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_mk859',
        displayName: 'MAXFIT81',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Fantech',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200LEDOtherH642
    },
    {
        id: -2147484341,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_kg045',
        displayName: 'CR-960',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Qeeke',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 4,
        otherSetting: yc200Other
    },
    {
        id: 693,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_kg045',
        displayName: 'CR-960',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Qeeke',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 4,
        otherSetting: yc200Other
    },
    {
        id: -2147484339,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_k870',
        displayName: 'K870',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'XIBERIA',
        layout: yc200CommonLayoutThree,
        layer: 3,
        fnLayer: 1,
        otherSetting: yc200Other
    },
    {
        id: 691,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_k870',
        displayName: 'K870',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'XIBERIA',
        layout: yc200CommonLayoutThree,
        layer: 3,
        fnLayer: 1,
        otherSetting: yc200Other
    },
    {
        id: -2147484338,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_ck75',
        displayName: 'CK75 2.0',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: '叠韵创新',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other
    },
    {
        id: 690,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_ck75',
        displayName: 'CK75 2.0',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: '叠韵创新',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other
    },
    {
        id: -2147484336,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_3068beu_plus_uk',
        displayName: '3068BEU Plus',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'akko',
        layout: lightAKKOWAPLayout,
        layer: 4,
        fnLayer: 2,
        otherSetting: yc200Other
    },
    {
        id: 688,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_3068beu_plus_uk',
        displayName: '3068BEU Plus',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'akko',
        layout: lightAKKOWAPLayout,
        layer: 4,
        fnLayer: 2,
        otherSetting: yc200Other
    },
    {
        id: -2147484335,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_k202s',
        displayName: 'K202S',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'MBWKD',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 4,
        otherSetting: yc200Other,
    },
    {
        id: 687,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_k202s',
        displayName: 'K202S',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'MBWKD',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 4,
        otherSetting: yc200Other,
    },
    {
        id: -2147484334,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_y98',
        displayName: 'Y98',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'ROYALAXE',
        layout: lightK401tLayout,
        layer: 3,
        fnLayer: 1,
        otherSetting: yc200Other,
    },
    {
        id: 686,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_y98',
        displayName: 'Y98',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'ROYALAXE',
        layout: lightK401tLayout,
        layer: 3,
        fnLayer: 1,
        otherSetting: yc200Other,
    },
    {
        id: -2147484332,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_zsx68',
        displayName: 'MAXFIT67',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Fantech',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other,
    },
    {
        id: 684,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_zsx68',
        displayName: 'MAXFIT67',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Fantech',
        layout: yc200CommonLayoutThree,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other,
    },
    {
        id: -2147484331,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_f081a',
        displayName: 'BW-KB3',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'BlitzwolfKB3',
        layout: lightF081Layout,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other,
    },
    {
        id: 683,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_f081a',
        displayName: 'BW-KB3',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'BlitzwolfKB3',
        layout: lightF081Layout,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other,
    },
    {
        id: -2147484330,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_3068_plus',
        displayName: '3068B Plus',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'akko',
        layout: lightAKKOWAPLayout,
        layer: 4,
        fnLayer: 2,
        otherSetting: yc200Other
    },
    {
        id: 682,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_3068_plus',
        displayName: '3068B Plus',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'akko',
        layout: lightAKKOWAPLayout,
        layer: 4,
        fnLayer: 2,
        otherSetting: yc200Other
    },
    {
        id: 675,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_dk732',
        displayName: 'Y2',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'HEXGEARS',
        layout: yc200CloseCommonLayoutThree,
        layer: 4,
        fnLayer: 1,
        otherSetting: yc200Other
    },
    {
        id: -2147484323,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_dk732',
        displayName: 'Y2',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'HEXGEARS',
        layout: yc200CloseCommonLayoutThree,
        layer: 4,
        fnLayer: 1,
        otherSetting: yc200Other
    },
    {
        id: 674,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_dk731',
        displayName: 'Y3',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'HEXGEARS',
        layout: yc200CloseCommonLayoutThree,
        layer: 4,
        fnLayer: 1,
        otherSetting: yc200Other
    },
    {
        id: -2147484322,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_dk731',
        displayName: 'Y3',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'HEXGEARS',
        layout: yc200CloseCommonLayoutThree,
        layer: 4,
        fnLayer: 1,
        otherSetting: yc200Other
    },
    {
        id: 673,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_dk730',
        displayName: 'Y5',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'HEXGEARS',
        layout: yc200CloseCommonLayoutThree,
        layer: 4,
        fnLayer: 1,
        otherSetting: yc200Other
    },
    {
        id: -2147484321,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_dk730',
        displayName: 'Y5',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'HEXGEARS',
        layout: yc200CloseCommonLayoutThree,
        layer: 4,
        fnLayer: 1,
        otherSetting: yc200Other
    },
    {
        id: 672,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_vn66',
        displayName: 'VN66 wap',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Dukharo',
        layout: lightVN66WapLayout,
        fnLayer: 1,
        layer: 4,
        otherSetting: yc200Other,
    },
    {
        id: -2147484320,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_vn66',
        displayName: 'VN66 wap',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Dukharo',
        layout: lightVN66WapLayout,
        fnLayer: 1,
        layer: 4,
        otherSetting: yc200Other,
    },
    {
        id: 671,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_rx980',
        displayName: 'RX980',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'RXSTORM',
        layout: yc200CommonLayout,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other,
    },
    {
        id: -2147484319,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_rx980',
        displayName: 'RX980',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'RXSTORM',
        layout: yc200CommonLayout,
        fnLayer: 1,
        layer: 3,
        otherSetting: yc200Other,
    },
    {
        id: 670,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_hf67',
        displayName: 'HF67 AP',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: '鸿丰',
        layout: yc200CommonLayout,
        otherSetting: yc200Other,
        fnLayer: 1,
        layer: 3,
    },
    {
        id: -2147484318,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_hf67',
        displayName: 'HF67 WAP',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: '鸿丰',
        layout: yc200CommonLayout,
        otherSetting: yc200Other,
        fnLayer: 1,
        layer: 3,
    },
    {
        id: 655,
        vid: 0x3151,
        pid: 0x4010,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_nj80',
        displayName: 'NJ80 AP500',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Keydous',
        layout: process.platform === 'darwin' ? lightYC200NJ80MacLayout : yc200CommonLayout,
        fnLayer: 1,
        otherSetting: OtherKeydous
    },
    {
        id: -2147484303,
        vid: 0x3151,
        pid: 0x4011,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_nj80',
        displayName: 'NJ80 AP500',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Keydous',
        layout: process.platform === 'darwin' ? lightYC200NJ80MacLayout : yc200CommonLayout,
        fnLayer: 1,
        otherSetting: OtherKeydous
    },
    {
        id: -7,
        vid: 0x3151,
        pid: 0x4015,
        usage: 0x02,
        usagePage: 0xffff,
        name: 'yc500_nj80',
        displayName: 'nj80SOC',
        support_onboard: 2,
        type: 'keyboard',
        group: kRGBGroup,
        featureReportByteLength: 65,
        company: 'Keydous',
        layout: process.platform === 'darwin' ? lightYC200NJ80MacLayout : yc200CommonLayout,
        fnLayer: 1,
        otherSetting: OtherKeydousAuto
    },
]