import { MouseKey } from '../../sdk/DriverIO/DeviceAPI/DeviceInterface'

export const MG912 = {
  deltX: 0,
  deltY: 0,
  layout: [
    {
      x: 645,
      y: 99,
      w: 22,
      h: 22,
      mark: '1',
      keyName: '左',
      value: MouseKey.Left,
    },
    {
      x: 737,
      y: 99,
      w: 22,
      h: 22,
      mark: '2',
      keyName: '右',
      value: MouseKey.Right,
    },
    {
      x: 694,
      y: 98,
      w: 22,
      h: 22,
      mark: '3',
      keyName: '中',
      value: MouseKey.Middle,
    },
    {
      x: 609,
      y: 191,
      w: 22,
      h: 22,
      mark: '4',
      keyName: '前进',
      value: MouseKey.Forward,
    },
    {
      x: 601,
      y: 229,
      w: 22,
      h: 22,
      mark: '5',
      keyName: '后退',
      value: MouseKey.Back,
    },
    {
      x: 778,
      y: 193,
      w: 22,
      h: 22,
      mark: '6',
      keyName: '自定义1',
      value: MouseKey.Key_1,
    },
    {
      x: 786,
      y: 227,
      w: 22,
      h: 22,
      mark: '7',
      keyName: '自定义2',
      value: MouseKey.Key_2,
    },
    {
      x: 694,
      y: 174,
      w: 22,
      h: 22,
      mark: '8',
      keyName: 'DPI',
      value: MouseKey.Dpi,
    },
    {
      x: 694,
      y: 70,
      w: 22,
      h: 22,
      mark: '9',
      keyName: '前滚',
      value: MouseKey.WheelForward,
    },
    {
      x: 694,
      y: 128,
      w: 22,
      h: 22,
      mark: '10',
      keyName: '后滚',
      value: MouseKey.WheelBack,
    },
  ],
}
