export const yc200_mk108l_uk = {
  deltX: 70,
  deltY: 6,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 35,
      h: 37,
     },
    {
      keyName: 'F1',
      value: 58,
      x: 48,
      y: 0,
      w: 35,
      h: 37,
    },
    {
      keyName: 'F2',
      value: 59,
      x: 94,
      y: 0,
      w: 35,
      h: 37,
    },
    {
      keyName: 'F3',
      value: 60,
      x: 141,
      y: 0,
      w: 35,
      h: 37,
    },
    {
      keyName: 'F4',
      value: 61,
      x: 187,
      y: 0,
      w: 35,
      h: 37,
    },
    {
      keyName: 'F5',
      value: 62,
      x: 233,
      y: 0,
      w: 35,
      h: 37,
    },
    {
      keyName: 'F6',
      value: 63,
      x: 279,
      y: 0,
      w: 35,
      h: 37,
    },
    {
      keyName: 'F7',
      value: 64,
      x: 325,
      y: 0,
      w: 35,
      h: 37,
    },
    {
      keyName: 'F8',
      value: 65,
      x: 371,
      y: 0,
      w: 35,
      h: 37,
    },
    {
      keyName: 'F9',
      value: 66,
      x: 417,
      y: 0,
      w: 35,
      h: 37,
    },
    {
      keyName: 'F10',
      value: 67,
      x: 463,
      y: 0,
      w: 35,
      h: 37,
    },
    {
      keyName: 'F11',
      value: 68,
      x: 510,
      y: 0,
      w: 35,
      h: 37,
    },
    {
      keyName: 'F12',
      value: 69,
      x: 556,
      y: 0,
      w: 35,
      h: 37,
    },
    {
      keyName: 'Print\nScreen',
      value: 70,
      x: 602,
      y: 0,
      w: 35,
      h: 37,
    },
    {
      keyName: 'Insert',
      value: 73,
      x: 649,
      y: 0,
      w: 35,
      h: 37,
    },
    {
      keyName: 'Delete',
      value: 76,
      x: 695,
      y: 0,
      w: 35,
      h: 37,
    },
    {
      keyName: '`',
      value: 53,
      x: 0,
      y: -45,
      w: 35,
      h: 37,
    },
    {
      keyName: '1',
      value: 30,
      x: 48,
      y: -45,
      w: 35,
      h: 37,
    },
    {
      keyName: '2',
      value: 31,
      x: 94,
      y: -45,
      w: 35,
      h: 37,
    },
    {
      keyName: '3',
      value: 32,
      x: 141,
      y: -45,
      w: 35,
      h: 37,
    },
    {
      keyName: '4',
      value: 33,
      x: 187,
      y: -45,
      w: 35,
      h: 37,
    },
    {
      keyName: '5',
      value: 34,
      x: 233,
      y: -45,
      w: 35,
      h: 37,
    },
    {
      keyName: '6',
      value: 35,
      x: 279,
      y: -45,
      w: 35,
      h: 37,
    },
    {
      keyName: '7',
      value: 36,
      x: 325,
      y: -45,
      w: 35,
      h: 37,
    },
    {
      keyName: '8',
      value: 37,
      x: 371,
      y: -45,
      w: 35,
      h: 37,
    },
    {
      keyName: '9',
      value: 38,
      x: 417,
      y: -45,
      w: 35,
      h: 37,
    },
    {
      keyName: '0',
      value: 39,
      x: 463,
      y: -45,
      w: 35,
      h: 37,
    },
    {
      keyName: '-',
      value: 45,
      x: 510,
      y: -45,
      w: 35,
      h: 37,
    },
    {
      keyName: '=',
      value: 46,
      x: 556,
      y: -45,
      w: 35,
      h: 37,
    },
    {
      keyName: 'BackSpace',
      value: 42,
      x: 602,
      y: -45,
      w: 82,
      h: 37,
    },
    {
      keyName: 'Home',
      value: 74,
      x: 695,
      y: -45,
      w: 35,
      h: 37,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -92,
      w: 57,
      h: 37,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 70,
      y: -92,
      w: 35,
      h: 37,
    },
    {
      keyName: 'W',
      value: 26,
      x: 116,
      y: -92,
      w: 35,
      h: 37,
    },
    {
      keyName: 'E',
      value: 8,
      x: 163,
      y: -92,
      w: 35,
      h: 37,
    },
    {
      keyName: 'R',
      value: 21,
      x: 209,
      y: -92,
      w: 35,
      h: 37,
    },
    {
      keyName: 'T',
      value: 23,
      x: 255,
      y: -92,
      w: 35,
      h: 37,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 301,
      y: -92,
      w: 35,
      h: 37,
    },
    {
      keyName: 'U',
      value: 24,
      x: 348,
      y: -92,
      w: 35,
      h: 37,
    },
    {
      keyName: 'I',
      value: 12,
      x: 394,
      y: -92,
      w: 35,
      h: 37,
    },
    {
      keyName: 'O',
      value: 18,
      x: 441,
      y: -92,
      w: 35,
      h: 37,
    },
    {
      keyName: 'P',
      value: 19,
      x: 487,
      y: -92,
      w: 35,
      h: 37,
    },
    {
      keyName: '[',
      value: 47,
      x: 533,
      y: -92,
      w: 35,
      h: 37,
    },
    {
      keyName: ']',
      value: 48,
      x: 580,
      y: -92,
      w: 35,
      h: 37,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 637,
      y: -92,
      w: 47,
      h: 82,
    },
    {
      keyName: 'End',
      value: 77,
      x: 695,
      y: -92,
      w: 35,
      h: 37,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -137,
      w: 69,
      h: 37,
    },
    {
      keyName: 'A',
      value: 4,
      x: 82,
      y: -137,
      w: 35,
      h: 37,
    },
    {
      keyName: 'S',
      value: 22,
      x: 128,
      y: -137,
      w: 35,
      h: 37,
    },
    {
      keyName: 'D',
      value: 7,
      x: 175,
      y: -137,
      w: 35,
      h: 37,
    },
    {
      keyName: 'F',
      value: 9,
      x: 221,
      y: -137,
      w: 35,
      h: 37,
    },
    {
      keyName: 'G',
      value: 10,
      x: 267,
      y: -137,
      w: 35,
      h: 37,
    },
    {
      keyName: 'H',
      value: 11,
      x: 313,
      y: -137,
      w: 35,
      h: 37,
    },
    {
      keyName: 'J',
      value: 13,
      x: 360,
      y: -137,
      w: 35,
      h: 37,
    },
    {
      keyName: 'K',
      value: 14,
      x: 406,
      y: -137,
      w: 35,
      h: 37,
    },
    {
      keyName: 'L',
      value: 15,
      x: 452,
      y: -137,
      w: 35,
      h: 37,
    },
    {
      keyName: ';',
      value: 51,
      x: 498,
      y: -137,
      w: 35,
      h: 37,
    },
    {
      keyName: '"',
      value: 52,
      x: 545,
      y: -137,
      w: 35,
      h: 37,
    },
    {
      keyName: '#',
      value: 50,
      x: 592,
      y: -137,
      w: 35,
      h: 37,
    },
    {
      keyName: 'Page\nUp',
      value: 75,
      x: 695,
      y: -137,
      w: 35,
      h: 37,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -184,
      w: 47,
      h: 37,
    },
    {
      keyName: '_\\',
      value: 100,
      x: 58,
      y: -184,
      w: 35,
      h: 37,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 104,
      y: -184,
      w: 35,
      h: 37,
    },
    {
      keyName: 'X',
      value: 27,
      x: 151,
      y: -184,
      w: 35,
      h: 37,
    },
    {
      keyName: 'C',
      value: 6,
      x: 197,
      y: -184,
      w: 35,
      h: 37,
    },
    {
      keyName: 'V',
      value: 25,
      x: 243,
      y: -184,
      w: 35,
      h: 37,
    },
    {
      keyName: 'B',
      value: 5,
      x: 290,
      y: -184,
      w: 35,
      h: 37,
    },
    {
      keyName: 'N',
      value: 17,
      x: 337,
      y: -184,
      w: 35,
      h: 37,
    },
    {
      keyName: 'M',
      value: 16,
      x: 383,
      y: -184,
      w: 35,
      h: 37,
    },
    {
      keyName: ',',
      value: 54,
      x: 429,
      y: -184,
      w: 35,
      h: 37,
    },
    {
      keyName: '.',
      value: 55,
      x: 475,
      y: -184,
      w: 35,
      h: 37,
    },
    {
      keyName: '/',
      value: 56,
      x: 522,
      y: -184,
      w: 35,
      h: 37,
    },
    {
      keyName: 'r_Shift',
      value: 229,
      x: 569,
      y: -184,
      w: 68,
      h: 37,
    },
    {
      keyName: '↑',
      value: 82,
      x: 649,
      y: -184,
      w: 35,
      h: 37,
    },
    {
      keyName: 'Page\nDown',
      value: 78,
      x: 695,
      y: -184,
      w: 35,
      h: 37,
    },
    {
      keyName: 'Ctrl',
      value: 224,
      x: 0,
      y: -231,
      w: 47,
      h: 37,
    },
    {
      keyName: 'Win',
      value: 227,
      x: 58,
      y: -231,
      w: 47,
      h: 37,
    },
    {
      keyName: 'Alt',
      value: 226,
      x: 116,
      y: -231,
      w: 47,
      h: 37,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 174,
      y: -231,
      w: 278,
      h: 37,
    },
    {
      keyName: 'r_Alt',
      value: 230,
      x: 465,
      y: -231,
      w: 35,
      h: 37,
    },
    {
      keyName: 'FN',
      value: 0x0a010000,
      x: 511,
      y: -231,
      w: 35,
      h: 37,
    },
    {
      keyName: 'r_Ctrl',
      value: 228,
      x: 557,
      y: -231,
      w: 35,
      h: 37,
    },
    {
      keyName: '←',
      value: 80,
      x: 603,
      y: -231,
      w: 35,
      h: 37,
    },
    {
      keyName: '↓',
      value: 81,
      x: 649,
      y: -231,
      w: 35,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
      h: 37,
    },
    {
      keyName: '→',
      value: 79,
      x: 695,
      y: -231,
      w: 35,
      h: 37,
    },
  ],
}
