export const yc200_k232 = {
  deltX: 124,
  deltY: 20,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 27,
      h: 30,
     },
    {
      keyName: 'F1',
      value: 58,
      x: 77,
      y: 0,
      w: 27,
      h: 30,
    },
    {
      keyName: 'F2',
      value: 59,
      x: 116,
      y: 0,
      w: 27,
      h: 30,
    },
    {
      keyName: 'F3',
      value: 60,
      x: 154,
      y: 0,
      w: 27,
      h: 30,
    },
    {
      keyName: 'F4',
      value: 61,
      x: 193,
      y: 0,
      w: 27,
      h: 30,
    },
    {
      keyName: 'F5',
      value: 62,
      x: 251,
      y: 0,
      w: 27,
      h: 30,
    },
    {
      keyName: 'F6',
      value: 63,
      x: 289,
      y: 0,
      w: 27,
      h: 30,
    },
    {
      keyName: 'F7',
      value: 64,
      x: 328,
      y: 0,
      w: 27,
      h: 30,
    },
    {
      keyName: 'F8',
      value: 65,
      x: 367,
      y: 0,
      w: 27,
      h: 30,
    },
    {
      keyName: 'F9',
      value: 66,
      x: 425,
      y: 0,
      w: 27,
      h: 30,
    },
    {
      keyName: 'F10',
      value: 67,
      x: 463,
      y: 0,
      w: 27,
      h: 30,
    },
    {
      keyName: 'F11',
      value: 68,
      x: 501,
      y: 0,
      w: 27,
      h: 30,
    },
    {
      keyName: 'F12',
      value: 69,
      x: 540,
      y: 0,
      w: 27,
      h: 30,
    },
    {
      keyName: 'Delete',
      value: 76,
      x: 597,
      y: 0,
      w: 27,
      h: 30,
    },
    {
      keyName: '`',
      value: 53,
      x: 0,
      y: -54,
      w: 27,
      h: 30,
    },
    {
      keyName: '1',
      value: 30,
      x: 39,
      y: -54,
      w: 27,
      h: 30,
    },
    {
      keyName: '2',
      value: 31,
      x: 78,
      y: -54,
      w: 27,
      h: 30,
    },
    {
      keyName: '3',
      value: 32,
      x: 116,
      y: -54,
      w: 27,
      h: 30,
    },
    {
      keyName: '4',
      value: 33,
      x: 155,
      y: -54,
      w: 27,
      h: 30,
    },
    {
      keyName: '5',
      value: 34,
      x: 193,
      y: -54,
      w: 27,
      h: 30,
    },
    {
      keyName: '6',
      value: 35,
      x: 232,
      y: -54,
      w: 27,
      h: 30,
    },
    {
      keyName: '7',
      value: 36,
      x: 270,
      y: -54,
      w: 27,
      h: 30,
    },
    {
      keyName: '8',
      value: 37,
      x: 309,
      y: -54,
      w: 27,
      h: 30,
    },
    {
      keyName: '9',
      value: 38,
      x: 347,
      y: -54,
      w: 27,
      h: 30,
    },
    {
      keyName: '0',
      value: 39,
      x: 386,
      y: -54,
      w: 27,
      h: 30,
    },
    {
      keyName: '-',
      value: 45,
      x: 425,
      y: -54,
      w: 27,
      h: 30,
    },
    {
      keyName: '=',
      value: 46,
      x: 463,
      y: -54,
      w: 27,
      h: 30,
    },
    {
      keyName: 'BackSpace',
      value: 42,
      x: 502,
      y: -54,
      w: 65,
      h: 30,
    },
    {
      keyName: 'Home',
      value: 74,
      x: 597,
      y: -54,
      w: 27,
      h: 30,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -92,
      w: 46,
      h: 30,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 58,
      y: -92,
      w: 27,
      h: 30,
    },
    {
      keyName: 'W',
      value: 26,
      x: 97,
      y: -92,
      w: 27,
      h: 30,
    },
    {
      keyName: 'E',
      value: 8,
      x: 135,
      y: -92,
      w: 27,
      h: 30,
    },
    {
      keyName: 'R',
      value: 21,
      x: 174,
      y: -92,
      w: 27,
      h: 30,
    },
    {
      keyName: 'T',
      value: 23,
      x: 212,
      y: -92,
      w: 27,
      h: 30,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 251,
      y: -92,
      w: 27,
      h: 30,
    },
    {
      keyName: 'U',
      value: 24,
      x: 289,
      y: -92,
      w: 27,
      h: 30,
    },
    {
      keyName: 'I',
      value: 12,
      x: 328,
      y: -92,
      w: 27,
      h: 30,
    },
    {
      keyName: 'O',
      value: 18,
      x: 366,
      y: -92,
      w: 27,
      h: 30,
    },
    {
      keyName: 'P',
      value: 19,
      x: 405,
      y: -92,
      w: 27,
      h: 30,
    },
    {
      keyName: '[',
      value: 47,
      x: 444,
      y: -92,
      w: 27,
      h: 30,
    },
    {
      keyName: ']',
      value: 48,
      x: 482,
      y: -92,
      w: 27,
      h: 30,
    },
    {
      keyName: '\\',
      value: 49,
      x: 521,
      y: -92,
      w: 46,
      h: 30,
    },
    {
      keyName: 'End',
      value: 77,
      x: 597,
      y: -92,
      w: 27,
      h: 30,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -130,
      w: 55,
      h: 30,
    },
    {
      keyName: 'A',
      value: 4,
      x: 68,
      y: -130,
      w: 27,
      h: 30,
    },
    {
      keyName: 'S',
      value: 22,
      x: 106,
      y: -130,
      w: 27,
      h: 30,
    },
    {
      keyName: 'D',
      value: 7,
      x: 145,
      y: -130,
      w: 27,
      h: 30,
    },
    {
      keyName: 'F',
      value: 9,
      x: 183,
      y: -130,
      w: 27,
      h: 30,
    },
    {
      keyName: 'G',
      value: 10,
      x: 222,
      y: -130,
      w: 27,
      h: 30,
    },
    {
      keyName: 'H',
      value: 11,
      x: 261,
      y: -130,
      w: 27,
      h: 30,
    },
    {
      keyName: 'J',
      value: 13,
      x: 299,
      y: -130,
      w: 27,
      h: 30,
    },
    {
      keyName: 'K',
      value: 14,
      x: 338,
      y: -130,
      w: 27,
      h: 30,
    },
    {
      keyName: 'L',
      value: 15,
      x: 376,
      y: -130,
      w: 27,
      h: 30,
    },
    {
      keyName: ';',
      value: 51,
      x: 415,
      y: -130,
      w: 27,
      h: 30,
    },
    {
      keyName: '\'',
      value: 52,
      x: 453,
      y: -130,
      w: 27,
      h: 30,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 493,
      y: -130,
      w: 74,
      h: 30,
    },
    {
      keyName: 'Page\nUp',
      value: 75,
      x: 597,
      y: -130,
      w: 27,
      h: 30,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -168,
      w: 75,
      h: 30,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 87,
      y: -168,
      w: 27,
      h: 30,
    },
    {
      keyName: 'X',
      value: 27,
      x: 125,
      y: -168,
      w: 27,
      h: 30,
    },
    {
      keyName: 'C',
      value: 6,
      x: 164,
      y: -168,
      w: 27,
      h: 30,
    },
    {
      keyName: 'V',
      value: 25,
      x: 202,
      y: -168,
      w: 27,
      h: 30,
    },
    {
      keyName: 'B',
      value: 5,
      x: 241,
      y: -168,
      w: 27,
      h: 30,
    },
    {
      keyName: 'N',
      value: 17,
      x: 280,
      y: -168,
      w: 27,
      h: 30,
    },
    {
      keyName: 'M',
      value: 16,
      x: 318,
      y: -168,
      w: 27,
      h: 30,
    },
    {
      keyName: ',',
      value: 54,
      x: 357,
      y: -168,
      w: 27,
      h: 30,
    },
    {
      keyName: '.',
      value: 55,
      x: 395,
      y: -168,
      w: 27,
      h: 30,
    },
    {
      keyName: '/',
      value: 56,
      x: 434,
      y: -168,
      w: 27,
      h: 30,
    },
    {
      keyName: 'r_Shift',
      value: 229,
      x: 472,
      y: -168,
      w: 56,
      h: 30,
    },
    {
      keyName: 'Page\nDown',
      value: 78,
      x: 597,
      y: -168,
      w: 27,
      h: 30,
    },
    {
      keyName: 'Ctrl',
      value: 224,
      x: 0,
      y: -207,
      w: 36,
      h: 30,
    },
    {
      keyName: 'Win',
      value: 227,
      x: 49,
      y: -207,
      w: 36,
      h: 30,
    },
    {
      keyName: 'Alt',
      value: 226,
      x: 97,
      y: -207,
      w: 36,
      h: 30,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 145,
      y: -207,
      w: 230,
      h: 30,
    },
    {
      keyName: 'r_Alt',
      value: 230,
      x: 386,
      y: -207,
      w: 27,
      h: 30,
    },
    {
      keyName: 'FN',
      value: 0x0a010000,
      x: 424,
      y: -207,
      w: 27,
      h: 30,
    },
    {
      keyName: 'r_Ctrl',
      value: 228,
      x: 463,
      y: -207,
      w: 27,
      h: 30,
    },
    {
      keyName: '↑',
      value: 82,
      x: 549,
      y: -178,
      w: 27,
      h: 30,
    },
    {
      keyName: '←',
      value: 80,
      x: 511,
      y: -216,
      w: 27,
      h: 30,
    },
    {
      keyName: '↓',
      value: 81,
      x: 549,
      y: -216,
      w: 27,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
      h: 30,
    },
    {
      keyName: '→',
      value: 79,
      x: 588,
      y: -216,
      w: 27,
      h: 30,
    },
  ],
}
