export const yc200_ac067 = {
  deltX: 58,
  deltY: 25,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 31,
      h: 35,
    },
    {
      keyName: '1',
      value: 30,
      x: 48,
      y: 0,
      w: 31,
      h: 35,
    },
    {
      keyName: '2',
      value: 31,
      x: 96,
      y: 0,
      w: 31,
      h: 35,
    },
    {
      keyName: '3',
      value: 32,
      x: 145,
      y: 0,
      w: 31,
      h: 35,
    },
    {
      keyName: '4',
      value: 33,
      x: 194,
      y: 0,
      w: 31,
      h: 35,
    },
    {
      keyName: '5',
      value: 34,
      x: 242,
      y: 0,
      w: 31,
      h: 35,
    },
    {
      keyName: '6',
      value: 35,
      x: 290,
      y: 0,
      w: 31,
      h: 35,
    },
    {
      keyName: '7',
      value: 36,
      x: 339,
      y: 0,
      w: 31,
      h: 35,
    },
    {
      keyName: '8',
      value: 37,
      x: 387,
      y: 0,
      w: 31,
      h: 35,
    },
    {
      keyName: '9',
      value: 38,
      x: 436,
      y: 0,
      w: 31,
      h: 35,
    },
    {
      keyName: '0',
      value: 39,
      x: 484,
      y: 0,
      w: 31,
      h: 35,
    },
    {
      keyName: '-',
      value: 45,
      x: 532,
      y: 0,
      w: 31,
      h: 35,
    },
    {
      keyName: '=',
      value: 46,
      x: 581,
      y: 0,
      w: 31,
      h: 35,
    },
    {
      keyName: 'Backspace',
      value: 42,
      x: 630,
      y: 0,
      w: 78,
      h: 35,
    },
    {
      keyName: 'Home',
      value: 74,
      x: 725,
      y: 0,
      w: 31,
      h: 35,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -49,
      w: 56,
      h: 35,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 73,
      y: -49,
      w: 31,
      h: 35,
    },
    {
      keyName: 'W',
      value: 26,
      x: 121,
      y: -49,
      w: 31,
      h: 35,
    },
    {
      keyName: 'E',
      value: 8,
      x: 170,
      y: -49,
      w: 31,
      h: 35,
    },
    {
      keyName: 'R',
      value: 21,
      x: 219,
      y: -49,
      w: 31,
      h: 35,
    },
    {
      keyName: 'T',
      value: 23,
      x: 267,
      y: -49,
      w: 31,
      h: 35,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 315,
      y: -49,
      w: 31,
      h: 35,
    },
    {
      keyName: 'U',
      value: 24,
      x: 364,
      y: -49,
      w: 31,
      h: 35,
    },
    {
      keyName: 'I',
      value: 12,
      x: 412,
      y: -49,
      w: 31,
      h: 35,
    },
    {
      keyName: 'O',
      value: 18,
      x: 460,
      y: -49,
      w: 31,
      h: 35,
    },
    {
      keyName: 'P',
      value: 19,
      x: 508,
      y: -49,
      w: 31,
      h: 35,
    },
    {
      keyName: '[',
      value: 47,
      x: 556,
      y: -49,
      w: 31,
      h: 35,
    },
    {
      keyName: ']',
      value: 48,
      x: 604,
      y: -49,
      w: 31,
      h: 35,
    },
    {
      keyName: '\\',
      value: 49,
      x: 653,
      y: -49,
      w: 54,
      h: 35,
    },
    {
      keyName: 'Delete',
      value: 76,
      x: 725,
      y: -49,
      w: 31,
      h: 35,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -97,
      w: 68,
      h: 35,
    },
    {
      keyName: 'A',
      value: 4,
      x: 86,
      y: -97,
      w: 31,
      h: 35,
    },
    {
      keyName: 'S',
      value: 22,
      x: 134,
      y: -97,
      w: 31,
      h: 35,
    },
    {
      keyName: 'D',
      value: 7,
      x: 182,
      y: -97,
      w: 31,
      h: 35,
    },
    {
      keyName: 'F',
      value: 9,
      x: 231,
      y: -97,
      w: 31,
      h: 35,
    },
    {
      keyName: 'G',
      value: 10,
      x: 279,
      y: -97,
      w: 31,
      h: 35,
    },
    {
      keyName: 'H',
      value: 11,
      x: 327,
      y: -97,
      w: 31,
      h: 35,
    },
    {
      keyName: 'J',
      value: 13,
      x: 375,
      y: -97,
      w: 31,
      h: 35,
    },
    {
      keyName: 'K',
      value: 14,
      x: 423,
      y: -97,
      w: 31,
      h: 35,
    },
    {
      keyName: 'L',
      value: 15,
      x: 471,
      y: -97,
      w: 31,
      h: 35,
    },
    {
      keyName: ';',
      value: 51,
      x: 520,
      y: -97,
      w: 31,
      h: 35,
    },
    {
      keyName: '\'',
      value: 52,
      x: 568,
      y: -97,
      w: 31,
      h: 35,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 617,
      y: -97,
      w: 91,
      h: 35,
    },
    {
      keyName: 'Page\nUp',
      value: 75,
      x: 725,
      y: -97,
      w: 31,
      h: 35,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -145,
      w: 91,
      h: 35,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 110,
      y: -145,
      w: 31,
      h: 35,
    },
    {
      keyName: 'X',
      value: 27,
      x: 158,
      y: -145,
      w: 31,
      h: 35,
    },
    {
      keyName: 'C',
      value: 6,
      x: 207,
      y: -145,
      w: 31,
      h: 35,
    },
    {
      keyName: 'V',
      value: 25,
      x: 255,
      y: -145,
      w: 31,
      h: 35,
    },
    {
      keyName: 'B',
      value: 5,
      x: 303,
      y: -145,
      w: 31,
      h: 35,
    },
    {
      keyName: 'N',
      value: 17,
      x: 351,
      y: -145,
      w: 31,
      h: 35,
    },
    {
      keyName: 'M',
      value: 16,
      x: 399,
      y: -145,
      w: 31,
      h: 35,
    },
    {
      keyName: ',',
      value: 54,
      x: 447,
      y: -145,
      w: 31,
      h: 35,
    },
    {
      keyName: '.',
      value: 55,
      x: 495,
      y: -145,
      w: 31,
      h: 35,
    },
    {
      keyName: '/',
      value: 56,
      x: 544,
      y: -145,
      w: 31,
      h: 35,
    },
    {
      keyName: 'r_Shift',
      value: 229,
      x: 592,
      y: -145,
      w: 66,
      h: 35,
    },
    {
      keyName: '↑',
      value: 82,
      x: 677,
      y: -145,
      w: 31,
      h: 35,
    },
    {
      keyName: 'Page\nDown',
      value: 78,
      x: 725,
      y: -145,
      w: 31,
      h: 35,
    },
    {
      keyName: 'CTRL',
      value: 224,
      x: 0,
      y: -194,
      w: 43,
      h: 35,
    },
    {
      keyName: 'Win',
      value: 227,
      x: 61,
      y: -194,
      w: 43,
      h: 35,
    },
    {
      keyName: 'ALT',
      value: 226,
      x: 122,
      y: -194,
      w: 43,
      h: 35,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 184,
      y: -194,
      w: 281,
      h: 35,
    },
    {
      keyName: 'r_Alt',
      value: 230,
      x: 483,
      y: -194,
      w: 43,
      h: 35,
    },
    {
      keyName: 'FN',
      value: 0x0a010000,
      x: 544,
      y: -194,
      w: 43,
      h: 35,
    },
    {
      keyName: '←',
      value: 80,
      x: 627,
      y: -194,
      w: 31,
      h: 35,
    },
    {
      keyName: '↓',
      value: 81,
      x: 677,
      y: -194,
      w: 31,
      h: 35,
    },
    {
      keyName: '→',
      value: 79,
      x: 725,
      y: -194,
      w: 31,
      h: 35,
    },
  ],
}
