export const yc200_b67 = {
  deltX: 76,
  deltY: 32,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 33,
      h: 32,
     },
    {
      keyName: '1',
      value: 30,
      x: 47,
      y: 0,
      w: 33,
      h: 32,
    },
    {
      keyName: '2',
      value: 31,
      x: 91,
      y: 0,
      w: 33,
      h: 32,
    },
    {
      keyName: '3',
      value: 32,
      x: 137,
      y: 0,
      w: 33,
      h: 32,
    },
    {
      keyName: '4',
      value: 33,
      x: 184,
      y: 0,
      w: 33,
      h: 32,
    },
    {
      keyName: '5',
      value: 34,
      x: 228,
      y: 0,
      w: 33,
      h: 32,
    },
    {
      keyName: '6',
      value: 35,
      x: 275,
      y: 0,
      w: 33,
      h: 32,
    },
    {
      keyName: '7',
      value: 36,
      x: 321,
      y: 0,
      w: 33,
      h: 32,
    },
    {
      keyName: '8',
      value: 37,
      x: 365,
      y: 0,
      w: 33,
      h: 32,
    },
    {
      keyName: '9',
      value: 38,
      x: 412,
      y: 0,
      w: 33,
      h: 32,
    },
    {
      keyName: '0',
      value: 39,
      x: 458,
      y: 0,
      w: 33,
      h: 32,
    },
    {
      keyName: '-',
      value: 45,
      x: 502,
      y: 0,
      w: 33,
      h: 32,
    },
    {
      keyName: '=',
      value: 46,
      x: 549,
      y: 0,
      w: 33,
      h: 32,
    },
    {
      keyName: 'Backspace',
      value: 42,
      x: 595,
      y: 0,
      w: 75,
      h: 32,
    },
    {
      keyName: 'Home',
      value: 74,
      x: 684,
      y: 0,
      w: 33,
      h: 32,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -46,
      w: 56,
      h: 32,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 70,
      y: -46,
      w: 33,
      h: 32,
    },
    {
      keyName: 'W',
      value: 26,
      x: 114,
      y: -46,
      w: 33,
      h: 32,
    },
    {
      keyName: 'E',
      value: 8,
      x: 160,
      y: -46,
      w: 33,
      h: 32,
    },
    {
      keyName: 'R',
      value: 21,
      x: 207,
      y: -46,
      w: 33,
      h: 32,
    },
    {
      keyName: 'T',
      value: 23,
      x: 251,
      y: -46,
      w: 33,
      h: 32,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 298,
      y: -46,
      w: 33,
      h: 32,
    },
    {
      keyName: 'U',
      value: 24,
      x: 344,
      y: -46,
      w: 33,
      h: 32,
    },
    {
      keyName: 'I',
      value: 12,
      x: 388,
      y: -46,
      w: 33,
      h: 32,
    },
    {
      keyName: 'O',
      value: 18,
      x: 435,
      y: -46,
      w: 33,
      h: 32,
    },
    {
      keyName: 'P',
      value: 19,
      x: 481,
      y: -46,
      w: 33,
      h: 32,
    },
    {
      keyName: '[',
      value: 47,
      x: 525,
      y: -46,
      w: 33,
      h: 32,
    },
    {
      keyName: ']',
      value: 48,
      x: 572,
      y: -46,
      w: 33,
      h: 32,
    },
    {
      keyName: '\\',
      value: 49,
      x: 619,
      y: -46,
      w: 51,
      h: 32,
    },
    {
      keyName: 'Delete',
      value: 76,
      x: 684,
      y: -46,
      w: 33,
      h: 32,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -92,
      w: 68,
      h: 32,
    },
    {
      keyName: 'A',
      value: 4,
      x: 81,
      y: -92,
      w: 33,
      h: 32,
    },
    {
      keyName: 'S',
      value: 22,
      x: 125,
      y: -92,
      w: 33,
      h: 32,
    },
    {
      keyName: 'D',
      value: 7,
      x: 171,
      y: -92,
      w: 33,
      h: 32,
    },
    {
      keyName: 'F',
      value: 9,
      x: 218,
      y: -92,
      w: 33,
      h: 32,
    },
    {
      keyName: 'G',
      value: 10,
      x: 262,
      y: -92,
      w: 33,
      h: 32,
    },
    {
      keyName: 'H',
      value: 11,
      x: 309,
      y: -92,
      w: 33,
      h: 32,
    },
    {
      keyName: 'J',
      value: 13,
      x: 355,
      y: -92,
      w: 33,
      h: 32,
    },
    {
      keyName: 'K',
      value: 14,
      x: 399,
      y: -92,
      w: 33,
      h: 32,
    },
    {
      keyName: 'L',
      value: 15,
      x: 446,
      y: -92,
      w: 33,
      h: 32,
    },
    {
      keyName: ';',
      value: 51,
      x: 492,
      y: -92,
      w: 33,
      h: 32,
    },
    {
      keyName: '\'',
      value: 52,
      x: 536,
      y: -92,
      w: 33,
      h: 32,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 583,
      y: -92,
      w: 87,
      h: 32,
    },
    {
      keyName: 'Page\nUp',
      value: 75,
      x: 684,
      y: -92,
      w: 33,
      h: 32,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -138,
      w: 87,
      h: 32,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 104,
      y: -138,
      w: 33,
      h: 32,
    },
    {
      keyName: 'X',
      value: 27,
      x: 148,
      y: -138,
      w: 33,
      h: 32,
    },
    {
      keyName: 'C',
      value: 6,
      x: 194,
      y: -138,
      w: 33,
      h: 32,
    },
    {
      keyName: 'V',
      value: 25,
      x: 241,
      y: -138,
      w: 33,
      h: 32,
    },
    {
      keyName: 'B',
      value: 5,
      x: 285,
      y: -138,
      w: 33,
      h: 32,
    },
    {
      keyName: 'N',
      value: 17,
      x: 332,
      y: -138,
      w: 33,
      h: 32,
    },
    {
      keyName: 'M',
      value: 16,
      x: 378,
      y: -138,
      w: 33,
      h: 32,
    },
    {
      keyName: ',',
      value: 54,
      x: 422,
      y: -138,
      w: 33,
      h: 32,
    },
    {
      keyName: '.',
      value: 55,
      x: 469,
      y: -138,
      w: 33,
      h: 32,
    },
    {
      keyName: '/',
      value: 56,
      x: 515,
      y: -138,
      w: 33,
      h: 32,
    },
    {
      keyName: 'r_Shift',
      value: 229,
      x: 559,
      y: -138,
      w: 52,
      h: 32,
    },
    {
      keyName: '↑',
      value: 82,
      x: 639,
      y: -138,
      w: 33,
      h: 32,
    },
    {
      keyName: 'Page\nDown',
      value: 78,
      x: 684,
      y: -138,
      w: 33,
      h: 32,
    },
    {
      keyName: 'CTRL',
      value: 224,
      x: 0,
      y: -184,
      w: 47,
      h: 32,
    },
    {
      keyName: 'Win',
      value: 227,
      x: 55,
      y: -184,
      w: 47,
      h: 32,
    },
    {
      keyName: 'ALT',
      value: 226,
      x: 114,
      y: -184,
      w: 47,
      h: 32,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 169,
      y: -184,
      w: 277,
      h: 32,
    },
    {
      keyName: 'FN',
      value: 0x0a010000,
      x: 456,
      y: -184,
      w: 47,
      h: 32,
    },
    {
      keyName: 'r_Ctrl',
      value: 228,
      x: 512,
      y: -184,
      w: 47,
      h: 32,
    },
    {
      keyName: '←',
      value: 80,
      x: 593,
      y: -184,
      w: 33,
      h: 32,
    },
    {
      keyName: '↓',
      value: 81,
      x: 640,
      y: -184,
      w: 33,
      h: 32,
    },
    {
      keyName: '→',
      value: 79,
      x: 686,
      y: -184,
      w: 33,
      h: 32,
    },
  ],
}
