export const yc200_acr_pro_75 = {
  deltX: 137,
  deltY: 29,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 25,
      h: 24,
     },
    {
      keyName: 'F1',
      value: 58,
      x: 58,
      y: 0,
      w: 25,
      h: 24,
    },
    {
      keyName: 'F2',
      value: 59,
      x: 96,
      y: 0,
      w: 25,
      h: 24,
    },
    {
      keyName: 'F3',
      value: 60,
      x: 134,
      y: 0,
      w: 25,
      h: 24,
    },
    {
      keyName: 'F4',
      value: 61,
      x: 172,
      y: 0,
      w: 25,
      h: 24,
    },
    {
      keyName: 'F5',
      value: 62,
      x: 230,
      y: 0,
      w: 25,
      h: 24,
    },
    {
      keyName: 'F6',
      value: 63,
      x: 268,
      y: 0,
      w: 25,
      h: 24,
    },
    {
      keyName: 'F7',
      value: 64,
      x: 307,
      y: 0,
      w: 25,
      h: 24,
    },
    {
      keyName: 'F8',
      value: 65,
      x: 345,
      y: 0,
      w: 25,
      h: 24,
    },
    {
      keyName: 'F9',
      value: 66,
      x: 403,
      y: 0,
      w: 25,
      h: 24,
    },
    {
      keyName: 'F10',
      value: 67,
      x: 440,
      y: 0,
      w: 25,
      h: 24,
    },
    {
      keyName: 'F11',
      value: 68,
      x: 479,
      y: 0,
      w: 25,
      h: 24,
    },
    {
      keyName: 'F12',
      value: 69,
      x: 517,
      y: 0,
      w: 25,
      h: 24,
    },
    {
      keyName: 'Delete',
      value: 76,
      x: 573,
      y: 0,
      w: 25,
      h: 24,
    },
    {
      keyName: '`',
      value: 53,
      x: 0,
      y: -48,
      w: 25,
      h: 24,
    },
    {
      keyName: '1',
      value: 30,
      x: 38,
      y: -48,
      w: 25,
      h: 24,
    },
    {
      keyName: '2',
      value: 31,
      x: 76,
      y: -48,
      w: 25,
      h: 24,
    },
    {
      keyName: '3',
      value: 32,
      x: 114,
      y: -48,
      w: 25,
      h: 24,
    },
    {
      keyName: '4',
      value: 33,
      x: 153,
      y: -48,
      w: 25,
      h: 24,
    },
    {
      keyName: '5',
      value: 34,
      x: 191,
      y: -48,
      w: 25,
      h: 24,
    },
    {
      keyName: '6',
      value: 35,
      x: 229,
      y: -48,
      w: 25,
      h: 24,
    },
    {
      keyName: '7',
      value: 36,
      x: 268,
      y: -48,
      w: 25,
      h: 24,
    },
    {
      keyName: '8',
      value: 37,
      x: 306,
      y: -48,
      w: 25,
      h: 24,
    },
    {
      keyName: '9',
      value: 38,
      x: 344,
      y: -48,
      w: 25,
      h: 24,
    },
    {
      keyName: '0',
      value: 39,
      x: 382,
      y: -48,
      w: 25,
      h: 24,
    },
    {
      keyName: '-',
      value: 45,
      x: 420,
      y: -48,
      w: 25,
      h: 24,
    },
    {
      keyName: '=',
      value: 46,
      x: 458,
      y: -48,
      w: 25,
      h: 24,
    },
    {
      keyName: 'BackSpace',
      value: 42,
      x: 496,
      y: -48,
      w: 64,
      h: 24,
    },
    {
      keyName: 'Home',
      value: 74,
      x: 573,
      y: -48,
      w: 25,
      h: 24,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -85,
      w: 45,
      h: 24,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 57,
      y: -85,
      w: 25,
      h: 24,
    },
    {
      keyName: 'W',
      value: 26,
      x: 95,
      y: -85,
      w: 25,
      h: 24,
    },
    {
      keyName: 'E',
      value: 8,
      x: 133,
      y: -85,
      w: 25,
      h: 24,
    },
    {
      keyName: 'R',
      value: 21,
      x: 172,
      y: -85,
      w: 25,
      h: 24,
    },
    {
      keyName: 'T',
      value: 23,
      x: 210,
      y: -85,
      w: 25,
      h: 24,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 248,
      y: -85,
      w: 25,
      h: 24,
    },
    {
      keyName: 'U',
      value: 24,
      x: 287,
      y: -85,
      w: 25,
      h: 24,
    },
    {
      keyName: 'I',
      value: 12,
      x: 325,
      y: -85,
      w: 25,
      h: 24,
    },
    {
      keyName: 'O',
      value: 18,
      x: 363,
      y: -85,
      w: 25,
      h: 24,
    },
    {
      keyName: 'P',
      value: 19,
      x: 401,
      y: -85,
      w: 25,
      h: 24,
    },
    {
      keyName: '[',
      value: 47,
      x: 439,
      y: -85,
      w: 25,
      h: 24,
    },
    {
      keyName: ']',
      value: 48,
      x: 477,
      y: -85,
      w: 25,
      h: 24,
    },
    {
      keyName: '\\',
      value: 49,
      x: 515,
      y: -85,
      w: 45,
      h: 24,
    },
    {
      keyName: 'Page\nUp',
      value: 75,
      x: 573,
      y: -85,
      w: 25,
      h: 24,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -123,
      w: 54,
      h: 24,
    },
    {
      keyName: 'A',
      value: 4,
      x: 67,
      y: -123,
      w: 25,
      h: 24,
    },
    {
      keyName: 'S',
      value: 22,
      x: 105,
      y: -123,
      w: 25,
      h: 24,
    },
    {
      keyName: 'D',
      value: 7,
      x: 143,
      y: -123,
      w: 25,
      h: 24,
    },
    {
      keyName: 'F',
      value: 9,
      x: 182,
      y: -123,
      w: 25,
      h: 24,
    },
    {
      keyName: 'G',
      value: 10,
      x: 220,
      y: -123,
      w: 25,
      h: 24,
    },
    {
      keyName: 'H',
      value: 11,
      x: 258,
      y: -123,
      w: 25,
      h: 24,
    },
    {
      keyName: 'J',
      value: 13,
      x: 297,
      y: -123,
      w: 25,
      h: 24,
    },
    {
      keyName: 'K',
      value: 14,
      x: 335,
      y: -123,
      w: 25,
      h: 24,
    },
    {
      keyName: 'L',
      value: 15,
      x: 373,
      y: -123,
      w: 25,
      h: 24,
    },
    {
      keyName: ';',
      value: 51,
      x: 411,
      y: -123,
      w: 25,
      h: 24,
    },
    {
      keyName: '\'',
      value: 52,
      x: 449,
      y: -123,
      w: 25,
      h: 24,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 486,
      y: -123,
      w: 74,
      h: 24,
    },
    {
      keyName: 'Page\nDown',
      value: 78,
      x: 573,
      y: -123,
      w: 25,
      h: 24,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -161,
      w: 73,
      h: 24,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 86,
      y: -161,
      w: 25,
      h: 24,
    },
    {
      keyName: 'X',
      value: 27,
      x: 124,
      y: -161,
      w: 25,
      h: 24,
    },
    {
      keyName: 'C',
      value: 6,
      x: 162,
      y: -161,
      w: 25,
      h: 24,
    },
    {
      keyName: 'V',
      value: 25,
      x: 200,
      y: -161,
      w: 25,
      h: 24,
    },
    {
      keyName: 'B',
      value: 5,
      x: 239,
      y: -161,
      w: 25,
      h: 24,
    },
    {
      keyName: 'N',
      value: 17,
      x: 276,
      y: -161,
      w: 25,
      h: 24,
    },
    {
      keyName: 'M',
      value: 16,
      x: 315,
      y: -161,
      w: 25,
      h: 24,
    },
    {
      keyName: ',',
      value: 54,
      x: 353,
      y: -161,
      w: 25,
      h: 24,
    },
    {
      keyName: '.',
      value: 55,
      x: 391,
      y: -161,
      w: 25,
      h: 24,
    },
    {
      keyName: '/',
      value: 56,
      x: 429,
      y: -161,
      w: 25,
      h: 24,
    },
    {
      keyName: 'r_Shift',
      value: 229,
      x: 467,
      y: -161,
      w: 54,
      h: 24,
    },
    {
      keyName: '↑',
      value: 82,
      x: 535,
      y: -161,
      w: 25,
      h: 24,
    },
    {
      keyName: 'End',
      value: 77,
      x: 573,
      y: -161,
      w: 25,
      h: 24,
    },
    {
      keyName: 'Ctrl',
      value: 224,
      x: 0,
      y: -199,
      w: 35,
      h: 24,
    },
    {
      keyName: 'Win',
      value: 227,
      x: 48,
      y: -199,
      w: 35,
      h: 24,
    },
    {
      keyName: 'Alt',
      value: 226,
      x: 95,
      y: -199,
      w: 35,
      h: 24,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 143,
      y: -199,
      w: 226,
      h: 24,
    },
    {
      keyName: 'r_Alt',
      value: 230,
      x: 382,
      y: -199,
      w: 35,
      h: 24,
    },
    {
      keyName: 'FN',
      value: 0x0a010000,
      x: 430,
      y: -199,
      w: 35,
      h: 24,
    },
    {
      keyName: '←',
      value: 80,
      x: 497,
      y: -199,
      w: 25,
      h: 24,
    },
    {
      keyName: '↓',
      value: 81,
      x: 535,
      y: -199,
      w: 25,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
      h: 24,
    },
    {
      keyName: '→',
      value: 79,
      x: 573,
      y: -199,
      w: 25,
      h: 24,
    },
  ],
}
