export const yc200_l8 = {
  deltX: 14,
  deltY: 23,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 32,
      h: 31,
     },
    {
      keyName: 'F1',
      value: 58,
      x: 43,
      y: 0,
      w: 32,
      h: 31,
    },
    {
      keyName: 'F2',
      value: 59,
      x: 85,
      y: 0,
      w: 32,
      h: 31,
    },
    {
      keyName: 'F3',
      value: 60,
      x: 127,
      y: 0,
      w: 32,
      h: 31,
    },
    {
      keyName: 'F4',
      value: 61,
      x: 169,
      y: 0,
      w: 32,
      h: 31,
    },
    {
      keyName: 'F5',
      value: 62,
      x: 211,
      y: 0,
      w: 32,
      h: 31,
    },
    {
      keyName: 'F6',
      value: 63,
      x: 253,
      y: 0,
      w: 32,
      h: 31,
    },
    {
      keyName: 'F7',
      value: 64,
      x: 295,
      y: 0,
      w: 32,
      h: 31,
    },
    {
      keyName: 'F8',
      value: 65,
      x: 337,
      y: 0,
      w: 32,
      h: 31,
    },
    {
      keyName: 'F9',
      value: 66,
      x: 379,
      y: 0,
      w: 32,
      h: 31,
    },
    {
      keyName: 'F10',
      value: 67,
      x: 421,
      y: 0,
      w: 32,
      h: 31,
    },
    {
      keyName: 'F11',
      value: 68,
      x: 463,
      y: 0,
      w: 32,
      h: 31,
    },
    {
      keyName: 'F12',
      value: 69,
      x: 505,
      y: 0,
      w: 32,
      h: 31,
    },
    {
      keyName: 'Print\nScreen',
      value: 70,
      x: 548,
      y: 0,
      w: 32,
      h: 31,
    },
    {
      keyName: 'Insert',
      value: 73,
      x: 590,
      y: 0,
      w: 32,
      h: 31,
    },
    {
      keyName: 'Delete',
      value: 76,
      x: 632,
      y: 0,
      w: 32,
      h: 31,
    },
    {
      keyName: '`',
      value: 53,
      x: 0,
      y: -42,
      w: 32,
      h: 31,
    },
    {
      keyName: '1',
      value: 30,
      x: 43,
      y: -42,
      w: 32,
      h: 31,
    },
    {
      keyName: '2',
      value: 31,
      x: 85,
      y: -42,
      w: 32,
      h: 31,
    },
    {
      keyName: '3',
      value: 32,
      x: 127,
      y: -42,
      w: 32,
      h: 31,
    },
    {
      keyName: '4',
      value: 33,
      x: 169,
      y: -42,
      w: 32,
      h: 31,
    },
    {
      keyName: '5',
      value: 34,
      x: 211,
      y: -42,
      w: 32,
      h: 31,
    },
    {
      keyName: '6',
      value: 35,
      x: 253,
      y: -42,
      w: 32,
      h: 31,
    },
    {
      keyName: '7',
      value: 36,
      x: 295,
      y: -42,
      w: 32,
      h: 31,
    },
    {
      keyName: '8',
      value: 37,
      x: 337,
      y: -42,
      w: 32,
      h: 31,
    },
    {
      keyName: '9',
      value: 38,
      x: 379,
      y: -42,
      w: 32,
      h: 31,
    },
    {
      keyName: '0',
      value: 39,
      x: 421,
      y: -42,
      w: 32,
      h: 31,
    },
    {
      keyName: '-',
      value: 45,
      x: 463,
      y: -42,
      w: 32,
      h: 31,
    },
    {
      keyName: '=',
      value: 46,
      x: 505,
      y: -42,
      w: 32,
      h: 31,
    },
    {
      keyName: 'BackSpace',
      value: 42,
      x: 548,
      y: -42,
      w: 74,
      h: 31,
    },
    {
      keyName: 'home',
      value: 74,
      x: 632,
      y: -42,
      w: 32,
      h: 31,
    },
    {
      keyName: 'Num\nLock',
      value: 83,
      x: 685,
      y: -41,
      w: 32,
      h: 31,
    },
    {
      keyName: 'num_/',
      value: 84,
      x: 727,
      y: -41,
      w: 32,
      h: 31,
    },
    {
      keyName: 'num_*',
      value: 85,
      x: 769,
      y: -41,
      w: 32,
      h: 31,
    },
    {
      keyName: 'num_-',
      value: 86,
      x: 811,
      y: -41,
      w: 32,
      h: 31,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -84,
      w: 54,
      h: 31,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 64,
      y: -84,
      w: 32,
      h: 31,
    },
    {
      keyName: 'W',
      value: 26,
      x: 106,
      y: -84,
      w: 32,
      h: 31,
    },
    {
      keyName: 'E',
      value: 8,
      x: 148,
      y: -84,
      w: 32,
      h: 31,
    },
    {
      keyName: 'R',
      value: 21,
      x: 190,
      y: -84,
      w: 32,
      h: 31,
    },
    {
      keyName: 'T',
      value: 23,
      x: 232,
      y: -84,
      w: 32,
      h: 31,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 274,
      y: -84,
      w: 32,
      h: 31,
    },
    {
      keyName: 'U',
      value: 24,
      x: 316,
      y: -84,
      w: 32,
      h: 31,
    },
    {
      keyName: 'I',
      value: 12,
      x: 358,
      y: -84,
      w: 32,
      h: 31,
    },
    {
      keyName: 'O',
      value: 18,
      x: 400,
      y: -84,
      w: 32,
      h: 31,
    },
    {
      keyName: 'P',
      value: 19,
      x: 442,
      y: -84,
      w: 32,
      h: 31,
    },
    {
      keyName: '[',
      value: 47,
      x: 484,
      y: -84,
      w: 32,
      h: 31,
    },
    {
      keyName: ']',
      value: 48,
      x: 526,
      y: -84,
      w: 32,
      h: 31,
    },
    {
      keyName: '\\',
      value: 49,
      x: 569,
      y: -84,
      w: 53,
      h: 31,
    },
    {
      keyName: 'end',
      value: 77,
      x: 632,
      y: -84,
      w: 32,
      h: 31,
    },
    {
      keyName: 'num_7',
      value: 95,
      x: 685,
      y: -82,
      w: 32,
      h: 31,
    },
    {
      keyName: 'num_8',
      value: 96,
      x: 727,
      y: -82,
      w: 32,
      h: 31,
    },
    {
      keyName: 'num_9',
      value: 97,
      x: 769,
      y: -82,
      w: 32,
      h: 31,
    },
    {
      keyName: 'num_+',
      value: 87,
      x: 811,
      y: -82,
      w: 32,
      h: 72,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -126,
      w: 64,
      h: 31,
    },
    {
      keyName: 'A',
      value: 4,
      x: 74,
      y: -126,
      w: 32,
      h: 31,
    },
    {
      keyName: 'S',
      value: 22,
      x: 116,
      y: -126,
      w: 32,
      h: 31,
    },
    {
      keyName: 'D',
      value: 7,
      x: 158,
      y: -126,
      w: 32,
      h: 31,
    },
    {
      keyName: 'F',
      value: 9,
      x: 200,
      y: -126,
      w: 32,
      h: 31,
    },
    {
      keyName: 'G',
      value: 10,
      x: 242,
      y: -126,
      w: 32,
      h: 31,
    },
    {
      keyName: 'H',
      value: 11,
      x: 284,
      y: -126,
      w: 32,
      h: 31,
    },
    {
      keyName: 'J',
      value: 13,
      x: 326,
      y: -126,
      w: 32,
      h: 31,
    },
    {
      keyName: 'K',
      value: 14,
      x: 368,
      y: -126,
      w: 32,
      h: 31,
    },
    {
      keyName: 'L',
      value: 15,
      x: 410,
      y: -126,
      w: 32,
      h: 31,
    },
    {
      keyName: ';',
      value: 51,
      x: 452,
      y: -126,
      w: 32,
      h: 31,
    },
    {
      keyName: '\'',
      value: 52,
      x: 494,
      y: -126,
      w: 32,
      h: 31,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 536,
      y: -126,
      w: 85,
      h: 31,
    },
    {
      keyName: 'Page\nUp',
      value: 75,
      x: 632,
      y: -126,
      w: 32,
      h: 31,
    },
    {
      keyName: 'num_4',
      value: 92,
      x: 685,
      y: -126,
      w: 32,
      h: 31,
    },
    {
      keyName: 'num_5',
      value: 93,
      x: 727,
      y: -126,
      w: 32,
      h: 31,
    },
    {
      keyName: 'num_6',
      value: 94,
      x: 769,
      y: -126,
      w: 32,
      h: 31,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -168,
      w: 85,
      h: 31,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 96,
      y: -168,
      w: 32,
      h: 31,
    },
    {
      keyName: 'X',
      value: 27,
      x: 138,
      y: -168,
      w: 32,
      h: 31,
    },
    {
      keyName: 'C',
      value: 6,
      x: 180,
      y: -168,
      w: 32,
      h: 31,
    },
    {
      keyName: 'V',
      value: 25,
      x: 222,
      y: -168,
      w: 32,
      h: 31,
    },
    {
      keyName: 'B',
      value: 5,
      x: 264,
      y: -168,
      w: 32,
      h: 31,
    },
    {
      keyName: 'N',
      value: 17,
      x: 306,
      y: -168,
      w: 32,
      h: 31,
    },
    {
      keyName: 'M',
      value: 16,
      x: 348,
      y: -168,
      w: 32,
      h: 31,
    },
    {
      keyName: ',',
      value: 54,
      x: 390,
      y: -168,
      w: 32,
      h: 31,
    },
    {
      keyName: '.',
      value: 55,
      x: 432,
      y: -168,
      w: 32,
      h: 31,
    },
    {
      keyName: '/',
      value: 56,
      x: 474,
      y: -168,
      w: 32,
      h: 31,
    },
    {
      keyName: 'r_Shift',
      value: 229,
      x: 516,
      y: -168,
      w: 64,
      h: 31,
    },
    {
      keyName: '↑',
      value: 82,
      x: 589,
      y: -168,
      w: 32,
      h: 31,
    },
    {
      keyName: 'Page\nDown',
      value: 78,
      x: 632,
      y: -168,
      w: 32,
      h: 31,
    },
    {
      keyName: 'num_1',
      value: 89,
      x: 685,
      y: -168,
      w: 32,
      h: 31,
    },
    {
      keyName: 'num_2',
      value: 90,
      x: 727,
      y: -168,
      w: 32,
      h: 31,
    },
    {
      keyName: 'num_3',
      value: 91,
      x: 769,
      y: -168,
      w: 32,
      h: 31,
    },
    {
      keyName: 'num_Enter',
      value: 88,
      x: 811,
      y: -168,
      w: 32,
      h: 72,
    },
    {
      keyName: 'Ctrl',
      value: 224,
      x: 0,
      y: -210,
      w: 32,
      h: 31,
    },
    {
      keyName: 'fn',
      value: 0x0a010000,
      x: 43,
      y: -210,
      w: 32,
      h: 31,
    },
    {
      keyName: 'Win',
      value: 227,
      x: 85,
      y: -210,
      w: 32,
      h: 31,
    },
    {
      keyName: 'Alt',
      value: 226,
      x: 127,
      y: -210,
      w: 32,
      h: 31,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 170,
      y: -210,
      w: 241,
      h: 31,
    },
    {
      keyName: 'r_Alt',
      value: 230,
      x: 421,
      y: -210,
      w: 32,
      h: 31,
    },
    {
      keyName: '(Application)',
      value: 101,
      x: 463,
      y: -210,
      w: 32,
      h: 31,
    },
    {
      keyName: 'r_Ctrl',
      value: 228,
      x: 505,
      y: -210,
      w: 32,
      h: 31,
    },
    {
      keyName: '←',
      value: 80,
      x: 547,
      y: -210,
      w: 32,
      h: 31,
    },
    {
      keyName: '↓',
      value: 81,
      x: 589,
      y: -210,
      w: 32,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
      h: 31,
    },
    {
      keyName: '→',
      value: 79,
      x: 632,
      y: -210,
      w: 32,
      h: 31,
    },
    {
      keyName: 'num_0',
      value: 98,
      x: 685,
      y: -210,
      w: 74,
      h: 31,
    },
    {
      keyName: 'num_.',
      value: 99,
      x: 769,
      y: -210,
      w: 32,
      h: 31,
    },
  ],
}
