export const yc200_sk66 = {
  deltX: 88,
  deltY: 41,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 30,
      h: 31,
     },
    {
      keyName: '1',
      value: 30,
      x: 48,
      y: 0,
      w: 30,
      h: 31,
    },
    {
      keyName: '2',
      value: 31,
      x: 95,
      y: 0,
      w: 30,
      h: 31,
    },
    {
      keyName: '3',
      value: 32,
      x: 143,
      y: 0,
      w: 30,
      h: 31,
    },
    {
      keyName: '4',
      value: 33,
      x: 190,
      y: 0,
      w: 30,
      h: 31,
    },
    {
      keyName: '5',
      value: 34,
      x: 238,
      y: 0,
      w: 30,
      h: 31,
    },
    {
      keyName: '6',
      value: 35,
      x: 285,
      y: 0,
      w: 30,
      h: 31,
    },
    {
      keyName: '7',
      value: 36,
      x: 332,
      y: 0,
      w: 30,
      h: 31,
    },
    {
      keyName: '8',
      value: 37,
      x: 380,
      y: 0,
      w: 30,
      h: 31,
    },
    {
      keyName: '9',
      value: 38,
      x: 427,
      y: 0,
      w: 30,
      h: 31,
    },
    {
      keyName: '0',
      value: 39,
      x: 475,
      y: 0,
      w: 30,
      h: 31,
    },
    {
      keyName: '-',
      value: 45,
      x: 522,
      y: 0,
      w: 30,
      h: 31,
    },
    {
      keyName: '=', 
      value: 46,
      x: 570,
      y: 0,
      w: 30,
      h: 31,
    },
    {
      keyName: 'Backspace',
      value: 42,
      x: 618,
      y: 0,
      w: 76,
      h: 31,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -47,
      w: 54,
      h: 31,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 72,
      y: -47,
      w: 30,
      h: 31,
    },
    {
      keyName: 'W',
      value: 26,
      x: 119,
      y: -47,
      w: 30,
      h: 31,
    },
    {
      keyName: 'E',
      value: 8,
      x: 167,
      y: -47,
      w: 30,
      h: 31,
    },
    {
      keyName: 'R',
      value: 21,
      x: 214,
      y: -47,
      w: 30,
      h: 31,
    },
    {
      keyName: 'T',
      value: 23,
      x: 262,
      y: -47,
      w: 30,
      h: 31,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 309,
      y: -47,
      w: 30,
      h: 31,
    },
    {
      keyName: 'U',
      value: 24,
      x: 356,
      y: -47,
      w: 30,
      h: 31,
    },
    {
      keyName: 'I',
      value: 12,
      x: 404,
      y: -47,
      w: 30,
      h: 31,
    },
    {
      keyName: 'O',
      value: 18,
      x: 451,
      y: -47,
      w: 30,
      h: 31,
    },
    {
      keyName: 'P',
      value: 19,
      x: 499,
      y: -47,
      w: 30,
      h: 31,
    },
    {
      keyName: '[',
      value: 47,
      x: 546,
      y: -47,
      w: 30,
      h: 31,
    },
    {
      keyName: ']',
      value: 48,
      x: 594,
      y: -47,
      w: 30,
      h: 31,
    },
    {
      keyName: '\\',
      value: 49,
      x: 642,
      y: -47,
      w: 53,
      h: 31,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -95,
      w: 65,
      h: 31,
    },
    {
      keyName: 'A',
      value: 4,
      x: 83,
      y: -95,
      w: 30,
      h: 31,
    },
    {
      keyName: 'S',
      value: 22,
      x: 130,
      y: -95,
      w: 30,
      h: 31,
    },
    {
      keyName: 'D',
      value: 7,
      x: 178,
      y: -95,
      w: 30,
      h: 31,
    },
    {
      keyName: 'F',
      value: 9,
      x: 225,
      y: -95,
      w: 30,
      h: 31,
    },
    {
      keyName: 'G',
      value: 10,
      x: 273,
      y: -95,
      w: 30,
      h: 31,
    },
    {
      keyName: 'H',
      value: 11,
      x: 320,
      y: -95,
      w: 30,
      h: 31,
    },
    {
      keyName: 'J',
      value: 13,
      x: 367,
      y: -95,
      w: 30,
      h: 31,
    },
    {
      keyName: 'K',
      value: 14,
      x: 415,
      y: -95,
      w: 30,
      h: 31,
    },
    {
      keyName: 'L',
      value: 15,
      x: 462,
      y: -95,
      w: 30,
      h: 31,
    },
    {
      keyName: ';',
      value: 51,
      x: 510,
      y: -95,
      w: 30,
      h: 31,
    },
    {
      keyName: '\'',
      value: 52,
      x: 557,
      y: -95,
      w: 30,
      h: 31,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 605,
      y: -95,
      w: 90,
      h: 31,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -142,
      w: 90,
      h: 31,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 108,
      y: -142,
      w: 30,
      h: 31,
    },
    {
      keyName: 'X',
      value: 27,
      x: 155,
      y: -142,
      w: 30,
      h: 31,
    },
    {
      keyName: 'C',
      value: 6,
      x: 203,
      y: -142,
      w: 30,
      h: 31,
    },
    {
      keyName: 'V',
      value: 25,
      x: 250,
      y: -142,
      w: 30,
      h: 31,
    },
    {
      keyName: 'B',
      value: 5,
      x: 299,
      y: -142,
      w: 30,
      h: 31,
    },
    {
      keyName: 'N',
      value: 17,
      x: 346,
      y: -142,
      w: 30,
      h: 31,
    },
    {
      keyName: 'M',
      value: 16,
      x: 393,
      y: -142,
      w: 30,
      h: 31,
    },
    {
      keyName: ',',
      value: 54,
      x: 441,
      y: -142,
      w: 30,
      h: 31,
    },
    {
      keyName: '.',
      value: 55,
      x: 488,
      y: -142,
      w: 30,
      h: 31,
    },
    {
      keyName: '↑',
      value: 82,
      x: 535,
      y: -142,
      w: 30,
      h: 31,
    },
    {
      keyName: 'r_Shift',
      value: 229,
      x: 583,
      y: -142,
      w: 112,
      h: 31,
    },
    {
      keyName: 'CTRL',
      value: 224,
      x: 0,
      y: -190,
      w: 42,
      h: 31,
    },
    {
      keyName: 'Win',
      value: 227,
      x: 59,
      y: -190,
      w: 42,
      h: 31,
    },
    {
      keyName: 'ALT',
      value: 226,
      x: 119,
      y: -190,
      w: 42,
      h: 31,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 178,
      y: -190,
      w: 278,
      h: 31,
    },
    {
      keyName: '←',
      value: 80,
      x: 476,
      y: -190,
      w: 42,
      h: 31,
    },
    {
      keyName: '↓',
      value: 81,
      x: 535,
      y: -190,
      w: 42,
      h: 31,
    },
    {
      keyName: '→',
      value: 79,
      x: 595,
      y: -190,
      w: 42,
      h: 31,
    },
    {
      keyName: 'FN',
      value: 0x0a010000,
      x: 653,
      y: -190,
      w: 42,
      h: 31,
    },
  ],
}
