export const yc200_l10 = {
  deltX: 61,
  deltY: 31,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 37,
      h: 36,
    },
    {
      keyName: '1',
      value: 30,
      x: 51,
      y: -0,
      w: 37,
      h: 36,
    },
    {
      keyName: '2',
      value: 31,
      x: 102,
      y: -0,
      w: 37,
      h: 36,
    },
    {
      keyName: '3',
      value: 32,
      x: 153,
      y: -0,
      w: 37,
      h: 36,
    },
    {
      keyName: '4',
      value: 33,
      x: 204,
      y: -0,
      w: 37,
      h: 36,
    },
    {
      keyName: '5',
      value: 34,
      x: 255,
      y: -0,
      w: 37,
      h: 36,
    },
    {
      keyName: '6',
      value: 35,
      x: 306,
      y: -0,
      w: 37,
      h: 36,
    },
    {
      keyName: '7',
      value: 36,
      x: 356,
      y: -0,
      w: 37,
      h: 36,
    },
    {
      keyName: '8',
      value: 37,
      x: 407,
      y: -0,
      w: 37,
      h: 36,
    },
    {
      keyName: '9',
      value: 38,
      x: 458,
      y: -0,
      w: 37,
      h: 36,
    },
    {
      keyName: '0',
      value: 39,
      x: 509,
      y: -0,
      w: 37,
      h: 36,
    },
    {
      keyName: '-',
      value: 45,
      x: 559,
      y: -0,
      w: 37,
      h: 36,
    },
    {
      keyName: '=',
      value: 46,
      x: 610,
      y: -0,
      w: 37,
      h: 36,
    },
    {
      keyName: 'BackSpace',
      value: 42,
      x: 661,
      y: -0,
      w: 87,
      h: 36,
    },
    {
      keyName: 'Insert',
      value: 73,
      x: 763,
      y: -0,
      w: 37,
      h: 36,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -50,
      w: 63,
      h: 36,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 77,
      y: -50,
      w: 37,
      h: 36,
    },
    {
      keyName: 'W',
      value: 26,
      x: 128,
      y: -50,
      w: 37,
      h: 36,
    },
    {
      keyName: 'E',
      value: 8,
      x: 179,
      y: -50,
      w: 37,
      h: 36,
    },
    {
      keyName: 'R',
      value: 21,
      x: 230,
      y: -50,
      w: 37,
      h: 36,
    },
    {
      keyName: 'T',
      value: 23,
      x: 281,
      y: -50,
      w: 37,
      h: 36,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 332,
      y: -50,
      w: 37,
      h: 36,
    },
    {
      keyName: 'U',
      value: 24,
      x: 382,
      y: -50,
      w: 37,
      h: 36,
    },
    {
      keyName: 'I',
      value: 12,
      x: 433,
      y: -50,
      w: 37,
      h: 36,
    },
    {
      keyName: 'O',
      value: 18,
      x: 484,
      y: -50,
      w: 37,
      h: 36,
    },
    {
      keyName: 'P',
      value: 19,
      x: 535,
      y: -50,
      w: 37,
      h: 36,
    },
    {
      keyName: '[',
      value: 47,
      x: 585,
      y: -50,
      w: 37,
      h: 36,
    },
    {
      keyName: ']',
      value: 48,
      x: 636,
      y: -50,
      w: 37,
      h: 36,
    },
    {
      keyName: '\\',
      value: 49,
      x: 686,
      y: -50,
      w: 62,
      h: 36,
    },
    {
      keyName: 'Delete',
      value: 76,
      x: 763,
      y: -50,
      w: 37,
      h: 36,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -99,
      w: 75,
      h: 36,
    },
    {
      keyName: 'A',
      value: 4,
      x: 89,
      y: -99,
      w: 37,
      h: 36,
    },
    {
      keyName: 'S',
      value: 22,
      x: 140,
      y: -99,
      w: 37,
      h: 36,
    },
    {
      keyName: 'D',
      value: 7,
      x: 191,
      y: -99,
      w: 37,
      h: 36,
    },
    {
      keyName: 'F',
      value: 9,
      x: 242,
      y: -99,
      w: 37,
      h: 36,
    },
    {
      keyName: 'G',
      value: 10,
      x: 293,
      y: -99,
      w: 37,
      h: 36,
    },
    {
      keyName: 'H',
      value: 11,
      x: 344,
      y: -99,
      w: 37,
      h: 36,
    },
    {
      keyName: 'J',
      value: 13,
      x: 394,
      y: -99,
      w: 37,
      h: 36,
    },
    {
      keyName: 'K',
      value: 14,
      x: 445,
      y: -99,
      w: 37,
      h: 36,
    },
    {
      keyName: 'L',
      value: 15,
      x: 496,
      y: -99,
      w: 37,
      h: 36,
    },
    {
      keyName: ';',
      value: 51,
      x: 547,
      y: -99,
      w: 37,
      h: 36,
    },
    {
      keyName: '\'',
      value: 52,
      x: 597,
      y: -99,
      w: 37,
      h: 36,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 648,
      y: -99,
      w: 100,
      h: 36,
    },
    {
      keyName: 'Page\nUp',
      value: 75,
      x: 763,
      y: -99,
      w: 37,
      h: 36,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -149,
      w: 102,
      h: 36,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 116,
      y: -149,
      w: 37,
      h: 36,
    },
    {
      keyName: 'X',
      value: 27,
      x: 167,
      y: -149,
      w: 37,
      h: 36,
    },
    {
      keyName: 'C',
      value: 6,
      x: 218,
      y: -149,
      w: 37,
      h: 36,
    },
    {
      keyName: 'V',
      value: 25,
      x: 269,
      y: -149,
      w: 37,
      h: 36,
    },
    {
      keyName: 'B',
      value: 5,
      x: 320,
      y: -149,
      w: 37,
      h: 36,
    },
    {
      keyName: 'N',
      value: 17,
      x: 371,
      y: -149,
      w: 37,
      h: 36,
    },
    {
      keyName: 'M',
      value: 16,
      x: 422,
      y: -149,
      w: 37,
      h: 36,
    },
    {
      keyName: ',',
      value: 54,
      x: 472,
      y: -149,
      w: 37,
      h: 36,
    },
    {
      keyName: '.',
      value: 55,
      x: 523,
      y: -149,
      w: 37,
      h: 36,
    },
    {
      keyName: '/',
      value: 56,
      x: 574,
      y: -149,
      w: 37,
      h: 36,
    },
    {
      keyName: 'r_Shift',
      value: 229,
      x: 624,
      y: -149,
      w: 74,
      h: 36,
    },
    {
      keyName: '↑',
      value: 82,
      x: 712,
      y: -149,
      w: 37,
      h: 36,
    },
    {
      keyName: 'Page\nDown',
      value: 78,
      x: 763,
      y: -149,
      w: 37,
      h: 36,
    },
    {
      keyName: 'Ctrl',
      value: 224,
      x: 0,
      y: -199,
      w: 37,
      h: 36,
    },
    {
      keyName: 'Win',
      value: 227,
      x: 52,
      y: -199,
      w: 37,
      h: 36,
    },
    {
      keyName: 'fn',
      value: 0x0a010000,
      x: 103,
      y: -199,
      w: 37,
      h: 36,
    },
    {
      keyName: 'Alt',
      value: 226,
      x: 154,
      y: -199,
      w: 37,
      h: 36,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 205,
      y: -199,
      w: 291,
      h: 36,
    },
    {
      keyName: 'r_Alt',
      value: 230,
      x: 510,
      y: -199,
      w: 37,
      h: 36,
    },
    {
      keyName: '(Application)',
      value: 101,
      x: 561,
      y: -199,
      w: 37,
      h: 36,
    },
    {
      keyName: 'r_Ctrl',
      value: 228,
      x: 612,
      y: -199,
      w: 37,
      h: 36,
    },
    {
      keyName: '←',
      value: 80,
      x: 662,
      y: -199,
      w: 37,
      h: 36,
    },
    {
      keyName: '↓',
      value: 81,
      x: 713,
      y: -199,
      w: 37,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
      h: 36,
    },
    {
      keyName: '→',
      value: 79,
      x: 763,
      y: -199,
      w: 37,
      h: 36,
    },
  ],
}
