export const yc300_acr68pile = {
  deltX: 70,
  deltY: 28,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 35,
      h: 36,
     },
    {
      keyName: '1',
      value: 30,
      x: 46,
      y: 0,
      w: 35,
      h: 36,
    },
    {
      keyName: '2',
      value: 31,
      x: 94,
      y: 0,
      w: 35,
      h: 36,
    },
    {
      keyName: '3',
      value: 32,
      x: 140,
      y: 0,
      w: 35,
      h: 36,
    },
    {
      keyName: '4',
      value: 33,
      x: 186,
      y: 0,
      w: 35,
      h: 36,
    },
    {
      keyName: '5',
      value: 34,
      x: 232,
      y: 0,
      w: 35,
      h: 36,
    },
    {
      keyName: '6',
      value: 35,
      x: 280,
      y: 0,
      w: 35,
      h: 36,
    },
    {
      keyName: '7',
      value: 36,
      x: 326,
      y: 0,
      w: 35,
      h: 36,
    },
    {
      keyName: '8',
      value: 37,
      x: 372,
      y: 0,
      w: 35,
      h: 36,
    },
    {
      keyName: '9',
      value: 38,
      x: 418,
      y: 0,
      w: 35,
      h: 36,
    },
    {
      keyName: '0',
      value: 39,
      x: 464,
      y: 0,
      w: 35,
      h: 36,
    },
    {
      keyName: '-',
      value: 45,
      x: 510,
      y: 0,
      w: 35,
      h: 36,
    },
    {
      keyName: '=',
      value: 46,
      x: 558,
      y: 0,
      w: 35,
      h: 36,
    },
    {
      keyName: 'Backspace',
      value: 42,
      x: 604,
      y: 0,
      w: 84,
      h: 36,
    },
    {
      keyName: '`',
      value: 53,
      x: 699,
      y: 0,
      w: 35,
      h: 36,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -48,
      w: 58,
      h: 36,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 70,
      y: -48,
      w: 35,
      h: 36,
    },
    {
      keyName: 'W',
      value: 26,
      x: 117,
      y: -48,
      w: 35,
      h: 36,
    },
    {
      keyName: 'E',
      value: 8,
      x: 164,
      y: -48,
      w: 35,
      h: 36,
    },
    {
      keyName: 'R',
      value: 21,
      x: 210,
      y: -48,
      w: 35,
      h: 36,
    },
    {
      keyName: 'T',
      value: 23,
      x: 256,
      y: -48,
      w: 35,
      h: 36,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 303,
      y: -48,
      w: 35,
      h: 36,
    },
    {
      keyName: 'U',
      value: 24,
      x: 349,
      y: -48,
      w: 35,
      h: 36,
    },
    {
      keyName: 'I',
      value: 12,
      x: 395,
      y: -48,
      w: 35,
      h: 36,
    },
    {
      keyName: 'O',
      value: 18,
      x: 442,
      y: -48,
      w: 35,
      h: 36,
    },
    {
      keyName: 'P',
      value: 19,
      x: 488,
      y: -48,
      w: 35,
      h: 36,
    },
    {
      keyName: '[',
      value: 47,
      x: 534,
      y: -48,
      w: 35,
      h: 36,
    },
    {
      keyName: ']',
      value: 48,
      x: 581,
      y: -48,
      w: 35,
      h: 36,
    },
    {
      keyName: '\\',
      value: 49,
      x: 628,
      y: -48,
      w: 60,
      h: 36,
    },
    {
      keyName: 'Delete',
      value: 76,
      x: 699,
      y: -48,
      w: 35,
      h: 36,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -95,
      w: 70,
      h: 36,
    },
    {
      keyName: 'A',
      value: 4,
      x: 81,
      y: -95,
      w: 35,
      h: 36,
    },
    {
      keyName: 'S',
      value: 22,
      x: 128,
      y: -95,
      w: 35,
      h: 36,
    },
    {
      keyName: 'D',
      value: 7,
      x: 175,
      y: -95,
      w: 35,
      h: 36,
    },
    {
      keyName: 'F',
      value: 9,
      x: 221,
      y: -95,
      w: 35,
      h: 36,
    },
    {
      keyName: 'G',
      value: 10,
      x: 267,
      y: -95,
      w: 35,
      h: 36,
    },
    {
      keyName: 'H',
      value: 11,
      x: 314,
      y: -95,
      w: 35,
      h: 36,
    },
    {
      keyName: 'J',
      value: 13,
      x: 360,
      y: -95,
      w: 35,
      h: 36,
    },
    {
      keyName: 'K',
      value: 14,
      x: 406,
      y: -95,
      w: 35,
      h: 36,
    },
    {
      keyName: 'L',
      value: 15,
      x: 453,
      y: -95,
      w: 35,
      h: 36,
    },
    {
      keyName: ';',
      value: 51,
      x: 499,
      y: -95,
      w: 35,
      h: 36,
    },
    {
      keyName: '\'',
      value: 52,
      x: 545,
      y: -95,
      w: 35,
      h: 36,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 593,
      y: -95,
      w: 95,
      h: 36,
    },
    {
      keyName: 'Page\nUp',
      value: 75,
      x: 699,
      y: -95,
      w: 35,
      h: 36,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -141,
      w: 94,
      h: 36,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 105,
      y: -141,
      w: 35,
      h: 36,
    },
    {
      keyName: 'X',
      value: 27,
      x: 152,
      y: -141,
      w: 35,
      h: 36,
    },
    {
      keyName: 'C',
      value: 6,
      x: 199,
      y: -141,
      w: 35,
      h: 36,
    },
    {
      keyName: 'V',
      value: 25,
      x: 245,
      y: -141,
      w: 35,
      h: 36,
    },
    {
      keyName: 'B',
      value: 5,
      x: 291,
      y: -141,
      w: 35,
      h: 36,
    },
    {
      keyName: 'N',
      value: 17,
      x: 338,
      y: -141,
      w: 35,
      h: 36,
    },
    {
      keyName: 'M',
      value: 16,
      x: 384,
      y: -141,
      w: 35,
      h: 36,
    },
    {
      keyName: ',',
      value: 54,
      x: 430,
      y: -141,
      w: 35,
      h: 36,
    },
    {
      keyName: '.',
      value: 55,
      x: 477,
      y: -141,
      w: 35,
      h: 36,
    },
    {
      keyName: '/',
      value: 56,
      x: 523,
      y: -141,
      w: 35,
      h: 36,
    },
    {
      keyName: 'r_Shift',
      value: 229,
      x: 569,
      y: -141,
      w: 71,
      h: 36,
    },
    {
      keyName: '↑',
      value: 82,
      x: 651,
      y: -141,
      w: 35,
      h: 36,
    },
    {
      keyName: 'Page\nDown',
      value: 78,
      x: 699,
      y: -141,
      w: 35,
      h: 36,
    },
    {
      keyName: 'Ctrl',
      value: 224,
      x: 0,
      y: -188,
      w: 46,
      h: 36,
    },
    {
      keyName: 'Win',
      value: 227,
      x: 58,
      y: -188,
      w: 46,
      h: 36,
    },
    {
      keyName: 'Alt',
      value: 226,
      x: 117,
      y: -188,
      w: 46,
      h: 36,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 175,
      y: -188,
      w: 278,
      h: 36,
    },
    {
      keyName: 'r_Alt',
      value: 230,
      x: 465,
      y: -188,
      w: 35,
      h: 36,
    },
    {
      keyName: 'FN',
      value: 0x0a010000,
      x: 511,
      y: -188,
      w: 35,
      h: 36,
    },
    {
      keyName: 'r_Ctrl',
      value: 228,
      x: 557,
      y: -188,
      w: 35,
      h: 36,
    },
    {
      keyName: '←',
      value: 80,
      x: 604,
      y: -188,
      w: 35,
      h: 36,
    },
    {
      keyName: '↓',
      value: 81,
      x: 651,
      y: -188,
      w: 35,
      h: 36,
    },
    {
      keyName: '→',
      value: 79,
      x: 699,
      y: -188,
      w: 35,
      h: 36,
    },
  ],
}
