export const yc300_k1pro = {
  deltX: 11,
  deltY: 9,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 32,
      h: 36,
     },
    {
      keyName: 'F1',
      value: 58,
      x: 45,
      y: 0,
      w: 32,
      h: 36,
    },
    {
      keyName: 'F2',
      value: 59,
      x: 91,
      y: 0,
      w: 32,
      h: 36,
    },
    {
      keyName: 'F3',
      value: 60,
      x: 137,
      y: 0,
      w: 32,
      h: 36,
    },
    {
      keyName: 'F4',
      value: 61,
      x: 182,
      y: 0,
      w: 32,
      h: 36,
    },
    {
      keyName: 'F5',
      value: 62,
      x: 228,
      y: 0,
      w: 32,
      h: 36,
    },
    {
      keyName: 'F6',
      value: 63,
      x: 273,
      y: 0,
      w: 32,
      h: 36,
    },
    {
      keyName: 'F7',
      value: 64,
      x: 319,
      y: 0,
      w: 32,
      h: 36,
    },
    {
      keyName: 'F8',
      value: 65,
      x: 364,
      y: 0,
      w: 32,
      h: 36,
    },
    {
      keyName: 'F9',
      value: 66,
      x: 409,
      y: 0,
      w: 32,
      h: 36,
    },
    {
      keyName: 'F10',
      value: 67,
      x: 455,
      y: 0,
      w: 32,
      h: 36,
    },
    {
      keyName: 'F11',
      value: 68,
      x: 500,
      y: 0,
      w: 32,
      h: 36,
    },
    {
      keyName: 'F12',
      value: 69,
      x: 545,
      y: 0,
      w: 32,
      h: 36,
    },
    {
      keyName: 'Print\nScreen',
      value: 70,
      x: 591,
      y: 0,
      w: 32,
      h: 36,
    },
    {
      keyName: 'Delete',
      value: 76,
      x: 637,
      y: 0,
      w: 32,
      h: 36,
    },
    {
      keyName: 'Insert',
      value: 73,
      x: 681,
      y: 0,
      w: 32,
      h: 36,
    },
    {
      keyName: 'Home',
      value: 74,
      x: 725,
      y: 0,
      w: 32,
      h: 36,
    },
    {
      keyName: 'Page\nUp',
      value: 75,
      x: 770,
      y: 0,
      w: 32,
      h: 36,
    },
    {
      keyName: 'Page\nDown',
      value: 78,
      x: 816,
      y: 0,
      w: 32,
      h: 36,
    },
    {
      keyName: '`',
      value: 53,
      x: 0,
      y: -46,
      w: 32,
      h: 36,
    },
    {
      keyName: '1',
      value: 30,
      x: 45,
      y: -46,
      w: 32,
      h: 36,
    },
    {
      keyName: '2',
      value: 31,
      x: 91,
      y: -46,
      w: 32,
      h: 36,
    },
    {
      keyName: '3',
      value: 32,
      x: 137,
      y: -46,
      w: 32,
      h: 36,
    },
    {
      keyName: '4',
      value: 33,
      x: 182,
      y: -46,
      w: 32,
      h: 36,
    },
    {
      keyName: '5',
      value: 34,
      x: 228,
      y: -46,
      w: 32,
      h: 36,
    },
    {
      keyName: '6',
      value: 35,
      x: 273,
      y: -46,
      w: 32,
      h: 36,
    },
    {
      keyName: '7',
      value: 36,
      x: 319,
      y: -46,
      w: 32,
      h: 36,
    },
    {
      keyName: '8',
      value: 37,
      x: 364,
      y: -46,
      w: 32,
      h: 36,
    },
    {
      keyName: '9',
      value: 38,
      x: 409,
      y: -46,
      w: 32,
      h: 36,
    },
    {
      keyName: '0',
      value: 39,
      x: 455,
      y: -46,
      w: 32,
      h: 36,
    },
    {
      keyName: '-',
      value: 45,
      x: 500,
      y: -46,
      w: 32,
      h: 36,
    },
    {
      keyName: '=',
      value: 46,
      x: 545,
      y: -46,
      w: 32,
      h: 36,
    },
    {
      keyName: 'BackSpace',
      value: 42,
      x: 591,
      y: -46,
      w: 78,
      h: 36,
    },
    {
      keyName: 'Num\nLock',
      value: 83,
      x: 681,
      y: -46,
      w: 32,
      h: 36,
    },
    {
      keyName: 'num_/',
      value: 84,
      x: 725,
      y: -46,
      w: 32,
      h: 36,
    },
    {
      keyName: 'num_*',
      value: 85,
      x: 770,
      y: -46,
      w: 32,
      h: 36,
    },
    {
      keyName: 'num_-',
      value: 86,
      x: 816,
      y: -46,
      w: 32,
      h: 36,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -92,
      w: 54,
      h: 36,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 68,
      y: -92,
      w: 32,
      h: 36,
    },
    {
      keyName: 'W',
      value: 26,
      x: 114,
      y: -92,
      w: 32,
      h: 36,
    },
    {
      keyName: 'E',
      value: 8,
      x: 160,
      y: -92,
      w: 32,
      h: 36,
    },
    {
      keyName: 'R',
      value: 21,
      x: 205,
      y: -92,
      w: 32,
      h: 36,
    },
    {
      keyName: 'T',
      value: 23,
      x: 251,
      y: -92,
      w: 32,
      h: 36,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 296,
      y: -92,
      w: 32,
      h: 36,
    },
    {
      keyName: 'U',
      value: 24,
      x: 342,
      y: -92,
      w: 32,
      h: 36,
    },
    {
      keyName: 'I',
      value: 12,
      x: 387,
      y: -92,
      w: 32,
      h: 36,
    },
    {
      keyName: 'O',
      value: 18,
      x: 432,
      y: -92,
      w: 32,
      h: 36,
    },
    {
      keyName: 'P',
      value: 19,
      x: 478,
      y: -92,
      w: 32,
      h: 36,
    },
    {
      keyName: '[',
      value: 47,
      x: 523,
      y: -92,
      w: 32,
      h: 36,
    },
    {
      keyName: ']',
      value: 48,
      x: 568,
      y: -92,
      w: 32,
      h: 36,
    },
    {
      keyName: '\\',
      value: 49,
      x: 614,
      y: -92,
      w: 55,
      h: 36,
    },
    {
      keyName: 'num_7',
      value: 95,
      x: 681,
      y: -92,
      w: 32,
      h: 36,
    },
    {
      keyName: 'num_8',
      value: 96,
      x: 725,
      y: -92,
      w: 32,
      h: 36,
    },
    {
      keyName: 'num_9',
      value: 97,
      x: 770,
      y: -92,
      w: 32,
      h: 36,
    },
    {
      keyName: 'num_+',
      value: 87,
      x: 816,
      y: -92,
      w: 32,
      h: 81,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -137,
      w: 65,
      h: 36,
    },
    {
      keyName: 'A',
      value: 4,
      x: 80,
      y: -137,
      w: 32,
      h: 36,
    },
    {
      keyName: 'S',
      value: 22,
      x: 126,
      y: -137,
      w: 32,
      h: 36,
    },
    {
      keyName: 'D',
      value: 7,
      x: 172,
      y: -137,
      w: 32,
      h: 36,
    },
    {
      keyName: 'F',
      value: 9,
      x: 217,
      y: -137,
      w: 32,
      h: 36,
    },
    {
      keyName: 'G',
      value: 10,
      x: 263,
      y: -137,
      w: 32,
      h: 36,
    },
    {
      keyName: 'H',
      value: 11,
      x: 308,
      y: -137,
      w: 32,
      h: 36,
    },
    {
      keyName: 'J',
      value: 13,
      x: 354,
      y: -137,
      w: 32,
      h: 36,
    },
    {
      keyName: 'K',
      value: 14,
      x: 399,
      y: -137,
      w: 32,
      h: 36,
    },
    {
      keyName: 'L',
      value: 15,
      x: 444,
      y: -137,
      w: 32,
      h: 36,
    },
    {
      keyName: ';',
      value: 51,
      x: 490,
      y: -137,
      w: 32,
      h: 36,
    },
    {
      keyName: '\'',
      value: 52,
      x: 535,
      y: -137,
      w: 32,
      h: 36,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 580,
      y: -137,
      w: 89,
      h: 36,
    },
    {
      keyName: 'num_4',
      value: 92,
      x: 681,
      y: -137,
      w: 32,
      h: 36,
    },
    {
      keyName: 'num_5',
      value: 93,
      x: 725,
      y: -137,
      w: 32,
      h: 36,
    },
    {
      keyName: 'num_6',
      value: 94,
      x: 770,
      y: -137,
      w: 32,
      h: 36,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -183,
      w: 88,
      h: 36,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 102,
      y: -183,
      w: 32,
      h: 36,
    },
    {
      keyName: 'X',
      value: 27,
      x: 148,
      y: -183,
      w: 32,
      h: 36,
    },
    {
      keyName: 'C',
      value: 6,
      x: 194,
      y: -183,
      w: 32,
      h: 36,
    },
    {
      keyName: 'V',
      value: 25,
      x: 239,
      y: -183,
      w: 32,
      h: 36,
    },
    {
      keyName: 'B',
      value: 5,
      x: 285,
      y: -183,
      w: 32,
      h: 36,
    },
    {
      keyName: 'N',
      value: 17,
      x: 330,
      y: -183,
      w: 32,
      h: 36,
    },
    {
      keyName: 'M',
      value: 16,
      x: 376,
      y: -183,
      w: 32,
      h: 36,
    },
    {
      keyName: ',',
      value: 54,
      x: 421,
      y: -183,
      w: 32,
      h: 36,
    },
    {
      keyName: '.',
      value: 55,
      x: 466,
      y: -183,
      w: 32,
      h: 36,
    },
    {
      keyName: '/',
      value: 56,
      x: 512,
      y: -183,
      w: 32,
      h: 36,
    },
    {
      keyName: 'r_Shift',
      value: 229,
      x: 557,
      y: -183,
      w: 66,
      h: 36,
    },
    {
      keyName: '↑',
      value: 82,
      x: 636,
      y: -183,
      w: 32,
      h: 36,
    },
    {
      keyName: 'num_1',
      value: 89,
      x: 681,
      y: -183,
      w: 32,
      h: 36,
    },
    {
      keyName: 'num_2',
      value: 90,
      x: 725,
      y: -183,
      w: 32,
      h: 36,
    },
    {
      keyName: 'num_3',
      value: 91,
      x: 770,
      y: -183,
      w: 32,
      h: 36,
    },
    {
      keyName: 'num_Enter',
      value: 88,
      x: 816,
      y: -183,
      w: 32,
      h: 81,
    },
    {
      keyName: 'Ctrl',
      value: 224,
      x: 0,
      y: -229,
      w: 44,
      h: 36,
    },
    {
      keyName: 'Win',
      value: 227,
      x: 56,
      y: -229,
      w: 44,
      h: 36,
    },
    {
      keyName: 'Alt',
      value: 226,
      x: 114,
      y: -229,
      w: 44,
      h: 36,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 172,
      y: -229,
      w: 269,
      h: 36,
    },
    {
      keyName: 'r_Alt',
      value: 230,
      x: 455,
      y: -229,
      w: 32,
      h: 36,
    },
    {
      keyName: 'fn',
      value: 0x0a010000,
      x: 501,
      y: -229,
      w: 32,
      h: 36,
    },
    {
      keyName: 'r_Ctrl',
      value: 228,
      x: 546,
      y: -229,
      w: 32,
      h: 36,
    },
    {
      keyName: '←',
      value: 80,
      x: 590,
      y: -229,
      w: 32,
      h: 36,
    },
    {
      keyName: '↓',
      value: 81,
      x: 635,
      y: -229,
      w: 32,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
      h: 36,
    },
    {
      keyName: '→',
      value: 79,
      x: 680,
      y: -229,
      w: 32,
      h: 36,
    },
    {
      keyName: 'num_0',
      value: 98,
      x: 725,
      y: -229,
      w: 32,
      h: 36,
    },
    {
      keyName: 'num_.',
      value: 99,
      x: 770,
      y: -229,
      w: 32,
      h: 36,
    },
  ],
}
