export const yc300_c84 = {
  deltX: 95,
  deltY: 17,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 29,
      h: 31,
    },
    {
      keyName: 'F1',
      value: 58,
      x: 43,
      y: 0,
      w: 29,
      h: 31,
    },
    {
      keyName: 'F2',
      value: 59,
      x: 86,
      y: 0,
      w: 29,
      h: 31,
    },
    {
      keyName: 'F3',
      value: 60,
      x: 130,
      y: 0,
      w: 29,
      h: 31,
    },
    {
      keyName: 'F4',
      value: 61,
      x: 173,
      y: 0,
      w: 29,
      h: 31,
    },
    {
      keyName: 'F5',
      value: 62,
      x: 216,
      y: 0,
      w: 29,
      h: 31,
    },
    {
      keyName: 'F6',
      value: 63,
      x: 259,
      y: 0,
      w: 29,
      h: 31,
    },
    {
      keyName: 'F7',
      value: 64,
      x: 303,
      y: 0,
      w: 29,
      h: 31,
    },
    {
      keyName: 'F8',
      value: 65,
      x: 347,
      y: 0,
      w: 29,
      h: 31,
    },
    {
      keyName: 'F9',
      value: 66,
      x: 390,
      y: 0,
      w: 29,
      h: 31,
    },
    {
      keyName: 'F10',
      value: 67,
      x: 433,
      y: 0,
      w: 29,
      h: 31,
    },
    {
      keyName: 'F11',
      value: 68,
      x: 477,
      y: 0,
      w: 29,
      h: 31,
    },
    {
      keyName: 'F12',
      value: 69,
      x: 521,
      y: 0,
      w: 29,
      h: 31,
    },
    {
      keyName: 'Print\nScreen',
      value: 70,
      x: 565,
      y: 0,
      w: 29,
      h: 31,
    },
    {
      keyName: 'Pause',
      value: 72,
      x: 608,
      y: 0,
      w: 29,
      h: 31,
    },
    {
      keyName: 'Delete',
      value: 76,
      x: 652,
      y: 0,
      w: 29,
      h: 31,
    },
    {
      keyName: '`',
      value: 53,
      x: 0,
      y: -44,
      w: 29,
      h: 31,
    },
    {
      keyName: '1',
      value: 30,
      x: 43,
      y: -44,
      w: 29,
      h: 31,
    },
    {
      keyName: '2',
      value: 31,
      x: 86,
      y: -44,
      w: 29,
      h: 31,
    },
    {
      keyName: '3',
      value: 32,
      x: 130,
      y: -44,
      w: 29,
      h: 31,
    },
    {
      keyName: '4',
      value: 33,
      x: 173,
      y: -44,
      w: 29,
      h: 31,
    },
    {
      keyName: '5',
      value: 34,
      x: 216,
      y: -44,
      w: 29,
      h: 31,
    },
    {
      keyName: '6',
      value: 35,
      x: 259,
      y: -44,
      w: 29,
      h: 31,
    },
    {
      keyName: '7',
      value: 36,
      x: 303,
      y: -44,
      w: 29,
      h: 31,
    },
    {
      keyName: '8',
      value: 37,
      x: 347,
      y: -44,
      w: 29,
      h: 31,
    },
    {
      keyName: '9',
      value: 38,
      x: 390,
      y: -44,
      w: 29,
      h: 31,
    },
    {
      keyName: '0',
      value: 39,
      x: 433,
      y: -44,
      w: 29,
      h: 31,
    },
    {
      keyName: '-',
      value: 45,
      x: 477,
      y: -44,
      w: 29,
      h: 31,
    },
    {
      keyName: '=',
      value: 46,
      x: 521,
      y: -44,
      w: 29,
      h: 31,
    },
    {
      keyName: 'BackSpace',
      value: 42,
      x: 565,
      y: -44,
      w: 72,
      h: 31,
    },
    {
      keyName: 'Home',
      value: 74,
      x: 652,
      y: -44,
      w: 29,
      h: 31,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -87,
      w: 51,
      h: 31,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 65,
      y: -87,
      w: 29,
      h: 31,
    },
    {
      keyName: 'W',
      value: 26,
      x: 108,
      y: -87,
      w: 29,
      h: 31,
    },
    {
      keyName: 'E',
      value: 8,
      x: 152,
      y: -87,
      w: 29,
      h: 31,
    },
    {
      keyName: 'R',
      value: 21,
      x: 195,
      y: -87,
      w: 29,
      h: 31,
    },
    {
      keyName: 'T',
      value: 23,
      x: 238,
      y: -87,
      w: 29,
      h: 31,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 281,
      y: -87,
      w: 29,
      h: 31,
    },
    {
      keyName: 'U',
      value: 24,
      x: 325,
      y: -87,
      w: 29,
      h: 31,
    },
    {
      keyName: 'I',
      value: 12,
      x: 369,
      y: -87,
      w: 29,
      h: 31,
    },
    {
      keyName: 'O',
      value: 18,
      x: 412,
      y: -87,
      w: 29,
      h: 31,
    },
    {
      keyName: 'P',
      value: 19,
      x: 455,
      y: -87,
      w: 29,
      h: 31,
    },
    {
      keyName: '[',
      value: 47,
      x: 499,
      y: -87,
      w: 29,
      h: 31,
    },
    {
      keyName: ']',
      value: 48,
      x: 543,
      y: -87,
      w: 29,
      h: 31,
    },
    {
      keyName: '\\',
      value: 49,
      x: 587,
      y: -87,
      w: 50,
      h: 31,
    },
    {
      keyName: 'Page\nUp',
      value: 75,
      x: 652,
      y: -87,
      w: 29,
      h: 31,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -130,
      w: 61,
      h: 31,
    },
    {
      keyName: 'A',
      value: 4,
      x: 76,
      y: -130,
      w: 29,
      h: 31,
    },
    {
      keyName: 'S',
      value: 22,
      x: 119,
      y: -130,
      w: 29,
      h: 31,
    },
    {
      keyName: 'D',
      value: 7,
      x: 163,
      y: -130,
      w: 29,
      h: 31,
    },
    {
      keyName: 'F',
      value: 9,
      x: 206,
      y: -130,
      w: 29,
      h: 31,
    },
    {
      keyName: 'G',
      value: 10,
      x: 249,
      y: -130,
      w: 29,
      h: 31,
    },
    {
      keyName: 'H',
      value: 11,
      x: 292,
      y: -130,
      w: 29,
      h: 31,
    },
    {
      keyName: 'J',
      value: 13,
      x: 336,
      y: -130,
      w: 29,
      h: 31,
    },
    {
      keyName: 'K',
      value: 14,
      x: 380,
      y: -130,
      w: 29,
      h: 31,
    },
    {
      keyName: 'L',
      value: 15,
      x: 423,
      y: -130,
      w: 29,
      h: 31,
    },
    {
      keyName: ';',
      value: 51,
      x: 466,
      y: -130,
      w: 29,
      h: 31,
    },
    {
      keyName: '\'',
      value: 52,
      x: 510,
      y: -130,
      w: 29,
      h: 31,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 554,
      y: -130,
      w: 83,
      h: 31,
    },
    {
      keyName: 'Page\nDown',
      value: 78,
      x: 652,
      y: -130,
      w: 29,
      h: 31,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -174,
      w: 83,
      h: 31,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 98,
      y: -174,
      w: 29,
      h: 31,
    },
    {
      keyName: 'X',
      value: 27,
      x: 141,
      y: -174,
      w: 29,
      h: 31,
    },
    {
      keyName: 'C',
      value: 6,
      x: 185,
      y: -174,
      w: 29,
      h: 31,
    },
    {
      keyName: 'V',
      value: 25,
      x: 228,
      y: -174,
      w: 29,
      h: 31,
    },
    {
      keyName: 'B',
      value: 5,
      x: 271,
      y: -174,
      w: 29,
      h: 31,
    },
    {
      keyName: 'N',
      value: 17,
      x: 314,
      y: -174,
      w: 29,
      h: 31,
    },
    {
      keyName: 'M',
      value: 16,
      x: 358,
      y: -174,
      w: 29,
      h: 31,
    },
    {
      keyName: ',',
      value: 54,
      x: 402,
      y: -174,
      w: 29,
      h: 31,
    },
    {
      keyName: '.',
      value: 55,
      x: 445,
      y: -174,
      w: 29,
      h: 31,
    },
    {
      keyName: '/',
      value: 56,
      x: 488,
      y: -174,
      w: 29,
      h: 31,
    },
    {
      keyName: 'r_Shift',
      value: 229,
      x: 532,
      y: -174,
      w: 62,
      h: 31,
    },
    {
      keyName: '↑',
      value: 82,
      x: 609,
      y: -174,
      w: 29,
      h: 31,
    },
    {
      keyName: 'End',
      value: 77,
      x: 652,
      y: -174,
      w: 29,
      h: 31,
    },
    {
      keyName: 'Ctrl',
      value: 224,
      x: 0,
      y: -216,
      w: 39,
      h: 31,
    },
    {
      keyName: 'Win',
      value: 227,
      x: 55,
      y: -216,
      w: 40,
      h: 31,
    },
    {
      keyName: 'Alt',
      value: 226,
      x: 108,
      y: -216,
      w: 41                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ,
      h: 31,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 163,
      y: -216,
      w: 256,
      h: 31,
    },
    {
      keyName: 'r_Alt',
      value: 230,
      x: 435,
      y: -216,
      w: 29,
      h: 31,
    },
    {
      keyName: 'r_Ctrl',
      value: 228,
      x: 478,
      y: -216,
      w: 29,
      h: 31,
    },
    {
      keyName: 'FN',
      value: 0x0a010000,
      x: 522,
      y: -216,
      w: 29,
      h: 31,
    },
    {
      keyName: '←',
      value: 80,
      x: 566,
       y: -216,
      w: 29,
      h: 31,
    },
    {
      keyName: '↓',
      value: 81,
      x: 609,
       y: -216,
      w: 29,
      h: 31,
    },
    {
      keyName: '→',
      value: 79,
      x: 652,
       y: -216,
      w: 29,
      h: 31,
    },
  ],
}
