export const yc300_3084bp_iso_ne = {
  deltX: 96,
  deltY: 16,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 29,
      h: 33,
     },
    {
      keyName: 'F1',
      value: 58,
      x: 44,
      y: 0,
      w: 29,
      h: 33,
    },
    {
      keyName: 'F2',
      value: 59,
      x: 87,
      y: 0,
      w: 29,
      h: 33,
    },
    {
      keyName: 'F3',
      value: 60,
      x: 130,
      y: 0,
      w: 29,
      h: 33,
    },
    {
      keyName: 'F4',
      value: 61,
      x: 174,
      y: 0,
      w: 29,
      h: 33,
    },
    {
      keyName: 'F5',
      value: 62,
      x: 217,
      y: 0,
      w: 29,
      h: 33,
    },
    {
      keyName: 'F6',
      value: 63,
      x: 261,
      y: 0,
      w: 29,
      h: 33,
    },
    {
      keyName: 'F7',
      value: 64,
      x: 304,
      y: 0,
      w: 29,
      h: 33,
    },
    {
      keyName: 'F8',
      value: 65,
      x: 347,
      y: 0,
      w: 29,
      h: 33,
    },
    {
      keyName: 'F9',
      value: 66,
      x: 391,
      y: 0,
      w: 29,
      h: 33,
    },
    {
      keyName: 'F10',
      value: 67,
      x: 435,
      y: 0,
      w: 29,
      h: 33,
    },
    {
      keyName: 'F11',
      value: 68,
      x: 478,
      y: 0,
      w: 29,
      h: 33,
    },
    {
      keyName: 'F12',
      value: 69,
      x: 521,
      y: 0,
      w: 29,
      h: 33,
    },
    {
      keyName: 'Print\nScreen',
      value: 70,
      x: 565,
      y: 0,
      w: 29,
      h: 33,
    },
    {
      keyName: 'Pause',
      value: 72,
      x: 608,
      y: 0,
      w: 29,
      h: 33,
    },
    {
      keyName: 'Delete',
      value: 76,
      x: 652,
      y: 0,
      w: 29,
      h: 33,
    },
    {
      keyName: '`',
      value: 53,
      x: 0,
      y: -43,
      w: 29,
      h: 33,
    },
    {
      keyName: '1',
      value: 30,
      x: 44,
      y: -43,
      w: 29,
      h: 33,
    },
    {
      keyName: '2',
      value: 31,
      x: 87,
      y: -43,
      w: 29,
      h: 33,
    },
    {
      keyName: '3',
      value: 32,
      x: 130,
      y: -43,
      w: 29,
      h: 33,
    },
    {
      keyName: '4',
      value: 33,
      x: 174,
      y: -43,
      w: 29,
      h: 33,
    },
    {
      keyName: '5',
      value: 34,
      x: 217,
      y: -43,
      w: 29,
      h: 33,
    },
    {
      keyName: '6',
      value: 35,
      x: 261,
      y: -43,
      w: 29,
      h: 33,
    },
    {
      keyName: '7',
      value: 36,
      x: 304,
      y: -43,
      w: 29,
      h: 33,
    },
    {
      keyName: '8',
      value: 37,
      x: 348,
      y: -43,
      w: 29,
      h: 33,
    },
    {
      keyName: '9',
      value: 38,
      x: 391,
      y: -43,
      w: 29,
      h: 33,
    },
    {
      keyName: '0',
      value: 39,
      x: 435,
      y: -43,
      w: 29,
      h: 33,
    },
    {
      keyName: '-',
      value: 45,
      x: 478,
      y: -43,
      w: 29,
      h: 33,
    },
    {
      keyName: '=',
      value: 46,
      x: 521,
      y: -43,
      w: 29,
      h: 33,
    },
    {
      keyName: 'BackSpace',
      value: 42,
      x: 565,
      y: -43,
      w: 72,
      h: 33,
    },
    {
      keyName: 'Home',
      value: 74,
      x: 652,
      y: -43,
      w: 29,
      h: 33,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -87,
      w: 51,
      h: 33,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 66,
      y: -87,
      w: 29,
      h: 33,
    },
    {
      keyName: 'W',
      value: 26,
      x: 109,
      y: -87,
      w: 29,
      h: 33,
    },
    {
      keyName: 'E',
      value: 8,
      x: 153,
      y: -87,
      w: 29,
      h: 33,
    },
    {
      keyName: 'R',
      value: 21,
      x: 196,
      y: -87,
      w: 29,
      h: 33,
    },
    {
      keyName: 'T',
      value: 23,
      x: 239,
      y: -87,
      w: 29,
      h: 33,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 283,
      y: -87,
      w: 29,
      h: 33,
    },
    {
      keyName: 'U',
      value: 24,
      x: 326,
      y: -87,
      w: 29,
      h: 33,
    },
    {
      keyName: 'I',
      value: 12,
      x: 369,
      y: -87,
      w: 29,
      h: 33,
    },
    {
      keyName: 'O',
      value: 18,
      x: 413,
      y: -87,
      w: 29,
      h: 33,
    },
    {
      keyName: 'P',
      value: 19,
      x: 456,
      y: -87,
      w: 29,
      h: 33,
    },
    {
      keyName: '[',
      value: 47,
      x: 500,
      y: -87,
      w: 29,
      h: 33,
    },
    {
      keyName: ']',
      value: 48,
      x: 543,
      y: -87,
      w: 29,
      h: 33,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 598,
      y: -87,
      w: 39,
      h: 76,
    },
    {
      keyName: 'Page\nUp',
      value: 75,
      x: 652,
      y: -87,
      w: 29,
      h: 33,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -130,
      w: 61,
      h: 33,
    },
    {
      keyName: 'A',
      value: 4,
      x: 76,
      y: -130,
      w: 29,
      h: 33,
    },
    {
      keyName: 'S',
      value: 22,
      x: 120,
      y: -130,
      w: 29,
      h: 33,
    },
    {
      keyName: 'D',
      value: 7,
      x: 164,
      y: -130,
      w: 29,
      h: 33,
    },
    {
      keyName: 'F',
      value: 9,
      x: 207,
      y: -130,
      w: 29,
      h: 33,
    },
    {
      keyName: 'G',
      value: 10,
      x: 250,
      y: -130,
      w: 29,
      h: 33,
    },
    {
      keyName: 'H',
      value: 11,
      x: 294,
      y: -130,
      w: 29,
      h: 33,
    },
    {
      keyName: 'J',
      value: 13,
      x: 337,
      y: -130,
      w: 29,
      h: 33,
    },
    {
      keyName: 'K',
      value: 14,
      x: 380,
      y: -130,
      w: 29,
      h: 33,
    },
    {
      keyName: 'L',
      value: 15,
      x: 424,
      y: -130,
      w: 29,
      h: 33,
    },
    {
      keyName: ';',
      value: 51,
      x: 467,
      y: -130,
      w: 29,
      h: 33,
    },
    {
      keyName: '\'',
      value: 52,
      x: 511,
      y: -130,
      w: 29,
      h: 33,
    },
    {
      keyName: '\\',
      value: 50,
      x: 554,
      y: -130,
      w: 29,
      h: 33,
    },
    {
      keyName: 'Page\nDown',
      value: 78,
      x: 652,
      y: -130,
      w: 29,
      h: 33,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -173,
      w: 39,
      h: 33,
    },
    {
      keyName: '\\',
      value: 100,
      x: 54,
      y: -173,
      w: 29,
      h: 33,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 98,
      y: -173,
      w: 29,
      h: 33,
    },
    {
      keyName: 'X',
      value: 27,
      x: 142,
      y: -173,
      w: 29,
      h: 33,
    },
    {
      keyName: 'C',
      value: 6,
      x: 185,
      y: -173,
      w: 29,
      h: 33,
    },
    {
      keyName: 'V',
      value: 25,
      x: 228,
      y: -173,
      w: 29,
      h: 33,
    },
    {
      keyName: 'B',
      value: 5,
      x: 272,
      y: -173,
      w: 29,
      h: 33,
    },
    {
      keyName: 'N',
      value: 17,
      x: 315,
      y: -173,
      w: 29,
      h: 33,
    },
    {
      keyName: 'M',
      value: 16,
      x: 358,
      y: -173,
      w: 29,
      h: 33,
    },
    {
      keyName: ',',
      value: 54,
      x: 402,
      y: -173,
      w: 29,
      h: 33,
    },
    {
      keyName: '.',
      value: 55,
      x: 445,
      y: -173,
      w: 29,
      h: 33,
    },
    {
      keyName: '/',
      value: 56,
      x: 489,
      y: -173,
      w: 29,
      h: 33,
    },
    {
      keyName: 'r_Shift',
      value: 229,
      x: 533,
      y: -173,
      w: 59,
      h: 33,
    },
    {
      keyName: '↑',
      value: 82,
      x: 609,
      y: -173,
      w: 29,
      h: 33,
    },
    {
      keyName: 'End',
      value: 77,
      x: 652,
      y: -173,
      w: 29,
      h: 33,
    },
    {
      keyName: 'Ctrl',
      value: 224,
      x: 0,
      y: -216,
      w: 39,
      h: 33,
    },
    {
      keyName: 'Win',
      value: 227,
      x: 55,
      y: -216,
      w: 39,
      h: 33,
    },
    {
      keyName: 'Alt',
      value: 226,
      x: 109,
      y: -216,
      w: 39,
      h: 33,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 165,
      y: -216,
      w: 253,
      h: 33,
    },
    {
      keyName: 'r_Alt',
      value: 230,
      x: 434,
      y: -216,
      w: 29,
      h: 33,
    },
    {
      keyName: 'FN',
      value: 0x0a010000,
      x: 478,
      y: -216,
      w: 29,
      h: 33,
    },
    {
      keyName: 'r_Ctrl',
      value: 228,
      x: 522,
      y: -216,
      w: 29,
      h: 33,
    },
    {
      keyName: '←',
      value: 80,
      x: 565,
      y: -216,
      w: 29,
      h: 33,
    },
    {
      keyName: '↓',
      value: 81,
      x: 608,
      y: -216,
      w: 29,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
      h: 33,
    },
    {
      keyName: '→',
      value: 79,
      x: 652,
      y: -216,
      w: 29,
      h: 33,
    },
  ],
}
