export const yc300_spr67_noled_dm = {
  deltX: 64,
  deltY: 28,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 33,
      h: 36,
     },
    {
      keyName: '1',
      value: 30,
      x: 48,
      y: 0,
      w: 33,
      h: 36,
    },
    {
      keyName: '2',
      value: 31,
      x: 95,
      y: 0,
      w: 33,
      h: 36,
    },
    {
      keyName: '3',
      value: 32,
      x: 142,
      y: 0,
      w: 33,
      h: 36,
    },
    {
      keyName: '4',
      value: 33,
      x: 190,
      y: 0,
      w: 33,
      h: 36,
    },
    {
      keyName: '5',
      value: 34,
      x: 237,
      y: 0,
      w: 33,
      h: 36,
    },
    {
      keyName: '6',
      value: 35,
      x: 284,
      y: 0,
      w: 33,
      h: 36,
    },
    {
      keyName: '7',
      value: 36,
      x: 331,
      y: 0,
      w: 33,
      h: 36,
    },
    {
      keyName: '8',
      value: 37,
      x: 378,
      y: 0,
      w: 33,
      h: 36,
    },
    {
      keyName: '9',
      value: 38,
      x: 426,
      y: 0,
      w: 33,
      h: 36,
    },
    {
      keyName: '0',
      value: 39,
      x: 473,
      y: 0,
      w: 33,
      h: 36,
    },
    {
      keyName: '-',
      value: 45,
      x: 521,
      y: 0,
      w: 33,
      h: 36,
    },
    {
      keyName: '=',
      value: 46,
      x: 568,
      y: 0,
      w: 33,
      h: 36,
    },
    {
      keyName: 'Backspace',
      value: 42,
      x: 616,
      y: 0,
      w: 80,
      h: 36,
    },
    {
      keyName: '`',
      value: 53,
      x: 711,
      y: 0,
      w: 33,
      h: 36,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -47,
      w: 57,
      h: 36,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 72,
      y: -47,
      w: 33,
      h: 36,
    },
    {
      keyName: 'W',
      value: 26,
      x: 119,
      y: -47,
      w: 33,
      h: 36,
    },
    {
      keyName: 'E',
      value: 8,
      x: 166,
      y: -47,
      w: 33,
      h: 36,
    },
    {
      keyName: 'R',
      value: 21,
      x: 214,
      y: -47,
      w: 33,
      h: 36,
    },
    {
      keyName: 'T',
      value: 23,
      x: 261,
      y: -47,
      w: 33,
      h: 36,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 308,
      y: -47,
      w: 33,
      h: 36,
    },
    {
      keyName: 'U',
      value: 24,
      x: 355,
      y: -47,
      w: 33,
      h: 36,
    },
    {
      keyName: 'I',
      value: 12,
      x: 402,
      y: -47,
      w: 33,
      h: 36,
    },
    {
      keyName: 'O',
      value: 18,
      x: 450,
      y: -47,
      w: 33,
      h: 36,
    },
    {
      keyName: 'P',
      value: 19,
      x: 497,
      y: -47,
      w: 33,
      h: 36,
    },
    {
      keyName: '[',
      value: 47,
      x: 545,
      y: -47,
      w: 33,
      h: 36,
    },
    {
      keyName: ']',
      value: 48,
      x: 592,
      y: -47,
      w: 33,
      h: 36,
    },
    {
      keyName: '\\',
      value: 49,
      x: 640,
      y: -47,
      w: 56,
      h: 36,
    },
    {
      keyName: 'Delete',
      value: 76,
      x: 711,
      y: -47,
      w: 33,
      h: 36,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -95,
      w: 69,
      h: 36,
    },
    {
      keyName: 'A',
      value: 4,
      x: 84,
      y: -95,
      w: 33,
      h: 36,
    },
    {
      keyName: 'S',
      value: 22,
      x: 131,
      y: -95,
      w: 33,
      h: 36,
    },
    {
      keyName: 'D',
      value: 7,
      x: 178,
      y: -95,
      w: 33,
      h: 36,
    },
    {
      keyName: 'F',
      value: 9,
      x: 226,
      y: -95,
      w: 33,
      h: 36,
    },
    {
      keyName: 'G',
      value: 10,
      x: 273,
      y: -95,
      w: 33,
      h: 36,
    },
    {
      keyName: 'H',
      value: 11,
      x: 320,
      y: -95,
      w: 33,
      h: 36,
    },
    {
      keyName: 'J',
      value: 13,
      x: 367,
      y: -95,
      w: 33,
      h: 36,
    },
    {
      keyName: 'K',
      value: 14,
      x: 414,
      y: -95,
      w: 33,
      h: 36,
    },
    {
      keyName: 'L',
      value: 15,
      x: 462,
      y: -95,
      w: 33,
      h: 36,
    },
    {
      keyName: ';',
      value: 51,
      x: 509,
      y: -95,
      w: 33,
      h: 36,
    },
    {
      keyName: '\'',
      value: 52,
      x: 557,
      y: -95,
      w: 33,
      h: 36,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 604,
      y: -95,
      w: 92,
      h: 36,
    },
    {
      keyName: 'Page\nUp',
      value: 75,
      x: 711,
      y: -95,
      w: 33,
      h: 36,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -142,
      w: 92,
      h: 36,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 107,
      y: -142,
      w: 33,
      h: 36,
    },
    {
      keyName: 'X',
      value: 27,
      x: 154,
      y: -142,
      w: 33,
      h: 36,
    },
    {
      keyName: 'C',
      value: 6,
      x: 202,
      y: -142,
      w: 33,
      h: 36,
    },
    {
      keyName: 'V',
      value: 25,
      x: 249,
      y: -142,
      w: 33,
      h: 36,
    },
    {
      keyName: 'B',
      value: 5,
      x: 296,
      y: -142,
      w: 33,
      h: 36,
    },
    {
      keyName: 'N',
      value: 17,
      x: 343,
      y: -142,
      w: 33,
      h: 36,
    },
    {
      keyName: 'M',
      value: 16,
      x: 391,
      y: -142,
      w: 33,
      h: 36,
    },
    {
      keyName: ',',
      value: 54,
      x: 438,
      y: -142,
      w: 33,
      h: 36,
    },
    {
      keyName: '.',
      value: 55,
      x: 486,
      y: -142,
      w: 33,
      h: 36,
    },
    {
      keyName: '/',
      value: 56,
      x: 533,
      y: -142,
      w: 33,
      h: 36,
    },
    {
      keyName: 'r_Shift',
      value: 229,
      x: 580,
      y: -142,
      w: 68,
      h: 36,
    },
    {
      keyName: '↑',
      value: 82,
      x: 663,
      y: -142,
      w: 33,
      h: 36,
    },
    {
      keyName: 'Page\nDown',
      value: 78,
      x: 711,
      y: -142,
      w: 33,
      h: 36,
    },
    {
      keyName: 'CTRL',
      value: 224,
      x: 0,
      y: -189,
      w: 45,
      h: 36,
    },
    {
      keyName: 'Win',
      value: 227,
      x: 60,
      y: -189,
      w: 45,
      h: 36,
    },
    {
      keyName: 'ALT',
      value: 226,
      x: 119,
      y: -189,
      w: 45,
      h: 36,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 178,
      y: -189,
      w: 281,
      h: 36,
    },
    {
      keyName: 'r_Alt',
      value: 230,
      x: 474,
      y: -189,
      w: 45,
      h: 36,
    },
    {
      keyName: 'FN',
      value: 0x0a010000,
      x: 533,
      y: -189,
      w: 45,
      h: 36,
    },
    {
      keyName: '←',
      value: 80,
      x: 616,
      y: -189,
      w: 33,
      h: 36,
    },
    {
      keyName: '↓',
      value: 81,
      x: 663,
      y: -189,
      w: 33,
      h: 36,
    },
    {
      keyName: '→',
      value: 79,
      x: 711,
      y: -189,
      w: 33,
      h: 36,
    },
  ],
}
