export const yc300_mk15_uk = {
  deltX: 73,
  deltY: 29,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 32,
      h: 35,
     },
    {
      keyName: '1',
      value: 30,
      x: 47,
      y: 0,
      w: 32,
      h: 35,
    },
    {
      keyName: '2',
      value: 31,
      x: 94,
      y: 0,
      w: 32,
      h: 35,
    },
    {
      keyName: '3',
      value: 32,
      x: 141,
      y: 0,
      w: 32,
      h: 35,
    },
    {
      keyName: '4',
      value: 33,
      x: 188,
      y: 0,
      w: 32,
      h: 35,
    },
    {
      keyName: '5',
      value: 34,
      x: 235,
      y: 0,
      w: 32,
      h: 35,
    },
    {
      keyName: '6',
      value: 35,
      x: 282,
      y: 0,
      w: 32,
      h: 35,
    },
    {
      keyName: '7',
      value: 36,
      x: 329,
      y: 0,
      w: 32,
      h: 35,
    },
    {
      keyName: '8',
      value: 37,
      x: 376,
      y: 0,
      w: 32,
      h: 35,
    },
    {
      keyName: '9',
      value: 38,
      x: 423,
      y: 0,
      w: 32,
      h: 35,
    },
    {
      keyName: '0',
      value: 39,
      x: 470,
      y: 0,
      w: 32,
      h: 35,
    },
    {
      keyName: '-',
      value: 45,
      x: 517,
      y: 0,
      w: 32,
      h: 35,
    },
    {
      keyName: '=',
      value: 46,
      x: 564,
      y: 0,
      w: 32,
      h: 35,
    },
    {
      keyName: 'Backspace',
      value: 42,
      x: 611,
      y: 0,
      w: 80,
      h: 35,
    },
    {
      keyName: '`',
      value: 53,
      x: 704,
      y: 0,
      w: 32,
      h: 35,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -48,
      w: 56,
      h: 35,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 71,
      y: -48,
      w: 32,
      h: 35,
    },
    {
      keyName: 'W',
      value: 26,
      x: 118,
      y: -48,
      w: 32,
      h: 35,
    },
    {
      keyName: 'E',
      value: 8,
      x: 165,
      y: -48,
      w: 32,
      h: 35,
    },
    {
      keyName: 'R',
      value: 21,
      x: 212,
      y: -48,
      w: 32,
      h: 35,
    },
    {
      keyName: 'T',
      value: 23,
      x: 259,
      y: -48,
      w: 32,
      h: 35,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 306,
      y: -48,
      w: 32,
      h: 35,
    },
    {
      keyName: 'U',
      value: 24,
      x: 353,
      y: -48,
      w: 32,
      h: 35,
    },
    {
      keyName: 'I',
      value: 12,
      x: 400,
      y: -48,
      w: 32,
      h: 35,
    },
    {
      keyName: 'O',
      value: 18,
      x: 447,
      y: -48,
      w: 32,
      h: 35,
    },
    {
      keyName: 'P',
      value: 19,
      x: 494,
      y: -48,
      w: 32,
      h: 35,
    },
    {
      keyName: '[',
      value: 47,
      x: 541,
      y: -48,
      w: 32,
      h: 35,
    },
    {
      keyName: ']',
      value: 48,
      x: 588,
      y: -48,
      w: 32,
      h: 35,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 646,
      y: -48,
      w: 45,
      h: 81,
    },
    {
      keyName: 'DEL',
      value: 76,
      x: 704,
      y: -48,
      w: 32,
      h: 35,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -94,
      w: 69,
      h: 35,
    },
    {
      keyName: 'A',
      value: 4,
      x: 82,
      y: -94,
      w: 32,
      h: 35,
    },
    {
      keyName: 'S',
      value: 22,
      x: 129,
      y: -94,
      w: 32,
      h: 35,
    },
    {
      keyName: 'D',
      value: 7,
      x: 176,
      y: -94,
      w: 32,
      h: 35,
    },
    {
      keyName: 'F',
      value: 9,
      x: 223,
      y: -94,
      w: 32,
      h: 35,
    },
    {
      keyName: 'G',
      value: 10,
      x: 270,
      y: -94,
      w: 32,
      h: 35,
    },
    {
      keyName: 'H',
      value: 11,
      x: 317,
      y: -94,
      w: 32,
      h: 35,
    },
    {
      keyName: 'J',
      value: 13,
      x: 364,
      y: -94,
      w: 32,
      h: 35,
    },
    {
      keyName: 'K',
      value: 14,
      x: 411,
      y: -94,
      w: 32,
      h: 35,
    },
    {
      keyName: 'L',
      value: 15,
      x: 458,
      y: -94,
      w: 32,
      h: 35,
    },
    {
      keyName: ';',
      value: 51,
      x: 505,
      y: -94,
      w: 32,
      h: 35,
    },
    {
      keyName: "'",
      value: 52,
      x: 552,
      y: -94,
      w: 32,
      h: 35,
    },
    {
      keyName: '\\',
      value: 49,
      x: 599,
      y: -94,
      w: 32,
      h: 35,
    },
    {
      keyName: 'Page\nUp',
      value: 75,
      x: 704,
      y: -94,
      w: 32,
      h: 35,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -140,
      w: 49,
      h: 35,
    },
    {
      keyName: '\\',
      value: 100,
      x: 62,
      y: -140,
      w: 32,
      h: 35,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 108,
      y: -140,
      w: 32,
      h: 35,
    },
    {
      keyName: 'X',
      value: 27,
      x: 154,
      y: -140,
      w: 32,
      h: 35,
    },
    {
      keyName: 'C',
      value: 6,
      x: 201,
      y: -140,
      w: 32,
      h: 35,
    },
    {
      keyName: 'V',
      value: 25,
      x: 247,
      y: -140,
      w: 32,
      h: 35,
    },
    {
      keyName: 'B',
      value: 5,
      x: 294,
      y: -140,
      w: 32,
      h: 35,
    },
    {
      keyName: 'N',
      value: 17,
      x: 343,
      y: -140,
      w: 32,
      h: 35,
    },
    {
      keyName: 'M',
      value: 16,
      x: 388,
      y: -140,
      w: 32,
      h: 35,
    },
    {
      keyName: ',',
      value: 54,
      x: 435,
      y: -140,
      w: 32,
      h: 35,
    },
    {
      keyName: '.',
      value: 55,
      x: 482,
      y: -140,
      w: 32,
      h: 35,
    },
    {
      keyName: '-',
      value: 45,
      x: 528,
      y: -140,
      w: 32,
      h: 35,
    },
    {
      keyName: 'r_Shift',
      value: 229,
      x: 578,
      y: -140,
      w: 68,
      h: 35,
    },
    {
      keyName: '↑',
      value: 82,
      x: 658,
      y: -140,
      w: 32,
      h: 35,
    },
    {
      keyName: 'Page\nDown',
      value: 78,
      x: 704,
      y: -140,
      w: 32,
      h: 35,
    },
    {
      keyName: 'ctrl',
      value: 224,
      x: 0,
      y: -188,
      w: 49,
      h: 35,
    },
    {
      keyName: 'Win',
      value: 227,
      x: 57,
      y: -188,
      w: 49,
      h: 35,
    },
    {
      keyName: 'ALT',
      value: 226,
      x: 117,
      y: -188,
      w: 49,
      h: 35,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 177,
      y: -188,
      w: 278,
      h: 35,
    },
    {
      keyName: 'r_Alt',
      value: 230,
      x: 470,
      y: -188,
      w: 32,
      h: 35,
    },
    {
      keyName: 'FN',
      value: 0x0a010000,
      x: 517,
      y: -188,
      w: 32,
      h: 35,
    },
    {
      keyName: 'r_Ctrl',
      value: 228,
      x: 564,
      y: -188,
      w: 32,
      h: 35,
    },
    {
      keyName: '←',
      value: 80,
      x: 610,
      y: -188,
      w: 32,
      h: 35,
    },
    {
      keyName: '↓',
      value: 81,
      x: 657,
      y: -188,
      w: 32,
      h: 35,
    },
    {
      keyName: '→',
      value: 79,
      x: 704,
      y: -188,
      w: 32,
      h: 35,
    },
  ],
}
