export const yc300_dk732 = {
  deltX: 136,
  deltY: 39,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 25,
      h: 25,
     },
    {
      keyName: 'F1',
      value: 58,
      x: 70,
      y: 0,
      w: 25,
      h: 25,
    },
    {
      keyName: 'F2',
      value: 59,
      x: 108,
      y: 0,
      w: 25,
      h: 25,
    },
    {
      keyName: 'F3',
      value: 60,
      x: 146,
      y: 0,
      w: 25,
      h: 25,
    },
    {
      keyName: 'F4',
      value: 61,
      x: 185,
      y: 0,
      w: 25,
      h: 25,
    },
    {
      keyName: 'F5',
      value: 62,
      x: 238,
      y: 0,
      w: 25,
      h: 25,
    },
    {
      keyName: 'F6',
      value: 63,
      x: 276,
      y: 0,
      w: 25,
      h: 25,
    },
    {
      keyName: 'F7',
      value: 64,
      x: 314,
      y: 0,
      w: 25,
      h: 25,
    },
    {
      keyName: 'F8',
      value: 65,
      x: 353,
      y: 0,
      w: 25,
      h: 25,
    },
    {
      keyName: 'F9',
      value: 66,
      x: 407,
      y: 0,
      w: 25,
      h: 25,
    },
    {
      keyName: 'F10',
      value: 67,
      x: 445,
      y: 0,
      w: 25,
      h: 25,
    },
    {
      keyName: 'F11',
      value: 68,
      x: 484,
      y: 0,
      w: 25,
      h: 25,
    },
    {
      keyName: 'F12',
      value: 69,
      x: 522,
      y: 0,
      w: 25,
      h: 25,
    },
    {
      keyName: 'Delete',
      value: 76,
      x: 576,
      y: 0,
      w: 25,
      h: 25,
    },
    {
      keyName: '`',
      value: 53,
      x: 0,
      y: -46,
      w: 25,
      h: 25,
    },
    {
      keyName: '1',
      value: 30,
      x: 38,
      y: -46,
      w: 25,
      h: 25,
    },
    {
      keyName: '2',
      value: 31,
      x: 77,
      y: -46,
      w: 25,
      h: 25,
    },
    {
      keyName: '3',
      value: 32,
      x: 115,
      y: -46,
      w: 25,
      h: 25,
    },
    {
      keyName: '4',
      value: 33,
      x: 154,
      y: -46,
      w: 25,
      h: 25,
    },
    {
      keyName: '5',
      value: 34,
      x: 192,
      y: -46,
      w: 25,
      h: 25,
    },
    {
      keyName: '6',
      value: 35,
      x: 231,
      y: -46,
      w: 25,
      h: 25,
    },
    {
      keyName: '7',
      value: 36,
      x: 269,
      y: -46,
      w: 25,
      h: 25,
    },
    {
      keyName: '8',
      value: 37,
      x: 307,
      y: -46,
      w: 25,
      h: 25,
    },
    {
      keyName: '9',
      value: 38,
      x: 346,
      y: -46,
      w: 25,
      h: 25,
    },
    {
      keyName: '0',
      value: 39,
      x: 384,
      y: -46,
      w: 25,
      h: 25,
    },
    {
      keyName: '-',
      value: 45,
      x: 422,
      y: -46,
      w: 25,
      h: 25,
    },
    {
      keyName: '=',
      value: 46,
      x: 461,
      y: -46,
      w: 25,
      h: 25,
    },
    {
      keyName: 'BackSpace',
      value: 42,
      x: 499,
      y: -46,
      w: 64,
      h: 25,
    },
    {
      keyName: 'Home',
      value: 74,
      x: 576,
      y: -46,
      w: 25,
      h: 25,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -84,
      w: 45,
      h: 25,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 57,
      y: -84,
      w: 25,
      h: 25,
    },
    {
      keyName: 'W',
      value: 26,
      x: 96,
      y: -84,
      w: 25,
      h: 25,
    },
    {
      keyName: 'E',
      value: 8,
      x: 134,
      y: -84,
      w: 25,
      h: 25,
    },
    {
      keyName: 'R',
      value: 21,
      x: 173,
      y: -84,
      w: 25,
      h: 25,
    },
    {
      keyName: 'T',
      value: 23,
      x: 211,
      y: -84,
      w: 25,
      h: 25,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 250,
      y: -84,
      w: 25,
      h: 25,
    },
    {
      keyName: 'U',
      value: 24,
      x: 288,
      y: -84,
      w: 25,
      h: 25,
    },
    {
      keyName: 'I',
      value: 12,
      x: 326,
      y: -84,
      w: 25,
      h: 25,
    },
    {
      keyName: 'O',
      value: 18,
      x: 365,
      y: -84,
      w: 25,
      h: 25,
    },
    {
      keyName: 'P',
      value: 19,
      x: 403,
      y: -84,
      w: 25,
      h: 25,
    },
    {
      keyName: '[',
      value: 47,
      x: 441,
      y: -84,
      w: 25,
      h: 25,
    },
    {
      keyName: ']',
      value: 48,
      x: 480,
      y: -84,
      w: 25,
      h: 25,
    },
    {
      keyName: '\\',
      value: 49,
      x: 518,
      y: -84,
      w: 45,
      h: 25,
    },
    {
      keyName: 'End',
      value: 77,
      x: 576,
      y: -84,
      w: 25,
      h: 25,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -122,
      w: 55,
      h: 25,
    },
    {
      keyName: 'A',
      value: 4,
      x: 68,
      y: -122,
      w: 25,
      h: 25,
    },
    {
      keyName: 'S',
      value: 22,
      x: 106,
      y: -122,
      w: 25,
      h: 25,
    },
    {
      keyName: 'D',
      value: 7,
      x: 144,
      y: -122,
      w: 25,
      h: 25,
    },
    {
      keyName: 'F',
      value: 9,
      x: 183,
      y: -122,
      w: 25,
      h: 25,
    },
    {
      keyName: 'G',
      value: 10,
      x: 221,
      y: -122,
      w: 25,
      h: 25,
    },
    {
      keyName: 'H',
      value: 11,
      x: 260,
      y: -122,
      w: 25,
      h: 25,
    },
    {
      keyName: 'J',
      value: 13,
      x: 298,
      y: -122,
      w: 25,
      h: 25,
    },
    {
      keyName: 'K',
      value: 14,
      x: 336,
      y: -122,
      w: 25,
      h: 25,
    },
    {
      keyName: 'L',
      value: 15,
      x: 375,
      y: -122,
      w: 25,
      h: 25,
    },
    {
      keyName: ';',
      value: 51,
      x: 413,
      y: -122,
      w: 25,
      h: 25,
    },
    {
      keyName: '\'',
      value: 52,
      x: 451,
      y: -122,
      w: 25,
      h: 25,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 489,
      y: -122,
      w: 74,
      h: 25,
    },
    {
      keyName: 'Page\nUp',
      value: 75,
      x: 576,
      y: -122,
      w: 25,
      h: 25,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -160,
      w: 74,
      h: 25,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 86,
      y: -160,
      w: 25,
      h: 25,
    },
    {
      keyName: 'X',
      value: 27,
      x: 124,
      y: -160,
      w: 25,
      h: 25,
    },
    {
      keyName: 'C',
      value: 6,
      x: 162,
      y: -160,
      w: 25,
      h: 25,
    },
    {
      keyName: 'V',
      value: 25,
      x: 201,
      y: -160,
      w: 25,
      h: 25,
    },
    {
      keyName: 'B',
      value: 5,
      x: 239,
      y: -160,
      w: 25,
      h: 25,
    },
    {
      keyName: 'N',
      value: 17,
      x: 278,
      y: -160,
      w: 25,
      h: 25,
    },
    {
      keyName: 'M',
      value: 16,
      x: 316,
      y: -160,
      w: 25,
      h: 25,
    },
    {
      keyName: ',',
      value: 54,
      x: 354,
      y: -160,
      w: 25,
      h: 25,
    },
    {
      keyName: '.',
      value: 55,
      x: 393,
      y: -160,
      w: 25,
      h: 25,
    },
    {
      keyName: '/',
      value: 56,
      x: 431,
      y: -160,
      w: 25,
      h: 25,
    },
    {
      keyName: 'r_Shift',
      value: 229,
      x: 470,
      y: -160,
      w: 54,
      h: 25,
    },
    {
      keyName: '↑',
      value: 82,
      x: 537,
      y: -160,
      w: 25,
      h: 25,
    },
    {
      keyName: 'Page\nDown',
      value: 78,
      x: 576,
      y: -160,
      w: 25,
      h: 25,
    },
    {
      keyName: 'Ctrl',
      value: 224,
      x: 0,
      y: -198,
      w: 35,
      h: 25,
    },
    {
      keyName: 'Win',
      value: 227,
      x: 48,
      y: -198,
      w: 35,
      h: 25,
    },
    {
      keyName: 'Alt',
      value: 226,
      x: 96,
      y: -198,
      w: 35,
      h: 25,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 145,
      y: -198,
      w: 226,
      h: 25,
    },
    {
      keyName: 'r_Alt',
      value: 230,
      x: 384,
      y: -198,
      w: 25,
      h: 25,
    },
    {
      keyName: 'FN',
      value: 0x0a010000,
      x: 423,
      y: -198,
      w: 25,
      h: 25,
    },
    {
      keyName: 'r_Ctrl',
      value: 228,
      x: 461,
      y: -198,
      w: 25,
      h: 25,
    },
    {
      keyName: '←',
      value: 80,
      x: 499,
      y: -198,
      w: 25,
      h: 25,
    },
    {
      keyName: '↓',
      value: 81,
      x: 538,
      y: -198,
      w: 25,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
      h: 25,
    },
    {
      keyName: '→',
      value: 79,
      x: 576,
      y: -198,
      w: 25,
      h: 25,
    },
  ],
}
