export const yc300_mek18_21 = {
  deltX: 359,
  deltY: 19,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 28,
      h: 32,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 42,
      y: 0,
      w: 28,
      h: 32,
    },
    {
      keyName: 'BackSpace',
      value: 42,
      x: 84,
      y: 0,
      w: 28,
      h: 32,
    },
    {
      keyName: 'FN',
      value: 0x0a010000,
      x: 127,
      y: 0,
      w: 28,
      h: 32,
    },
    {
      keyName: 'Num\nLock',
      value: 83,
      x: 0,
      y: -42,
      w: 28,
      h: 32,
    },
    {
      keyName: 'num_/',
      value: 84,
      x: 42,
      y: -42,
      w: 28,
      h: 32,
    },
    {
      keyName: 'num_*',
      value: 85,
      x: 84,
      y: -42,
      w: 28,
      h: 32,
    },
    {
      keyName: 'num_-',
      value: 86,
      x: 127,
      y: -42,
      w: 28,
      h: 32,
    },
    {
      keyName: 'num_7',
      value: 95,
      x: 0,
      y: -85,
      w: 28,
      h: 32,
    },
    {
      keyName: 'num_8',
      value: 96,
      x: 42,
      y: -85,
      w: 28,
      h: 32,
    },
    {
      keyName: 'num_9',
      value: 97,
      x: 84,
      y: -85,
      w: 28,
      h: 32,
    },
    {
      keyName: 'num_+',
      value: 87,
      x: 127,
      y: -85,
      w: 28,
      h: 72,
    },
    {
      keyName: 'num_4',
      value: 92,
      x: 0,
      y: -127,
      w: 28,
      h: 32,
    },
    {
      keyName: 'num_5',
      value: 93,
      x: 42,
      y: -127,
      w: 28,
      h: 32,
    },
    {
      keyName: 'num_6',
      value: 94,
      x: 84,
      y: -127,
      w: 28,
      h: 32,
    },
    {
      keyName: 'num_1',
      value: 89,
      x: 0,
      y: -169,
      w: 28,
      h: 32,
    },
    {
      keyName: 'num_2',
      value: 90,
      x: 42,
      y: -169,
      w: 28,
      h: 32,
    },
    {
      keyName: 'num_3',
      value: 91,
      x: 84,
      y: -169,
      w: 28,
      h: 32,
    },
    {
      keyName: 'num_Enter',
      value: 88,
      x: 127,
      y: -169,
      w: 28,
      h: 72,
    },
    {
      keyName: 'num_0',
      value: 98,
      x: 0,
      y: -210,
      w: 70,
      h: 32,
    },
    {
      keyName: 'num_.',
      value: 99,
      x: 84,
      y: -210,
      w: 28,
      h: 32,
    },
  ],
}
