export const yc300_gi80 = {
  deltX: 115,
  deltY: 21,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 26,
      h: 29,
     },
    {
      keyName: 'F1',
      value: 58,
      x: 80,
      y: 0,
      w: 26,
      h: 29,
    },
    {
      keyName: 'F2',
      value: 59,
      x: 120,
      y: 0,
      w: 26,
      h: 29,
    },
    {
      keyName: 'F3',
      value: 60,
      x: 160,
      y: 0,
      w: 26,
      h: 29,
    },
    {
      keyName: 'F4',
      value: 61,
      x: 199,
      y: 0,
      w: 26,
      h: 29,
    },
    {
      keyName: 'F5',
      value: 62,
      x: 260,
      y: 0,
      w: 26,
      h: 29,
    },
    {
      keyName: 'F6',
      value: 63,
      x: 299,
      y: 0,
      w: 26,
      h: 29,
    },
    {
      keyName: 'F7',
      value: 64,
      x: 339,
      y: 0,
      w: 26,
      h: 29,
    },
    {
      keyName: 'F8',
      value: 65,
      x: 378,
      y: 0,
      w: 26,
      h: 29,
    },
    {
      keyName: 'F9',
      value: 66,
      x: 439,
      y: 0,
      w: 26,
      h: 29,
    },
    {
      keyName: 'F10',
      value: 67,
      x: 479,
      y: 0,
      w: 26,
      h: 29,
    },
    {
      keyName: 'F11',
      value: 68,
      x: 518,
      y: 0,
      w: 26,
      h: 29,
    },
    {
      keyName: 'F12',
      value: 69,
      x: 558,
      y: 0,
      w: 26,
      h: 29,
    },
    {
      keyName: 'U-',
      value: 0x0300ea00,
      knob: true,
      x: 609,
      y: 0,
      w: 11,
      h: 35,
    },
    {
      keyName: 'play',
      value: 0x0300e200,
      knob: true,
      x: 625,
      y: 0,
      w: 11,
      h: 35,
    },
    {
      keyName: 'U+',
      value: 0x0300e900,
      knob: true,
      x: 640,
      y: 0,
      w: 11,
      h: 35,
    },
    {
      keyName: '`',
      value: 53,
      x: 0,
      y: -55,
      w: 26,
      h: 29,
    },
    {
      keyName: '1',
      value: 30,
      x: 41,
      y: -55,
      w: 26,
      h: 29,
    },
    {
      keyName: '2',
      value: 31,
      x: 81,
      y: -55,
      w: 26,
      h: 29,
    },
    {
      keyName: '3',
      value: 32,
      x: 120,
      y: -55,
      w: 26,
      h: 29,
    },
    {
      keyName: '4',
      value: 33,
      x: 160,
      y: -55,
      w: 26,
      h: 29,
    },
    {
      keyName: '5',
      value: 34,
      x: 200,
      y: -55,
      w: 26,
      h: 29,
    },
    {
      keyName: '6',
      value: 35,
      x: 239,
      y: -55,
      w: 26,
      h: 29,
    },
    {
      keyName: '7',
      value: 36,
      x: 279,
      y: -55,
      w: 26,
      h: 29,
    },
    {
      keyName: '8',
      value: 37,
      x: 319,
      y: -55,
      w: 26,
      h: 29,
    },
    {
      keyName: '9',
      value: 38,
      x: 359,
      y: -55,
      w: 26,
      h: 29,
    },
    {
      keyName: '0',
      value: 39,
      x: 398,
      y: -55,
      w: 26,
      h: 29,
    },
    {
      keyName: '-',
      value: 45,
      x: 438,
      y: -55,
      w: 26,
      h: 29,
    },
    {
      keyName: '=',
      value: 46,
      x: 478,
      y: -55,
      w: 26,
      h: 29,
    },
    {
      keyName: 'BackSpace',
      value: 42,
      x: 517,
      y: -55,
      w: 67,
      h: 29,
    },
    {
      keyName: 'Delete',
      value: 76,
      x: 616,
      y: -55,
      w: 26,
      h: 29,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -94,
      w: 48,
      h: 29,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 62,
      y: -94,
      w: 26,
      h: 29,
    },
    {
      keyName: 'W',
      value: 26,
      x: 102,
      y: -94,
      w: 26,
      h: 29,
    },
    {
      keyName: 'E',
      value: 8,
      x: 141,
      y: -94,
      w: 26,
      h: 29,
    },
    {
      keyName: 'R',
      value: 21,
      x: 181,
      y: -94,
      w: 26,
      h: 29,
    },
    {
      keyName: 'T',
      value: 23,
      x: 220,
      y: -94,
      w: 26,
      h: 29,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 259,
      y: -94,
      w: 26,
      h: 29,
    },
    {
      keyName: 'U',
      value: 24,
      x: 299,
      y: -94,
      w: 26,
      h: 29,
    },
    {
      keyName: 'I',
      value: 12,
      x: 339,
      y: -94,
      w: 26,
      h: 29,
    },
    {
      keyName: 'O',
      value: 18,
      x: 378,
      y: -94,
      w: 26,
      h: 29,
    },
    {
      keyName: 'P',
      value: 19,
      x: 418,
      y: -94,
      w: 26,
      h: 29,
    },
    {
      keyName: '[',
      value: 47,
      x: 457,
      y: -94,
      w: 26,
      h: 29,
    },
    {
      keyName: ']',
      value: 48,
      x: 497,
      y: -94,
      w: 26,
      h: 29,
    },
    {
      keyName: '\\',
      value: 49,
      x: 536,
      y: -94,
      w: 48,
      h: 29,
    },
    {
      keyName: 'Home',
      value: 74,
      x: 616,
      y: -94,
      w: 26,
      h: 29,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -133,
      w: 58,
      h: 29,
    },
    {
      keyName: 'A',
      value: 4,
      x: 72,
      y: -133,
      w: 26,
      h: 29,
    },
    {
      keyName: 'S',
      value: 22,
      x: 112,
      y: -133,
      w: 26,
      h: 29,
    },
    {
      keyName: 'D',
      value: 7,
      x: 151,
      y: -133,
      w: 26,
      h: 29,
    },
    {
      keyName: 'F',
      value: 9,
      x: 191,
      y: -133,
      w: 26,
      h: 29,
    },
    {
      keyName: 'G',
      value: 10,
      x: 230,
      y: -133,
      w: 26,
      h: 29,
    },
    {
      keyName: 'H',
      value: 11,
      x: 269,
      y: -133,
      w: 26,
      h: 29,
    },
    {
      keyName: 'J',
      value: 13,
      x: 309,
      y: -133,
      w: 26,
      h: 29,
    },
    {
      keyName: 'K',
      value: 14,
      x: 349,
      y: -133,
      w: 26,
      h: 29,
    },
    {
      keyName: 'L',
      value: 15,
      x: 388,
      y: -133,
      w: 26,
      h: 29,
    },
    {
      keyName: ';',
      value: 51,
      x: 428,
      y: -133,
      w: 26,
      h: 29,
    },
    {
      keyName: '\'',
      value: 52,
      x: 467,
      y: -133,
      w: 26,
      h: 29,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 506,
      y: -133,
      w: 78,
      h: 29,
    },
    {
      keyName: 'Page\nUp',
      value: 75,
      x: 616,
      y: -133,
      w: 26,
      h: 29,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -172,
      w: 78,
      h: 29,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 92,
      y: -172,
      w: 26,
      h: 29,
    },
    {
      keyName: 'X',
      value: 27,
      x: 132,
      y: -172,
      w: 26,
      h: 29,
    },
    {
      keyName: 'C',
      value: 6,
      x: 171,
      y: -172,
      w: 26,
      h: 29,
    },
    {
      keyName: 'V',
      value: 25,
      x: 211,
      y: -172,
      w: 26,
      h: 29,
    },
    {
      keyName: 'B',
      value: 5,
      x: 250,
      y: -172,
      w: 26,
      h: 29,
    },
    {
      keyName: 'N',
      value: 17,
      x: 289,
      y: -172,
      w: 26,
      h: 29,
    },
    {
      keyName: 'M',
      value: 16,
      x: 329,
      y: -172,
      w: 26,
      h: 29,
    },
    {
      keyName: ',',
      value: 54,
      x: 369,
      y: -172,
      w: 26,
      h: 29,
    },
    {
      keyName: '.',
      value: 55,
      x: 408,
      y: -172,
      w: 26,
      h: 29,
    },
    {
      keyName: '/',
      value: 56,
      x: 448,
      y: -172,
      w: 26,
      h: 29,
    },
    {
      keyName: 'r_Shift',
      value: 229,
      x: 487,
      y: -172,
      w: 55,
      h: 29,
    },
    {
      keyName: 'Page\nDown',
      value: 78,
      x: 616,
      y: -172,
      w: 26,
      h: 29,
    },
    {
      keyName: 'Ctrl',
      value: 224,
      x: 0,
      y: -211,
      w: 39,
      h: 29,
    },
    {
      keyName: 'Win',
      value: 227,
      x: 51,
      y: -211,
      w: 39,
      h: 29,
    },
    {
      keyName: 'Alt',
      value: 226,
      x: 101,
      y: -211,
      w: 39,
      h: 29,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 152,
      y: -211,
      w: 233,
      h: 29,
    },
    {
      keyName: 'r_Alt',
      value: 230,
      x: 398,
      y: -211,
      w: 26,
      h: 29,
    },
    {
      keyName: 'FN',
      value: 0x0a010000,
      x: 437,
      y: -211,
      w: 26,
      h: 29,
    },
    {
      keyName: 'r_Ctrl',
      value: 228,
      x: 477,
      y: -211,
      w: 26,
      h: 29,
    },
    {
      keyName: '↑',
      value: 82,
      x: 566,
      y: -182,
      w: 26,
      h: 29,
    },
    {
      keyName: '←',
      value: 80,
      x: 526,
      y: -221,
      w: 26,
      h: 29,
    },
    {
      keyName: '↓',
      value: 81,
      x: 566,
      y: -221,
      w: 26,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
      h: 29,
    },
    {
      keyName: '→',
      value: 79,
      x: 605,
      y: -221,
      w: 26,
      h: 29,
    },
  ],
}
