export const yc300_y68 = {
  deltX: 75,
  deltY: 33,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 31,
      h: 36,
    },
    {
      keyName: '1',
      value: 30,
      x: 46,
      y: 0,
      w: 31,
      h: 36,
    },
    {
      keyName: '2',
      value: 31,
      x: 92,
      y: 0,
      w: 31,
      h: 36,
    },
    {
      keyName: '3',
      value: 32,
      x: 138,
      y: 0,
      w: 31,
      h: 36,
    },
    {
      keyName: '4',
      value: 33,
      x: 185,
      y: 0,
      w: 31,
      h: 36,
    },
    {
      keyName: '5',
      value: 34,
      x: 231,
      y: 0,
      w: 31,
      h: 36,
    },
    {
      keyName: '6',
      value: 35,
      x: 277,
      y: 0,
      w: 31,
      h: 36,
    },
    {
      keyName: '7',
      value: 36,
      x: 323,
      y: 0,
      w: 31,
      h: 36,
    },
    {
      keyName: '8',
      value: 37,
      x: 369,
      y: 0,
      w: 31,
      h: 36,
    },
    {
      keyName: '9',
      value: 38,
      x: 415,
      y: 0,
      w: 31,
      h: 36,
    },
    {
      keyName: '0',
      value: 39,
      x: 461,
      y: 0,
      w: 31,
      h: 36,
    },
    {
      keyName: '-',
      value: 45,
      x: 507,
      y: 0,
      w: 31,
      h: 36,
    },
    {
      keyName: '=',
      value: 46,
      x: 553,
      y: 0,
      w: 31,
      h: 36,
    },
    {
      keyName: 'Backspace',
      value: 42,
      x: 599,
      y: 0,
      w: 77,
      h: 36,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -46,
      w: 54,
      h: 36,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 69,
      y: -46,
      w: 31,
      h: 36,
    },
    {
      keyName: 'W',
      value: 26,
      x: 115,
      y: -46,
      w: 31,
      h: 36,
    },
    {
      keyName: 'E',
      value: 8,
      x: 161,
      y: -46,
      w: 31,
      h: 36,
    },
    {
      keyName: 'R',
      value: 21,
      x: 207,
      y: -46,
      w: 31,
      h: 36,
    },
    {
      keyName: 'T',
      value: 23,
      x: 253,
      y: -46,
      w: 31,
      h: 36,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 299,
      y: -46,
      w: 31,
      h: 36,
    },
    {
      keyName: 'U',
      value: 24,
      x: 346,
      y: -46,
      w: 31,
      h: 36,
    },
    {
      keyName: 'I',
      value: 12,
      x: 392,
      y: -46,
      w: 31,
      h: 36,
    },
    {
      keyName: 'O',
      value: 18,
      x: 438,
      y: -46,
      w: 31,
      h: 36,
    },
    {
      keyName: 'P',
      value: 19,
      x: 484,
      y: -46,
      w: 31,
      h: 36,
    },
    {
      keyName: '[',
      value: 47,
      x: 530,
      y: -46,
      w: 31,
      h: 36,
    },
    {
      keyName: ']',
      value: 48,
      x: 576,
      y: -46,
      w: 31,
      h: 36,
    },
    {
      keyName: '\\',
      value: 49,
      x: 622,
      y: -46,
      w: 54,
      h: 36,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -92,
      w: 65,
      h: 36,
    },
    {
      keyName: 'A',
      value: 4,
      x: 80,
      y: -92,
      w: 31,
      h: 36,
    },
    {
      keyName: 'S',
      value: 22,
      x: 126,
      y: -92,
      w: 31,
      h: 36,
    },
    {
      keyName: 'D',
      value: 7,
      x: 172,
      y: -92,
      w: 31,
      h: 36,
    },
    {
      keyName: 'F',
      value: 9,
      x: 218,
      y: -92,
      w: 31,
      h: 36,
    },
    {
      keyName: 'G',
      value: 10,
      x: 264,
      y: -92,
      w: 31,
      h: 36,
    },
    {
      keyName: 'H',
      value: 11,
      x: 310,
      y: -92,
      w: 31,
      h: 36,
    },
    {
      keyName: 'J',
      value: 13,
      x: 357,
      y: -92,
      w: 31,
      h: 36,
    },
    {
      keyName: 'K',
      value: 14,
      x: 403,
      y: -92,
      w: 31,
      h: 36,
    },
    {
      keyName: 'L',
      value: 15,
      x: 449,
      y: -92,
      w: 31,
      h: 36,
    },
    {
      keyName: ';',
      value: 51,
      x: 495,
      y: -92,
      w: 31,
      h: 36,
    },
    {
      keyName: '"',
      value: 52,
      x: 541,
      y: -92,
      w: 31,
      h: 36,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 587,
      y: -92,
      w: 89,
      h: 36,
    },
    {
      keyName: 'r_FN',
      value: 0x0a010100,
      x: 691,
      y: -92,
      w: 31,
      h: 36,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -138,
      w: 88,
      h: 36,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 104,
      y: -138,
      w: 31,
      h: 36,
    },
    {
      keyName: 'X',
      value: 27,
      x: 150,
      y: -138,
      w: 31,
      h: 36,
    },
    {
      keyName: 'C',
      value: 6,
      x: 196,
      y: -138,
      w: 31,
      h: 36,
    },
    {
      keyName: 'V',
      value: 25,
      x: 242,
      y: -138,
      w: 31,
      h: 36,
    },
    {
      keyName: 'B',
      value: 5,
      x: 288,
      y: -138,
      w: 31,
      h: 36,
    },
    {
      keyName: 'N',
      value: 17,
      x: 334,
      y: -138,
      w: 31,
      h: 36,
    },
    {
      keyName: 'M',
      value: 16,
      x: 381,
      y: -138,
      w: 31,
      h: 36,
    },
    {
      keyName: ',',
      value: 54,
      x: 427,
      y: -138,
      w: 31,
      h: 36,
    },
    {
      keyName: '.',
      value: 55,
      x: 473,
      y: -138,
      w: 31,
      h: 36,
    },
    {
      keyName: '/',
      value: 56,
      x: 519,
      y: -138,
      w: 31,
      h: 36,
    },
    {
      keyName: 'R-Shift',
      value: 229,
      x: 565,
      y: -138,
      w: 64,
      h: 36,
    },
    {
      keyName: '↑',
      value: 82,
      x: 645,
      y: -138,
      w: 31,
      h: 36,
    },
    {
      keyName: 'Delete',
      value:  76,
      x: 691,
      y: -138,
      w: 31,
      h: 36,
    },
    {
      keyName: 'Ctrl',
      value: 224,
      x: 0,
      y: -184,
      w: 42,
      h: 36,
    },
    {
      keyName: 'win',
      value: 227,
      x: 58,
      y: -184,
      w: 42,
      h: 36,
    },
    {
      keyName: 'Alt',
      value: 226,
      x: 115,
      y: -184,
      w: 42,
      h: 36,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 173,
      y: -184,
      w: 273,
      h: 36,
    },
    {
      keyName: 'r-Alt',
      value: 230,
      x: 461,
      y: -184,
      w: 31,
      h: 36,
    },
    {
      keyName: 'Fn',
      value: 0x0a010000,
      x: 507,
      y: -184,
      w: 31,
      h: 36,
    },
    {
      keyName: 'r-Ctrl',
      value: 228,
      x: 553,
      y: -184,
      w: 31,
      h: 36,
    },
    {
      keyName: '←',
      value: 80,
      x: 599,
      y: -184,
      w: 31,
      h: 36,
    },
    {
      keyName: '↓',
      value: 81,
      x: 645,
      y: -184,
      w: 31,
      h: 36,
    },
    {
      keyName: '→',
      value: 79,
      x: 691,
      y: -184,
      w: 31,
      h: 36,
    },
  ],
}
