export const yc300_yz21_dm= {
  deltX: 355,
  deltY: 15,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 32,
      h: 33,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 43,
      y: 0,
      w: 32,
      h: 33,
    },
    {
      keyName: 'FN',
      value: 0x0a010000,
      x: 86,
      y: 0,
      w: 32,
      h: 33,
    },
    {
      keyName: 'BackSpace',
      value: 42,
      x: 130,
      y: 0,
      w: 32,
      h: 33,
    },
    {
      keyName: 'Num\nLock',
      value: 83,
      x: 0,
      y: -58,
      w: 32,
      h: 33,
    },
    {
      keyName: 'num_/',
      value: 84,
      x: 43,
      y: -58,
      w: 32,
      h: 33,
    },
    {
      keyName: 'num_*',
      value: 85,
      x: 86,
      y: -58,
      w: 32,
      h: 33,
    },
    {
      keyName: 'num_-',
      value: 86,
      x: 129,
      y: -58,
      w: 32,
      h: 33,
    },
    {
      keyName: 'num_7',
      value: 95,
      x: 0,
      y: -101,
      w: 32,
      h: 33,
    },
    {
      keyName: 'num_8',
      value: 96,
      x: 43,
      y: -101,
      w: 32,
      h: 33,
    },
    {
      keyName: 'num_9',
      value: 97,
      x: 86,
      y: -101,
      w: 32,
      h: 33,
    },
    {
      keyName: 'num_+',
      value: 87,
      x: 129,
      y: -101,
      w: 32,
      h: 73,
    },
    {
      keyName: 'num_4',
      value: 92,
      x: 0,
      y: -144,
      w: 32,
      h: 33,
    },
    {
      keyName: 'num_5',
      value: 93,
      x: 43,
      y: -144,
      w: 32,
      h: 33,
    },
    {
      keyName: 'num_6',
      value: 94,
      x: 86,
      y: -144,
      w: 32,
      h: 33,
    },
    {
      keyName: 'num_1',
      value: 89,
      x: 0,
      y: -186,
      w: 32,
      h: 33,
    },
    {
      keyName: 'num_2',
      value: 90,
      x: 43,
      y: -186,
      w: 32,
      h: 33,
    },
    {
      keyName: 'num_3',
      value: 91,
      x: 86,
      y: -186,
      w: 32,
      h: 33,
    },
    {
      keyName: 'num_Enter',
      value: 88,
      x: 129,
      y: -186,
      w: 32,
      h: 73,
    },
    {
      keyName: 'num_0',
      value: 98,
      x: 0,
      y: -228,
      w: 76,
      h: 33,
    },
    {
      keyName: 'num_.',
      value: 99,
      x: 86,
      y: -228,
      w: 32,
      h: 33,
    },
  ],
}
