export const yc300_yk630us_a = {
  deltX: 29,
  deltY: 34,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 38,
      h: 31,
     },
    {
      keyName: '1',
      value: 30,
      x: 56,
      y: 0,
      w: 38,
      h: 31,
    },
    {
      keyName: '2',
      value: 31,
      x: 112,
      y: 0,
      w: 38,
      h: 31,
    },
    {
      keyName: '3',
      value: 32,
      x: 168,
      y: 0,
      w: 38,
      h: 31,
    },
    {
      keyName: '4',
      value: 33,
      x: 224,
      y: 0,
      w: 38,
      h: 31,
    },
    {
      keyName: '5',
      value: 34,
      x: 280,
      y: 0,
      w: 38,
      h: 31,
    },
    {
      keyName: '6',
      value: 35,
      x: 336,
      y: 0,
      w: 38,
      h: 31,
    },
    {
      keyName: '7',
      value: 36,
      x: 392,
      y: 0,
      w: 38,
      h: 31,
    },
    {
      keyName: '8',
      value: 37,
      x: 448,
      y: 0,
      w: 38,
      h: 31,
    },
    {
      keyName: '9',
      value: 38,
      x: 502,
      y: 0,
      w: 38,
      h: 31,
    },
    {
      keyName: '0',
      value: 39,
      x: 556,
      y: 0,
      w: 38,
      h: 31,
    },
    {
      keyName: '-',
      value: 45,
      x: 612,
      y: 0,
      w: 38,
      h: 31,
    },
    {
      keyName: '=',
      value: 46,
      x: 668,
      y: 0,
      w: 38,
      h: 31,
    },
    {
      keyName: 'Backspace',
      value: 42,
      x: 724,
      y: 0,
      w: 95,
      h: 31,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -46,
      w: 98,
      h: 31,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 114,
      y: -46,
      w: 38,
      h: 31,
    },
    {
      keyName: 'W',
      value: 26,
      x: 170,
      y: -46,
      w: 38,
      h: 31,
    },
    {
      keyName: 'E',
      value: 8,
      x: 226,
      y: -46,
      w: 38,
      h: 31,
    },
    {
      keyName: 'R',
      value: 21,
      x: 282,
      y: -46,
      w: 38,
      h: 31,
    },
    {
      keyName: 'T',
      value: 23,
      x: 338,
      y: -46,
      w: 38,
      h: 31,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 394,
      y: -46,
      w: 38,
      h: 31,
    },
    {
      keyName: 'U',
      value: 24,
      x: 450,
      y: -46,
      w: 38,
      h: 31,
    },
    {
      keyName: 'I',
      value: 12,
      x: 504,
      y: -46,
      w: 38,
      h: 31,
    },
    {
      keyName: 'O',
      value: 18,
      x: 558,
      y: -46,
      w: 38,
      h: 31,
    },
    {
      keyName: 'P',
      value: 19,
      x: 614,
      y: -46,
      w: 38,
      h: 31,
    },
    {
      keyName: '[',
      value: 47,
      x: 670,
      y: -46,
      w: 38,
      h: 31,
    },
    {
      keyName: ']',
      value: 48,
      x: 724,
      y: -46,
      w: 38,
      h: 31,
    },
    {
      keyName: '\\',
      value: 49,
      x: 780,
      y: -46,
      w: 38,
      h: 31,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -92,
      w: 82,
      h: 31,
    },
    {
      keyName: 'A',
      value: 4,
      x: 99,
      y: -92,
      w: 38,
      h: 31,
    },
    {
      keyName: 'S',
      value: 22,
      x: 155,
      y: -92,
      w: 38,
      h: 31,
    },
    {
      keyName: 'D',
      value: 7,
      x: 211,
      y: -92,
      w: 38,
      h: 31,
    },
    {
      keyName: 'F',
      value: 9,
      x: 267,
      y: -92,
      w: 38,
      h: 31,
    },
    {
      keyName: 'G',
      value: 10,
      x: 323,
      y: -92,
      w: 38,
      h: 31,
    },
    {
      keyName: 'H',
      value: 11,
      x: 379,
      y: -92,
      w: 38,
      h: 31,
    },
    {
      keyName: 'J',
      value: 13,
      x: 435,
      y: -92,
      w: 38,
      h: 31,
    },
    {
      keyName: 'K',
      value: 14,
      x: 489,
      y: -92,
      w: 38,
      h: 31,
    },
    {
      keyName: 'L',
      value: 15,
      x: 543,
      y: -92,
      w: 38,
      h: 31,
    },
    {
      keyName: ';',
      value: 51,
      x: 599,
      y: -92,
      w: 38,
      h: 31,
    },
    {
      keyName: '\'',
      value: 52,
      x: 655,
      y: -92,
      w: 38,
      h: 31,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 709,
      y: -88,
      w: 109,
      h: 31,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -138,
      w: 109,
      h: 31,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 127,
      y: -138,
      w: 38,
      h: 31,
    },
    {
      keyName: 'X',
      value: 27,
      x: 183,
      y: -138,
      w: 38,
      h: 31,
    },
    {
      keyName: 'C',
      value: 6,
      x: 239,
      y: -138,
      w: 38,
      h: 31,
    },
    {
      keyName: 'V',
      value: 25,
      x: 295,
      y: -138,
      w: 38,
      h: 31,
    },
    {
      keyName: 'B',
      value: 5,
      x: 351,
      y: -138,
      w: 38,
      h: 31,
    },
    {
      keyName: 'N',
      value: 17,
      x: 407,
      y: -138,
      w: 38,
      h: 31,
    },
    {
      keyName: 'M',
      value: 16,
      x: 463,
      y: -138,
      w: 38,
      h: 31,
    },
    {
      keyName: ',',
      value: 54,
      x: 517,
      y: -138,
      w: 38,
      h: 31,
    },
    {
      keyName: '.',
      value: 55,
      x: 571,
      y: -138,
      w: 38,
      h: 31,
    },
    {
      keyName: 'r_Shift',
      value: 229,
      x: 627,
      y: -138,
      w: 79,
      h: 31,
    },
    {
      keyName: '↑',
      value: 82,
      x: 723,
      y: -138,
      w: 38,
      h: 31,
    },
    {
      keyName: '/',
      value: 56,
      x: 777,
      y: -138,
      w: 38,
      h: 31,
    },
    {
      keyName: 'CTRL',
      value: 224,
      x: 0,
      y: -182,
      w: 65,
      h: 31,
    },
    {
      keyName: 'Win',
      value: 227,
      x: 85,
      y: -182,
      w: 51,
      h: 31,
    },
    {
      keyName: 'ALT',
      value: 226,
      x: 156,
      y: -182,
      w: 51,
      h: 31,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 226,
      y: -182,
      w: 297,
      h: 31,
    },
    {
      keyName: 'r_ALT',
      value: 230,
      x: 543,
      y: -182,
      w: 51,
      h: 31,
    },
    {
      keyName: 'FN',
      value: 0x0a010000,
      x: 612,
      y: -182,
      w: 38,
      h: 31,
    },
    {
      keyName: '←',
      value: 80,
      x: 668,
      y: -182,
      w: 38,
      h: 31,
    },
    {
      keyName: '↓',
      value: 81,
      x: 720,
      y: -182,
      w: 38,
      h: 31,
    },
    {
      keyName: '→',
      value: 79,
      x: 776,
      y: -182,
      w: 38,
      h: 31,
    },
  ],
}
