
export const yc300_h75s = {
  deltX: 132,
  deltY: 29,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 25,
      h: 27,
     },
    {
      keyName: 'F1',
      value: 58,
      x: 47,
      y: 0,
      w: 25,
      h: 27,
    },
    {
      keyName: 'F2',
      value: 59,
      x: 84,
      y: 0,
      w: 25,
      h: 27,
    },
    {
      keyName: 'F3',
      value: 60,
      x: 122,
      y: 0,
      w: 25,
      h: 27,
    },
    {
      keyName: 'F4',
      value: 61,
      x: 160,
      y: 0,
      w: 25,
      h: 27,
    },
    {
      keyName: 'F5',
      value: 62,
      x: 207,
      y: 0,
      w: 25,
      h: 27,
    },
    {
      keyName: 'F6',
      value: 63,
      x: 245,
      y: 0,
      w: 25,
      h: 27,
    },
    {
      keyName: 'F7',
      value: 64,
      x: 282,
      y: 0,
      w: 25,
      h: 27,
    },
    {
      keyName: 'F8',
      value: 65,
      x: 320,
      y: 0,
      w: 25,
      h: 27,
    },
    {
      keyName: 'F9',
      value: 66,
      x: 367,
      y: 0,
      w: 25,
      h: 27,
    },
    {
      keyName: 'F10',
      value: 67,
      x: 404,
      y: 0,
      w: 25,
      h: 27,
    },
    {
      keyName: 'F11',
      value: 68,
      x: 442,
      y: 0,
      w: 25,
      h: 27,
    },
    {
      keyName: 'F12',
      value: 69,
      x: 480,
      y: 0,
      w: 25,
      h: 27,
    },
    {
      keyName: 'Delete',
      value: 76,
      x: 527,
      y: 0,
      w: 25,
      h: 27,
    },
    {
      keyName: 'U-',
      value: 0x0300ea00,
      ban: true,
      knob: true,
      x: 570,
      y: 10,
      w: 12,
      h: 47,
    },
    {
      keyName: '音量<->键盘亮度',
      value: 0x0a0f0000,
      ban: true,
      knob: true,
      x: 590,
      y: 10,
      w: 12,
      h: 47,
    },
    {
      keyName: 'U+',
      value: 0x0300e900,
      knob: true,
      ban: true,
      x: 609,
      y: 10,
      w: 12,
      h: 47,
    },
    {
      keyName: '`',
      value: 53,
      x: 0,
      y: -46,
      w: 25,
      h: 27,
    },
    {
      keyName: '1',
      value: 30,
      x: 37,
      y: -46,
      w: 25,
      h: 27,
    },
    {
      keyName: '2',
      value: 31,
      x: 74,
      y: -46,
      w: 25,
      h: 27,
    },
    {
      keyName: '3',
      value: 32,
      x: 112,
      y: -46,
      w: 25,
      h: 27,
    },
    {
      keyName: '4',
      value: 33,
      x: 150,
      y: -46,
      w: 25,
      h: 27,
    },
    {
      keyName: '5',
      value: 34,
      x: 188,
      y: -46,
      w: 25,
      h: 27,
    },
    {
      keyName: '6',
      value: 35,
      x: 225,
      y: -46,
      w: 25,
      h: 27,
    },
    {
      keyName: '7',
      value: 36,
      x: 263,
      y: -46,
      w: 25,
      h: 27,
    },
    {
      keyName: '8',
      value: 37,
      x: 301,
      y: -46,
      w: 25,
      h: 27,
    },
    {
      keyName: '9',
      value: 38,
      x: 339,
      y: -46,
      w: 25,
      h: 27,
    },
    {
      keyName: '0',
      value: 39,
      x: 376,
      y: -46,
      w: 25,
      h: 27,
    },
    {
      keyName: '-',
      value: 45,
      x: 414,
      y: -46,
      w: 25,
      h: 27,
    },
    {
      keyName: '=',
      value: 46,
      x: 452,
      y: -46,
      w: 25,
      h: 27,
    },
    {
      keyName: 'BackSpace',
      value: 42,
      x: 489,
      y: -46,
      w: 63,
      h: 27,
    },
    {
      keyName: 'Home',
      value: 74,
      x: 583,
      y: -46,
      w: 25,
      h: 27,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -84,
      w: 44,
      h: 27,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 56,
      y: -84,
      w: 25,
      h: 27,
    },
    {
      keyName: 'W',
      value: 26,
      x: 93,
      y: -84,
      w: 25,
      h: 27,
    },
    {
      keyName: 'E',
      value: 8,
      x: 131,
      y: -84,
      w: 25,
      h: 27,
    },
    {
      keyName: 'R',
      value: 21,
      x: 169,
      y: -84,
      w: 25,
      h: 27,
    },
    {
      keyName: 'T',
      value: 23,
      x: 207,
      y: -84,
      w: 25,
      h: 27,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 245,
      y: -84,
      w: 25,
      h: 27,
    },
    {
      keyName: 'U',
      value: 24,
      x: 282,
      y: -84,
      w: 25,
      h: 27,
    },
    {
      keyName: 'I',
      value: 12,
      x: 320,
      y: -84,
      w: 25,
      h: 27,
    },
    {
      keyName: 'O',
      value: 18,
      x: 358,
      y: -84,
      w: 25,
      h: 27,
    },
    {
      keyName: 'P',
      value: 19,
      x: 395,
      y: -84,
      w: 25,
      h: 27,
    },
    {
      keyName: '[',
      value: 47,
      x: 433,
      y: -84,
      w: 25,
      h: 27,
    },
    {
      keyName: ']',
      value: 48,
      x: 471,
      y: -84,
      w: 25,
      h: 27,
    },
    {
      keyName: '\\',
      value: 49,
      x: 508,
      y: -84,
      w: 44,
      h: 27,
    },
    {
      keyName: 'Page\nUp',
      value: 75,
      x: 583,
      y: -84,
      w: 25,
      h: 27,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -122,
      w: 53,
      h: 27,
    },
    {
      keyName: 'A',
      value: 4,
      x: 66,
      y: -122,
      w: 25,
      h: 27,
    },
    {
      keyName: 'S',
      value: 22,
      x: 103,
      y: -122,
      w: 25,
      h: 27,
    },
    {
      keyName: 'D',
      value: 7,
      x: 141,
      y: -122,
      w: 25,
      h: 27,
    },
    {
      keyName: 'F',
      value: 9,
      x: 179,
      y: -122,
      w: 25,
      h: 27,
    },
    {
      keyName: 'G',
      value: 10,
      x: 217,
      y: -122,
      w: 25,
      h: 27,
    },
    {
      keyName: 'H',
      value: 11,
      x: 254,
      y: -122,
      w: 25,
      h: 27,
    },
    {
      keyName: 'J',
      value: 13,
      x: 291,
      y: -122,
      w: 25,
      h: 27,
    },
    {
      keyName: 'K',
      value: 14,
      x: 329,
      y: -122,
      w: 25,
      h: 27,
    },
    {
      keyName: 'L',
      value: 15,
      x: 367,
      y: -122,
      w: 25,
      h: 27,
    },
    {
      keyName: ';',
      value: 51,
      x: 405,
      y: -122,
      w: 25,
      h: 27,
    },
    {
      keyName: '\'',
      value: 52,
      x: 442,
      y: -122,
      w: 25,
      h: 27,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 480,
      y: -122,
      w: 72,
      h: 27,
    },
    {
      keyName: 'Page\nDown',
      value: 78,
      x: 583,
      y: -122,
      w: 25,
      h: 27,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -159,
      w: 72,
      h: 27,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 84,
      y: -159,
      w: 25,
      h: 27,
    },
    {
      keyName: 'X',
      value: 27,
      x: 122,
      y: -159,
      w: 25,
      h: 27,
    },
    {
      keyName: 'C',
      value: 6,
      x: 159,
      y: -159,
      w: 25,
      h: 27,
    },
    {
      keyName: 'V',
      value: 25,
      x: 197,
      y: -159,
      w: 25,
      h: 27,
    },
    {
      keyName: 'B',
      value: 5,
      x: 236,
      y: -159,
      w: 25,
      h: 27,
    },
    {
      keyName: 'N',
      value: 17,
      x: 273,
      y: -159,
      w: 25,
      h: 27,
    },
    {
      keyName: 'M',
      value: 16,
      x: 311,
      y: -159,
      w: 25,
      h: 27,
    },
    {
      keyName: ',',
      value: 54,
      x: 348,
      y: -159,
      w: 25,
      h: 27,
    },
    {
      keyName: '.',
      value: 55,
      x: 386,
      y: -159,
      w: 25,
      h: 27,
    },
    {
      keyName: '/',
      value: 56,
      x: 424,
      y: -159,
      w: 25,
      h: 27,
    },
    {
      keyName: 'r_Shift',
      value: 229,
      x: 461,
      y: -159,
      w: 55,
      h: 27,
    },
    {
      keyName: 'End',
      value: 77,
      x: 583,
      y: -159,
      w: 25,
      h: 27,
    },
    {
      keyName: 'Ctrl',
      value: 224,
      x: 0,
      y: -197,
      w: 34,
      h: 27,
    },
    {
      keyName: 'Win',
      value: 227,
      x: 47,
      y: -197,
      w: 34,
      h: 27,
    },
    {
      keyName: 'Alt',
      value: 226,
      x: 94,
      y: -197,
      w: 34,
      h: 27,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 141,
      y: -197,
      w: 223,
      h: 27,
    },
    {
      keyName: 'r_Alt',
      value: 230,
      x: 377,
      y: -197,
      w: 25,
      h: 27,
    },
    {
      keyName: 'FN',
      value: 0x0a010000,
      x: 414,
      y: -197,
      w: 25,
      h: 27,
    },
    {
      keyName: 'r_Ctrl',
      value: 228,
      x: 452,
      y: -197,
      w: 25,
      h: 27,
    },
    {
      keyName: '↑',
      value: 82,
      x: 536,
      y: -168,
      w: 25,
      h: 27,
    },
    {
      keyName: '←',
      value: 80,
      x: 498,
      y: -206,
      w: 25,
      h: 27,
    },
    {
      keyName: '↓',
      value: 81,
      x: 536,
      y: -206,
      w: 25,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
      h: 27,
    },
    {
      keyName: '→',
      value: 79,
      x: 574,
      y: -206,
      w: 25,
      h: 27,
    },
  ],
}
