export const yc300_kc21_dm= {
  deltX: 357,
  deltY: 18,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 32,
      h: 33,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 42,
      y: 0,
      w: 32,
      h: 33,
    },
    {
      keyName: 'FN',
      value: 0x0a010000,
      x: 83,
      y: 0,
      w: 32,
      h: 33,
    },
    {
      keyName: 'BackSpace',
      value: 42,
      x: 126,
      y: 0,
      w: 32,
      h: 33,
    },
    {
      keyName: 'Num\nLock',
      value: 83,
      x: 0,
      y: -56,
      w: 32,
      h: 33,
    },
    {
      keyName: 'num_/',
      value: 84,
      x: 42,
      y: -56,
      w: 32,
      h: 33,
    },
    {
      keyName: 'num_*',
      value: 85,
      x: 83,
      y: -56,
      w: 32,
      h: 33,
    },
    {
      keyName: 'num_-',
      value: 86,
      x: 126,
      y: -56,
      w: 32,
      h: 33,
    },
    {
      keyName: 'num_7',
      value: 95,
      x: 0,
      y: -99,
      w: 32,
      h: 33,
    },
    {
      keyName: 'num_8',
      value: 96,
      x: 42,
      y: -99,
      w: 32,
      h: 33,
    },
    {
      keyName: 'num_9',
      value: 97,
      x: 83,
      y: -99,
      w: 32,
      h: 33,
    },
    {
      keyName: 'num_+',
      value: 87,
      x: 126,
      y: -99,
      w: 32,
      h: 72,
    },
    {
      keyName: 'num_4',
      value: 92,
      x: 0,
      y: -140,
      w: 32,
      h: 33,
    },
    {
      keyName: 'num_5',
      value: 93,
      x: 42,
      y: -140,
      w: 32,
      h: 33,
    },
    {
      keyName: 'num_6',
      value: 94,
      x: 83,
      y: -140,
      w: 32,
      h: 33,
    },
    {
      keyName: 'num_1',
      value: 89,
      x: 0,
      y: -182,
      w: 32,
      h: 33,
    },
    {
      keyName: 'num_2',
      value: 90,
      x: 42,
      y: -182,
      w: 32,
      h: 33,
    },
    {
      keyName: 'num_3',
      value: 91,
      x: 83,
      y: -182,
      w: 32,
      h: 33,
    },
    {
      keyName: 'num_Enter',
      value: 88,
      x: 126,
      y: -182,
      w: 32,
      h: 72,
    },
    {
      keyName: 'num_0',
      value: 98,
      x: 0,
      y: -223,
      w: 74,
      h: 33,
    },
    {
      keyName: 'num_.',
      value: 99,
      x: 83,
      y: -223,
      w: 32,
      h: 33,
    },
  ],
}
