export const yc300_3068bp_iso_de = {
  deltX: 33,
  deltY: 24,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 33,
      h: 38,
    },
    {
      keyName: '1',
      value: 30,
      x: 51,
      y: -0,
      w: 33,
      h: 38,
    },
    {
      keyName: '2',
      value: 31,
      x: 103,
      y: -0,
      w: 33,
      h: 38,
    },
    {
      keyName: '3',
      value: 32,
      x: 155,
      y: -0,
      w: 33,
      h: 38,
    },
    {
      keyName: '4',
      value: 33,
      x: 206,
      y: -0,
      w: 33,
      h: 38,
    },
    {
      keyName: '5',
      value: 34,
      x: 258,
      y: -0,
      w: 33,
      h: 38,
    },
    {
      keyName: '6',
      value: 35,
      x: 310,
      y: -0,
      w: 33,
      h: 38,
    },
    {
      keyName: '7',
      value: 36,
      x: 361,
      y: -0,
      w: 33,
      h: 38,
    },
    {
      keyName: '8',
      value: 37,
      x: 412,
      y: -0,
      w: 33,
      h: 38,
    },
    {
      keyName: '9',
      value: 38,
      x: 463,
      y: -0,
      w: 33,
      h: 38,
    },
    {
      keyName: '0',
      value: 39,
      x: 515,
      y: -0,
      w: 33,
      h: 38,
    },
    {
      keyName: '-',
      value: 45,
      x: 567,
      y: -0,
      w: 33,
      h: 38,
    },
    {
      keyName: '=',
      value: 46,
      x: 618,
      y: -0,
      w: 33,
      h: 38,
    },
    {
      keyName: 'BackSpace',
      value: 42,
      x: 670,
      y: -0,
      w: 84,
      h: 38,
    },
    {
      keyName: '`',
      value: 53,
      x: 774,
      y: -0,
      w: 33,
      h: 38,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -50,
      w: 59,
      h: 38,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 77,
      y: -50,
      w: 33,
      h: 38,
    },
    {
      keyName: 'W',
      value: 26,
      x: 129,
      y: -50,
      w: 33,
      h: 38,
    },
    {
      keyName: 'E',
      value: 8,
      x: 181,
      y: -50,
      w: 33,
      h: 38,
    },
    {
      keyName: 'R',
      value: 21,
      x: 232,
      y: -50,
      w: 33,
      h: 38,
    },
    {
      keyName: 'T',
      value: 23,
      x: 284,
      y: -50,
      w: 33,
      h: 38,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 336,
      y: -50,
      w: 33,
      h: 38,
    },
    {
      keyName: 'U',
      value: 24,
      x: 387,
      y: -50,
      w: 33,
      h: 38,
    },
    {
      keyName: 'I',
      value: 12,
      x: 438,
      y: -50,
      w: 33,
      h: 38,
    },
    {
      keyName: 'O',
      value: 18,
      x: 490,
      y: -50,
      w: 33,
      h: 38,
    },
    {
      keyName: 'P',
      value: 19,
      x: 541,
      y: -50,
      w: 33,
      h: 38,
    },
    {
      keyName: '[',
      value: 47,
      x: 593,
      y: -50,
      w: 33,
      h: 38,
    },
    {
      keyName: ']',
      value: 48,
      x: 644,
      y: -50,
      w: 33,
      h: 38,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 706,
      y: -50,
      w: 48,
      h: 89,
    },
    {
      keyName: 'Delete',
      value: 76,
      x: 774,
      y: -50,
      w: 33,
      h: 38,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -101,
      w: 71,
      h: 38,
    },
    {
      keyName: 'A',
      value: 4,
      x: 91,
      y: -101,
      w: 33,
      h: 38,
    },
    {
      keyName: 'S',
      value: 22,
      x: 142,
      y: -101,
      w: 33,
      h: 38,
    },
    {
      keyName: 'D',
      value: 7,
      x: 195,
      y: -101,
      w: 33,
      h: 38,
    },
    {
      keyName: 'F',
      value: 9,
      x: 245,
      y: -101,
      w: 33,
      h: 38,
    },
    {
      keyName: 'G',
      value: 10,
      x: 297,
      y: -101,
      w: 33,
      h: 38,
    },
    {
      keyName: 'H',
      value: 11,
      x: 349,
      y: -101,
      w: 33,
      h: 38,
    },
    {
      keyName: 'J',
      value: 13,
      x: 401,
      y: -101,
      w: 33,
      h: 38,
    },
    {
      keyName: 'K',
      value: 14,
      x: 452,
      y: -101,
      w: 33,
      h: 38,
    },
    {
      keyName: 'L',
      value: 15,
      x: 503,
      y: -101,
      w: 33,
      h: 38,
    },
    {
      keyName: ';',
      value: 51,
      x: 555,
      y: -101,
      w: 33,
      h: 38,
    },
    {
      keyName: '\'',
      value: 52,
      x: 607,
      y: -101,
      w: 33,
      h: 38,
    },
    {
      keyName: '\\',
      value: 50,
      x: 658,
      y: -101,
      w: 33,
      h: 38,
    },
    {
      keyName: 'Page\nUp',
      value: 75,
      x: 774,
      y: -101,
      w: 33,
      h: 38,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -152,
      w: 45,
      h: 38,
    },
    {
      keyName: '\\',
      value: 100,
      x: 65,
      y: -152,
      w: 33,
      h: 38,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 117,
      y: -152,
      w: 33,
      h: 38,
    },
    {
      keyName: 'X',
      value: 27,
      x: 169,
      y: -152,
      w: 33,
      h: 38,
    },
    {
      keyName: 'C',
      value: 6,
      x: 220,
      y: -152,
      w: 33,
      h: 38,
    },
    {
      keyName: 'V',
      value: 25,
      x: 272,
      y: -152,
      w: 33,
      h: 38,
    },
    {
      keyName: 'B',
      value: 5,
      x: 324,
      y: -152,
      w: 33,
      h: 38,
    },
    {
      keyName: 'N',
      value: 17,
      x: 375,
      y: -152,
      w: 33,
      h: 38,
    },
    {
      keyName: 'M',
      value: 16,
      x: 426,
      y: -152,
      w: 33,
      h: 38,
    },
    {
      keyName: ',',
      value: 54,
      x: 477,
      y: -152,
      w: 33,
      h: 38,
    },
    {
      keyName: '.',
      value: 55,
      x: 529,
      y: -152,
      w: 33,
      h: 38,
    },
    {
      keyName: '/',
      value: 56,
      x: 581,
      y: -152,
      w: 33,
      h: 38,
    },
    {
      keyName: 'r_Shift',
      value: 229,
      x: 632,
      y: -152,
      w: 70,
      h: 38,
    },
    {
      keyName: '↑',
      value: 82,
      x: 722,
      y: -152,
      w: 33,
      h: 38,
    },
    {
      keyName: 'Page\nDown',
      value: 78,
      x: 774,
      y: -152,
      w: 33,
      h: 38,
    },
    {
      keyName: 'Ctrl',
      value: 224,
      x: 0,
      y: -203,
      w: 45,
      h: 38,
    },
    {
      keyName: 'Win',
      value: 227,
      x: 65,
      y: -203,
      w: 47,
      h: 38,
    },
    {
      keyName: 'Alt',
      value: 226,
      x: 129,
      y: -203,
      w: 47,
      h: 38,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 194,
      y: -203,
      w: 302,
      h: 38,
    },
    {
      keyName: 'r_Alt',
      value: 230,
      x: 516,
      y: -203,
      w: 33,
      h: 38,
    },
    {
      keyName: 'FN',
      value: 0x0a010000,
      x: 567,
      y: -203,
      w: 33,
      h: 38,
    },
    {
      keyName: 'r_Ctrl',
      value: 228,
      x: 619,
      y: -203,
      w: 33,
      h: 38,
    },
    {
      keyName: '←',
      value: 80,
      x: 670,
      y: -203,
      w: 33,
      h: 38,
    },
    {
      keyName: '↓',
      value: 81,
      x: 722,
      y: -203,
      w: 33,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
      h: 38,
    },
    {
      keyName: '→',
      value: 79,
      x: 774,
      y: -203,
      w: 33,
      h: 38,
    },
  ],
}
