export const yc300_k402t = {
  deltX: 16,
  deltY: 17,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'F1',
      value: 58,
      x: 45,
      y: 0,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'F2',
      value: 59,
      x: 89,
      y: 0,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'F3',
      value: 60,
      x: 134,
      y: 0,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'F4',
      value: 61,
      x: 179,
      y: 0,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'F5',
      value: 62,
      x: 224,
      y: 0,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'F6',
      value: 63,
      x: 269,
      y: 0,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'F7',
      value: 64,
      x: 314,
      y: 0,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'F8',
      value: 65,
      x: 359,
      y: 0,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'F9',
      value: 66,
      x: 404,
      y: 0,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'F10',
      value: 67,
      x: 449,
      y: 0,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'F11',
      value: 68,
      x: 494,
      y: 0,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'F12',
      value: 69,
      x: 539,
      y: 0,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'Delete',
      value: 76,
      x: 584,
      y: 0,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'Print\nScreen',
      value: 70,
      x: 629,
      y: 0,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'Scroll\nLock',
      value: 71,
      x: 674,
      y: 0,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'Pause',
      value: 72,
      x: 718,
      y: 0,
      w: 30, 
      h: 31, 
    },
    {
      keyName: '`',
      value: 53,
      x: 0,
      y: -45,
      w: 30, 
      h: 31, 
     },
    {
      keyName: '1',
      value: 30,
      x: 45,
      y: -45,
      w: 30, 
      h: 31, 
    },
    {
      keyName: '2',
      value: 31,
      x: 89,
      y: -45,
      w: 30, 
      h: 31, 
    },
    {
      keyName: '3',
      value: 32,
      x: 134,
      y: -45,
      w: 30, 
      h: 31, 
    },
    {
      keyName: '4',
      value: 33,
      x: 179,
      y: -45,
      w: 30, 
      h: 31, 
    },
    {
      keyName: '5',
      value: 34,
      x: 224,
      y: -45,
      w: 30, 
      h: 31, 
    },
    {
      keyName: '6',
      value: 35,
      x: 269,
      y: -45,
      w: 30, 
      h: 31, 
    },
    {
      keyName: '7',
      value: 36,
      x: 314,
      y: -45,
      w: 30, 
      h: 31, 
    },
    {
      keyName: '8',
      value: 37,
      x: 359,
      y: -45,
      w: 30, 
      h: 31, 
    },
    {
      keyName: '9',
      value: 38,
      x: 404,
      y: -45,
      w: 30, 
      h: 31, 
    },
    {
      keyName: '0',
      value: 39,
      x: 449,
      y: -45,
      w: 30, 
      h: 31, 
    },
    {
      keyName: '-',
      value: 45,
      x: 494,
      y: -45,
      w: 30, 
      h: 31, 
    },
    {
      keyName: '=',
      value: 46,
      x: 539,
      y: -45,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'BackSpace',
      value: 42,
      x: 584,
      y: -45,
      w: 75, 
      h: 31, 
    },
    {
      keyName: 'Num\nLock',
      value: 83,
      x: 674,
      y: -45,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'num_/',
      value: 84,
      x: 718,
      y: -45,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'num_*',
      value: 85,
      x: 764,
      y: -45,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'num_-',
      value: 86,
      x: 808,
      y: -45,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -90,
      w: 52, 
      h: 31, 
    },
    {
      keyName: 'Q',
      value: 20,
      x: 67,
      y: -90,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'W',
      value: 26,
      x: 111,
      y: -90,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'E',
      value: 8,
      x: 156,
      y: -90,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'R',
      value: 21,
      x: 201,
      y: -90,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'T',
      value: 23,
      x: 246,
      y: -90,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'Y',
      value: 28,
      x: 291,
      y: -90,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'U',
      value: 24,
      x: 336,
      y: -90,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'I',
      value: 12,
      x: 381,
      y: -90,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'O',
      value: 18,
      x: 426,
      y: -90,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'P',
      value: 19,
      x: 471,
      y: -90,
      w: 30, 
      h: 31, 
    },
    {
      keyName: '[',
      value: 47,
      x: 516,
      y: -90,
      w: 30, 
      h: 31, 
    },
    {
      keyName: ']',
      value: 48,
      x: 561,
      y: -90,
      w: 30, 
      h: 31, 
    },
    {
      keyName: '\\',
      value: 49,
      x: 606,
      y: -90,
      w: 53, 
      h: 31, 
    },
    {
      keyName: 'num_7',
      value: 95,
      x: 674,
      y: -90,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'num_8',
      value: 96,
      x: 718,
      y: -90,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'num_9',
      value: 97,
      x: 764,
      y: -90,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'num_+',
      value: 87,
      x: 808,
      y: -90,
      w: 30, 
      h: 76, 
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -135,
      w: 63, 
      h: 31, 
    },
    {
      keyName: 'A',
      value: 4,
      x: 78,
      y: -135,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'S',
      value: 22,
      x: 123,
      y: -135,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'D',
      value: 7,
      x: 168,
      y: -135,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'F',
      value: 9,
      x: 213,
      y: -135,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'G',
      value: 10,
      x: 258,
      y: -135,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'H',
      value: 11,
      x: 303,
      y: -135,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'J',
      value: 13,
      x: 347,
      y: -135,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'K',
      value: 14,
      x: 392,
      y: -135,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'L',
      value: 15,
      x: 438,
      y: -135,
      w: 30, 
      h: 31, 
    },
    {
      keyName: ';',
      value: 51,
      x: 483,
      y: -135,
      w: 30, 
      h: 31, 
    },
    {
      keyName: '\'',
      value: 52,
      x: 527,
      y: -135,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 572,
      y: -135,
      w: 87, 
      h: 31, 
    },
    {
      keyName: 'num_4',
      value: 92,
      x: 674,
      y: -135,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'num_5',
      value: 93,
      x: 718,
      y: -135,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'num_6',
      value: 94,
      x: 764,
      y: -135,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -179,
      w: 86, 
      h: 31, 
    },
    {
      keyName: 'Z',
      value: 29,
      x: 100,
      y: -179,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'X',
      value: 27,
      x: 145,
      y: -179,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'C',
      value: 6,
      x: 190,
      y: -179,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'V',
      value: 25,
      x: 235,
      y: -179,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'B',
      value: 5,
      x: 280,
      y: -179,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'N',
      value: 17,
      x: 325,
      y: -179,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'M',
      value: 16,
      x: 369,
      y: -179,
      w: 30, 
      h: 31, 
    },
    {
      keyName: ',',
      value: 54,
      x: 414,
      y: -179,
      w: 30, 
      h: 31, 
    },
    {
      keyName: '.',
      value: 55,
      x: 460,
      y: -179,
      w: 30, 
      h: 31, 
    },
    {
      keyName: '/',
      value: 56,
      x: 505,
      y: -179,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'r_Shift',
      value: 229,
      x: 549,
      y: -179,
      w: 65, 
      h: 31, 
    },
    {
      keyName: '↑',
      value: 82,
      x: 628,
      y: -179,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'num_1',
      value: 89,
      x: 674,
      y: -179,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'num_2',
      value: 90,
      x: 718,
      y: -179,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'num_3',
      value: 91,
      x: 764,
      y: -179,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'num_Enter',
      value: 88,
      x: 808,
      y: -179,
      w: 30, 
      h: 76, 
    },
    {
      keyName: 'Ctrl',
      value: 224,
      x: 0,
      y: -224,
      w: 40, 
      h: 31, 
    },
    {
      keyName: 'Win',
      value: 227,
      x: 55,
      y: -224,
      w: 40, 
      h: 31, 
    },
    {
      keyName: 'Alt',
      value: 226,
      x: 111,
      y: -224,
      w: 40, 
      h: 31, 
    },
    {
      keyName: '(space)',
      value: 44,
      x: 166,
      y: -224,
      w: 268, 
      h: 31, 
    },
    {
      keyName: 'r_Alt',
      value: 230,
      x: 449,
      y: -224,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'Fn',
      value: 0x0a010000,
      x: 494,
      y: -224,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'r_Ctrl',
      value: 228,
      x: 538,
      y: -224,
      w: 30, 
      h: 31, 
    },
    {
      keyName: '←',
      value: 80,
      x: 583,
      y: -224,
      w: 30, 
      h: 31, 
    },
    {
      keyName: '↓',
      value: 81,
      x: 629,
      y: -224,
      w: 30, 
      h: 31, 
    },
    {
      keyName: '→',
      value: 79,
      x: 674,
      y: -224,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'num_0',
      value: 98,
      x: 718,
      y: -224,
      w: 30, 
      h: 31, 
    },
    {
      keyName: 'num_.',
      value: 99,
      x: 764,
      y: -224,
      w: 30, 
      h: 31, 
    },
  ],
}
