export const yc300_ck75 = {
  deltX: 116,
  deltY: 22,
  layout: [
    {
      keyName: 'Esc',
      value: 41,
      x: 0,
      y: 0,
      w: 29,
      h: 30,
     },
    {
      keyName: 'F1',
      value: 58,
      x: 96,
      y: 0,
      w: 29,
      h: 30,
    },
    {
      keyName: 'F2',
      value: 59,
      x: 135,
      y: 0,
      w: 29,
      h: 30,
    },
    {
      keyName: 'F3',
      value: 60,
      x: 175,
      y: 0,
      w: 29,
      h: 30,
    },
    {
      keyName: 'F4',
      value: 61,
      x: 215,
      y: 0,
      w: 29,
      h: 30,
    },
    {
      keyName: 'F5',
      value: 62,
      x: 268,
      y: 0,
      w: 29,
      h: 30,
    },
    {
      keyName: 'F6',
      value: 63,
      x: 307,
      y: 0,
      w: 29,
      h: 30,
    },
    {
      keyName: 'F7',
      value: 64,
      x: 347,
      y: 0,
      w: 29,
      h: 30,
    },
    {
      keyName: 'F8',
      value: 65,
      x: 387,
      y: 0,
      w: 29,
      h: 30,
    },
    {
      keyName: 'F9',
      value: 66,
      x: 439,
      y: 0,
      w: 29,
      h: 30,
    },
    {
      keyName: 'F10',
      value: 67,
      x: 479,
      y: 0,
      w: 29,
      h: 30,
    },
    {
      keyName: 'F11',
      value: 68,
      x: 519,
      y: 0,
      w: 29,
      h: 30,
    },
    {
      keyName: 'F12',
      value: 69,
      x: 559,
      y: 0,
      w: 29,
      h: 30,
    },
    {
      keyName: 'Delete',
      value: 76,
      x: 611,
      y: 0,
      w: 29,
      h: 30,
    },
    {
      keyName: '`',
      value: 53,
      x: 0,
      y: -52,
      w: 29,
      h: 30,
    },
    {
      keyName: '1',
      value: 30,
      x: 42,
      y: -52,
      w: 29,
      h: 30,
    },
    {
      keyName: '2',
      value: 31,
      x: 81,
      y: -52,
      w: 29,
      h: 30,
    },
    {
      keyName: '3',
      value: 32,
      x: 121,
      y: -52,
      w: 29,
      h: 30,
    },
    {
      keyName: '4',
      value: 33,
      x: 160,
      y: -52,
      w: 29,
      h: 30,
    },
    {
      keyName: '5',
      value: 34,
      x: 200,
      y: -52,
      w: 29,
      h: 30,
    },
    {
      keyName: '6',
      value: 35,
      x: 240,
      y: -52,
      w: 29,
      h: 30,
    },
    {
      keyName: '7',
      value: 36,
      x: 280,
      y: -52,
      w: 29,
      h: 30,
    },
    {
      keyName: '8',
      value: 37,
      x: 319,
      y: -52,
      w: 29,
      h: 30,
    },
    {
      keyName: '9',
      value: 38,
      x: 359,
      y: -52,
      w: 29,
      h: 30,
    },
    {
      keyName: '0',
      value: 39,
      x: 399,
      y: -52,
      w: 29,
      h: 30,
    },
    {
      keyName: '-',
      value: 45,
      x: 439,
      y: -52,
      w: 29,
      h: 30,
    },
    {
      keyName: '=',
      value: 46,
      x: 480,
      y: -52,
      w: 29,
      h: 30,
    },
    {
      keyName: 'BackSpace',
      value: 42,
      x: 517,
      y: -52,
      w: 72,
      h: 30,
    },
    {
      keyName: 'Page\nUp',
      value: 75,
      x: 611,
      y: -52,
      w: 29,
      h: 30,
    },
    {
      keyName: 'Tab',
      value: 43,
      x: 0,
      y: -93,
      w: 50,
      h: 30,
    },
    {
      keyName: 'Q',
      value: 20,
      x: 61,
      y: -93,
      w: 29,
      h: 30,
    },
    {
      keyName: 'W',
      value: 26,
      x: 101,
      y: -93,
      w: 29,
      h: 30,
    },
    {
      keyName: 'E',
      value: 8,
      x: 141,
      y: -93,
      w: 29,
      h: 30,
    },
    {
      keyName: 'R',
      value: 21,
      x: 180,
      y: -93,
      w: 29,
      h: 30,
    },
    {
      keyName: 'T',
      value: 23,
      x: 220,
      y: -93,
      w: 29,
      h: 30,
    },
    {
      keyName: 'Y',
      value: 28,
      x: 260,
      y: -93,
      w: 29,
      h: 30,
    },
    {
      keyName: 'U',
      value: 24,
      x: 300,
      y: -93,
      w: 29,
      h: 30,
    },
    {
      keyName: 'I',
      value: 12,
      x: 339,
      y: -93,
      w: 29,
      h: 30,
    },
    {
      keyName: 'O',
      value: 18,
      x: 379,
      y: -93,
      w: 29,
      h: 30,
    },
    {
      keyName: 'P',
      value: 19,
      x: 419,
      y: -93,
      w: 29,
      h: 30,
    },
    {
      keyName: '[',
      value: 47,
      x: 458,
      y: -93,
      w: 29,
      h: 30,
    },
    {
      keyName: ']',
      value: 48,
      x: 498,
      y: -93,
      w: 29,
      h: 30,
    },
    {
      keyName: '\\',
      value: 49,
      x: 537,
      y: -93,
      w: 49,
      h: 30,
    },
    {
      keyName: 'Page\nDown',
      value: 78,
      x: 611,
      y: -93,
      w: 29,
      h: 30,
    },
    {
      keyName: 'Caps Lock',
      value: 57,
      x: 0,
      y: -134,
      w: 60,
      h: 30,
    },
    {
      keyName: 'A',
      value: 4,
      x: 71,
      y: -134,
      w: 29,
      h: 30,
    },
    {
      keyName: 'S',
      value: 22,
      x: 111,
      y: -134,
      w: 29,
      h: 30,
    },
    {
      keyName: 'D',
      value: 7,
      x: 151,
      y: -134,
      w: 29,
      h: 30,
    },
    {
      keyName: 'F',
      value: 9,
      x: 190,
      y: -134,
      w: 29,
      h: 30,
    },
    {
      keyName: 'G',
      value: 10,
      x: 230,
      y: -134,
      w: 29,
      h: 30,
    },
    {
      keyName: 'H',
      value: 11,
      x: 270,
      y: -134,
      w: 29,
      h: 30,
    },
    {
      keyName: 'J',
      value: 13,
      x: 310,
      y: -134,
      w: 29,
      h: 30,
    },
    {
      keyName: 'K',
      value: 14,
      x: 349,
      y: -134,
      w: 29,
      h: 30,
    },
    {
      keyName: 'L',
      value: 15,
      x: 388,
      y: -134,
      w: 29,
      h: 30,
    },
    {
      keyName: ';',
      value: 51,
      x: 428,
      y: -134,
      w: 29,
      h: 30,
    },
    {
      keyName: '\'',
      value: 52,
      x: 468,
      y: -134,
      w: 29,
      h: 30,
    },
    {
      keyName: 'Enter',
      value: 40,
      x: 508,
      y: -134,
      w: 78,
      h: 30,
    },
    {
      keyName: 'Shift',
      value: 0xe1,
      x: 0,
      y: -174,
      w: 79,
      h: 30,
    },
    {
      keyName: 'Z',
      value: 29,
      x: 91,
      y: -174,
      w: 29,
      h: 30,
    },
    {
      keyName: 'X',
      value: 27,
      x: 131,
      y: -174,
      w: 29,
      h: 30,
    },
    {
      keyName: 'C',
      value: 6,
      x: 171,
      y: -174,
      w: 29,
      h: 30,
    },
    {
      keyName: 'V',
      value: 25,
      x: 210,
      y: -174,
      w: 29,
      h: 30,
    },
    {
      keyName: 'B',
      value: 5,
      x: 250,
      y: -174,
      w: 29,
      h: 30,
    },
    {
      keyName: 'N',
      value: 17,
      x: 290,
      y: -174,
      w: 29,
      h: 30,
    },
    {
      keyName: 'M',
      value: 16,
      x: 330,
      y: -174,
      w: 29,
      h: 30,
    },
    {
      keyName: ',',
      value: 54,
      x: 369,
      y: -174,
      w: 29,
      h: 30,
    },
    {
      keyName: '.',
      value: 55,
      x: 409,
      y: -174,
      w: 29,
      h: 30,
    },
    {
      keyName: '/',
      value: 56,
      x: 449,
      y: -174,
      w: 29,
      h: 30,
    },
    {
      keyName: 'r_Shift',
      value: 229,
      x: 489,
      y: -174,
      w: 57,
      h: 30,
    },
    {
      keyName: 'Ctrl',
      value: 224,
      x: 0,
      y: -213,
      w: 40,
      h: 30,
    },
    {
      keyName: 'Win',
      value: 227,
      x: 51,
      y: -213,
      w: 40,
      h: 30,
    },
    {
      keyName: 'Alt',
      value: 226,
      x: 101,
      y: -213,
      w: 40,
      h: 30,
    },
    {
      keyName: '(space)',
      value: 44,
      x: 151,
      y: -213,
      w: 238,
      h: 30,
    },
    {
      keyName: 'r_Alt',
      value: 230,
      x: 399,
      y: -213,
      w: 29,
      h: 30,
    },
    {
      keyName: 'FN',
      value: 0x0a010000,
      x: 439,
      y: -213,
      w: 29,
      h: 30,
    },
    {
      keyName: 'r_Ctrl',
      value: 228,
      x: 479,
      y: -213,
      w: 29,
      h: 30,
    },
    {
      keyName: '↑',
      value: 82,
      x: 564,
      y: -178,
      w: 29,
      h: 30,
    },
    {
      keyName: '←',
      value: 80,
      x: 524,
      y: -219,
      w: 29,
      h: 30,
    },
    {
      keyName: '↓',
      value: 81,
      x: 564,
      y: -219,
      w: 29,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
      h: 30,
    },
    {
      keyName: '→',
      value: 79,
      x: 604,
      y: -219,
      w: 29,
      h: 30,
    },
  ],
}
